const translationsPart2 = {
  fa: {
    watermark: { heroBadge: "حفاظت از برند", heroTitle: "از کار خود محافظت کنید.", heroTitle2: "هویت خود را بسازید.", heroDesc: "برای محافظت از دارایی فکری خود واترمارک‌های بسیار قابل تنظیم اعمال کنید.", feat1Title: "لایه‌های غیرمخرب", feat1Desc: "لایه‌های واترمارک متعدد را بدون تغییر تصویر اصلی اضافه کنید.", feat2Title: "کنترل شفافیت", feat2Desc: "شفافیت متن یا لوگوی خود را تنظیم کنید.", feat3Title: "حالت الگوی کاشی", feat3Desc: "واترمارک خود را به طور خودکار در سراسر تصویر تکرار کنید.", stepsTag: "گردش کار", stepsTitle: "محافظت در ۳ مرحله", s1Title: "آپلود", s1Desc: "عکس‌های اصلی خود را با خیال راحت در مرورگر بارگذاری کنید.", s2Title: "مهر زدن", s2Desc: "متن یا لوگوی سفارشی خود را اعمال کنید.", s3Title: "خروجی", s3Desc: "تصاویر محافظت شده را فوراً ذخیره کنید." },
    blurface: { heroBadge: "حریم خصوصی نهایی", heroTitle: "سانسور با هوش مصنوعی.", heroTitle2: "محافظت از هویت.", heroDesc: "چهره‌ها و اطلاعات حساس را در چند ثانیه به طور خودکار محو کنید. ۱۰۰٪ خصوصی.", feat1Title: "تشخیص چهره", feat1Desc: "مدل هوش مصنوعی محلی ما چهره‌ها را با دقت باورنکردنی پیدا می‌کند.", feat2Title: "تاری هوشمند", feat2Desc: "برای پنهان کردن دائمی مناطق حساس از تار شدن گاوسی استفاده کنید.", feat3Title: "کنترل دستی", feat3Desc: "نیاز به پنهان کردن یک سند دارید؟ از ابزار دستی ما استفاده کنید.", stepsTag: "چگونه کار می کند", stepsTitle: "ناشناس کردن در ۳ مرحله", s1Title: "آپلود", s1Desc: "عکس ها را با خیال راحت در مرورگر رها کنید.", s2Title: "تشخیص", s2Desc: "اجازه دهید هوش مصنوعی به طور خودکار چهره ها را انتخاب کند.", s3Title: "ذخیره", s3Desc: "عکس های ناشناس را دانلود کنید." },
    convert: { heroBadge: "سازگاری جهانی", heroTitle: "مبدل فرمت.", heroTitle2: "بدون افت کیفیت.", heroDesc: "بین WebP، PNG، JPG و AVIF به طور یکپارچه تبدیل کنید.", feat1Title: "بسیار سریع", feat1Desc: "فایل های حجیم را با استفاده از قدرت دستگاه خود فوراً تبدیل کنید.", feat2Title: "پردازش دسته‌ای", feat2Desc: "نیاز به تبدیل ۵۰۰ تصویر دارید؟ فقط کل پوشه را بکشید و رها کنید.", feat3Title: "پشتیبانی گسترده", feat3Desc: "پشتیبانی کامل از فرمت های نسل بعدی مانند WebP.", stepsTag: "گردش کار", stepsTitle: "تبدیل در ۳ مرحله", s1Title: "آپلود", s1Desc: "تصاویر خود را به فضای کاری بکشید و رها کنید.", s2Title: "فرمت", s2Desc: "فرمت خروجی مورد نظر خود را انتخاب کنید.", s3Title: "خروجی", s3Desc: "روی خروجی کلیک کنید و فایل های خود را فوراً دریافت کنید." },
    faqs: {
      "landing.watermark.faq1.q": "آیا می توانم به چندین عکس واترمارک اضافه کنم؟",
      "landing.watermark.faq1.a": "بله! پردازش دسته‌ای ما واترمارک کردن صدها عکس را سریع و آسان می‌کند.",
      "landing.watermark.faq2.q": "آیا عکس های اصلی من امن هستند؟",
      "landing.watermark.faq2.a": "بله، فرآیند ۱۰۰٪ خصوصی و محلی است.",
      "landing.watermark.faq3.q": "آیا می توانم از لوگوی خودم استفاده کنم؟",
      "landing.watermark.faq3.a": "قطعا. می توانید لوگوهای PNG سفارشی آپلود کنید.",
      "landing.watermark.faq4.q": "آیا محدودیتی برای تعداد عکس وجود دارد؟",
      "landing.watermark.faq4.a": "بدون محدودیت! این ابزار کاملاً رایگان است.",
      "landing.blurface.faq1.q": "آیا چندین چهره را تشخیص می دهد؟",
      "landing.blurface.faq1.a": "بله، هوش مصنوعی محلی ما می تواند به سرعت چندین چهره را تشخیص دهد.",
      "landing.blurface.faq2.q": "آیا تشخیص چهره خصوصی است؟",
      "landing.blurface.faq2.a": "۱۰۰٪ خصوصی. هوش مصنوعی مستقیماً در مرورگر شما اجرا می شود.",
      "landing.blurface.faq3.q": "آیا باید برای استفاده از هوش مصنوعی هزینه بپردازم؟",
      "landing.blurface.faq3.a": "خیر، ابزار ما کاملاً رایگان است.",
      "landing.blurface.faq4.q": "آیا تنظیم شدت تاری آسان است؟",
      "landing.blurface.faq4.a": "بله، شما کنترل کاملی روی شعاع تاری دارید.",
      "landing.convert.faq1.q": "چه فرمت هایی پشتیبانی می شوند؟",
      "landing.convert.faq1.a": "ما از WebP، PNG، JPEG و غیره پشتیبانی می کنیم.",
      "landing.convert.faq2.q": "آیا تبدیل سریع است؟",
      "landing.convert.faq2.a": "بسیار سریع. به صورت محلی در میلی ثانیه انجام می شود.",
      "landing.convert.faq3.q": "آیا این ابزار برای تبدیل دسته‌ای رایگان است؟",
      "landing.convert.faq3.a": "بله! می توانید صدها تصویر را به صورت رایگان تبدیل کنید.",
      "landing.convert.faq4.q": "آیا فایل های تبدیل شده من خصوصی هستند؟",
      "landing.convert.faq4.a": "کاملاً خصوصی. همه چیز در مرورگر شما اتفاق می افتد."
    }
  },
  ur: {
    watermark: { heroBadge: "برانڈ کا تحفظ", heroTitle: "اپنے کام کی حفاظت کریں۔", heroTitle2: "اپنی شناخت بنائیں۔", heroDesc: "اپنی فکری املاک کی حفاظت کے لیے انتہائی حسب ضرورت واٹر مارکس لگائیں۔", feat1Title: "غیر تباہ کن تہیں", feat1Desc: "اپنی اصل تصویر کو تبدیل کیے بغیر متعدد واٹر مارک تہیں شامل کریں۔", feat2Title: "شفافیت کا کنٹرول", feat2Desc: "اپنے متن یا لوگو کی شفافیت کو ایڈجسٹ کریں۔", feat3Title: "ٹائل پیٹرن موڈ", feat3Desc: "پوری تصویر میں خود بخود اپنا واٹر مارک دہرائیں۔", stepsTag: "ورک فلو", stepsTitle: "3 مراحل میں حفاظت کریں", s1Title: "اپ لوڈ کریں", s1Desc: "اپنی اصل تصاویر کو براؤزر میں محفوظ طریقے سے لوڈ کریں۔", s2Title: "مہر", s2Desc: "اپنا کسٹم متن یا لوگو لاگو کریں۔", s3Title: "ایکسپورٹ", s3Desc: "محفوظ کی گئی تصاویر کو فوری طور پر محفوظ کریں۔" },
    blurface: { heroBadge: "انتہائی رازداری", heroTitle: "AI کے ساتھ سنسر کریں۔", heroTitle2: "شناخت کی حفاظت کریں۔", heroDesc: "چہروں اور حساس معلومات کو سیکنڈوں میں خود بخود دھندلا کریں۔", feat1Title: "چہرے کی شناخت", feat1Desc: "ہمارا مقامی AI ماڈل ناقابل یقین درستگی کے ساتھ چہرے تلاش کرتا ہے۔", feat2Title: "سمارٹ بلرنگ", feat2Desc: "حساس علاقوں کو چھپانے کے لیے گاسین بلر لگائیں۔", feat3Title: "دستی کنٹرول", feat3Desc: "کوئی دستاویز چھپانے کی ضرورت ہے؟ ہمارا دستی ٹول استعمال کریں۔", stepsTag: "یہ کیسے کام کرتا ہے", stepsTitle: "3 مراحل میں گمنام کریں", s1Title: "اپ لوڈ کریں", s1Desc: "تصاویر کو براؤزر میں محفوظ طریقے سے چھوڑیں۔", s2Title: "پتہ لگائیں", s2Desc: "AI کو خود بخود چہرے منتخب کرنے دیں۔", s3Title: "محفوظ کریں", s3Desc: "گمنام تصاویر ڈاؤن لوڈ کریں۔" },
    convert: { heroBadge: "عالمگیر مطابقت", heroTitle: "فارمیٹ کنورٹر۔", heroTitle2: "صفر معیار کا نقصان۔", heroDesc: "WebP، PNG، JPG اور AVIF کے درمیان بغیر کسی رکاوٹ کے تبدیل کریں۔", feat1Title: "انتہائی تیز", feat1Desc: "اپنے آلے کی طاقت کا استعمال کرتے ہوئے بڑی فائلوں کو فوری طور پر تبدیل کریں۔", feat2Title: "بلک پروسیسنگ", feat2Desc: "500 تصاویر کو تبدیل کرنے کی ضرورت ہے؟ بس پورا فولڈر چھوڑ دیں۔", feat3Title: "وسیع تعاون", feat3Desc: "JPG جیسے کلاسک فارمیٹس کے ساتھ WebP کی مکمل حمایت۔", stepsTag: "ورک فلو", stepsTitle: "3 مراحل میں تبدیل کریں", s1Title: "اپ لوڈ کریں", s1Desc: "اپنی تصاویر کو ورک اسپیس میں چھوڑیں۔", s2Title: "فارمیٹ", s2Desc: "اپنا مطلوبہ آؤٹ پٹ فارمیٹ منتخب کریں۔", s3Title: "ایکسپورٹ", s3Desc: "ایکسپورٹ پر کلک کریں اور فوری طور پر اپنی فائلیں حاصل کریں۔" },
    faqs: {
      "landing.watermark.faq1.q": "کیا میں ایک سے زیادہ تصاویر پر واٹر مارک لگا سکتا ہوں؟",
      "landing.watermark.faq1.a": "ہاں! بلک پروسیسنگ سینکڑوں تصاویر کو ایک ساتھ واٹر مارک کرنا آسان بناتی ہے۔",
      "landing.watermark.faq2.q": "کیا میری اصل تصاویر محفوظ ہیں؟",
      "landing.watermark.faq2.a": "ہاں، یہ عمل 100% نجی اور مقامی ہے۔",
      "landing.watermark.faq3.q": "کیا میں اپنا لوگو استعمال کر سکتا ہوں؟",
      "landing.watermark.faq3.a": "بالکل۔ آپ کسٹم PNG لوگو یا متن استعمال کر سکتے ہیں۔",
      "landing.watermark.faq4.q": "کیا تصاویر کی تعداد کی کوئی حد ہے؟",
      "landing.watermark.faq4.a": "کوئی حد نہیں! آپ اسے مفت میں استعمال کر سکتے ہیں۔",
      "landing.blurface.faq1.q": "کیا یہ ایک سے زیادہ چہروں کا پتہ لگاتا ہے؟",
      "landing.blurface.faq1.a": "ہاں، ہمارا مقامی AI تیزی سے متعدد چہروں کو دھندلا کر سکتا ہے۔",
      "landing.blurface.faq2.q": "کیا چہرے کی شناخت نجی ہے؟",
      "landing.blurface.faq2.a": "100% نجی۔ AI ماڈل آپ کے براؤزر میں چلتا ہے۔",
      "landing.blurface.faq3.q": "کیا مجھے AI استعمال کرنے کے لیے ادائیگی کرنی ہوگی؟",
      "landing.blurface.faq3.a": "نہیں، ہمارا ٹول بالکل مفت ہے۔",
      "landing.blurface.faq4.q": "کیا بلر کی شدت کو ایڈجسٹ کرنا آسان ہے؟",
      "landing.blurface.faq4.a": "ہاں، آپ کو بلر کے رداس پر مکمل کنٹرول حاصل ہے۔",
      "landing.convert.faq1.q": "کون سے فارمیٹس تعاون یافتہ ہیں؟",
      "landing.convert.faq1.a": "ہم WebP، PNG، JPEG اور مزید کی حمایت کرتے ہیں۔",
      "landing.convert.faq2.q": "کیا تبادلوں کا عمل تیز ہے؟",
      "landing.convert.faq2.a": "انتہائی تیز۔ یہ مقامی طور پر ملی سیکنڈ میں ہوتا ہے۔",
      "landing.convert.faq3.q": "کیا یہ ٹول بلک تبادلوں کے لیے مفت ہے؟",
      "landing.convert.faq3.a": "ہاں! آپ سینکڑوں تصاویر کو مفت میں تبدیل کر سکتے ہیں۔",
      "landing.convert.faq4.q": "کیا میری تبدیل شدہ فائلیں نجی ہیں؟",
      "landing.convert.faq4.a": "مکمل طور پر نجی۔ سب کچھ آپ کے براؤزر میں ہوتا ہے۔"
    }
  },
  uk: {
    watermark: { heroBadge: "ЗАХИСТ БРЕНДУ", heroTitle: "Захистіть свою роботу.", heroTitle2: "Створіть свою ідентичність.", heroDesc: "Застосовуйте гнучкі водяні знаки для захисту своєї інтелектуальної власності.", feat1Title: "Недеструктивні шари", feat1Desc: "Додавайте кілька шарів водяних знаків без зміни оригінального зображення.", feat2Title: "Контроль непрозорості", feat2Desc: "Точно налаштовуйте прозорість тексту або логотипу.", feat3Title: "Режим шаблону", feat3Desc: "Автоматично повторюйте водяний знак по всьому зображенню.", stepsTag: "РОБОЧИЙ ПРОЦЕС", stepsTitle: "Захистіть за 3 кроки", s1Title: "Завантажити", s1Desc: "Безпечно завантажте оригінальні фотографії в браузер.", s2Title: "Штамп", s2Desc: "Застосуйте власний текст або логотип.", s3Title: "Експорт", s3Desc: "Миттєво збережіть захищені зображення." },
    blurface: { heroBadge: "АБСОЛЮТНА КОНФІДЕНЦІЙНІСТЬ", heroTitle: "Цензура за допомогою ШІ.", heroTitle2: "Захистіть особистості.", heroDesc: "Автоматично виявляйте та розмивайте обличчя за лічені секунди. 100% приватно.", feat1Title: "Виявлення облич", feat1Desc: "Наш локальний ШІ знаходить обличчя з неймовірною точністю.", feat2Title: "Розумне розмиття", feat2Desc: "Застосуйте розмиття за Гауссом, щоб приховати конфіденційні ділянки.", feat3Title: "Ручний контроль", feat3Desc: "Потрібно приховати документ? Використовуйте наш ручний інструмент.", stepsTag: "ЯК ЦЕ ПРАЦЮЄ", stepsTitle: "Анонімізуйте за 3 кроки", s1Title: "Завантажити", s1Desc: "Безпечно перетягніть фотографії в браузер.", s2Title: "Виявити", s2Desc: "Дозвольте ШІ автоматично вибрати обличчя.", s3Title: "Зберегти", s3Desc: "Завантажте анонімізовані фотографії." },
    convert: { heroBadge: "УНІВЕРСАЛЬНА СУМІСНІСТЬ", heroTitle: "Трансформатор форматів.", heroTitle2: "Без втрати якості.", heroDesc: "Легко конвертуйте між WebP, PNG, JPG та AVIF.", feat1Title: "Блискавично швидко", feat1Desc: "Миттєво перетворюйте великі файли, використовуючи потужність вашого пристрою.", feat2Title: "Масова обробка", feat2Desc: "Потрібно конвертувати 500 зображень? Просто перетягніть всю папку.", feat3Title: "Широка підтримка", feat3Desc: "Повна підтримка форматів нового покоління, таких як WebP.", stepsTag: "РОБОЧИЙ ПРОЦЕС", stepsTitle: "Конвертуйте за 3 кроки", s1Title: "Завантажити", s1Desc: "Перетягніть ваші зображення в робочу область.", s2Title: "Формат", s2Desc: "Виберіть потрібний вихідний формат.", s3Title: "Експорт", s3Desc: "Натисніть експорт і миттєво отримайте свої файли." },
    faqs: {
      "landing.watermark.faq1.q": "Чи можу я додати водяний знак до кількох фотографій?",
      "landing.watermark.faq1.a": "Так! Масова обробка дозволяє швидко додавати водяні знаки до сотень фотографій.",
      "landing.watermark.faq2.q": "Чи мої оригінальні фотографії в безпеці?",
      "landing.watermark.faq2.a": "Так, процес 100% приватний і локальний.",
      "landing.watermark.faq3.q": "Чи можу я використати власний логотип?",
      "landing.watermark.faq3.a": "Звичайно. Ви можете завантажити власні логотипи PNG або використовувати текст.",
      "landing.watermark.faq4.q": "Чи є обмеження на кількість фотографій?",
      "landing.watermark.faq4.a": "Без обмежень! Ви можете користуватися інструментом безкоштовно.",
      "landing.blurface.faq1.q": "Чи виявляє він кілька облич?",
      "landing.blurface.faq1.a": "Так, наш локальний ШІ може дуже швидко розмити кілька облич.",
      "landing.blurface.faq2.q": "Чи виявлення облич є приватним?",
      "landing.blurface.faq2.a": "100% приватно. Модель ШІ працює безпосередньо у вашому браузері.",
      "landing.blurface.faq3.q": "Чи потрібно платити за використання ШІ?",
      "landing.blurface.faq3.a": "Ні, наш інструмент абсолютно безкоштовний.",
      "landing.blurface.faq4.q": "Чи легко налаштувати інтенсивність розмиття?",
      "landing.blurface.faq4.a": "Так, ви маєте повний контроль над радіусом розмиття.",
      "landing.convert.faq1.q": "Які формати підтримуються?",
      "landing.convert.faq1.a": "Ми підтримуємо WebP, PNG, JPEG та інші.",
      "landing.convert.faq2.q": "Чи конвертація швидка?",
      "landing.convert.faq2.a": "Надзвичайно швидка. Відбувається локально за мілісекунди.",
      "landing.convert.faq3.q": "Чи цей інструмент безкоштовний для масової конвертації?",
      "landing.convert.faq3.a": "Так! Ви можете безкоштовно конвертувати сотні зображень.",
      "landing.convert.faq4.q": "Чи мої конвертовані файли приватні?",
      "landing.convert.faq4.a": "Абсолютно приватні. Все відбувається у вашому браузері."
    }
  },
  ro: {
    watermark: { heroBadge: "PROTECȚIA BRANDULUI", heroTitle: "Protejați-vă munca.", heroTitle2: "Construiți-vă identitatea.", heroDesc: "Aplicați filigrane personalizabile pentru a vă proteja proprietatea intelectuală.", feat1Title: "Straturi nedistructive", feat1Desc: "Adăugați mai multe straturi de filigran fără a modifica imaginea originală.", feat2Title: "Control opacitate", feat2Desc: "Ajustați transparența textului sau logo-ului dvs.", feat3Title: "Mod model", feat3Desc: "Repetați automat filigranul pe întreaga imagine.", stepsTag: "FLUX DE LUCRU", stepsTitle: "Protejați în 3 pași", s1Title: "Încărcare", s1Desc: "Încărcați fotografiile originale în siguranță în browser.", s2Title: "Ștampilă", s2Desc: "Aplicați textul sau logo-ul personalizat.", s3Title: "Export", s3Desc: "Salvați instantaneu imaginile protejate." },
    blurface: { heroBadge: "CONFIDENȚIALITATE SUPREMĂ", heroTitle: "Cenzurați cu IA.", heroTitle2: "Protejați identitățile.", heroDesc: "Detectați și estompați automat fețele în câteva secunde. 100% privat.", feat1Title: "Detectare facială", feat1Desc: "Modelul nostru IA local găsește fețele cu o acuratețe incredibilă.", feat2Title: "Estompare inteligentă", feat2Desc: "Aplicați estompare gaussiană pentru a ascunde zonele sensibile.", feat3Title: "Control manual", feat3Desc: "Trebuie să ascundeți un document? Folosiți instrumentul nostru manual.", stepsTag: "CUM FUNCȚIONEAZĂ", stepsTitle: "Anonimizați în 3 pași", s1Title: "Încărcare", s1Desc: "Plasați fotografiile în siguranță în browser.", s2Title: "Detectare", s2Desc: "Lăsați IA să selecteze automat fețele.", s3Title: "Salvare", s3Desc: "Descărcați fotografiile anonimizate." },
    convert: { heroBadge: "COMPATIBILITATE UNIVERSALĂ", heroTitle: "Transformator format.", heroTitle2: "Zero pierderi de calitate.", heroDesc: "Convertiți fără probleme între WebP, PNG, JPG și AVIF.", feat1Title: "Fulgere", feat1Desc: "Transformați fișierele mari folosind puterea dispozitivului dvs.", feat2Title: "Procesare în masă", feat2Desc: "Trebuie să convertiți 500 de imagini? Doar trageți întregul folder.", feat3Title: "Suport extins", feat3Desc: "Suport complet pentru formatele de nouă generație precum WebP.", stepsTag: "FLUX DE LUCRU", stepsTitle: "Convertiți în 3 pași", s1Title: "Încărcare", s1Desc: "Trageți și plasați imaginile în spațiul de lucru.", s2Title: "Format", s2Desc: "Selectați formatul de ieșire dorit.", s3Title: "Export", s3Desc: "Faceți clic pe export și obțineți fișierele instantaneu." },
    faqs: {
      "landing.watermark.faq1.q": "Pot adăuga filigran pe mai multe fotografii?",
      "landing.watermark.faq1.a": "Da! Procesarea în loturi face rapidă și ușoară adăugarea filigranelor pe sute de fotografii.",
      "landing.watermark.faq2.q": "Sunt fotografiile mele originale în siguranță?",
      "landing.watermark.faq2.a": "Da, procesul este 100% privat și local.",
      "landing.watermark.faq3.q": "Pot folosi propriul meu logo?",
      "landing.watermark.faq3.a": "Absolut. Puteți încărca logo-uri PNG personalizate.",
      "landing.watermark.faq4.q": "Există o limită a numărului de fotografii?",
      "landing.watermark.faq4.a": "Fără limite! Puteți folosi instrumentul gratuit.",
      "landing.blurface.faq1.q": "Detectează mai multe fețe?",
      "landing.blurface.faq1.a": "Da, IA noastră locală poate detecta și estompa rapid mai multe fețe.",
      "landing.blurface.faq2.q": "Detectarea facială este privată?",
      "landing.blurface.faq2.a": "100% privat. Modelul IA rulează direct în browser-ul tău.",
      "landing.blurface.faq3.q": "Trebuie să plătesc pentru a folosi IA?",
      "landing.blurface.faq3.a": "Nu, instrumentul nostru este complet gratuit.",
      "landing.blurface.faq4.q": "Este ușor să ajustez intensitatea estompării?",
      "landing.blurface.faq4.a": "Da, aveți control complet asupra razei de estompare.",
      "landing.convert.faq1.q": "Ce formate sunt acceptate?",
      "landing.convert.faq1.a": "Acceptăm WebP, PNG, JPEG și altele.",
      "landing.convert.faq2.q": "Conversia este rapidă?",
      "landing.convert.faq2.a": "Extrem de rapidă. Are loc local în milisecunde.",
      "landing.convert.faq3.q": "Acest instrument este gratuit pentru conversia în masă?",
      "landing.convert.faq3.a": "Da! Puteți converti sute de imagini gratuit.",
      "landing.convert.faq4.q": "Fișierele mele convertite sunt private?",
      "landing.convert.faq4.a": "Complet privat. Totul are loc în browser-ul tău."
    }
  },
  hu: {
    watermark: { heroBadge: "MÁRKAVÉDELEM", heroTitle: "Védje munkáját.", heroTitle2: "Építse fel arculatát.", heroDesc: "Alkalmazzon testreszabható vízjeleket szellemi tulajdona védelme érdekében.", feat1Title: "Roncsolásmentes rétegek", feat1Desc: "Adjon hozzá több vízjel réteget az eredeti kép megváltoztatása nélkül.", feat2Title: "Átlátszóság vezérlése", feat2Desc: "Finomhangolja a szöveg vagy logó átlátszóságát.", feat3Title: "Minta mód", feat3Desc: "Automatikusan ismételje meg a vízjelet a teljes képen.", stepsTag: "MUNKAfolyamat", stepsTitle: "Védelem 3 lépésben", s1Title: "Feltöltés", s1Desc: "Töltse be eredeti fényképeit biztonságosan a böngészőbe.", s2Title: "Bélyegző", s2Desc: "Alkalmazza egyéni szövegét vagy logóját.", s3Title: "Exportálás", s3Desc: "Azonnal mentse el a védett képeket." },
    blurface: { heroBadge: "TELJES MAGÁNSZFÉRA", heroTitle: "Cenzúrázás MI-vel.", heroTitle2: "Identitások védelme.", heroDesc: "Automatikusan észlelje és homályosítsa el az arcokat másodpercek alatt. 100% privát.", feat1Title: "Arcfelismerés", feat1Desc: "Helyi MI modellünk hihetetlen pontossággal találja meg az arcokat.", feat2Title: "Intelligens elmosódás", feat2Desc: "Alkalmazzon Gauss-elmosódást az érzékeny területek elrejtéséhez.", feat3Title: "Kézi vezérlés", feat3Desc: "El kell rejtenie egy dokumentumot? Használja kézi eszközünket.", stepsTag: "HOGYAN MŰKÖDIK", stepsTitle: "Anonimizálás 3 lépésben", s1Title: "Feltöltés", s1Desc: "Dobjon be fényképeket biztonságosan a böngészőbe.", s2Title: "Felismerés", s2Desc: "Hagyja, hogy az MI automatikusan kiválassza az arcokat.", s3Title: "Mentés", s3Desc: "Töltse le az anonimizált fényképeket." },
    convert: { heroBadge: "UNIVERZÁLIS KOMPATIBILITÁS", heroTitle: "Formátum átalakító.", heroTitle2: "Nulla minőségromlás.", heroDesc: "Zökkenőmentesen konvertáljon WebP, PNG, JPG és AVIF között.", feat1Title: "Villámgyors", feat1Desc: "Azonnal alakítsa át a nagy fájlokat az eszköze teljesítményét használva.", feat2Title: "Tömeges feldolgozás", feat2Desc: "500 képet kell konvertálnia? Csak húzza be a teljes mappát.", feat3Title: "Széleskörű támogatás", feat3Desc: "Teljes támogatás a következő generációs formátumokhoz, mint a WebP.", stepsTag: "MUNKAfolyamat", stepsTitle: "Konvertálás 3 lépésben", s1Title: "Feltöltés", s1Desc: "Húzza be a képeket a munkaterületre.", s2Title: "Formátum", s2Desc: "Válassza ki a kívánt kimeneti formátumot.", s3Title: "Exportálás", s3Desc: "Kattintson az exportálásra, és azonnal megkapja fájljait." },
    faqs: {
      "landing.watermark.faq1.q": "Több fotót is vízjelezhetek?",
      "landing.watermark.faq1.a": "Igen! A kötegelt feldolgozás segítségével gyorsan és egyszerűen vízjelezhet több száz fotót.",
      "landing.watermark.faq2.q": "Biztonságban vannak az eredeti fotóim?",
      "landing.watermark.faq2.a": "Igen, a folyamat 100%-ban privát és helyi.",
      "landing.watermark.faq3.q": "Használhatom a saját logómat?",
      "landing.watermark.faq3.a": "Természetesen. Feltölthet egyedi PNG logókat vagy használhat szöveget.",
      "landing.watermark.faq4.q": "Van korlát a fotók számára vonatkozóan?",
      "landing.watermark.faq4.a": "Nincsenek korlátok! Az eszközt ingyenesen használhatja.",
      "landing.blurface.faq1.q": "Több arcot is felismer?",
      "landing.blurface.faq1.a": "Igen, a helyi MI gyorsan felismer és elmos több arcot is.",
      "landing.blurface.faq2.q": "Privát az arcfelismerés?",
      "landing.blurface.faq2.a": "100%-ban privát. Az MI modell közvetlenül a böngészőjében fut.",
      "landing.blurface.faq3.q": "Fizetnem kell az MI használatáért?",
      "landing.blurface.faq3.a": "Nem, az eszközünk teljesen ingyenes.",
      "landing.blurface.faq4.q": "Könnyű beállítani az elmosódás intenzitását?",
      "landing.blurface.faq4.a": "Igen, teljes irányítással rendelkezik az elmosódás sugara felett.",
      "landing.convert.faq1.q": "Milyen formátumok támogatottak?",
      "landing.convert.faq1.a": "Támogatjuk a WebP, PNG, JPEG és más formátumokat.",
      "landing.convert.faq2.q": "Gyors a konvertálás?",
      "landing.convert.faq2.a": "Rendkívül gyors. Helyben, ezredmásodpercek alatt történik.",
      "landing.convert.faq3.q": "Ez az eszköz ingyenes a tömeges konvertáláshoz?",
      "landing.convert.faq3.a": "Igen! Több száz képet konvertálhat ingyenesen.",
      "landing.convert.faq4.q": "Privátak a konvertált fájljaim?",
      "landing.convert.faq4.a": "Teljesen privát. Minden közvetlenül a böngészőjében történik."
    }
  },
  cs: {
    watermark: { heroBadge: "OCHRANA ZNAČKY", heroTitle: "Chraňte svou práci.", heroTitle2: "Budujte svou identitu.", heroDesc: "Aplikujte přizpůsobitelné vodoznaky k ochraně svého duševního vlastnictví.", feat1Title: "Nedestruktivní vrstvy", feat1Desc: "Přidejte více vrstev vodoznaků bez změny původního obrázku.", feat2Title: "Kontrola neprůhlednosti", feat2Desc: "Vylaďte průhlednost vašeho textu nebo loga.", feat3Title: "Režim vzoru", feat3Desc: "Automaticky opakujte svůj vodoznak po celém obrázku.", stepsTag: "PRACOVNÍ POSTUP", stepsTitle: "Chraňte ve 3 krocích", s1Title: "Nahrát", s1Desc: "Bezpečně načtěte původní fotografie do prohlížeče.", s2Title: "Razítko", s2Desc: "Aplikujte svůj vlastní text nebo logo.", s3Title: "Exportovat", s3Desc: "Okamžitě uložte chráněné obrázky." },
    blurface: { heroBadge: "MAXIMÁLNÍ SOUKROMÍ", heroTitle: "Cenzurujte pomocí AI.", heroTitle2: "Chraňte identity.", heroDesc: "Automaticky detekujte a rozostřete tváře během několika sekund. 100% soukromé.", feat1Title: "Detekce obličejů", feat1Desc: "Náš lokální model AI nachází tváře s neuvěřitelnou přesností.", feat2Title: "Chytré rozostření", feat2Desc: "Aplikujte Gaussovo rozostření pro skrytí citlivých oblastí.", feat3Title: "Manuální ovládání", feat3Desc: "Potřebujete skrýt dokument? Použijte náš manuální nástroj.", stepsTag: "JAK TO FUNGUJE", stepsTitle: "Anonymizujte ve 3 krocích", s1Title: "Nahrát", s1Desc: "Přetáhněte fotografie bezpečně do prohlížeče.", s2Title: "Detekovat", s2Desc: "Nechte AI automaticky vybrat tváře.", s3Title: "Uložit", s3Desc: "Stáhněte si anonymizované fotografie." },
    convert: { heroBadge: "UNIVERZÁLNÍ KOMPATIBILITA", heroTitle: "Transformátor formátů.", heroTitle2: "Nulová ztráta kvality.", heroDesc: "Bezproblémově převádějte mezi WebP, PNG, JPG a AVIF.", feat1Title: "Bleskurychle", feat1Desc: "Okamžitě transformujte velké soubory pomocí výkonu vašeho zařízení.", feat2Title: "Hromadné zpracování", feat2Desc: "Potřebujete převést 500 obrázků? Stačí přetáhnout celou složku.", feat3Title: "Široká podpora", feat3Desc: "Plná podpora pro formáty nové generace, jako je WebP.", stepsTag: "PRACOVNÍ POSTUP", stepsTitle: "Převést ve 3 krocích", s1Title: "Nahrát", s1Desc: "Přetáhněte a pusťte své obrázky do pracovního prostoru.", s2Title: "Formát", s2Desc: "Vyberte požadovaný výstupní formát.", s3Title: "Exportovat", s3Desc: "Klikněte na exportovat a okamžitě získejte své soubory." },
    faqs: {
      "landing.watermark.faq1.q": "Mohu přidat vodoznak k více fotografiím?",
      "landing.watermark.faq1.a": "Ano! Hromadné zpracování umožňuje rychle a snadno přidat vodoznak ke stovkám fotografií.",
      "landing.watermark.faq2.q": "Jsou mé původní fotografie v bezpečí?",
      "landing.watermark.faq2.a": "Ano, proces je 100% soukromý a lokální.",
      "landing.watermark.faq3.q": "Mohu použít vlastní logo?",
      "landing.watermark.faq3.a": "Absolutně. Můžete nahrát vlastní PNG loga nebo použít text.",
      "landing.watermark.faq4.q": "Existuje limit na počet fotografií?",
      "landing.watermark.faq4.a": "Žádné limity! Nástroj můžete používat zdarma.",
      "landing.blurface.faq1.q": "Detekuje více tváří?",
      "landing.blurface.faq1.a": "Ano, naše lokální AI může velmi rychle rozostřit více tváří.",
      "landing.blurface.faq2.q": "Je detekce obličeje soukromá?",
      "landing.blurface.faq2.a": "100% soukromé. Model AI běží přímo ve vašem prohlížeči.",
      "landing.blurface.faq3.q": "Musím za používání AI platit?",
      "landing.blurface.faq3.a": "Ne, náš nástroj je zcela zdarma.",
      "landing.blurface.faq4.q": "Je snadné upravit intenzitu rozostření?",
      "landing.blurface.faq4.a": "Ano, máte plnou kontrolu nad poloměrem rozostření.",
      "landing.convert.faq1.q": "Jaké formáty jsou podporovány?",
      "landing.convert.faq1.a": "Podporujeme WebP, PNG, JPEG a další.",
      "landing.convert.faq2.q": "Je převod rychlý?",
      "landing.convert.faq2.a": "Extrémně rychlý. Probíhá lokálně v milisekundách.",
      "landing.convert.faq3.q": "Je tento nástroj zdarma pro hromadný převod?",
      "landing.convert.faq3.a": "Ano! Můžete převést stovky obrázků zdarma.",
      "landing.convert.faq4.q": "Jsou mé převedené soubory soukromé?",
      "landing.convert.faq4.a": "Zcela soukromé. Vše se odehrává ve vašem prohlížeči."
    }
  }
};
module.exports = translationsPart2;
