const translationsPart3 = {
  el: {
    watermark: { heroBadge: "ΠΡΟΣΤΑΣΙΑ ΕΠΩΝΥΜΙΑΣ", heroTitle: "Προστατέψτε τη Δουλειά σας.", heroTitle2: "Χτίστε την Ταυτότητά σας.", heroDesc: "Εφαρμόστε εξαιρετικά προσαρμόσιμα υδατογραφήματα για να προστατεύσετε την πνευματική σας ιδιοκτησία.", feat1Title: "Μη καταστροφικά επίπεδα", feat1Desc: "Προσθέστε πολλαπλά υδατογραφήματα χωρίς να αλλάξετε την αρχική εικόνα.", feat2Title: "Έλεγχος αδιαφάνειας", feat2Desc: "Προσαρμόστε τη διαφάνεια του κειμένου ή του λογότυπου σας.", feat3Title: "Λειτουργία μοτίβου", feat3Desc: "Επαναλάβετε αυτόματα το υδατογράφημά σας σε όλη την εικόνα.", stepsTag: "ΡΟΗ ΕΡΓΑΣΙΑΣ", stepsTitle: "Προστασία σε 3 βήματα", s1Title: "Μεταφόρτωση", s1Desc: "Φορτώστε τις αρχικές φωτογραφίες σας με ασφάλεια στο πρόγραμμα περιήγησης.", s2Title: "Σφραγίδα", s2Desc: "Εφαρμόστε το προσαρμοσμένο κείμενο ή το λογότυπό σας.", s3Title: "Εξαγωγή", s3Desc: "Αποθηκεύστε άμεσα τις προστατευμένες εικόνες." },
    blurface: { heroBadge: "ΑΠΟΛΥΤΟ ΑΠΟΡΡΗΤΟ", heroTitle: "Λογοκρισία με AI.", heroTitle2: "Προστατέψτε τις ταυτότητες.", heroDesc: "Ανιχνεύστε και θολώστε αυτόματα πρόσωπα σε δευτερόλεπτα. 100% ιδιωτικό.", feat1Title: "Ανίχνευση προσώπου", feat1Desc: "Το τοπικό μας μοντέλο AI βρίσκει πρόσωπα με απίστευτη ακρίβεια.", feat2Title: "Έξυπνο θόλωμα", feat2Desc: "Εφαρμόστε θόλωμα Gaussian για να κρύψετε ευαίσθητες περιοχές.", feat3Title: "Χειροκίνητος έλεγχος", feat3Desc: "Πρέπει να κρύψετε ένα έγγραφο; Χρησιμοποιήστε το χειροκίνητο εργαλείο μας.", stepsTag: "ΠΩΣ ΛΕΙΤΟΥΡΓΕΙ", stepsTitle: "Ανωνυμοποίηση σε 3 βήματα", s1Title: "Μεταφόρτωση", s1Desc: "Αποθέστε τις φωτογραφίες με ασφάλεια στο πρόγραμμα περιήγησης.", s2Title: "Ανίχνευση", s2Desc: "Αφήστε το AI να επιλέξει αυτόματα τα πρόσωπα.", s3Title: "Αποθήκευση", s3Desc: "Κατεβάστε τις ανωνυμοποιημένες φωτογραφίες." },
    convert: { heroBadge: "ΚΑΘΟΛΙΚΗ ΣΥΜΒΑΤΟΤΗΤΑ", heroTitle: "Μετατροπέας Μορφών.", heroTitle2: "Μηδενική απώλεια ποιότητας.", heroDesc: "Μετατρέψτε απρόσκοπτα μεταξύ WebP, PNG, JPG και AVIF.", feat1Title: "Αστραπιαία", feat1Desc: "Μετατρέψτε μεγάλα αρχεία άμεσα χρησιμοποιώντας τη δύναμη της συσκευής σας.", feat2Title: "Μαζική επεξεργασία", feat2Desc: "Πρέπει να μετατρέψετε 500 εικόνες; Απλώς σύρετε ολόκληρο το φάκελο.", feat3Title: "Ευρεία υποστήριξη", feat3Desc: "Πλήρης υποστήριξη για μορφές νέας γενιάς όπως το WebP.", stepsTag: "ΡΟΗ ΕΡΓΑΣΙΑΣ", stepsTitle: "Μετατροπή σε 3 βήματα", s1Title: "Μεταφόρτωση", s1Desc: "Σύρετε και αποθέστε τις εικόνες σας στο χώρο εργασίας.", s2Title: "Μορφή", s2Desc: "Επιλέξτε την επιθυμητή μορφή εξόδου.", s3Title: "Εξαγωγή", s3Desc: "Κάντε κλικ στην εξαγωγή και λάβετε τα αρχεία σας αμέσως." },
    faqs: {
      "landing.watermark.faq1.q": "Μπορώ να προσθέσω υδατογράφημα σε πολλές φωτογραφίες;",
      "landing.watermark.faq1.a": "Ναι! Η μαζική επεξεργασία επιτρέπει τη γρήγορη προσθήκη υδατογραφημάτων σε εκατοντάδες φωτογραφίες.",
      "landing.watermark.faq2.q": "Είναι ασφαλείς οι αρχικές μου φωτογραφίες;",
      "landing.watermark.faq2.a": "Ναι, η διαδικασία είναι 100% ιδιωτική και τοπική.",
      "landing.watermark.faq3.q": "Μπορώ να χρησιμοποιήσω το δικό μου λογότυπο;",
      "landing.watermark.faq3.a": "Απολύτως. Μπορείτε να ανεβάσετε προσαρμοσμένα λογότυπα PNG.",
      "landing.watermark.faq4.q": "Υπάρχει όριο στον αριθμό των φωτογραφιών;",
      "landing.watermark.faq4.a": "Χωρίς όρια! Το εργαλείο είναι εντελώς δωρεάν.",
      "landing.blurface.faq1.q": "Ανιχνεύει πολλαπλά πρόσωπα;",
      "landing.blurface.faq1.a": "Ναι, το AI μας μπορεί να ανιχνεύσει και να θολώσει γρήγορα πολλά πρόσωπα.",
      "landing.blurface.faq2.q": "Είναι ιδιωτική η ανίχνευση προσώπου;",
      "landing.blurface.faq2.a": "100% ιδιωτικό. Το μοντέλο AI τρέχει στο πρόγραμμα περιήγησής σας.",
      "landing.blurface.faq3.q": "Πρέπει να πληρώσω για το AI;",
      "landing.blurface.faq3.a": "Όχι, το εργαλείο μας είναι εντελώς δωρεάν.",
      "landing.blurface.faq4.q": "Είναι εύκολο να προσαρμοστεί η θολούρα;",
      "landing.blurface.faq4.a": "Ναι, έχετε πλήρη έλεγχο στην ακτίνα θολώματος.",
      "landing.convert.faq1.q": "Ποιες μορφές υποστηρίζονται;",
      "landing.convert.faq1.a": "Υποστηρίζουμε WebP, PNG, JPEG και άλλα.",
      "landing.convert.faq2.q": "Είναι γρήγορη η μετατροπή;",
      "landing.convert.faq2.a": "Εξαιρετικά γρήγορη. Γίνεται τοπικά σε χιλιοστά του δευτερολέπτου.",
      "landing.convert.faq3.q": "Είναι δωρεάν για μαζική μετατροπή;",
      "landing.convert.faq3.a": "Ναι! Μπορείτε να μετατρέψετε εκατοντάδες εικόνες δωρεάν.",
      "landing.convert.faq4.q": "Είναι ιδιωτικά τα αρχεία μου;",
      "landing.convert.faq4.a": "Εντελώς ιδιωτικά. Όλα γίνονται στο πρόγραμμα περιήγησής σας."
    }
  },
  sv: {
    watermark: { heroBadge: "VARUMÄRKESSKYDD", heroTitle: "Skydda ditt arbete.", heroTitle2: "Bygg din identitet.", heroDesc: "Applicera anpassningsbara vattenstämplar för att skydda din immateriella egendom.", feat1Title: "Icke-destruktiva lager", feat1Desc: "Lägg till flera vattenstämpellager utan att ändra din originalbild.", feat2Title: "Opacitetskontroll", feat2Desc: "Finjustera transparensen för din text eller logotyp.", feat3Title: "Mönsterläge", feat3Desc: "Upprepa din vattenstämpel automatiskt över hela bilden.", stepsTag: "ARBETSFLÖDE", stepsTitle: "Skydda i 3 steg", s1Title: "Ladda upp", s1Desc: "Ladda dina originalbilder säkert i webbläsaren.", s2Title: "Stämpel", s2Desc: "Applicera din anpassade text eller logotyp.", s3Title: "Exportera", s3Desc: "Spara de skyddade bilderna direkt." },
    blurface: { heroBadge: "ULTIMAT INTEGRITET", heroTitle: "Censurera med AI.", heroTitle2: "Skydda identiteter.", heroDesc: "Upptäck och oskärpa ansikten automatiskt på några sekunder. 100% privat.", feat1Title: "Ansiktsigenkänning", feat1Desc: "Vår lokala AI-modell hittar ansikten med otrolig noggrannhet.", feat2Title: "Smart oskärpa", feat2Desc: "Applicera gaussisk oskärpa för att dölja känsliga områden.", feat3Title: "Manuell kontroll", feat3Desc: "Behöver du dölja ett dokument? Använd vårt manuella verktyg.", stepsTag: "HUR DET FUNGERAR", stepsTitle: "Anonymisera i 3 steg", s1Title: "Ladda upp", s1Desc: "Släpp foton säkert i webbläsaren.", s2Title: "Upptäck", s2Desc: "Låt AI välja ansikten automatiskt.", s3Title: "Spara", s3Desc: "Ladda ner de anonymiserade bilderna." },
    convert: { heroBadge: "UNIVERSELL KOMPATIBILITET", heroTitle: "Formatomvandlare.", heroTitle2: "Ingen kvalitetsförlust.", heroDesc: "Konvertera sömlöst mellan WebP, PNG, JPG och AVIF.", feat1Title: "Blixtsnabbt", feat1Desc: "Transformera stora filer direkt med hjälp av din enhets kraft.", feat2Title: "Satsvis bearbetning", feat2Desc: "Behöver du konvertera 500 bilder? Dra bara hela mappen.", feat3Title: "Brett stöd", feat3Desc: "Fullt stöd för nästa generations format som WebP.", stepsTag: "ARBETSFLÖDE", stepsTitle: "Konvertera i 3 steg", s1Title: "Ladda upp", s1Desc: "Dra och släpp dina bilder på arbetsytan.", s2Title: "Format", s2Desc: "Välj önskat utdataformat.", s3Title: "Exportera", s3Desc: "Klicka på exportera och få dina filer direkt." },
    faqs: {
      "landing.watermark.faq1.q": "Kan jag lägga till vattenstämpel på flera foton?",
      "landing.watermark.faq1.a": "Ja! Vår satsvisa bearbetning gör det enkelt att hantera hundratals foton.",
      "landing.watermark.faq2.q": "Är mina originalfoton säkra?",
      "landing.watermark.faq2.a": "Ja, processen är 100% privat och lokal.",
      "landing.watermark.faq3.q": "Kan jag använda min egen logotyp?",
      "landing.watermark.faq3.a": "Absolut. Du kan ladda upp egna PNG-logotyper.",
      "landing.watermark.faq4.q": "Finns det en gräns för antalet foton?",
      "landing.watermark.faq4.a": "Inga gränser! Du kan använda det gratis.",
      "landing.blurface.faq1.q": "Upptäcker den flera ansikten?",
      "landing.blurface.faq1.a": "Ja, vår AI kan snabbt upptäcka och oskärpa flera ansikten.",
      "landing.blurface.faq2.q": "Är ansiktsigenkänningen privat?",
      "landing.blurface.faq2.a": "100% privat. AI-modellen körs i din webbläsare.",
      "landing.blurface.faq3.q": "Måste jag betala för AI?",
      "landing.blurface.faq3.a": "Nej, vårt verktyg är helt gratis.",
      "landing.blurface.faq4.q": "Är det enkelt att justera oskärpan?",
      "landing.blurface.faq4.a": "Ja, du har full kontroll över radien.",
      "landing.convert.faq1.q": "Vilka format stöds?",
      "landing.convert.faq1.a": "Vi stöder WebP, PNG, JPEG och mer.",
      "landing.convert.faq2.q": "Är konverteringen snabb?",
      "landing.convert.faq2.a": "Extremt snabb. Det sker lokalt i millisekunder.",
      "landing.convert.faq3.q": "Är det gratis för satsvis konvertering?",
      "landing.convert.faq3.a": "Ja! Du kan konvertera hundratals bilder gratis.",
      "landing.convert.faq4.q": "Är mina filer privata?",
      "landing.convert.faq4.a": "Helt privata. Allt sker i din webbläsare."
    }
  },
  bg: {
    watermark: { heroBadge: "ЗАЩИТА НА МАРКАТА", heroTitle: "Защитете работата си.", heroTitle2: "Изградете своята идентичност.", heroDesc: "Прилагайте персонализируеми водни знаци, за да защитите интелектуалната си собственост.", feat1Title: "Неразрушаващи слоеве", feat1Desc: "Добавете множество слоеве водни знаци, без да променяте оригиналното изображение.", feat2Title: "Контрол на непрозрачността", feat2Desc: "Настройте прозрачността на вашия текст или лого.", feat3Title: "Режим на шаблон", feat3Desc: "Автоматично повтаряйте вашия воден знак върху цялото изображение.", stepsTag: "РАБОТЕН ПРОЦЕС", stepsTitle: "Защитете в 3 стъпки", s1Title: "Качване", s1Desc: "Заредете сигурно оригиналните си снимки в браузъра.", s2Title: "Печат", s2Desc: "Приложете вашия персонализиран текст или лого.", s3Title: "Експортиране", s3Desc: "Запазете защитените изображения незабавно." },
    blurface: { heroBadge: "МАКСИМАЛНА ПОВЕРИТЕЛНОСТ", heroTitle: "Цензура с AI.", heroTitle2: "Защитете самоличностите.", heroDesc: "Автоматично откривайте и размазвайте лица за секунди. 100% поверително.", feat1Title: "Откриване на лица", feat1Desc: "Нашият локален AI модел намира лица с невероятна точност.", feat2Title: "Интелигентно размазване", feat2Desc: "Приложете Гаусово размазване, за да скриете чувствителни зони.", feat3Title: "Ръчен контрол", feat3Desc: "Трябва да скриете документ? Използвайте нашия ръчен инструмент.", stepsTag: "КАК РАБОТИ", stepsTitle: "Анонимизирайте в 3 стъпки", s1Title: "Качване", s1Desc: "Пуснете снимките сигурно в браузъра.", s2Title: "Откриване", s2Desc: "Оставете AI автоматично да избере лицата.", s3Title: "Запазване", s3Desc: "Изтеглете анонимизираните снимки." },
    convert: { heroBadge: "УНИВЕРСАЛНА СЪВМЕСТИМОСТ", heroTitle: "Трансформатор на формати.", heroTitle2: "Нулева загуба на качество.", heroDesc: "Безпроблемно конвертирайте между WebP, PNG, JPG и AVIF.", feat1Title: "Светкавично бързо", feat1Desc: "Трансформирайте големи файлове, използвайки мощността на вашето устройство.", feat2Title: "Масова обработка", feat2Desc: "Трябва да конвертирате 500 изображения? Просто плъзнете цялата папка.", feat3Title: "Широка поддръжка", feat3Desc: "Пълна поддръжка за формати от ново поколение като WebP.", stepsTag: "РАБОТЕН ПРОЦЕС", stepsTitle: "Конвертирайте в 3 стъпки", s1Title: "Качване", s1Desc: "Плъзнете и пуснете вашите изображения в работната област.", s2Title: "Формат", s2Desc: "Изберете желания изходен формат.", s3Title: "Експортиране", s3Desc: "Кликнете върху експортиране и получете файловете си веднага." },
    faqs: {
      "landing.watermark.faq1.q": "Мога ли да добавя воден знак към множество снимки?",
      "landing.watermark.faq1.a": "Да! Масовата обработка позволява бързо поставяне на воден знак.",
      "landing.watermark.faq2.q": "В безопасност ли са оригиналните ми снимки?",
      "landing.watermark.faq2.a": "Да, процесът е 100% поверителен и локален.",
      "landing.watermark.faq3.q": "Мога ли да използвам собствено лого?",
      "landing.watermark.faq3.a": "Абсолютно. Можете да качвате персонализирани PNG лога.",
      "landing.watermark.faq4.q": "Има ли ограничение за броя снимки?",
      "landing.watermark.faq4.a": "Без ограничения! Можете да го използвате безплатно.",
      "landing.blurface.faq1.q": "Открива ли множество лица?",
      "landing.blurface.faq1.a": "Да, нашият AI може бързо да открие и размаже множество лица.",
      "landing.blurface.faq2.q": "Поверително ли е откриването на лица?",
      "landing.blurface.faq2.a": "100% поверително. AI работи директно във вашия браузър.",
      "landing.blurface.faq3.q": "Трябва ли да плащам за AI?",
      "landing.blurface.faq3.a": "Не, нашият инструмент е напълно безплатен.",
      "landing.blurface.faq4.q": "Лесно ли е да се регулира размазването?",
      "landing.blurface.faq4.a": "Да, имате пълен контрол върху радиуса на размазване.",
      "landing.convert.faq1.q": "Кои формати се поддържат?",
      "landing.convert.faq1.a": "Поддържаме WebP, PNG, JPEG и други.",
      "landing.convert.faq2.q": "Бързо ли е конвертирането?",
      "landing.convert.faq2.a": "Изключително бързо. Случва се локално за милисекунди.",
      "landing.convert.faq3.q": "Безплатен ли е инструментът за масово конвертиране?",
      "landing.convert.faq3.a": "Да! Можете да конвертирате стотици изображения безплатно.",
      "landing.convert.faq4.q": "Поверителни ли са файловете ми?",
      "landing.convert.faq4.a": "Напълно поверителни. Всичко се случва във вашия браузър."
    }
  },
  da: {
    watermark: { heroBadge: "BRANDBESKYTTELSE", heroTitle: "Beskyt dit arbejde.", heroTitle2: "Opbyg din identitet.", heroDesc: "Anvend tilpasselige vandmærker for at beskytte din intellektuelle ejendom.", feat1Title: "Ikke-destruktive lag", feat1Desc: "Tilføj flere lag uden at ændre dit originale billede.", feat2Title: "Opacitetskontrol", feat2Desc: "Finjuster gennemsigtigheden af din tekst eller dit logo.", feat3Title: "Mønstertilstand", feat3Desc: "Gentag automatisk dit vandmærke over hele billedet.", stepsTag: "ARBEJDSGANG", stepsTitle: "Beskyt i 3 trin", s1Title: "Upload", s1Desc: "Indlæs dine billeder sikkert i browseren.", s2Title: "Stempel", s2Desc: "Anvend din brugerdefinerede tekst eller logo.", s3Title: "Eksport", s3Desc: "Gem de beskyttede billeder med det samme." },
    blurface: { heroBadge: "ULTIMATIVT PRIVATLIV", heroTitle: "Censurer med AI.", heroTitle2: "Beskyt identiteter.", heroDesc: "Opdag og slør automatisk ansigter på få sekunder. 100% privat.", feat1Title: "Ansiktsgenkendelse", feat1Desc: "Vores lokale AI-model finder ansigter med utrolig nøjagtighed.", feat2Title: "Smart sløring", feat2Desc: "Anvend Gaussisk sløring for at skjule følsomme områder.", feat3Title: "Manuel kontrol", feat3Desc: "Brug for at skjule et dokument? Brug vores manuelle værktøj.", stepsTag: "SÅDAN VIRKER DET", stepsTitle: "Anonymiser i 3 trin", s1Title: "Upload", s1Desc: "Slip billeder sikkert i browseren.", s2Title: "Opdag", s2Desc: "Lad AI vælge ansigter automatisk.", s3Title: "Gem", s3Desc: "Download de anonymiserede billeder." },
    convert: { heroBadge: "UNIVERSEL KOMPATIBILITET", heroTitle: "Format Transformer.", heroTitle2: "Nul kvalitetstab.", heroDesc: "Konverter problemfrit mellem WebP, PNG, JPG og AVIF.", feat1Title: "Lynhurtigt", feat1Desc: "Transformer store filer ved hjælp af din enheds kraft.", feat2Title: "Massebehandling", feat2Desc: "Brug for at konvertere 500 billeder? Træk bare hele mappen.", feat3Title: "Bred support", feat3Desc: "Fuld support for næste generations formater som WebP.", stepsTag: "ARBEJDSGANG", stepsTitle: "Konverter i 3 trin", s1Title: "Upload", s1Desc: "Træk og slip dine billeder i arbejdsområdet.", s2Title: "Format", s2Desc: "Vælg det ønskede outputformat.", s3Title: "Eksport", s3Desc: "Klik på eksport og få dine filer med det samme." },
    faqs: {
      "landing.watermark.faq1.q": "Kan jeg tilføje vandmærke på flere billeder?",
      "landing.watermark.faq1.a": "Ja! Vores massebehandling gør det nemt at håndtere hundredvis af billeder.",
      "landing.watermark.faq2.q": "Er mine originale billeder sikre?",
      "landing.watermark.faq2.a": "Ja, processen er 100% privat og lokal.",
      "landing.watermark.faq3.q": "Kan jeg bruge mit eget logo?",
      "landing.watermark.faq3.a": "Absolut. Du kan uploade brugerdefinerede PNG-logoer.",
      "landing.watermark.faq4.q": "Er der en grænse for antallet af billeder?",
      "landing.watermark.faq4.a": "Ingen grænser! Du kan bruge det gratis.",
      "landing.blurface.faq1.q": "Opdager den flere ansigter?",
      "landing.blurface.faq1.a": "Ja, vores AI kan hurtigt opdage og sløre flere ansigter.",
      "landing.blurface.faq2.q": "Er ansigtsgenkendelsen privat?",
      "landing.blurface.faq2.a": "100% privat. AI-modellen kører i din browser.",
      "landing.blurface.faq3.q": "Skal jeg betale for AI?",
      "landing.blurface.faq3.a": "Nej, vores værktøj er helt gratis.",
      "landing.blurface.faq4.q": "Er det nemt at justere sløringen?",
      "landing.blurface.faq4.a": "Ja, du har fuld kontrol over radius.",
      "landing.convert.faq1.q": "Hvilke formater understøttes?",
      "landing.convert.faq1.a": "Vi understøtter WebP, PNG, JPEG og mere.",
      "landing.convert.faq2.q": "Er konverteringen hurtig?",
      "landing.convert.faq2.a": "Ekstremt hurtig. Det sker lokalt i millisekunder.",
      "landing.convert.faq3.q": "Er det gratis for massekonvertering?",
      "landing.convert.faq3.a": "Ja! Du kan konvertere hundredvis af billeder gratis.",
      "landing.convert.faq4.q": "Er mine filer private?",
      "landing.convert.faq4.a": "Helt private. Alt sker i din browser."
    }
  },
  fi: {
    watermark: { heroBadge: "BRÄNDIN SUOJAUS", heroTitle: "Suojaa työsi.", heroTitle2: "Rakenna identiteettisi.", heroDesc: "Käytä mukautettavia vesileimoja immateriaalioikeuksiesi suojaamiseksi.", feat1Title: "Tuhoamattomat tasot", feat1Desc: "Lisää useita vesileimatasoja muuttamatta alkuperäistä kuvaa.", feat2Title: "Läpinäkyvyyden hallinta", feat2Desc: "Hienosäädä tekstin tai logon läpinäkyvyyttä.", feat3Title: "Kuviotila", feat3Desc: "Toista vesileima automaattisesti koko kuvassa.", stepsTag: "TYÖNKULKU", stepsTitle: "Suojaa 3 vaiheessa", s1Title: "Lataa", s1Desc: "Lataa alkuperäiset valokuvasi turvallisesti selaimeen.", s2Title: "Leima", s2Desc: "Käytä mukautettua tekstiä tai logoa.", s3Title: "Vie", s3Desc: "Tallenna suojatut kuvat välittömästi." },
    blurface: { heroBadge: "TÄYDELLINEN YKSITYISYYS", heroTitle: "Sensuroi tekoälyllä.", heroTitle2: "Suojaa identiteetit.", heroDesc: "Tunnista ja sumenna kasvot automaattisesti sekunneissa. 100% yksityinen.", feat1Title: "Kasvojentunnistus", feat1Desc: "Paikallinen tekoälymallimme löytää kasvot uskomattomalla tarkkuudella.", feat2Title: "Älykäs sumennus", feat2Desc: "Käytä Gaussin sumennusta herkkien alueiden piilottamiseen.", feat3Title: "Manuaalinen hallinta", feat3Desc: "Tarvitseeko asiakirja piilottaa? Käytä manuaalista työkalua.", stepsTag: "KUINKA SE TOIMII", stepsTitle: "Anonymisoi 3 vaiheessa", s1Title: "Lataa", s1Desc: "Pudota valokuvat turvallisesti selaimeen.", s2Title: "Tunnista", s2Desc: "Anna tekoälyn valita kasvot automaattisesti.", s3Title: "Tallenna", s3Desc: "Lataa anonymisoidut valokuvat." },
    convert: { heroBadge: "YLEINEN YHTEENSOPIVUUS", heroTitle: "Muodonmuunnin.", heroTitle2: "Nolla laadun heikkenemistä.", heroDesc: "Muunna saumattomasti WebP, PNG, JPG ja AVIF välillä.", feat1Title: "Salamannopea", feat1Desc: "Muunna suuret tiedostot välittömästi laitteesi teholla.", feat2Title: "Eräajo", feat2Desc: "Tarvitseeko muuntaa 500 kuvaa? Vedä vain koko kansio.", feat3Title: "Laaja tuki", feat3Desc: "Täysi tuki uuden sukupolven muodoille kuten WebP.", stepsTag: "TYÖNKULKU", stepsTitle: "Muunna 3 vaiheessa", s1Title: "Lataa", s1Desc: "Vedä ja pudota kuvat työtilaan.", s2Title: "Muoto", s2Desc: "Valitse haluamasi tulostusmuoto.", s3Title: "Vie", s3Desc: "Napsauta vie ja saat tiedostot heti." },
    faqs: {
      "landing.watermark.faq1.q": "Voinko lisätä vesileiman useisiin kuviin?",
      "landing.watermark.faq1.a": "Kyllä! Eräajo tekee sadan kuvan käsittelystä helppoa.",
      "landing.watermark.faq2.q": "Ovatko alkuperäiset kuvani turvassa?",
      "landing.watermark.faq2.a": "Kyllä, prosessi on 100% yksityinen ja paikallinen.",
      "landing.watermark.faq3.q": "Voinko käyttää omaa logoani?",
      "landing.watermark.faq3.a": "Ehdottomasti. Voit ladata mukautettuja PNG-logoja.",
      "landing.watermark.faq4.q": "Onko kuvien määrällä rajaa?",
      "landing.watermark.faq4.a": "Ei rajoja! Voit käyttää sitä ilmaiseksi.",
      "landing.blurface.faq1.q": "Tunnistaako se useita kasvoja?",
      "landing.blurface.faq1.a": "Kyllä, tekoälymme tunnistaa ja sumentaa useita kasvoja nopeasti.",
      "landing.blurface.faq2.q": "Onko kasvojentunnistus yksityinen?",
      "landing.blurface.faq2.a": "100% yksityinen. Tekoäly toimii selaimessasi.",
      "landing.blurface.faq3.q": "Pitääkö tekoälystä maksaa?",
      "landing.blurface.faq3.a": "Ei, työkalu on täysin ilmainen.",
      "landing.blurface.faq4.q": "Onko sumennusta helppo säätää?",
      "landing.blurface.faq4.a": "Kyllä, sinulla on täysi hallinta säteeseen.",
      "landing.convert.faq1.q": "Mitä muotoja tuetaan?",
      "landing.convert.faq1.a": "Tuemme WebP, PNG, JPEG ja muuta.",
      "landing.convert.faq2.q": "Onko muunnos nopea?",
      "landing.convert.faq2.a": "Erittäin nopea. Se tapahtuu paikallisesti millisekunneissa.",
      "landing.convert.faq3.q": "Onko tämä työkalu ilmainen eräajolle?",
      "landing.convert.faq3.a": "Kyllä! Voit muuntaa satoja kuvia ilmaiseksi.",
      "landing.convert.faq4.q": "Ovatko tiedostoni yksityisiä?",
      "landing.convert.faq4.a": "Täysin yksityisiä. Kaikki tapahtuu selaimessasi."
    }
  },
  sk: {
    watermark: { heroBadge: "OCHRANA ZNAČKY", heroTitle: "Chráňte svoju prácu.", heroTitle2: "Budujte svoju identitu.", heroDesc: "Aplikujte prispôsobiteľné vodoznaky na ochranu svojho duševného vlastníctva.", feat1Title: "Nedeštruktívne vrstvy", feat1Desc: "Pridajte viac vrstiev vodoznakov bez zmeny pôvodného obrázka.", feat2Title: "Kontrola nepriehľadnosti", feat2Desc: "Vylaďte priehľadnosť vášho textu alebo loga.", feat3Title: "Režim vzoru", feat3Desc: "Automaticky opakujte svoj vodoznak po celom obrázku.", stepsTag: "PRACOVNÝ POSTUP", stepsTitle: "Chráňte v 3 krokoch", s1Title: "Nahrať", s1Desc: "Bezpečne načítajte pôvodné fotografie do prehliadača.", s2Title: "Pečiatka", s2Desc: "Aplikujte svoj vlastný text alebo logo.", s3Title: "Exportovať", s3Desc: "Okamžite uložte chránené obrázky." },
    blurface: { heroBadge: "MAXIMÁLNE SÚKROMIE", heroTitle: "Cenzúrujte pomocou AI.", heroTitle2: "Chráňte identity.", heroDesc: "Automaticky detekujte a rozostrite tváre v priebehu niekoľkých sekúnd. 100% súkromné.", feat1Title: "Detekcia tvárí", feat1Desc: "Náš lokálny model AI nachádza tváre s neuveriteľnou presnosťou.", feat2Title: "Inteligentné rozostrenie", feat2Desc: "Aplikujte Gaussovo rozostrenie na skrytie citlivých oblastí.", feat3Title: "Manuálne ovládanie", feat3Desc: "Potrebujete skryť dokument? Použite náš manuálny nástroj.", stepsTag: "AKO TO FUNGUJE", stepsTitle: "Anonymizujte v 3 krokoch", s1Title: "Nahrať", s1Desc: "Pretiahnite fotografie bezpečne do prehliadača.", s2Title: "Detegovať", s2Desc: "Nechajte AI automaticky vybrať tváre.", s3Title: "Uložiť", s3Desc: "Stiahnite si anonymizované fotografie." },
    convert: { heroBadge: "UNIVERZÁLNA KOMPATIBILITA", heroTitle: "Transformátor formátov.", heroTitle2: "Nulová strata kvality.", heroDesc: "Bezproblémovo prevádzajte medzi WebP, PNG, JPG a AVIF.", feat1Title: "Bleskurýchlo", feat1Desc: "Okamžite transformujte veľké súbory pomocou výkonu vášho zariadenia.", feat2Title: "Hromadné spracovanie", feat2Desc: "Potrebujete previesť 500 obrázkov? Stačí pretiahnuť celú zložku.", feat3Title: "Široká podpora", feat3Desc: "Plná podpora pre formáty novej generácie ako WebP.", stepsTag: "PRACOVNÝ POSTUP", stepsTitle: "Previesť v 3 krokoch", s1Title: "Nahrať", s1Desc: "Pretiahnite svoje obrázky do pracovného priestoru.", s2Title: "Formát", s2Desc: "Vyberte požadovaný výstupný formát.", s3Title: "Exportovať", s3Desc: "Kliknite na exportovať a okamžite získajte svoje súbory." },
    faqs: {
      "landing.watermark.faq1.q": "Môžem pridať vodoznak na viac fotografií?",
      "landing.watermark.faq1.a": "Áno! Hromadné spracovanie umožňuje rýchlo pridať vodoznak.",
      "landing.watermark.faq2.q": "Sú moje pôvodné fotografie v bezpečí?",
      "landing.watermark.faq2.a": "Áno, proces je 100% súkromný a lokálny.",
      "landing.watermark.faq3.q": "Môžem použiť vlastné logo?",
      "landing.watermark.faq3.a": "Absolútne. Môžete nahrať vlastné PNG logá.",
      "landing.watermark.faq4.q": "Existuje limit na počet fotografií?",
      "landing.watermark.faq4.a": "Žiadne limity! Nástroj môžete používať zadarmo.",
      "landing.blurface.faq1.q": "Deteguje viacero tvárí?",
      "landing.blurface.faq1.a": "Áno, naša lokálna AI môže veľmi rýchlo rozostriť viacero tvárí.",
      "landing.blurface.faq2.q": "Je detekcia tváre súkromná?",
      "landing.blurface.faq2.a": "100% súkromné. Model AI beží vo vašom prehliadači.",
      "landing.blurface.faq3.q": "Musím za používanie AI platiť?",
      "landing.blurface.faq3.a": "Nie, náš nástroj je úplne zadarmo.",
      "landing.blurface.faq4.q": "Je ľahké upraviť intenzitu rozostrenia?",
      "landing.blurface.faq4.a": "Áno, máte plnú kontrolu nad polomerom rozostrenia.",
      "landing.convert.faq1.q": "Aké formáty sú podporované?",
      "landing.convert.faq1.a": "Podporujeme WebP, PNG, JPEG a ďalšie.",
      "landing.convert.faq2.q": "Je prevod rýchly?",
      "landing.convert.faq2.a": "Extrémne rýchly. Prebieha lokálne v milisekundách.",
      "landing.convert.faq3.q": "Je tento nástroj zadarmo na hromadný prevod?",
      "landing.convert.faq3.a": "Áno! Môžete previesť stovky obrázkov zadarmo.",
      "landing.convert.faq4.q": "Sú moje prevedené súbory súkromné?",
      "landing.convert.faq4.a": "Úplne súkromné. Všetko sa odohráva vo vašom prehliadači."
    }
  }
};
module.exports = translationsPart3;
