const translationsPart5 = {
  fr: {
    watermark: { heroBadge: "PROTECTION DE LA MARQUE", heroTitle: "Protégez votre travail.", heroTitle2: "Construisez votre identité.", heroDesc: "Appliquez des filigranes personnalisables pour protéger votre propriété intellectuelle.", feat1Title: "Couches non destructives", feat1Desc: "Ajoutez plusieurs couches de filigrane sans altérer votre image d'origine.", feat2Title: "Contrôle de l'opacité", feat2Desc: "Ajustez la transparence de votre texte ou logo.", feat3Title: "Mode motif", feat3Desc: "Répétez automatiquement votre filigrane sur toute l'image.", stepsTag: "FLUX DE TRAVAIL", stepsTitle: "Protégez en 3 étapes", s1Title: "Télécharger", s1Desc: "Chargez vos photos originales en toute sécurité dans le navigateur.", s2Title: "Tampon", s2Desc: "Appliquez votre texte ou logo personnalisé.", s3Title: "Exporter", s3Desc: "Enregistrez instantanément les images protégées." },
    blurface: { heroBadge: "CONFIDENTIALITÉ TOTALE", heroTitle: "Censurez avec l'IA.", heroTitle2: "Protégez les identités.", heroDesc: "Détectez et floutez automatiquement les visages en quelques secondes. 100% privé.", feat1Title: "Détection de visage", feat1Desc: "Notre modèle d'IA local trouve les visages avec une précision incroyable.", feat2Title: "Floutage intelligent", feat2Desc: "Appliquez un flou gaussien pour masquer les zones sensibles.", feat3Title: "Contrôle manuel", feat3Desc: "Besoin de masquer un document ? Utilisez notre outil manuel.", stepsTag: "COMMENT ÇA MARCHE", stepsTitle: "Anonymisez en 3 étapes", s1Title: "Télécharger", s1Desc: "Déposez les photos en toute sécurité dans le navigateur.", s2Title: "Détecter", s2Desc: "Laissez l'IA sélectionner automatiquement les visages.", s3Title: "Enregistrer", s3Desc: "Téléchargez les photos anonymisées." },
    convert: { heroBadge: "COMPATIBILITÉ UNIVERSELLE", heroTitle: "Transformateur de format.", heroTitle2: "Zéro perte de qualité.", heroDesc: "Convertissez facilement entre WebP, PNG, JPG et AVIF.", feat1Title: "Ultra rapide", feat1Desc: "Transformez les gros fichiers instantanément grâce à la puissance de votre appareil.", feat2Title: "Traitement par lots", feat2Desc: "Besoin de convertir 500 images ? Glissez simplement le dossier complet.", feat3Title: "Large support", feat3Desc: "Support complet des formats de nouvelle génération comme WebP.", stepsTag: "FLUX DE TRAVAIL", stepsTitle: "Convertissez en 3 étapes", s1Title: "Télécharger", s1Desc: "Glissez et déposez vos images dans l'espace de travail.", s2Title: "Format", s2Desc: "Sélectionnez le format de sortie souhaité.", s3Title: "Exporter", s3Desc: "Cliquez sur exporter et obtenez vos fichiers instantanément." },
    faqs: {
      "landing.watermark.faq1.q": "Puis-je ajouter un filigrane à plusieurs photos ?",
      "landing.watermark.faq1.a": "Oui ! Le traitement par lots facilite le filigranage de centaines de photos.",
      "landing.watermark.faq2.q": "Mes photos originales sont-elles en sécurité ?",
      "landing.watermark.faq2.a": "Oui, le processus est 100% privé et local.",
      "landing.watermark.faq3.q": "Puis-je utiliser mon propre logo ?",
      "landing.watermark.faq3.a": "Absolument. Vous pouvez télécharger des logos PNG personnalisés.",
      "landing.watermark.faq4.q": "Y a-t-il une limite au nombre de photos ?",
      "landing.watermark.faq4.a": "Aucune limite ! Vous pouvez l'utiliser gratuitement.",
      "landing.blurface.faq1.q": "Détecte-t-il plusieurs visages ?",
      "landing.blurface.faq1.a": "Oui, notre IA peut détecter et flouter rapidement plusieurs visages.",
      "landing.blurface.faq2.q": "La détection faciale est-elle privée ?",
      "landing.blurface.faq2.a": "100% privé. Le modèle d'IA s'exécute dans votre navigateur.",
      "landing.blurface.faq3.q": "Dois-je payer pour utiliser l'IA ?",
      "landing.blurface.faq3.a": "Non, notre outil est entièrement gratuit.",
      "landing.blurface.faq4.q": "Est-il facile d'ajuster l'intensité du flou ?",
      "landing.blurface.faq4.a": "Oui, vous avez un contrôle total sur le rayon de flou.",
      "landing.convert.faq1.q": "Quels formats sont pris en charge ?",
      "landing.convert.faq1.a": "Nous prenons en charge WebP, PNG, JPEG et bien plus.",
      "landing.convert.faq2.q": "La conversion est-elle rapide ?",
      "landing.convert.faq2.a": "Extrêmement rapide. Cela se produit localement en quelques millisecondes.",
      "landing.convert.faq3.q": "Cet outil est-il gratuit pour la conversion par lots ?",
      "landing.convert.faq3.a": "Oui ! Vous pouvez convertir des centaines d'images gratuitement.",
      "landing.convert.faq4.q": "Mes fichiers convertis sont-ils privés ?",
      "landing.convert.faq4.a": "Totalement privé. Tout se passe dans votre navigateur."
    }
  },
  he: {
    watermark: { heroBadge: "הגנת מותג", heroTitle: "הגן על העבודה שלך.", heroTitle2: "בנה את הזהות שלך.", heroDesc: "החל סימני מים הניתנים להתאמה אישית כדי להגן על הקניין הרוחני שלך.", feat1Title: "שכבות לא הרסניות", feat1Desc: "הוסף מספר שכבות סימן מים מבלי לשנות את התמונה המקורית.", feat2Title: "בקרת אטימות", feat2Desc: "כוונן את שקיפות הטקסט או הלוגו שלך.", feat3Title: "מצב דפוס", feat3Desc: "חזור אוטומטית על סימן המים שלך על פני כל התמונה.", stepsTag: "זרימת עבודה", stepsTitle: "הגן ב-3 שלבים", s1Title: "העלה", s1Desc: "טען את התמונות המקוריות שלך בבטחה בדפדפן.", s2Title: "חותמת", s2Desc: "החל את הטקסט המותאם אישית או הלוגו שלך.", s3Title: "ייצוא", s3Desc: "שמור את התמונות המוגנות באופן מיידי." },
    blurface: { heroBadge: "פרטיות מוחלטת", heroTitle: "צנזר בעזרת AI.", heroTitle2: "הגן על זהויות.", heroDesc: "גלה וטשטש פנים אוטומטית תוך שניות. 100% פרטי.", feat1Title: "זיהוי פנים", feat1Desc: "מודל ה-AI המקומי שלנו מוצא פנים בדיוק מדהים.", feat2Title: "טשטוש חכם", feat2Desc: "החל טשטוש גאוסייני כדי להסתיר אזורים רגישים.", feat3Title: "שליטה ידנית", feat3Desc: "צריך להסתיר מסמך? השתמש בכלי הידני שלנו.", stepsTag: "איך זה עובד", stepsTitle: "הפוך לאנונימי ב-3 שלבים", s1Title: "העלה", s1Desc: "שחרר תמונות בבטחה בדפדפן.", s2Title: "גלה", s2Desc: "תן ל-AI לבחור פנים אוטומטית.", s3Title: "שמור", s3Desc: "הורד את התמונות האנונימיות." },
    convert: { heroBadge: "תאימות אוניברסלית", heroTitle: "ממיר פורמטים.", heroTitle2: "אפס אובדן איכות.", heroDesc: "המר בצורה חלקה בין WebP, PNG, JPG ו-AVIF.", feat1Title: "מהיר כברק", feat1Desc: "המר קבצים גדולים באופן מיידי באמצעות כוח המכשיר שלך.", feat2Title: "עיבוד בכמויות", feat2Desc: "צריך להמיר 500 תמונות? פשוט גרור את כל התיקיה.", feat3Title: "תמיכה רחבה", feat3Desc: "תמיכה מלאה לפורמטים של הדור הבא כמו WebP.", stepsTag: "זרימת עבודה", stepsTitle: "המר ב-3 שלבים", s1Title: "העלה", s1Desc: "גרור ושחרר את התמונות שלך לסביבת העבודה.", s2Title: "פורמט", s2Desc: "בחר את פורמט הפלט הרצוי.", s3Title: "ייצוא", s3Desc: "לחץ על ייצוא וקבל את הקבצים שלך מיד." },
    faqs: {
      "landing.watermark.faq1.q": "האם אני יכול להוסיף סימן מים למספר תמונות?",
      "landing.watermark.faq1.a": "כן! עיבוד בכמויות מקל על הוספת סימן מים למאות תמונות.",
      "landing.watermark.faq2.q": "האם התמונות המקוריות שלי בטוחות?",
      "landing.watermark.faq2.a": "כן, התהליך 100% פרטי ומקומי.",
      "landing.watermark.faq3.q": "האם אני יכול להשתמש בלוגו שלי?",
      "landing.watermark.faq3.a": "בהחלט. אתה יכול להעלות סמלילי PNG מותאמים אישית.",
      "landing.watermark.faq4.q": "האם יש הגבלה על מספר התמונות?",
      "landing.watermark.faq4.a": "אין גבולות! אתה יכול להשתמש בזה בחינם.",
      "landing.blurface.faq1.q": "האם זה מגלה מספר פנים?",
      "landing.blurface.faq1.a": "כן, ה-AI שלנו יכול לגלות ולטשטש במהירות מספר פנים.",
      "landing.blurface.faq2.q": "האם זיהוי הפנים פרטי?",
      "landing.blurface.faq2.a": "100% פרטי. מודל ה-AI פועל בדפדפן שלך.",
      "landing.blurface.faq3.q": "האם עלי לשלם כדי להשתמש ב-AI?",
      "landing.blurface.faq3.a": "לא, הכלי שלנו חינמי לחלוטין.",
      "landing.blurface.faq4.q": "האם קל להתאים את עצמת הטשטוש?",
      "landing.blurface.faq4.a": "כן, יש לך שליטה מלאה על רדיוס הטשטוש.",
      "landing.convert.faq1.q": "אילו פורמטים נתמכים?",
      "landing.convert.faq1.a": "אנו תומכים ב-WebP, PNG, JPEG ועוד.",
      "landing.convert.faq2.q": "האם ההמרה מהירה?",
      "landing.convert.faq2.a": "מהירה מאוד. מתבצעת באופן מקומי במילי-שניות.",
      "landing.convert.faq3.q": "האם כלי זה חינמי להמרה בכמויות?",
      "landing.convert.faq3.a": "כן! אתה יכול להמיר מאות תמונות בחינם.",
      "landing.convert.faq4.q": "האם הקבצים המומרים שלי פרטיים?",
      "landing.convert.faq4.a": "פרטיים לחלוטין. הכל קורה בדפדפן שלך."
    }
  },
  no: {
    watermark: { heroBadge: "MERKEVAREBESKYTTELSE", heroTitle: "Beskytt arbeidet ditt.", heroTitle2: "Bygg din identitet.", heroDesc: "Bruk tilpassbare vannmerker for å beskytte din immaterielle eiendom.", feat1Title: "Ikke-destruktive lag", feat1Desc: "Legg til flere vannmerkelag uten å endre det originale bildet.", feat2Title: "Opasitetskontroll", feat2Desc: "Finjuster gjennomsiktigheten til teksten eller logoen din.", feat3Title: "Mønstermodus", feat3Desc: "Gjenta automatisk vannmerket ditt over hele bildet.", stepsTag: "ARBEIDSFLY", stepsTitle: "Beskytt i 3 trinn", s1Title: "Last opp", s1Desc: "Last de originale bildene dine trygt inn i nettleseren.", s2Title: "Stempel", s2Desc: "Bruk din egendefinerte tekst eller logo.", s3Title: "Eksport", s3Desc: "Lagre de beskyttede bildene umiddelbart." },
    blurface: { heroBadge: "ULTIMAT PERSONVERN", heroTitle: "Sensurer med AI.", heroTitle2: "Beskytt identiteter.", heroDesc: "Oppdag og slør ansikter automatisk på sekunder. 100% privat.", feat1Title: "Ansiktsgjenkjenning", feat1Desc: "Vår lokale AI-modell finner ansikter med utrolig nøyaktighet.", feat2Title: "Smart sløring", feat2Desc: "Bruk Gaussisk sløring for å skjule sensitive områder.", feat3Title: "Manuell kontroll", feat3Desc: "Trenger du å skjule et dokument? Bruk vårt manuelle verktøy.", stepsTag: "HVORDAN DET FUNGERER", stepsTitle: "Anonymiser i 3 trinn", s1Title: "Last opp", s1Desc: "Slipp bilder trygt i nettleseren.", s2Title: "Oppdag", s2Desc: "La AI velge ansikter automatisk.", s3Title: "Lagre", s3Desc: "Last ned de anonymiserte bildene." },
    convert: { heroBadge: "UNIVERSELL KOMPATIBILITET", heroTitle: "Formattomformer.", heroTitle2: "Null kvalitetstap.", heroDesc: "Konverter sømløst mellom WebP, PNG, JPG og AVIF.", feat1Title: "Lynraskt", feat1Desc: "Forvandle store filer umiddelbart ved hjelp av enhetens kraft.", feat2Title: "Satsvis behandling", feat2Desc: "Trenger du å konvertere 500 bilder? Bare dra hele mappen.", feat3Title: "Bred støtte", feat3Desc: "Full støtte for neste generasjons formater som WebP.", stepsTag: "ARBEIDSFLY", stepsTitle: "Konverter i 3 trinn", s1Title: "Last opp", s1Desc: "Dra og slipp bildene dine i arbeidsområdet.", s2Title: "Format", s2Desc: "Velg ønsket utdataformat.", s3Title: "Eksport", s3Desc: "Klikk på eksport og få filene dine umiddelbart." },
    faqs: {
      "landing.watermark.faq1.q": "Kan jeg legge til vannmerke på flere bilder?",
      "landing.watermark.faq1.a": "Ja! Satsvis behandling gjør det enkelt å håndtere hundrevis av bilder.",
      "landing.watermark.faq2.q": "Er mine originale bilder trygge?",
      "landing.watermark.faq2.a": "Ja, prosessen er 100% privat og lokal.",
      "landing.watermark.faq3.q": "Kan jeg bruke min egen logo?",
      "landing.watermark.faq3.a": "Absolutt. Du kan laste opp egendefinerte PNG-logoer.",
      "landing.watermark.faq4.q": "Er det en grense for antall bilder?",
      "landing.watermark.faq4.a": "Ingen grenser! Du kan bruke det gratis.",
      "landing.blurface.faq1.q": "Oppdager den flere ansikter?",
      "landing.blurface.faq1.a": "Ja, vår AI kan raskt oppdage og sløre flere ansikter.",
      "landing.blurface.faq2.q": "Er ansiktsgjenkjenningen privat?",
      "landing.blurface.faq2.a": "100% privat. AI-modellen kjører i nettleseren din.",
      "landing.blurface.faq3.q": "Må jeg betale for å bruke AI?",
      "landing.blurface.faq3.a": "Nei, verktøyet vårt er helt gratis.",
      "landing.blurface.faq4.q": "Er det enkelt å justere sløringen?",
      "landing.blurface.faq4.a": "Ja, du har full kontroll over radiusen.",
      "landing.convert.faq1.q": "Hvilke formater støttes?",
      "landing.convert.faq1.a": "Vi støtter WebP, PNG, JPEG og mer.",
      "landing.convert.faq2.q": "Er konverteringen rask?",
      "landing.convert.faq2.a": "Ekstremt rask. Det skjer lokalt i millisekunder.",
      "landing.convert.faq3.q": "Er det gratis for satsvis konvertering?",
      "landing.convert.faq3.a": "Ja! Du kan konvertere hundrevis av bilder gratis.",
      "landing.convert.faq4.q": "Er filene mine private?",
      "landing.convert.faq4.a": "Helt private. Alt skjer i nettleseren din."
    }
  },
  tl: {
    watermark: { heroBadge: "PROTEKSYON SA BRAND", heroTitle: "Protektahan ang iyong gawa.", heroTitle2: "Bumuo ng iyong pagkakakilanlan.", heroDesc: "Maglapat ng napapasadyang mga watermark upang maprotektahan ang iyong intelektwal na ari-arian.", feat1Title: "Mga Layer na Hindi Nakakasira", feat1Desc: "Magdagdag ng maraming watermark na hindi binabago ang iyong orihinal na larawan.", feat2Title: "Kontrol sa Opacity", feat2Desc: "Ayuhin ang transparency ng iyong text o logo.", feat3Title: "Pattern Mode", feat3Desc: "Awtomatikong ulitin ang iyong watermark sa buong larawan.", stepsTag: "WORKFLOW", stepsTitle: "Protektahan sa 3 Hakbang", s1Title: "I-upload", s1Desc: "I-load ang iyong orihinal na mga larawan nang ligtas sa browser.", s2Title: "Tatak", s2Desc: "Ilapat ang iyong custom na text o logo.", s3Title: "I-export", s3Desc: "I-save agad ang mga protektadong larawan." },
    blurface: { heroBadge: "MATINDING PRIVACY", heroTitle: "I-censor gamit ang AI.", heroTitle2: "Protektahan ang mga pagkakakilanlan.", heroDesc: "Awtomatikong makita at i-blur ang mga mukha sa loob ng ilang segundo. 100% pribado.", feat1Title: "Face Detection", feat1Desc: "Ang aming lokal na AI model ay nakakahanap ng mga mukha nang may hindi kapani-paniwalang katumpakan.", feat2Title: "Smart Blurring", feat2Desc: "Mag-apply ng Gaussian blur upang itago ang mga sensitibong bahagi.", feat3Title: "Manual Control", feat3Desc: "Kailangang itago ang isang dokumento? Gamitin ang aming manual na tool.", stepsTag: "PAANO ITO GUMAGANA", stepsTitle: "I-anonymize sa 3 Hakbang", s1Title: "I-upload", s1Desc: "I-drop nang ligtas ang mga larawan sa browser.", s2Title: "Tukuyin", s2Desc: "Hayaan ang AI na awtomatikong pumili ng mga mukha.", s3Title: "I-save", s3Desc: "I-download ang mga hindi kilalang larawan." },
    convert: { heroBadge: "UNIBERSAL NA COMPATIBILITY", heroTitle: "Format Transformer.", heroTitle2: "Walang Nawawalang Kalidad.", heroDesc: "Madaling mag-convert sa pagitan ng WebP, PNG, JPG at AVIF.", feat1Title: "Kasing Bilis ng Kidlat", feat1Desc: "I-transform ang malalaking file kaagad gamit ang kapangyarihan ng iyong device.", feat2Title: "Batch Processing", feat2Desc: "Kailangang mag-convert ng 500 larawan? I-drag lang ang buong folder.", feat3Title: "Malawak na Suporta", feat3Desc: "Buong suporta para sa mga next-gen na format tulad ng WebP.", stepsTag: "WORKFLOW", stepsTitle: "I-convert sa 3 Hakbang", s1Title: "I-upload", s1Desc: "I-drag at i-drop ang iyong mga larawan sa workspace.", s2Title: "Format", s2Desc: "Piliin ang iyong nais na format ng output.", s3Title: "I-export", s3Desc: "I-click ang export at makuha agad ang iyong mga file." },
    faqs: {
      "landing.watermark.faq1.q": "Maaari ba akong maglagay ng watermark sa maraming larawan?",
      "landing.watermark.faq1.a": "Oo! Pinapadali ng aming batch processing ang paglalagay ng watermark sa daan-daang larawan.",
      "landing.watermark.faq2.q": "Ligtas ba ang aking mga orihinal na larawan?",
      "landing.watermark.faq2.a": "Oo, ang proseso ay 100% pribado at lokal.",
      "landing.watermark.faq3.q": "Maaari ko bang gamitin ang aking sariling logo?",
      "landing.watermark.faq3.a": "Oo naman. Maaari kang mag-upload ng mga custom na PNG logo.",
      "landing.watermark.faq4.q": "May limitasyon ba sa bilang ng mga larawan?",
      "landing.watermark.faq4.a": "Walang limitasyon! Maaari mo itong gamitin nang libre.",
      "landing.blurface.faq1.q": "Nakakakita ba ito ng maraming mukha?",
      "landing.blurface.faq1.a": "Oo, mabilis na nakakakita at nakakapag-blur ng maraming mukha ang aming AI.",
      "landing.blurface.faq2.q": "Pribado ba ang face detection?",
      "landing.blurface.faq2.a": "100% pribado. Tumatakbo ang AI model sa iyong browser.",
      "landing.blurface.faq3.q": "Kailangan ko bang magbayad para magamit ang AI?",
      "landing.blurface.faq3.a": "Hindi, ang aming tool ay libre.",
      "landing.blurface.faq4.q": "Madali bang ayusin ang blur intensity?",
      "landing.blurface.faq4.a": "Oo, mayroon kang buong kontrol sa radius ng blur.",
      "landing.convert.faq1.q": "Anong mga format ang sinusuportahan?",
      "landing.convert.faq1.a": "Sinusuportahan namin ang WebP, PNG, JPEG at marami pa.",
      "landing.convert.faq2.q": "Mabilis ba ang conversion?",
      "landing.convert.faq2.a": "Napakabilis. Nangyayari nang lokal sa milliseconds.",
      "landing.convert.faq3.q": "Libre ba ang tool na ito para sa batch conversion?",
      "landing.convert.faq3.a": "Oo! Maaari kang mag-convert ng daan-daang larawan nang libre.",
      "landing.convert.faq4.q": "Pribado ba ang aking mga na-convert na file?",
      "landing.convert.faq4.a": "Ligtas at pribado. Nangyayari ang lahat sa iyong browser."
    }
  }
};
module.exports = translationsPart5;
