const translationsPart1 = {
  th: {
    watermark: { heroBadge: "การปกป้องแบรนด์", heroTitle: "ปกป้องผลงานของคุณ", heroTitle2: "สร้างตัวตนของคุณ", heroDesc: "ใช้ลายน้ำที่ปรับแต่งได้สูงเพื่อปกป้องทรัพย์สินทางปัญญาของคุณ เพิ่มข้อความหรือโลโก้พร้อมการควบคุมความทึบ ตำแหน่ง และโหมดการผสมอย่างแม่นยำ", feat1Title: "เลเยอร์ที่ไม่ทำลาย", feat1Desc: "เพิ่มเลเยอร์ลายน้ำหลายชั้นโดยไม่เปลี่ยนข้อมูลภาพต้นฉบับของคุณ จัดตำแหน่ง ปรับขนาด และหมุนได้ง่าย", feat2Title: "การควบคุมความทึบและการผสม", feat2Desc: "ปรับความโปร่งใสของข้อความหรือโลโก้ของคุณ เลือกระดับการผสมขั้นสูงเพื่อให้ลายน้ำของคุณดูกลมกลืนแต่ลบไม่ได้", feat3Title: "โหมดลวดลาย", feat3Desc: "ทำซ้ำลายน้ำของคุณทั่วทั้งภาพโดยอัตโนมัติ การปกป้องสูงสุดจากการครอบตัดโดยไม่ได้รับอนุญาต", stepsTag: "ขั้นตอนการทำงาน", stepsTitle: "ปกป้องใน 3 ขั้นตอน", s1Title: "อัปโหลด", s1Desc: "โหลดรูปภาพต้นฉบับของคุณอย่างปลอดภัยในเบราว์เซอร์", s2Title: "ประทับตรา", s2Desc: "ใช้ข้อความหรือลายน้ำโลโก้ที่กำหนดเองพร้อมสไตล์", s3Title: "ส่งออก", s3Desc: "บันทึกภาพที่ได้รับการปกป้องทันที" },
    blurface: { heroBadge: "ความเป็นส่วนตัวขั้นสุด", heroTitle: "เซ็นเซอร์ด้วย AI", heroTitle2: "ปกป้องตัวตน", heroDesc: "ตรวจจับและเบลอใบหน้า ป้ายทะเบียน หรือข้อมูลละเอียดอ่อนอัตโนมัติในไม่กี่วินาที ส่วนตัว 100%", feat1Title: "การตรวจจับใบหน้า", feat1Desc: "โมเดล AI ในเครื่องของเราค้นหาและเน้นใบหน้าในภาพถ่ายของคุณอย่างแม่นยำอัตโนมัติ", feat2Title: "การเบลออัจฉริยะ", feat2Desc: "ใช้การเบลอแบบ Gaussian พิกเซล หรือบล็อกสีทึบเพื่อบดบังพื้นที่ละเอียดอ่อนอย่างถาวร", feat3Title: "การควบคุมด้วยตนเอง", feat3Desc: "ต้องการซ่อนป้ายทะเบียนหรือเอกสารใช่ไหม? ใช้เครื่องมือเลือกด้วยตนเองของเรา", stepsTag: "วิธีการทำงาน", stepsTitle: "ไม่ระบุตัวตนใน 3 ขั้นตอน", s1Title: "อัปโหลด", s1Desc: "วางรูปภาพอย่างปลอดภัยในเบราว์เซอร์", s2Title: "ตรวจจับ", s2Desc: "ให้ AI ค้นหาและเลือกใบหน้าอัตโนมัติ", s3Title: "บันทึก", s3Desc: "ดาวน์โหลดรูปภาพที่ไม่ระบุตัวตน" },
    convert: { heroBadge: "ความเข้ากันได้สากล", heroTitle: "ตัวแปลงรูปแบบ", heroTitle2: "ไม่สูญเสียคุณภาพ", heroDesc: "แปลงระหว่าง WebP, PNG, JPG และ AVIF ได้อย่างราบรื่น การประมวลผลจำนวนมากที่รวดเร็ว", feat1Title: "รวดเร็วปานสายฟ้า", feat1Desc: "แปลงไฟล์รูปภาพขนาดใหญ่ทันทีโดยใช้พลังประมวลผลเต็มที่ของอุปกรณ์ของคุณ", feat2Title: "การประมวลผลจำนวนมาก", feat2Desc: "ต้องการแปลง 500 ภาพ? เพียงลากและวางโฟลเดอร์ทั้งหมด", feat3Title: "การสนับสนุนที่กว้างขวาง", feat3Desc: "รองรับรูปแบบยุคใหม่อย่าง WebP รวมถึงรูปแบบคลาสสิกอย่าง JPG", stepsTag: "ขั้นตอนการทำงาน", stepsTitle: "แปลงใน 3 ขั้นตอน", s1Title: "อัปโหลด", s1Desc: "ลากและวางรูปภาพหรือโฟลเดอร์ของคุณในพื้นที่ทำงาน", s2Title: "รูปแบบ", s2Desc: "เลือกรูปแบบผลลัพธ์ที่คุณต้องการ", s3Title: "ส่งออก", s3Desc: "คลิกส่งออกและรับไฟล์ของคุณทันที" },
    faqs: {
      "landing.watermark.faq1.q": "ฉันสามารถใส่ลายน้ำรูปภาพหลายรูปได้หรือไม่?",
      "landing.watermark.faq1.a": "ใช่! การประมวลผลเป็นชุดของเราช่วยให้ใส่ลายน้ำรูปภาพนับร้อยรูปพร้อมกันได้อย่างรวดเร็วและง่ายดาย",
      "landing.watermark.faq2.q": "รูปภาพต้นฉบับของฉันปลอดภัยหรือไม่?",
      "landing.watermark.faq2.a": "ใช่ กระบวนการนี้เป็นส่วนตัวและทำในเครื่อง 100% เราไม่เคยเก็บหรืออัปโหลดภาพของคุณ",
      "landing.watermark.faq3.q": "ฉันสามารถใช้โลโก้ของตัวเองได้หรือไม่?",
      "landing.watermark.faq3.a": "แน่นอน คุณสามารถอัปโหลดโลโก้ PNG หรือใช้ข้อความที่มีแบบอักษรที่กำหนดเอง",
      "landing.watermark.faq4.q": "มีการจำกัดจำนวนภาพหรือไม่?",
      "landing.watermark.faq4.a": "ไม่จำกัด! เนื่องจากทำงานบนอุปกรณ์ของคุณ คุณสามารถใช้ได้ฟรี",
      "landing.blurface.faq1.q": "มันตรวจจับใบหน้าหลายใบหน้าหรือไม่?",
      "landing.blurface.faq1.a": "ใช่ AI ของเราสามารถตรวจจับและเบลอหลายใบหน้าในภาพเดียวได้อย่างรวดเร็ว",
      "landing.blurface.faq2.q": "การตรวจจับใบหน้าเป็นส่วนตัวหรือไม่?",
      "landing.blurface.faq2.a": "ส่วนตัว 100% โมเดล AI ทำงานในเบราว์เซอร์ของคุณ ไม่มีการอัปโหลดรูปภาพ",
      "landing.blurface.faq3.q": "ฉันต้องจ่ายเงินเพื่อใช้ AI หรือไม่?",
      "landing.blurface.faq3.a": "ไม่ เครื่องมือของเราฟรีทั้งหมด เราไม่คิดค่าบริการเพราะใช้พลังของเครื่องคุณ",
      "landing.blurface.faq4.q": "ปรับระดับการเบลอได้ง่ายหรือไม่?",
      "landing.blurface.faq4.a": "ใช่ คุณควบคุมระดับความเบลอได้เต็มที่และเลือกใบหน้าที่ต้องการเบลอได้",
      "landing.convert.faq1.q": "รองรับรูปแบบใดบ้าง?",
      "landing.convert.faq1.a": "เรารองรับการแปลง WebP, PNG, JPEG และอื่นๆ เปลี่ยนรูปแบบได้ง่ายดาย",
      "landing.convert.faq2.q": "การแปลงรวดเร็วหรือไม่?",
      "landing.convert.faq2.a": "เร็วมาก ด้วย WebAssembly การแปลงเกิดขึ้นในเสี้ยววินาทีโดยไม่ต้องรอเซิร์ฟเวอร์",
      "landing.convert.faq3.q": "เครื่องมือนี้แปลงเป็นชุดได้ฟรีหรือไม่?",
      "landing.convert.faq3.a": "ใช่! คุณสามารถแปลงรูปภาพเป็นชุดนับร้อยได้ฟรีโดยไม่มีข้อจำกัด",
      "landing.convert.faq4.q": "ไฟล์ที่แปลงแล้วเป็นส่วนตัวหรือไม่?",
      "landing.convert.faq4.a": "ส่วนตัวแน่นอน ทุกอย่างเกิดขึ้นโดยตรงภายในเบราว์เซอร์ของคุณ"
    }
  },
  vi: {
    watermark: { heroBadge: "BẢO VỆ THƯƠNG HIỆU", heroTitle: "Bảo vệ tác phẩm.", heroTitle2: "Xây dựng bản sắc.", heroDesc: "Sử dụng hình mờ có thể tùy chỉnh để bảo vệ tài sản trí tuệ. Thêm văn bản hoặc biểu trưng với khả năng kiểm soát độ mờ và vị trí.", feat1Title: "Lớp không phá hủy", feat1Desc: "Thêm nhiều lớp hình mờ mà không làm thay đổi dữ liệu ảnh gốc. Dễ dàng định vị và xoay.", feat2Title: "Kiểm soát độ mờ", feat2Desc: "Tinh chỉnh độ trong suốt của văn bản hoặc biểu trưng. Chọn chế độ hòa trộn nâng cao.", feat3Title: "Chế độ lặp lại", feat3Desc: "Tự động lặp lại hình mờ trên toàn bộ hình ảnh. Bảo vệ tuyệt đối khỏi việc cắt xén.", stepsTag: "QUY TRÌNH QUY TRÌNH", stepsTitle: "Bảo vệ trong 3 bước", s1Title: "Tải lên", s1Desc: "Tải ảnh gốc của bạn an toàn vào trình duyệt.", s2Title: "Đóng dấu", s2Desc: "Áp dụng văn bản tùy chỉnh hoặc hình mờ biểu trưng.", s3Title: "Xuất khẩu", s3Desc: "Lưu hình ảnh được bảo vệ ngay lập tức." },
    blurface: { heroBadge: "BẢO MẬT TUYỆT ĐỐI", heroTitle: "Kiểm duyệt bằng AI.", heroTitle2: "Bảo vệ danh tính.", heroDesc: "Tự động phát hiện và làm mờ khuôn mặt, biển số xe trong vài giây. Riêng tư 100%.", feat1Title: "Nhận diện khuôn mặt", feat1Desc: "Mô hình AI cục bộ của chúng tôi tự động tìm khuôn mặt với độ chính xác đáng kinh ngạc.", feat2Title: "Làm mờ thông minh", feat2Desc: "Áp dụng độ mờ gaussian hoặc pixel để ẩn các khu vực nhạy cảm một cách vĩnh viễn.", feat3Title: "Kiểm soát thủ công", feat3Desc: "Cần ẩn tài liệu? Sử dụng công cụ chọn thủ công của chúng tôi.", stepsTag: "CÁCH HOẠT ĐỘNG", stepsTitle: "Ẩn danh trong 3 bước", s1Title: "Tải lên", s1Desc: "Thả ảnh an toàn vào trình duyệt.", s2Title: "Phát hiện", s2Desc: "Để AI tự động tìm và chọn khuôn mặt.", s3Title: "Lưu", s3Desc: "Tải xuống các bức ảnh đã được ẩn danh." },
    convert: { heroBadge: "TƯƠNG THÍCH PHỔ BIẾN", heroTitle: "Trình chuyển đổi định dạng.", heroTitle2: "Không giảm chất lượng.", heroDesc: "Chuyển đổi liền mạch giữa WebP, PNG, JPG và AVIF. Xử lý hàng loạt cực nhanh.", feat1Title: "Nhanh như chớp", feat1Desc: "Chuyển đổi các tệp lớn thành định dạng phổ biến ngay lập tức bằng thiết bị của bạn.", feat2Title: "Xử lý hàng loạt", feat2Desc: "Cần chuyển đổi 500 hình ảnh? Chỉ cần kéo và thả toàn bộ thư mục.", feat3Title: "Hỗ trợ rộng rãi", feat3Desc: "Hỗ trợ đầy đủ cho các định dạng như WebP cùng với JPG, PNG cổ điển.", stepsTag: "QUY TRÌNH QUY TRÌNH", stepsTitle: "Chuyển đổi trong 3 bước", s1Title: "Tải lên", s1Desc: "Kéo và thả hình ảnh hoặc thư mục của bạn vào không gian làm việc.", s2Title: "Định dạng", s2Desc: "Chọn định dạng đầu ra mong muốn của bạn.", s3Title: "Xuất khẩu", s3Desc: "Nhấp vào xuất và lấy tệp của bạn ngay lập tức." },
    faqs: {
      "landing.watermark.faq1.q": "Tôi có thể đóng dấu nhiều ảnh không?",
      "landing.watermark.faq1.a": "Có! Xử lý hàng loạt giúp đóng dấu hàng trăm bức ảnh cùng lúc dễ dàng và nhanh chóng.",
      "landing.watermark.faq2.q": "Ảnh gốc của tôi có an toàn không?",
      "landing.watermark.faq2.a": "Có, quá trình này riêng tư và cục bộ 100%. Chúng tôi không bao giờ tải lên máy chủ.",
      "landing.watermark.faq3.q": "Tôi có thể sử dụng logo của mình không?",
      "landing.watermark.faq3.a": "Chắc chắn. Bạn có thể tải lên logo PNG tùy chỉnh hoặc sử dụng văn bản.",
      "landing.watermark.faq4.q": "Có giới hạn số lượng ảnh không?",
      "landing.watermark.faq4.a": "Không giới hạn! Vì nó chạy trên thiết bị của bạn, nó hoàn toàn miễn phí.",
      "landing.blurface.faq1.q": "Nó có phát hiện nhiều khuôn mặt không?",
      "landing.blurface.faq1.a": "Có, AI cục bộ có thể phát hiện và làm mờ nhiều khuôn mặt cực kỳ nhanh chóng.",
      "landing.blurface.faq2.q": "Việc nhận diện khuôn mặt có riêng tư không?",
      "landing.blurface.faq2.a": "Riêng tư 100%. Mô hình AI chạy trong trình duyệt, không có ảnh nào bị tải lên.",
      "landing.blurface.faq3.q": "Tôi có phải trả tiền để dùng AI không?",
      "landing.blurface.faq3.a": "Không, công cụ làm mờ AI của chúng tôi hoàn toàn miễn phí.",
      "landing.blurface.faq4.q": "Điều chỉnh mức độ mờ có dễ không?",
      "landing.blurface.faq4.a": "Có, bạn có toàn quyền kiểm soát độ mờ và dễ dàng chọn khuôn mặt để làm mờ.",
      "landing.convert.faq1.q": "Hỗ trợ những định dạng nào?",
      "landing.convert.faq1.a": "Chúng tôi hỗ trợ chuyển đổi giữa WebP, PNG, JPEG và hơn thế nữa.",
      "landing.convert.faq2.q": "Quá trình chuyển đổi có nhanh không?",
      "landing.convert.faq2.a": "Cực kỳ nhanh. Chuyển đổi diễn ra trong phần nghìn giây nhờ WebAssembly cục bộ.",
      "landing.convert.faq3.q": "Công cụ này có miễn phí để chuyển đổi hàng loạt không?",
      "landing.convert.faq3.a": "Có! Bạn có thể chuyển đổi hàng loạt hàng trăm hình ảnh miễn phí.",
      "landing.convert.faq4.q": "Các tệp đã chuyển đổi có riêng tư không?",
      "landing.convert.faq4.a": "Hoàn toàn riêng tư. Mọi thứ diễn ra ngay trong cửa sổ trình duyệt của bạn."
    }
  },
  tr: {
    watermark: { heroBadge: "MARKA KORUMASI", heroTitle: "İşinizi Koruyun.", heroTitle2: "Kimliğinizi Oluşturun.", heroDesc: "Fikri mülkiyetinizi korumak için son derece özelleştirilebilir filigranlar uygulayın.", feat1Title: "Tahribatsız Katmanlar", feat1Desc: "Orijinal resim verilerinizi değiştirmeden birden fazla filigran katmanı ekleyin.", feat2Title: "Opaklık Kontrolü", feat2Desc: "Metninizin veya logonuzun şeffaflığına ince ayar yapın.", feat3Title: "Döşeme Desen Modu", feat3Desc: "Filigranınızı tüm resim boyunca otomatik olarak tekrarlayın.", stepsTag: "İŞ AKIŞI", stepsTitle: "3 Adımda Koru", s1Title: "Yükle", s1Desc: "Orijinal fotoğraflarınızı tarayıcıya güvenli bir şekilde yükleyin.", s2Title: "Damga", s2Desc: "Özel metninizi veya logo filigranınızı uygulayın.", s3Title: "Dışa Aktar", s3Desc: "Korunan resimleri anında kaydedin." },
    blurface: { heroBadge: "NİHAİ GİZLİLİK", heroTitle: "Yapay Zeka ile Sansürle.", heroTitle2: "Kimlikleri Koru.", heroDesc: "Saniyeler içinde yüzleri ve hassas bilgileri otomatik olarak algılayın ve bulanıklaştırın. %100 özel.", feat1Title: "Yüz Algılama", feat1Desc: "Yerel yapay zeka modelimiz yüzleri inanılmaz bir doğrulukla bulur.", feat2Title: "Akıllı Bulanıklaştırma", feat2Desc: "Hassas bölgeleri gizlemek için Gauss bulanıklığı uygulayın.", feat3Title: "Manuel Kontrol", feat3Desc: "Bir belgeyi gizlemeniz mi gerekiyor? Manuel seçim aracımızı kullanın.", stepsTag: "NASIL ÇALIŞIR", stepsTitle: "3 Adımda Anonimleştir", s1Title: "Yükle", s1Desc: "Fotoğrafları tarayıcıya güvenle bırakın.", s2Title: "Algıla", s2Desc: "Yapay zekanın yüzleri otomatik olarak seçmesine izin verin.", s3Title: "Kaydet", s3Desc: "Anonimleştirilmiş fotoğrafları indirin." },
    convert: { heroBadge: "EVRENSEL UYUMLULUK", heroTitle: "Format Dönüştürücü.", heroTitle2: "Sıfır Kalite Kaybı.", heroDesc: "WebP, PNG, JPG ve AVIF arasında sorunsuz bir şekilde dönüştürün.", feat1Title: "Yıldırım Hızında", feat1Desc: "Büyük dosyaları cihazınızın gücünü kullanarak anında dönüştürün.", feat2Title: "Toplu İşlem", feat2Desc: "500 resmi dönüştürmeniz mi gerekiyor? Tüm klasörü sürükleyin.", feat3Title: "Geniş Destek", feat3Desc: "JPG gibi klasik formatlarla birlikte WebP gibi yeni nesil formatlar için tam destek.", stepsTag: "İŞ AKIŞI", stepsTitle: "3 Adımda Dönüştür", s1Title: "Yükle", s1Desc: "Resimlerinizi çalışma alanına sürükleyip bırakın.", s2Title: "Format", s2Desc: "İstediğiniz çıktı formatını seçin.", s3Title: "Dışa Aktar", s3Desc: "Dışa aktar'a tıklayın ve dosyalarınızı anında alın." },
    faqs: {
      "landing.watermark.faq1.q": "Birden fazla fotoğrafa filigran ekleyebilir miyim?",
      "landing.watermark.faq1.a": "Evet! Toplu işlem sayesinde yüzlerce fotoğrafa aynı anda filigran eklemek hızlı ve kolaydır.",
      "landing.watermark.faq2.q": "Orijinal fotoğraflarım güvende mi?",
      "landing.watermark.faq2.a": "Evet, süreç %100 özeldir ve yereldir. Görüntüleri asla sunucularımıza yüklemeyiz.",
      "landing.watermark.faq3.q": "Kendi logomu kullanabilir miyim?",
      "landing.watermark.faq3.a": "Kesinlikle. Özel PNG logoları yükleyebilir veya metin kullanabilirsiniz.",
      "landing.watermark.faq4.q": "İşleyebileceğim fotoğraf sayısında bir sınır var mı?",
      "landing.watermark.faq4.a": "Sınır yok! Cihazınızda çalıştığı için ücretsiz kullanabilirsiniz.",
      "landing.blurface.faq1.q": "Birden fazla yüzü algılar mı?",
      "landing.blurface.faq1.a": "Evet, yapay zekamız tek bir fotoğraftaki birden fazla yüzü hızla algılar.",
      "landing.blurface.faq2.q": "Yüz algılama özel mi?",
      "landing.blurface.faq2.a": "%100 özel. Yapay zeka modeli tarayıcınızda çalışır, hiçbir şey yüklenmez.",
      "landing.blurface.faq3.q": "Yapay zekayı kullanmak için ödeme yapmam gerekiyor mu?",
      "landing.blurface.faq3.a": "Hayır, yapay zeka bulanıklaştırma aracımız tamamen ücretsizdir.",
      "landing.blurface.faq4.q": "Bulanıklık yoğunluğunu ayarlamak kolay mı?",
      "landing.blurface.faq4.a": "Evet, bulanıklık yarıçapı üzerinde tam kontrole sahipsiniz.",
      "landing.convert.faq1.q": "Hangi formatlar destekleniyor?",
      "landing.convert.faq1.a": "WebP, PNG, JPEG ve daha fazlası arasında dönüştürmeyi destekliyoruz.",
      "landing.convert.faq2.q": "Dönüştürme hızlı mı?",
      "landing.convert.faq2.a": "Son derece hızlı. Sunucu yüklemelerini beklemeden milisaniyeler içinde gerçekleşir.",
      "landing.convert.faq3.q": "Bu araç toplu dönüştürme için ücretsiz mi?",
      "landing.convert.faq3.a": "Evet! Yüzlerce görüntüyü ücretsiz olarak dönüştürebilirsiniz.",
      "landing.convert.faq4.q": "Dönüştürülen dosyalarım özel mi?",
      "landing.convert.faq4.a": "Tamamen özel. Her şey doğrudan tarayıcı pencerenizin içinde gerçekleşir."
    }
  },
  nl: {
    watermark: { heroBadge: "MERKBESCHERMING", heroTitle: "Bescherm Uw Werk.", heroTitle2: "Bouw Uw Identiteit.", heroDesc: "Pas aanpasbare watermerken toe om uw eigendom te beschermen.", feat1Title: "Niet-destructieve Lagen", feat1Desc: "Voeg meerdere lagen toe zonder uw originele afbeelding te wijzigen.", feat2Title: "Dekking Controle", feat2Desc: "Pas de transparantie van uw tekst of logo aan.", feat3Title: "Tegelpatroon Modus", feat3Desc: "Herhaal uw watermerk automatisch over de hele afbeelding.", stepsTag: "WERKSTROOM", stepsTitle: "Bescherm in 3 Stappen", s1Title: "Uploaden", s1Desc: "Laad uw originele foto's veilig in de browser.", s2Title: "Stempelen", s2Desc: "Pas uw aangepaste tekst of logo watermerk toe.", s3Title: "Exporteren", s3Desc: "Sla de beschermde afbeeldingen direct op." },
    blurface: { heroBadge: "ULTIEME PRIVACY", heroTitle: "Censureer met AI.", heroTitle2: "Bescherm Identiteiten.", heroDesc: "Detecteer en vervaag gezichten automatisch in seconden. 100% privé.", feat1Title: "Gezichtsherkenning", feat1Desc: "Ons lokale AI-model vindt gezichten met ongelooflijke nauwkeurigheid.", feat2Title: "Slim Vervagen", feat2Desc: "Pas Gaussiaanse vervaging toe om gevoelige gebieden te verbergen.", feat3Title: "Handmatige Bediening", feat3Desc: "Moet u een document verbergen? Gebruik ons selectiegereedschap.", stepsTag: "HOE HET WERKT", stepsTitle: "Anonimiseer in 3 Stappen", s1Title: "Uploaden", s1Desc: "Zet foto's veilig in de browser.", s2Title: "Detecteren", s2Desc: "Laat AI automatisch gezichten selecteren.", s3Title: "Opslaan", s3Desc: "Download de geanonimiseerde foto's." },
    convert: { heroBadge: "UNIVERSELE COMPATIBILITEIT", heroTitle: "Formaat Transformator.", heroTitle2: "Geen Kwaliteitsverlies.", heroDesc: "Converteer naadloos tussen WebP, PNG, JPG en AVIF.", feat1Title: "Razendsnel", feat1Desc: "Transformeer bestanden direct met behulp van de volledige kracht van uw apparaat.", feat2Title: "Bulkverwerking", feat2Desc: "500 afbeeldingen converteren? Sleep gewoon de hele map.", feat3Title: "Brede Ondersteuning", feat3Desc: "Ondersteuning voor WebP en klassieke formaten zoals JPG.", stepsTag: "WERKSTROOM", stepsTitle: "Converteer in 3 Stappen", s1Title: "Uploaden", s1Desc: "Sleep uw afbeeldingen naar de werkruimte.", s2Title: "Formaat", s2Desc: "Selecteer het gewenste uitvoerformaat.", s3Title: "Exporteren", s3Desc: "Klik op exporteren en ontvang direct uw bestanden." },
    faqs: {
      "landing.watermark.faq1.q": "Kan ik meerdere foto's tegelijk watermerken?",
      "landing.watermark.faq1.a": "Ja! Onze batchverwerking maakt het snel en eenvoudig om honderden foto's tegelijk te watermerken.",
      "landing.watermark.faq2.q": "Zijn mijn originele foto's veilig?",
      "landing.watermark.faq2.a": "Ja, het proces is 100% privé en lokaal. We slaan nooit afbeeldingen op.",
      "landing.watermark.faq3.q": "Kan ik mijn eigen logo gebruiken?",
      "landing.watermark.faq3.a": "Absoluut. U kunt aangepaste PNG-logo's of tekst met aangepaste lettertypen uploaden.",
      "landing.watermark.faq4.q": "Is er een limiet aan het aantal foto's?",
      "landing.watermark.faq4.a": "Geen limieten! Omdat het op uw apparaat draait, is het helemaal gratis.",
      "landing.blurface.faq1.q": "Detecteert het meerdere gezichten?",
      "landing.blurface.faq1.a": "Ja, onze lokale AI kan snel meerdere gezichten detecteren en vervagen.",
      "landing.blurface.faq2.q": "Is de gezichtsherkenning privé?",
      "landing.blurface.faq2.a": "100% privé. Het AI-model draait direct in uw browser.",
      "landing.blurface.faq3.q": "Moet ik betalen om de AI te gebruiken?",
      "landing.blurface.faq3.a": "Nee, onze AI-tool is volledig gratis.",
      "landing.blurface.faq4.q": "Is het makkelijk om de vervaging aan te passen?",
      "landing.blurface.faq4.a": "Ja, u heeft volledige controle over de vervagingsradius.",
      "landing.convert.faq1.q": "Welke formaten worden ondersteund?",
      "landing.convert.faq1.a": "We ondersteunen WebP, PNG, JPEG en meer.",
      "landing.convert.faq2.q": "Is de conversie snel?",
      "landing.convert.faq2.a": "Extreem snel, het gebeurt lokaal in milliseconden.",
      "landing.convert.faq3.q": "Is deze tool gratis voor bulkconversie?",
      "landing.convert.faq3.a": "Ja! U kunt gratis honderden afbeeldingen tegelijk converteren.",
      "landing.convert.faq4.q": "Zijn mijn geconverteerde bestanden privé?",
      "landing.convert.faq4.a": "Volledig privé. Alles gebeurt direct in uw eigen browservenster."
    }
  },
  it: {
    watermark: { heroBadge: "PROTEZIONE DEL MARCHIO", heroTitle: "Proteggi il Tuo Lavoro.", heroTitle2: "Costruisci la Tua Identità.", heroDesc: "Applica filigrane altamente personalizzabili per proteggere la tua proprietà intellettuale.", feat1Title: "Livelli Non Distruttivi", feat1Desc: "Aggiungi più livelli di filigrana senza alterare l'immagine originale.", feat2Title: "Controllo dell'Opacità", feat2Desc: "Regola la trasparenza del tuo testo o logo.", feat3Title: "Modalità Pattern Ripetuto", feat3Desc: "Ripeti automaticamente la tua filigrana su tutta l'immagine.", stepsTag: "FLUSSO DI LAVORO", stepsTitle: "Proteggi in 3 Passaggi", s1Title: "Carica", s1Desc: "Carica le tue foto originali in modo sicuro nel browser.", s2Title: "Timbra", s2Desc: "Applica il tuo testo o logo personalizzato.", s3Title: "Esporta", s3Desc: "Salva istantaneamente le immagini protette." },
    blurface: { heroBadge: "PRIVACY ASSOLUTA", heroTitle: "Censura con l'IA.", heroTitle2: "Proteggi le Identità.", heroDesc: "Rileva e sfoca automaticamente i volti in pochi secondi. 100% privato.", feat1Title: "Rilevamento Facciale", feat1Desc: "Il nostro modello IA locale trova i volti con incredibile precisione.", feat2Title: "Sfocatura Intelligente", feat2Desc: "Applica sfocatura gaussiana per nascondere le aree sensibili.", feat3Title: "Controllo Manuale", feat3Desc: "Hai bisogno di nascondere un documento? Usa lo strumento manuale.", stepsTag: "COME FUNZIONA", stepsTitle: "Anonimizza in 3 Passaggi", s1Title: "Carica", s1Desc: "Rilascia le foto in modo sicuro nel browser.", s2Title: "Rileva", s2Desc: "Lascia che l'IA selezioni automaticamente i volti.", s3Title: "Salva", s3Desc: "Scarica le foto anonimizzate." },
    convert: { heroBadge: "COMPATIBILITÀ UNIVERSALE", heroTitle: "Trasformatore di Formato.", heroTitle2: "Nessuna Perdita di Qualità.", heroDesc: "Converti senza problemi tra WebP, PNG, JPG e AVIF.", feat1Title: "Velocissimo", feat1Desc: "Trasforma file di grandi dimensioni sfruttando la potenza del tuo dispositivo.", feat2Title: "Elaborazione in Blocco", feat2Desc: "Devi convertire 500 immagini? Trascina l'intera cartella.", feat3Title: "Ampio Supporto", feat3Desc: "Supporto per formati di nuova generazione come WebP e classici come JPG.", stepsTag: "FLUSSO DI LAVORO", stepsTitle: "Converti in 3 Passaggi", s1Title: "Carica", s1Desc: "Trascina le tue immagini nell'area di lavoro.", s2Title: "Formato", s2Desc: "Seleziona il formato di output desiderato.", s3Title: "Esporta", s3Desc: "Fai clic su esporta e ottieni subito i tuoi file." },
    faqs: {
      "landing.watermark.faq1.q": "Posso aggiungere la filigrana a più foto?",
      "landing.watermark.faq1.a": "Sì! L'elaborazione in batch rende facile e veloce aggiungere filigrane a centinaia di foto.",
      "landing.watermark.faq2.q": "Le mie foto originali sono al sicuro?",
      "landing.watermark.faq2.a": "Sì, il processo è privato e locale al 100%.",
      "landing.watermark.faq3.q": "Posso usare il mio logo?",
      "landing.watermark.faq3.a": "Assolutamente. Puoi caricare loghi PNG o usare testo personalizzato.",
      "landing.watermark.faq4.q": "C'è un limite al numero di foto?",
      "landing.watermark.faq4.a": "Nessun limite! Funziona sul tuo dispositivo ed è gratuito.",
      "landing.blurface.faq1.q": "Rileva più volti?",
      "landing.blurface.faq1.a": "Sì, la nostra IA può rilevare e sfocare più volti rapidamente.",
      "landing.blurface.faq2.q": "Il rilevamento facciale è privato?",
      "landing.blurface.faq2.a": "Privato al 100%. L'IA funziona direttamente nel browser.",
      "landing.blurface.faq3.q": "Devo pagare per usare l'IA?",
      "landing.blurface.faq3.a": "No, il nostro strumento di sfocatura IA è completamente gratuito.",
      "landing.blurface.faq4.q": "È facile regolare l'intensità della sfocatura?",
      "landing.blurface.faq4.a": "Sì, hai il pieno controllo sul raggio della sfocatura.",
      "landing.convert.faq1.q": "Quali formati sono supportati?",
      "landing.convert.faq1.a": "Supportiamo WebP, PNG, JPEG e molti altri.",
      "landing.convert.faq2.q": "La conversione è veloce?",
      "landing.convert.faq2.a": "Estremamente veloce. Avviene in millisecondi localmente.",
      "landing.convert.faq3.q": "È gratuito per la conversione in blocco?",
      "landing.convert.faq3.a": "Sì! Puoi convertire centinaia di immagini gratuitamente.",
      "landing.convert.faq4.q": "I miei file convertiti sono privati?",
      "landing.convert.faq4.a": "Completamente privati. Tutto avviene nel tuo browser."
    }
  },
  pl: {
    watermark: { heroBadge: "OCHRONA MARKI", heroTitle: "Chroń Swoją Pracę.", heroTitle2: "Zbuduj Swoją Tożsamość.", heroDesc: "Stosuj wysoce konfigurowalne znaki wodne, aby chronić swoją własność intelektualną.", feat1Title: "Warstwy Niedestrukcyjne", feat1Desc: "Dodawaj wiele warstw znaków wodnych bez zmiany oryginalnego obrazu.", feat2Title: "Kontrola Krycia", feat2Desc: "Dostosuj przezroczystość tekstu lub logo.", feat3Title: "Tryb Wzoru Płytek", feat3Desc: "Automatycznie powtarzaj znak wodny na całym obrazie.", stepsTag: "PRZEPŁYW PRACY", stepsTitle: "Chroń w 3 Krokach", s1Title: "Prześlij", s1Desc: "Bezpiecznie wczytaj oryginalne zdjęcia w przeglądarce.", s2Title: "Stempel", s2Desc: "Zastosuj niestandardowy tekst lub logo.", s3Title: "Eksport", s3Desc: "Błyskawicznie zapisz chronione obrazy." },
    blurface: { heroBadge: "MAKSYMALNA PRYWATNOŚĆ", heroTitle: "Cenzuruj za pomocą AI.", heroTitle2: "Chroń Tożsamość.", heroDesc: "Automatycznie wykrywaj i zamazuj twarze w kilka sekund. 100% prywatności.", feat1Title: "Wykrywanie Twarzy", feat1Desc: "Nasz lokalny model AI automatycznie znajduje twarze na zdjęciach.", feat2Title: "Inteligentne Rozmycie", feat2Desc: "Zastosuj rozmycie gaussowskie, aby trwale ukryć poufne obszary.", feat3Title: "Sterowanie Ręczne", feat3Desc: "Musisz ukryć dokument? Użyj naszego narzędzia ręcznego.", stepsTag: "JAK TO DZIAŁA", stepsTitle: "Anonimizuj w 3 Krokach", s1Title: "Prześlij", s1Desc: "Bezpiecznie upuść zdjęcia do przeglądarki.", s2Title: "Wykryj", s2Desc: "Pozwól AI automatycznie wybrać twarze.", s3Title: "Zapisz", s3Desc: "Pobierz zanonimizowane zdjęcia." },
    convert: { heroBadge: "UNIWERSALNA ZGODNOŚĆ", heroTitle: "Transformator Formatów.", heroTitle2: "Zero Utraty Jakości.", heroDesc: "Płynnie konwertuj między WebP, PNG, JPG i AVIF.", feat1Title: "Błyskawicznie", feat1Desc: "Błyskawicznie przekształcaj pliki przy użyciu pełnej mocy urządzenia.", feat2Title: "Przetwarzanie Zbiorcze", feat2Desc: "Musisz przekonwertować 500 zdjęć? Po prostu przeciągnij cały folder.", feat3Title: "Szerokie Wsparcie", feat3Desc: "Pełne wsparcie dla formatów takich jak WebP oraz klasycznych jak JPG.", stepsTag: "PRZEPŁYW PRACY", stepsTitle: "Konwertuj w 3 Krokach", s1Title: "Prześlij", s1Desc: "Przeciągnij i upuść obrazy do obszaru roboczego.", s2Title: "Format", s2Desc: "Wybierz żądany format wyjściowy.", s3Title: "Eksport", s3Desc: "Kliknij eksportuj i natychmiast uzyskaj pliki." },
    faqs: {
      "landing.watermark.faq1.q": "Czy mogę dodać znak wodny do wielu zdjęć?",
      "landing.watermark.faq1.a": "Tak! Przetwarzanie wsadowe umożliwia szybkie dodawanie znaków wodnych do setek zdjęć.",
      "landing.watermark.faq2.q": "Czy moje oryginalne zdjęcia są bezpieczne?",
      "landing.watermark.faq2.a": "Tak, proces jest w 100% prywatny i lokalny.",
      "landing.watermark.faq3.q": "Czy mogę użyć własnego logo?",
      "landing.watermark.faq3.a": "Oczywiście. Możesz przesłać własne logo PNG lub użyć tekstu.",
      "landing.watermark.faq4.q": "Czy istnieje limit liczby przetwarzanych zdjęć?",
      "landing.watermark.faq4.a": "Bez limitów! Możesz korzystać z narzędzia za darmo.",
      "landing.blurface.faq1.q": "Czy wykrywa wiele twarzy?",
      "landing.blurface.faq1.a": "Tak, nasz lokalny model AI może bardzo szybko zamazać wiele twarzy.",
      "landing.blurface.faq2.q": "Czy wykrywanie twarzy jest prywatne?",
      "landing.blurface.faq2.a": "100% prywatne. Model AI działa w przeglądarce.",
      "landing.blurface.faq3.q": "Czy muszę płacić za korzystanie z AI?",
      "landing.blurface.faq3.a": "Nie, nasze narzędzie jest całkowicie darmowe.",
      "landing.blurface.faq4.q": "Czy łatwo jest dostosować siłę rozmycia?",
      "landing.blurface.faq4.a": "Tak, masz pełną kontrolę nad promieniem rozmycia.",
      "landing.convert.faq1.q": "Jakie formaty są obsługiwane?",
      "landing.convert.faq1.a": "Obsługujemy WebP, PNG, JPEG i więcej.",
      "landing.convert.faq2.q": "Czy konwersja jest szybka?",
      "landing.convert.faq2.a": "Bardzo szybka. Odbywa się lokalnie w przeglądarce.",
      "landing.convert.faq3.q": "Czy to narzędzie jest darmowe do konwersji zbiorczej?",
      "landing.convert.faq3.a": "Tak! Możesz darmowo konwertować setki obrazów.",
      "landing.convert.faq4.q": "Czy moje skonwertowane pliki są prywatne?",
      "landing.convert.faq4.a": "Całkowicie prywatne. Wszystko dzieje się w przeglądarce."
    }
  }
};
module.exports = translationsPart1;
