const faqsPart4 = {
  ms: {
    "landing.watermark.faq1.q": "Bolehkah saya meletakkan tera air pada banyak foto?",
    "landing.watermark.faq1.a": "Ya! Pemprosesan kelompok kami memudahkan anda meletakkan tera air pada ratusan foto sekaligus.",
    "landing.watermark.faq2.q": "Adakah foto asal saya selamat?",
    "landing.watermark.faq2.a": "Ya, proses ini 100% peribadi dan tempatan.",
    "landing.watermark.faq3.q": "Bolehkah saya menggunakan logo saya sendiri?",
    "landing.watermark.faq3.a": "Sudah tentu. Anda boleh memuat naik logo PNG tersuai.",
    "landing.watermark.faq4.q": "Adakah terdapat had jumlah foto?",
    "landing.watermark.faq4.a": "Tiada had! Anda boleh menggunakannya secara percuma.",
    "landing.blurface.faq1.q": "Adakah ia mengesan pelbagai wajah?",
    "landing.blurface.faq1.a": "Ya, AI tempatan kami boleh mengesan dan mengaburkan pelbagai wajah dengan pantas.",
    "landing.blurface.faq2.q": "Adakah pengesanan wajah ini peribadi?",
    "landing.blurface.faq2.a": "100% peribadi. Model AI berjalan terus dalam penyemak imbas anda.",
    "landing.blurface.faq3.q": "Adakah saya perlu membayar untuk menggunakan AI?",
    "landing.blurface.faq3.a": "Tidak, alat kabur AI kami percuma sepenuhnya.",
    "landing.blurface.faq4.q": "Adakah mudah untuk melaraskan intensiti kabur?",
    "landing.blurface.faq4.a": "Ya, anda mempunyai kawalan penuh terhadap jejari kabur.",
    "landing.convert.faq1.q": "Apakah format yang disokong?",
    "landing.convert.faq1.a": "Kami menyokong WebP, PNG, JPEG, dan banyak lagi.",
    "landing.convert.faq2.q": "Adakah penukaran itu pantas?",
    "landing.convert.faq2.a": "Sangat pantas. Berlaku secara tempatan dalam masa milisaat.",
    "landing.convert.faq3.q": "Adakah alat ini percuma untuk penukaran kelompok?",
    "landing.convert.faq3.a": "Ya! Anda boleh menukar ratusan imej secara percuma.",
    "landing.convert.faq4.q": "Adakah fail yang ditukar saya peribadi?",
    "landing.convert.faq4.a": "Sepenuhnya peribadi. Semuanya berlaku dalam penyemak imbas anda."
  },
  id: {
    "landing.watermark.faq1.q": "Bisakah saya menambahkan watermark ke banyak foto?",
    "landing.watermark.faq1.a": "Ya! Pemrosesan massal kami memudahkan menambahkan watermark ke ratusan foto sekaligus.",
    "landing.watermark.faq2.q": "Apakah foto asli saya aman?",
    "landing.watermark.faq2.a": "Ya, prosesnya 100% pribadi dan lokal.",
    "landing.watermark.faq3.q": "Bisakah saya menggunakan logo sendiri?",
    "landing.watermark.faq3.a": "Tentu saja. Anda dapat mengunggah logo PNG kustom.",
    "landing.watermark.faq4.q": "Apakah ada batasan jumlah foto?",
    "landing.watermark.faq4.a": "Tanpa batas! Anda dapat menggunakannya secara gratis.",
    "landing.blurface.faq1.q": "Apakah ini mendeteksi banyak wajah?",
    "landing.blurface.faq1.a": "Ya, AI lokal kami dapat dengan cepat mendeteksi dan memburamkan banyak wajah.",
    "landing.blurface.faq2.q": "Apakah deteksi wajah ini pribadi?",
    "landing.blurface.faq2.a": "100% pribadi. Model AI berjalan di browser Anda.",
    "landing.blurface.faq3.q": "Apakah saya harus membayar untuk menggunakan AI?",
    "landing.blurface.faq3.a": "Tidak, alat ini sepenuhnya gratis.",
    "landing.blurface.faq4.q": "Apakah mudah untuk menyesuaikan intensitas blur?",
    "landing.blurface.faq4.a": "Ya, Anda memiliki kontrol penuh atas radius blur.",
    "landing.convert.faq1.q": "Format apa saja yang didukung?",
    "landing.convert.faq1.a": "Kami mendukung WebP, PNG, JPEG, dan lainnya.",
    "landing.convert.faq2.q": "Apakah konversinya cepat?",
    "landing.convert.faq2.a": "Sangat cepat. Dilakukan secara lokal dalam hitungan milidetik.",
    "landing.convert.faq3.q": "Apakah alat ini gratis untuk konversi massal?",
    "landing.convert.faq3.a": "Ya! Anda dapat mengonversi ratusan gambar secara gratis.",
    "landing.convert.faq4.q": "Apakah file hasil konversi saya pribadi?",
    "landing.convert.faq4.a": "Sepenuhnya pribadi. Semuanya terjadi di browser Anda."
  },
  es: {
    "landing.watermark.faq1.q": "¿Puedo poner marca de agua a varias fotos?",
    "landing.watermark.faq1.a": "¡Sí! Nuestro procesamiento por lotes hace que sea fácil y rápido.",
    "landing.watermark.faq2.q": "¿Mis fotos originales están seguras?",
    "landing.watermark.faq2.a": "Sí, el proceso es 100% privado y local.",
    "landing.watermark.faq3.q": "¿Puedo usar mi propio logotipo?",
    "landing.watermark.faq3.a": "Absolutamente. Puedes subir logotipos PNG personalizados.",
    "landing.watermark.faq4.q": "¿Hay un límite en la cantidad de fotos?",
    "landing.watermark.faq4.a": "¡Sin límites! Puedes usarlo gratis.",
    "landing.blurface.faq1.q": "¿Detecta múltiples rostros?",
    "landing.blurface.faq1.a": "Sí, nuestra IA puede detectar y desenfocar múltiples rostros rápidamente.",
    "landing.blurface.faq2.q": "¿La detección de rostros es privada?",
    "landing.blurface.faq2.a": "100% privado. La IA se ejecuta en tu navegador.",
    "landing.blurface.faq3.q": "¿Tengo que pagar por usar la IA?",
    "landing.blurface.faq3.a": "No, nuestra herramienta es completamente gratuita.",
    "landing.blurface.faq4.q": "¿Es fácil ajustar la intensidad del desenfoque?",
    "landing.blurface.faq4.a": "Sí, tienes control total sobre el radio de desenfoque.",
    "landing.convert.faq1.q": "¿Qué formatos son compatibles?",
    "landing.convert.faq1.a": "Soportamos WebP, PNG, JPEG y más.",
    "landing.convert.faq2.q": "¿La conversión es rápida?",
    "landing.convert.faq2.a": "Extremadamente rápida. Ocurre localmente en milisegundos.",
    "landing.convert.faq3.q": "¿Esta herramienta es gratuita para conversión masiva?",
    "landing.convert.faq3.a": "¡Sí! Puedes convertir cientos de imágenes gratis.",
    "landing.convert.faq4.q": "¿Mis archivos convertidos son privados?",
    "landing.convert.faq4.a": "Completamente privados. Todo sucede en tu navegador."
  },
  zh: {
    "landing.watermark.faq1.q": "我可以给多张照片加水印吗？",
    "landing.watermark.faq1.a": "可以！我们的批量处理让一次给数百张照片加水印变得又快又简单。",
    "landing.watermark.faq2.q": "我的原照片安全吗？",
    "landing.watermark.faq2.a": "是的，整个过程 100% 保护隐私且在本地进行。",
    "landing.watermark.faq3.q": "我可以使用自己的徽标吗？",
    "landing.watermark.faq3.a": "当然可以。你可以上传自定义的 PNG 徽标或使用自定义字体的文本。",
    "landing.watermark.faq4.q": "处理照片数量有限制吗？",
    "landing.watermark.faq4.a": "没有限制！因为它是运行在你的设备上，所以免费无限使用。",
    "landing.blurface.faq1.q": "它能检测多张人脸吗？",
    "landing.blurface.faq1.a": "可以，我们的本地 AI 能够极其快速地检测并模糊单张照片中的多张人脸。",
    "landing.blurface.faq2.q": "人脸检测涉及隐私吗？",
    "landing.blurface.faq2.a": "100% 保护隐私。AI 模型直接在浏览器中运行，不会上传照片。",
    "landing.blurface.faq3.q": "使用 AI 模糊需要付费吗？",
    "landing.blurface.faq3.a": "不需要，完全免费。",
    "landing.blurface.faq4.q": "调整模糊强度容易吗？",
    "landing.blurface.faq4.a": "是的，你可以完全控制模糊半径。",
    "landing.convert.faq1.q": "支持哪些格式？",
    "landing.convert.faq1.a": "我们支持在 WebP、PNG、JPEG 等格式之间转换。",
    "landing.convert.faq2.q": "转换快吗？",
    "landing.convert.faq2.a": "非常快。通过在本地使用 WebAssembly，转换以毫秒计算。",
    "landing.convert.faq3.q": "批量转换收费吗？",
    "landing.convert.faq3.a": "完全免费！你可以免费批量转换数百张图片。",
    "landing.convert.faq4.q": "我转换后的文件私密吗？",
    "landing.convert.faq4.a": "绝对私密。一切操作都在你自己的浏览器窗口中完成。"
  },
  hi: {
    "landing.watermark.faq1.q": "क्या मैं कई तस्वीरों में वॉटरमार्क जोड़ सकता हूँ?",
    "landing.watermark.faq1.a": "हाँ! हमारी बैच प्रोसेसिंग सैकड़ों तस्वीरों में एक साथ वॉटरमार्क जोड़ना आसान बनाती है।",
    "landing.watermark.faq2.q": "क्या मेरी मूल तस्वीरें सुरक्षित हैं?",
    "landing.watermark.faq2.a": "हाँ, प्रक्रिया 100% निजी और स्थानीय है।",
    "landing.watermark.faq3.q": "क्या मैं अपने स्वयं के लोगो का उपयोग कर सकता हूँ?",
    "landing.watermark.faq3.a": "बिल्कुल। आप कस्टम PNG लोगो अपलोड कर सकते हैं।",
    "landing.watermark.faq4.q": "क्या तस्वीरों की संख्या की कोई सीमा है?",
    "landing.watermark.faq4.a": "कोई सीमा नहीं! आप इसे मुफ्त में इस्तेमाल कर सकते हैं।",
    "landing.blurface.faq1.q": "क्या यह कई चेहरों का पता लगाता है?",
    "landing.blurface.faq1.a": "हाँ, हमारा स्थानीय AI कई चेहरों को तेज़ी से पहचान और धुंधला कर सकता है।",
    "landing.blurface.faq2.q": "क्या चेहरे की पहचान निजी है?",
    "landing.blurface.faq2.a": "100% निजी। AI मॉडल आपके ब्राउज़र में चलता है।",
    "landing.blurface.faq3.q": "क्या मुझे AI का उपयोग करने के लिए भुगतान करना होगा?",
    "landing.blurface.faq3.a": "नहीं, हमारा टूल पूरी तरह से मुफ्त है।",
    "landing.blurface.faq4.q": "क्या धुंधलेपन की तीव्रता को समायोजित करना आसान है?",
    "landing.blurface.faq4.a": "हाँ, आपके पास धुंधलेपन की त्रिज्या पर पूर्ण नियंत्रण है।",
    "landing.convert.faq1.q": "कौन से प्रारूप समर्थित हैं?",
    "landing.convert.faq1.a": "हम WebP, PNG, JPEG आदि का समर्थन करते हैं।",
    "landing.convert.faq2.q": "क्या रूपांतरण तेज़ है?",
    "landing.convert.faq2.a": "अत्यंत तेज़। यह स्थानीय स्तर पर मिलीसेकंड में होता है।",
    "landing.convert.faq3.q": "क्या यह टूल बल्क रूपांतरण के लिए मुफ्त है?",
    "landing.convert.faq3.a": "हाँ! आप मुफ्त में सैकड़ों छवियों को परिवर्तित कर सकते हैं।",
    "landing.convert.faq4.q": "क्या मेरी परिवर्तित फ़ाइलें निजी हैं?",
    "landing.convert.faq4.a": "पूरी तरह से निजी। सब कुछ आपके ब्राउज़र में होता है।"
  },
  ja: {
    "landing.watermark.faq1.q": "複数の写真に透かしを入れることはできますか？",
    "landing.watermark.faq1.a": "はい！一括処理機能で、数百枚の写真に簡単に透かしを入れることができます。",
    "landing.watermark.faq2.q": "元の写真は安全ですか？",
    "landing.watermark.faq2.a": "はい、プロセスは100％プライベートでローカルに行われます。",
    "landing.watermark.faq3.q": "自分のロゴを使用できますか？",
    "landing.watermark.faq3.a": "もちろん。カスタムPNGロゴをアップロードできます。",
    "landing.watermark.faq4.q": "処理できる写真の数に制限はありますか？",
    "landing.watermark.faq4.a": "制限はありません！無料でご利用いただけます。",
    "landing.blurface.faq1.q": "複数の顔を検出できますか？",
    "landing.blurface.faq1.a": "はい、AIは複数の顔をすばやく検出してぼかすことができます。",
    "landing.blurface.faq2.q": "顔検出はプライベートですか？",
    "landing.blurface.faq2.a": "100％プライベート。AIモデルはブラウザ上で直接実行されます。",
    "landing.blurface.faq3.q": "AIの使用に料金はかかりますか？",
    "landing.blurface.faq3.a": "いいえ、完全に無料です。",
    "landing.blurface.faq4.q": "ぼかしの強さは簡単に調整できますか？",
    "landing.blurface.faq4.a": "はい、ぼかしの半径を完全に制御できます。",
    "landing.convert.faq1.q": "どのフォーマットがサポートされていますか？",
    "landing.convert.faq1.a": "WebP、PNG、JPEGなどをサポートしています。",
    "landing.convert.faq2.q": "変換は速いですか？",
    "landing.convert.faq2.a": "非常に高速です。ローカルでミリ秒単位で処理されます。",
    "landing.convert.faq3.q": "一括変換は無料ですか？",
    "landing.convert.faq3.a": "はい！何百もの画像を無料で変換できます。",
    "landing.convert.faq4.q": "変換されたファイルはプライベートですか？",
    "landing.convert.faq4.a": "完全にプライベート。すべてブラウザ内で行われます。"
  },
  de: {
    "landing.watermark.faq1.q": "Kann ich mehrere Fotos mit Wasserzeichen versehen?",
    "landing.watermark.faq1.a": "Ja! Die Stapelverarbeitung macht es schnell und einfach.",
    "landing.watermark.faq2.q": "Sind meine Originalfotos sicher?",
    "landing.watermark.faq2.a": "Ja, der Prozess ist zu 100 % privat und lokal.",
    "landing.watermark.faq3.q": "Kann ich mein eigenes Logo verwenden?",
    "landing.watermark.faq3.a": "Absolut. Sie können eigene PNG-Logos hochladen.",
    "landing.watermark.faq4.q": "Gibt es ein Limit für die Anzahl der Fotos?",
    "landing.watermark.faq4.a": "Keine Limits! Sie können es kostenlos nutzen.",
    "landing.blurface.faq1.q": "Erkennt es mehrere Gesichter?",
    "landing.blurface.faq1.a": "Ja, unsere KI kann mehrere Gesichter schnell erkennen und unkenntlich machen.",
    "landing.blurface.faq2.q": "Ist die Gesichtserkennung privat?",
    "landing.blurface.faq2.a": "100 % privat. Das KI-Modell läuft in Ihrem Browser.",
    "landing.blurface.faq3.q": "Muss ich für die Nutzung der KI bezahlen?",
    "landing.blurface.faq3.a": "Nein, unser Tool ist völlig kostenlos.",
    "landing.blurface.faq4.q": "Ist es einfach, die Unschärfe anzupassen?",
    "landing.blurface.faq4.a": "Ja, Sie haben die volle Kontrolle über den Radius.",
    "landing.convert.faq1.q": "Welche Formate werden unterstützt?",
    "landing.convert.faq1.a": "Wir unterstützen WebP, PNG, JPEG und mehr.",
    "landing.convert.faq2.q": "Ist die Konvertierung schnell?",
    "landing.convert.faq2.a": "Extrem schnell. Erfolgt lokal in Millisekunden.",
    "landing.convert.faq3.q": "Ist die Stapelkonvertierung kostenlos?",
    "landing.convert.faq3.a": "Ja! Sie können Hunderte von Bildern kostenlos konvertieren.",
    "landing.convert.faq4.q": "Sind meine konvertierten Dateien privat?",
    "landing.convert.faq4.a": "Völlig privat. Alles passiert in Ihrem Browser."
  },
  ru: {
    "landing.watermark.faq1.q": "Могу ли я добавить водяной знак на несколько фото?",
    "landing.watermark.faq1.a": "Да! Пакетная обработка делает это быстро и легко.",
    "landing.watermark.faq2.q": "Мои оригинальные фото в безопасности?",
    "landing.watermark.faq2.a": "Да, процесс на 100% приватный и локальный.",
    "landing.watermark.faq3.q": "Могу ли я использовать свой логотип?",
    "landing.watermark.faq3.a": "Безусловно. Вы можете загрузить логотипы PNG.",
    "landing.watermark.faq4.q": "Есть ли ограничение на количество фото?",
    "landing.watermark.faq4.a": "Никаких ограничений! Инструмент бесплатный.",
    "landing.blurface.faq1.q": "Распознает ли он несколько лиц?",
    "landing.blurface.faq1.a": "Да, наш ИИ может быстро найти и размыть несколько лиц.",
    "landing.blurface.faq2.q": "Распознавание лиц конфиденциально?",
    "landing.blurface.faq2.a": "На 100% конфиденциально. ИИ работает в вашем браузере.",
    "landing.blurface.faq3.q": "Нужно ли платить за использование ИИ?",
    "landing.blurface.faq3.a": "Нет, наш инструмент абсолютно бесплатен.",
    "landing.blurface.faq4.q": "Легко ли настроить размытие?",
    "landing.blurface.faq4.a": "Да, у вас полный контроль над радиусом.",
    "landing.convert.faq1.q": "Какие форматы поддерживаются?",
    "landing.convert.faq1.a": "Мы поддерживаем WebP, PNG, JPEG и другие.",
    "landing.convert.faq2.q": "Конвертация быстрая?",
    "landing.convert.faq2.a": "Очень быстрая. Происходит локально за миллисекунды.",
    "landing.convert.faq3.q": "Этот инструмент бесплатен для пакетной конвертации?",
    "landing.convert.faq3.a": "Да! Вы можете бесплатно конвертировать сотни изображений.",
    "landing.convert.faq4.q": "Мои конвертированные файлы конфиденциальны?",
    "landing.convert.faq4.a": "Абсолютно конфиденциальны. Всё происходит в вашем браузере."
  },
  ar: {
    "landing.watermark.faq1.q": "هل يمكنني إضافة علامة مائية لعدة صور؟",
    "landing.watermark.faq1.a": "نعم! المعالجة الجماعية تجعل الأمر سريعًا وسهلاً.",
    "landing.watermark.faq2.q": "هل صوري الأصلية آمنة؟",
    "landing.watermark.faq2.a": "نعم، العملية خاصة ومحلية بنسبة 100%.",
    "landing.watermark.faq3.q": "هل يمكنني استخدام شعاري الخاص؟",
    "landing.watermark.faq3.a": "بالتأكيد. يمكنك تحميل شعارات PNG مخصصة.",
    "landing.watermark.faq4.q": "هل هناك حد لعدد الصور؟",
    "landing.watermark.faq4.a": "بلا حدود! يمكنك استخدامه مجانًا.",
    "landing.blurface.faq1.q": "هل يكتشف وجوهًا متعددة؟",
    "landing.blurface.faq1.a": "نعم، يمكن للذكاء الاصطناعي اكتشاف وجوه متعددة وطمسها بسرعة.",
    "landing.blurface.faq2.q": "هل اكتشاف الوجه خاص؟",
    "landing.blurface.faq2.a": "خاص 100%. يعمل نموذج الذكاء الاصطناعي في متصفحك.",
    "landing.blurface.faq3.q": "هل يجب أن أدفع لاستخدام الذكاء الاصطناعي؟",
    "landing.blurface.faq3.a": "لا، الأداة مجانية تمامًا.",
    "landing.blurface.faq4.q": "هل من السهل ضبط الضبابية؟",
    "landing.blurface.faq4.a": "نعم، لديك سيطرة كاملة على نصف القطر.",
    "landing.convert.faq1.q": "ما هي التنسيقات المدعومة؟",
    "landing.convert.faq1.a": "ندعم WebP وPNG وJPEG والمزيد.",
    "landing.convert.faq2.q": "هل التحويل سريع؟",
    "landing.convert.faq2.a": "سريع للغاية. يحدث محليًا في غضون أجزاء من الثانية.",
    "landing.convert.faq3.q": "هل هذه الأداة مجانية للتحويل الجماعي؟",
    "landing.convert.faq3.a": "نعم! يمكنك تحويل مئات الصور مجانًا.",
    "landing.convert.faq4.q": "هل ملفاتي المحولة خاصة؟",
    "landing.convert.faq4.a": "خاصة تمامًا. يحدث كل شيء في متصفحك."
  },
  pt: {
    "landing.watermark.faq1.q": "Posso colocar marca d'água em várias fotos?",
    "landing.watermark.faq1.a": "Sim! O processamento em lote facilita colocar marca d'água em centenas de fotos de uma vez.",
    "landing.watermark.faq2.q": "Minhas fotos originais estão seguras?",
    "landing.watermark.faq2.a": "Sim, o processo é 100% privado e local.",
    "landing.watermark.faq3.q": "Posso usar meu próprio logotipo?",
    "landing.watermark.faq3.a": "Absolutamente. Você pode fazer upload de logotipos PNG personalizados.",
    "landing.watermark.faq4.q": "Existe um limite para a quantidade de fotos?",
    "landing.watermark.faq4.a": "Sem limites! Você pode usá-lo gratuitamente.",
    "landing.blurface.faq1.q": "Ele detecta vários rostos?",
    "landing.blurface.faq1.a": "Sim, nossa IA pode detectar e desfocar vários rostos rapidamente.",
    "landing.blurface.faq2.q": "A detecção de rosto é privada?",
    "landing.blurface.faq2.a": "100% privado. O modelo de IA é executado no seu navegador.",
    "landing.blurface.faq3.q": "Tenho que pagar para usar a IA?",
    "landing.blurface.faq3.a": "Não, nossa ferramenta é totalmente gratuita.",
    "landing.blurface.faq4.q": "É fácil ajustar a intensidade do desfoque?",
    "landing.blurface.faq4.a": "Sim, você tem controle total sobre o raio de desfoque.",
    "landing.convert.faq1.q": "Quais formatos são suportados?",
    "landing.convert.faq1.a": "Suportamos WebP, PNG, JPEG e muito mais.",
    "landing.convert.faq2.q": "A conversão é rápida?",
    "landing.convert.faq2.a": "Extremamente rápido. Acontece localmente em milissegundos.",
    "landing.convert.faq3.q": "Esta ferramenta é gratuita para conversão em lote?",
    "landing.convert.faq3.a": "Sim! Você pode converter centenas de imagens gratuitamente.",
    "landing.convert.faq4.q": "Meus arquivos convertidos são privados?",
    "landing.convert.faq4.a": "Totalmente privado. Tudo acontece no seu navegador."
  },
  ko: {
    "landing.watermark.faq1.q": "여러 장의 사진에 워터마크를 넣을 수 있나요?",
    "landing.watermark.faq1.a": "네! 일괄 처리 기능을 사용하면 한 번에 수백 장의 사진에 빠르고 쉽게 워터마크를 적용할 수 있습니다.",
    "landing.watermark.faq2.q": "원본 사진은 안전한가요?",
    "landing.watermark.faq2.a": "네, 프로세스는 100% 프라이빗하고 로컬에서 처리됩니다.",
    "landing.watermark.faq3.q": "나만의 로고를 사용할 수 있나요?",
    "landing.watermark.faq3.a": "물론입니다. 커스텀 PNG 로고를 업로드하거나 커스텀 폰트로 텍스트 워터마크를 사용할 수 있습니다.",
    "landing.watermark.faq4.q": "처리할 수 있는 사진 수에 제한이 있나요?",
    "landing.watermark.faq4.a": "제한이 없습니다! 기기에서 실행되므로 원하는 만큼 무료로 처리할 수 있습니다.",
    "landing.blurface.faq1.q": "여러 명의 얼굴을 감지하나요?",
    "landing.blurface.faq1.a": "네, 저희 로컬 AI 모델은 한 사진에 있는 여러 명의 얼굴을 매우 빠르게 감지하고 블러 처리할 수 있습니다.",
    "landing.blurface.faq2.q": "얼굴 감지는 프라이빗한가요?",
    "landing.blurface.faq2.a": "100% 프라이빗합니다. AI 모델은 브라우저에서 직접 실행되며, 어떤 서버에도 업로드되지 않습니다.",
    "landing.blurface.faq3.q": "AI 사용 시 비용을 지불해야 하나요?",
    "landing.blurface.faq3.a": "아니요, 저희 AI 블러 도구는 완전히 무료입니다.",
    "landing.blurface.faq4.q": "블러 강도를 조절하기 쉽나요?",
    "landing.blurface.faq4.a": "네, 블러 반경을 완벽하게 제어할 수 있습니다.",
    "landing.convert.faq1.q": "어떤 형식이 지원되나요?",
    "landing.convert.faq1.a": "WebP, PNG, JPEG 등 다양한 형식 변환을 지원합니다.",
    "landing.convert.faq2.q": "변환이 빠른가요?",
    "landing.convert.faq2.a": "매우 빠릅니다. 로컬에서 WebAssembly를 사용하기 때문에 밀리초 만에 완료됩니다.",
    "landing.convert.faq3.q": "대량 변환 도구는 무료인가요?",
    "landing.convert.faq3.a": "네! 어떤 제한도 없이 수백 장의 이미지를 무료로 일괄 변환할 수 있습니다.",
    "landing.convert.faq4.q": "변환된 파일은 프라이빗한가요?",
    "landing.convert.faq4.a": "완벽하게 프라이빗합니다. 모든 작업은 브라우저 창 내부에서 직접 이루어집니다."
  }
};
module.exports = faqsPart4;
