const fs = require('fs');
const path = require('path');

const translations = {
  id: {
    "landing.compress.redesign.heroBadge": "KOMPRESI PINTAR",
    "landing.compress.redesign.heroTitle": "Kecilkan Ukuran File Gambar Hingga 90% Seketika",
    "landing.compress.redesign.heroDesc": "Kurangi ukuran foto Anda tanpa kehilangan kualitas visual. Sempurna untuk website dan email.",
    "landing.compress.redesign.feat1Badge": "TANPA KEHILANGAN KUALITAS",
    "landing.compress.redesign.feat1Title": "Optimasi Pintar",
    "landing.compress.redesign.feat1Desc": "Secara otomatis menemukan keseimbangan sempurna antara ukuran file minimal dan kualitas gambar maksimal.",
    "landing.compress.redesign.feat2Badge": "100% PRIVAT",
    "landing.compress.redesign.feat2Title": "Tanpa Unggah",
    "landing.compress.redesign.feat2Desc": "Seperti semua alat kami, kompresi terjadi langsung di browser web Anda. Tidak ada yang dikirim ke server.",
    "landing.compress.redesign.feat3Badge": "SEMUA FORMAT",
    "landing.compress.redesign.feat3Title": "Dukungan Luas",
    "landing.compress.redesign.feat3Desc": "Bekerja dengan format standar JPG dan PNG serta format WEBP modern.",
    "landing.compress.redesign.whoTag": "UNTUK SIAPA INI",
    "landing.compress.redesign.whoTitle": "Dibuat untuk Web & Media",
    "landing.compress.redesign.whoDesc": "Sempurna untuk pengembang, desainer, dan manajer media sosial yang membutuhkan gambar teroptimasi.",
    "landing.compress.redesign.who1Title": "Pengembang Web",
    "landing.compress.redesign.who1Desc": "Tingkatkan skor PageSpeed dan kurangi waktu muat tanpa mengorbankan kualitas gambar.",
    "landing.compress.redesign.who1Tags": "OPTIMASI SEO",
    "landing.compress.redesign.who2Title": "Pembuat Konten",
    "landing.compress.redesign.who2Desc": "Penuhi batas ukuran unggahan ketat untuk platform seperti Discord atau Twitter.",
    "landing.compress.redesign.who2Tags": "MEDIA SOSIAL",
    "landing.compress.redesign.stepsTag": "CARA KERJA",
    "landing.compress.redesign.stepsTitle": "3 Langkah Optimasi",
    "landing.compress.redesign.s1Title": "Unggah Gambar",
    "landing.compress.redesign.s1Desc": "Seret dan lepas foto Anda ke ruang kerja kompresi.",
    "landing.compress.redesign.s2Title": "Atur Tingkat Kompresi",
    "landing.compress.redesign.s2Desc": "Sesuaikan slider kualitas untuk menemukan keseimbangan yang tepat.",
    "landing.compress.redesign.s3Title": "Hemat Penyimpanan",
    "landing.compress.redesign.s3Desc": "Unduh gambar Anda yang telah dioptimalkan dan nikmati ukuran file yang lebih kecil.",
    "landing.remove.redesign.heroBadge": "POTONGAN AI",
    "landing.remove.redesign.heroTitle": "Hapus Latar Belakang dalam 1 Detik dengan Presisi Sempurna",
    "landing.remove.redesign.heroDesc": "Didukung oleh AI WebAssembly canggih, dapatkan potongan rambut sempurna dan tepi halus tanpa pernah mengunggah foto Anda ke server.",
    "landing.remove.redesign.feat1Badge": "AKURASI 99,8%",
    "landing.remove.redesign.feat1Title": "Deteksi Rambut & Tepi Sempurna",
    "landing.remove.redesign.feat1Desc": "Jaringan saraf kami dengan mudah menangani detail kompleks seperti rambut manusia, bulu hewan, dan objek semi-transparan.",
    "landing.remove.redesign.feat2Badge": "100% AMAN",
    "landing.remove.redesign.feat2Title": "Privasi Offline Total",
    "landing.remove.redesign.feat2Desc": "Model AI dimuat langsung ke browser Anda. Gambar Anda tidak pernah meninggalkan komputer Anda.",
    "landing.remove.redesign.feat3Badge": "MODE BATCH",
    "landing.remove.redesign.feat3Title": "Siap untuk Pemrosesan Massal",
    "landing.remove.redesign.feat3Desc": "Seret dan lepas hingga 10 foto sekaligus. Proses secara bersamaan dan unduh semuanya dalam satu file ZIP.",
    "landing.remove.redesign.whoTag": "UNTUK SIAPA INI",
    "landing.remove.redesign.whoTitle": "Sempurna untuk Setiap Kebutuhan Kreatif",
    "landing.remove.redesign.whoDesc": "Baik Anda menjual mobil, mendesain poster, atau membuat dokumen resmi.",
    "landing.remove.redesign.who1Title": "Penjual E-Commerce",
    "landing.remove.redesign.who1Desc": "Buat latar belakang putih bersih untuk daftar produk yang laku keras.",
    "landing.remove.redesign.who1Tags": "DAFTAR PRODUK",
    "landing.remove.redesign.who2Title": "Desainer Grafis",
    "landing.remove.redesign.who2Desc": "Ekstrak logo, tanda tangan, dan aset secara instan untuk desain komposit Anda.",
    "landing.remove.redesign.who2Tags": "ASET DESAIN",
    "landing.remove.redesign.stepsTag": "CARA KERJA",
    "landing.remove.redesign.stepsTitle": "3 Langkah Menuju Latar Belakang Transparan",
    "landing.remove.redesign.s1Title": "Unggah Gambar",
    "landing.remove.redesign.s1Desc": "Pilih atau seret foto Anda. PNG, JPG atau WEBP didukung.",
    "landing.remove.redesign.s2Title": "Pemrosesan AI",
    "landing.remove.redesign.s2Desc": "AI lokal mendeteksi subjek utama dalam 1 detik.",
    "landing.remove.redesign.s3Title": "Unduh HD",
    "landing.remove.redesign.s3Desc": "Ekspor foto Anda yang telah dipotong dengan latar belakang transparan.",
    "home.why.tag": "MENGAPA HELPMYIMG",
    "home.why.title": "Mengapa HelpMyIMG adalah Pilihan Tercerdas untuk Kreator & Bisnis",
    "home.why.desc": "Dirancang dari awal untuk privasi maksimal, kecepatan kilat, dan tanpa biaya. Inilah mengapa ribuan orang mempercayai HelpMyIMG setiap hari.",
    "home.why.c1.t": "Kecepatan Lokal Instan",
    "home.why.c1.d": "Foto Anda diproses langsung di dalam memori perangkat dengan nol latensi. Tidak ada unggahan file yang lambat.",
    "home.why.c1.b": "Penundaan Server 0ms",
    "home.why.c2.t": "100% Privasi Absolut",
    "home.why.c2.d": "Potret pribadi dan dokumen rahasia Anda tidak pernah meninggalkan komputer Anda.",
    "home.why.c2.b": "Nol Penyimpanan Cloud",
    "home.why.c3.t": "Selamanya Gratis & Tanpa Batas",
    "home.why.c3.d": "Tanpa langganan, tanpa tanda air. Pengeditan foto definisi tinggi dapat diakses oleh semua orang.",
    "home.why.c3.b": "$0 / Seumur Hidup",
    "home.why.c4.t": "Kekuatan Batch hingga 10",
    "home.why.c4.d": "Seret dan lepas hingga 10 foto secara bersamaan, potong latar belakang, dan ekspor sebagai ZIP.",
    "home.why.c4.b": "Kecepatan Kerja 10x",
    "home.steps.tag": "CARA KERJA",
    "home.steps.title": "Bagaimana HelpMyIMG Bekerja dalam 3 Langkah Sederhana",
    "home.steps.desc": "Tidak perlu instalasi perangkat lunak. Dapatkan hasil profesional langsung dari web browser Anda."
  },
  zh: {
    "landing.compress.redesign.heroBadge": "智能压缩",
    "landing.compress.redesign.heroTitle": "立即将图像文件大小缩小高达 90%",
    "landing.compress.redesign.heroDesc": "在不降低视觉质量的情况下减小照片的尺寸。非常适合网站和电子邮件。",
    "landing.compress.redesign.feat1Badge": "无质量损失",
    "landing.compress.redesign.feat1Title": "智能优化",
    "landing.compress.redesign.feat1Desc": "自动找到最小文件大小和最大图像质量之间的完美平衡。",
    "landing.compress.redesign.feat2Badge": "100% 隐私",
    "landing.compress.redesign.feat2Title": "零上传",
    "landing.compress.redesign.feat2Desc": "与我们所有的工具一样，压缩直接在您的浏览器中进行。不会发送任何数据到服务器。",
    "landing.compress.redesign.feat3Badge": "任何格式",
    "landing.compress.redesign.feat3Title": "广泛支持",
    "landing.compress.redesign.feat3Desc": "支持标准的 JPG 和 PNG 格式，以及现代的 WEBP 格式。",
    "landing.compress.redesign.whoTag": "适用人群",
    "landing.compress.redesign.whoTitle": "专为网络和媒体打造",
    "landing.compress.redesign.whoDesc": "非常适合需要优化图像的开发人员、设计师和社交媒体经理。",
    "landing.compress.redesign.who1Title": "网络开发者",
    "landing.compress.redesign.who1Desc": "在不牺牲图像质量的情况下提高 PageSpeed 分数并缩短加载时间。",
    "landing.compress.redesign.who1Tags": "SEO 优化",
    "landing.compress.redesign.who2Title": "内容创作者",
    "landing.compress.redesign.who2Desc": "满足 Discord 或 Twitter 等平台严格的上传大小限制。",
    "landing.compress.redesign.who2Tags": "社交媒体",
    "landing.compress.redesign.stepsTag": "工作原理",
    "landing.compress.redesign.stepsTitle": "3步优化",
    "landing.compress.redesign.s1Title": "上传图片",
    "landing.compress.redesign.s1Desc": "将您的照片拖放到压缩工作区。",
    "landing.compress.redesign.s2Title": "设置压缩级别",
    "landing.compress.redesign.s2Desc": "调整质量滑块以找到正确的平衡。",
    "landing.compress.redesign.s3Title": "节省存储空间",
    "landing.compress.redesign.s3Desc": "下载优化后的图像，享受缩小的文件大小。",
    "landing.remove.redesign.heroBadge": "AI 抠图",
    "landing.remove.redesign.heroTitle": "1秒内以完美精度去除背景",
    "landing.remove.redesign.heroDesc": "由高级 WebAssembly AI 提供支持，获得完美的发丝抠图和光滑边缘，无需上传您的照片。",
    "landing.remove.redesign.feat1Badge": "99.8% 准确率",
    "landing.remove.redesign.feat1Title": "完美的发丝和边缘检测",
    "landing.remove.redesign.feat1Desc": "我们的神经网络可轻松处理复杂的细节，如人类头发、动物皮毛等。",
    "landing.remove.redesign.feat2Badge": "100% 安全",
    "landing.remove.redesign.feat2Title": "完全离线隐私",
    "landing.remove.redesign.feat2Desc": "AI 模型直接加载到您的浏览器中。您的图像永远不会离开您的计算机。",
    "landing.remove.redesign.feat3Badge": "批量模式",
    "landing.remove.redesign.feat3Title": "准备好批量处理",
    "landing.remove.redesign.feat3Desc": "一次最多拖放 10 张照片。将所有内容下载到一个 ZIP 文件中。",
    "landing.remove.redesign.whoTag": "适用人群",
    "landing.remove.redesign.whoTitle": "完美满足各种创意需求",
    "landing.remove.redesign.whoDesc": "无论您是销售汽车、设计海报还是创建官方文件。",
    "landing.remove.redesign.who1Title": "电商卖家",
    "landing.remove.redesign.who1Desc": "为产品列表创建干净的白色背景。",
    "landing.remove.redesign.who1Tags": "产品列表",
    "landing.remove.redesign.who2Title": "平面设计师",
    "landing.remove.redesign.who2Desc": "立即提取徽标、签名和资产。",
    "landing.remove.redesign.who2Tags": "设计资产",
    "landing.remove.redesign.stepsTag": "工作原理",
    "landing.remove.redesign.stepsTitle": "通往透明背景的3个步骤",
    "landing.remove.redesign.s1Title": "上传图片",
    "landing.remove.redesign.s1Desc": "拖放您的照片。PNG、JPG 或 WEBP。",
    "landing.remove.redesign.s2Title": "AI 处理",
    "landing.remove.redesign.s2Desc": "本地 AI 在 1 秒内检测主要主体。",
    "landing.remove.redesign.s3Title": "高清下载",
    "landing.remove.redesign.s3Desc": "导出带有透明背景的抠图照片。",
    "home.why.tag": "为什么选择 HELPMYIMG",
    "home.why.title": "为什么 HelpMyIMG 是创作者的最明智选择",
    "home.why.desc": "从头开始设计，以实现最大的隐私性、闪电般的速度和零成本。",
    "home.why.c1.t": "即时本地速度",
    "home.why.c1.d": "您的照片直接在您的设备内存中处理，零延迟。",
    "home.why.c1.b": "0ms 服务器延迟",
    "home.why.c2.t": "100% 绝对隐私",
    "home.why.c2.d": "您的个人肖像和机密文件永远不会离开您的计算机。",
    "home.why.c2.b": "零云存储",
    "home.why.c3.t": "永远免费且无限制",
    "home.why.c3.d": "无需订阅，无水印。所有人均可使用高清照片编辑。",
    "home.why.c3.b": "$0 / 终身",
    "home.why.c4.t": "最高 10 的批处理能力",
    "home.why.c4.d": "同时拖放多达 10 张照片，并在几秒钟内将其导出为 ZIP 存档。",
    "home.why.c4.b": "10倍 工作速度",
    "home.steps.tag": "工作原理",
    "home.steps.title": "HelpMyIMG 的简单3步操作",
    "home.steps.desc": "无需安装软件。直接从您的网络浏览器获得专业结果。"
  },
  hi: {
    "landing.compress.redesign.heroBadge": "स्मार्ट कम्प्रेशन",
    "landing.compress.redesign.heroTitle": "छवि फ़ाइल का आकार तुरंत 90% तक कम करें",
    "landing.compress.redesign.heroDesc": "दृश्य गुणवत्ता खोए बिना अपनी तस्वीरों का आकार कम करें। वेबसाइटों और ईमेल के लिए बिल्कुल सही।",
    "landing.compress.redesign.feat1Badge": "कोई गुणवत्ता हानि नहीं",
    "landing.compress.redesign.feat1Title": "स्मार्ट अनुकूलन",
    "landing.compress.redesign.feat1Desc": "न्यूनतम फ़ाइल आकार और अधिकतम छवि गुणवत्ता के बीच सही संतुलन स्वचालित रूप से ढूँढता है।",
    "landing.compress.redesign.feat2Badge": "100% निजी",
    "landing.compress.redesign.feat2Title": "शून्य अपलोड",
    "landing.compress.redesign.feat2Desc": "हमारे सभी टूल की तरह, संपीड़न सीधे आपके वेब ब्राउज़र में होता है। सर्वर पर कुछ भी नहीं जाता है।",
    "landing.compress.redesign.feat3Badge": "कोई भी प्रारूप",
    "landing.compress.redesign.feat3Title": "व्यापक समर्थन",
    "landing.compress.redesign.feat3Desc": "मानक JPG और PNG स्वरूपों के साथ-साथ आधुनिक WEBP स्वरूपों के साथ काम करता है।",
    "landing.compress.redesign.whoTag": "यह किसके लिए है",
    "landing.compress.redesign.whoTitle": "वेब और मीडिया के लिए निर्मित",
    "landing.compress.redesign.whoDesc": "डेवलपर्स, डिजाइनरों और सोशल मीडिया प्रबंधकों के लिए बिल्कुल सही जिन्हें अनुकूलित छवियों की आवश्यकता होती है।",
    "landing.compress.redesign.who1Title": "वेब डेवलपर्स",
    "landing.compress.redesign.who1Desc": "छवि गुणवत्ता से समझौता किए बिना PageSpeed ​​स्कोर में सुधार करें और लोड समय कम करें।",
    "landing.compress.redesign.who1Tags": "एसईओ अनुकूलन",
    "landing.compress.redesign.who2Title": "सामग्री निर्माता",
    "landing.compress.redesign.who2Desc": "डिस्कॉर्ड या ट्विटर जैसे प्लेटफार्मों के लिए सख्त अपलोड आकार सीमाएं पूरी करें।",
    "landing.compress.redesign.who2Tags": "सोशल मीडिया",
    "landing.compress.redesign.stepsTag": "यह कैसे काम करता है",
    "landing.compress.redesign.stepsTitle": "अनुकूलन के लिए 3 चरण",
    "landing.compress.redesign.s1Title": "छवियां अपलोड करें",
    "landing.compress.redesign.s1Desc": "अपनी तस्वीरों को संपीड़न कार्यक्षेत्र में खींचें और छोड़ें।",
    "landing.compress.redesign.s2Title": "संपीड़न स्तर सेट करें",
    "landing.compress.redesign.s2Desc": "सही संतुलन खोजने के लिए गुणवत्ता स्लाइडर समायोजित करें।",
    "landing.compress.redesign.s3Title": "भंडारण बचाएं",
    "landing.compress.redesign.s3Desc": "अपनी अनुकूलित छवियां डाउनलोड करें और कम फ़ाइल आकार का आनंद लें।",
    "landing.remove.redesign.heroBadge": "एआई संचालित कटआउट",
    "landing.remove.redesign.heroTitle": "निर्दोष सटीकता के साथ 1 सेकंड में पृष्ठभूमि हटाएं",
    "landing.remove.redesign.heroDesc": "उन्नत WebAssembly AI द्वारा संचालित, कभी भी अपनी तस्वीरें सर्वर पर अपलोड किए बिना सही बालों के कटआउट और चिकने किनारे प्राप्त करें।",
    "landing.remove.redesign.feat1Badge": "99.8% सटीकता",
    "landing.remove.redesign.feat1Title": "निर्दोष बाल और किनारे का पता लगाना",
    "landing.remove.redesign.feat1Desc": "हमारा तंत्रिका नेटवर्क मानव बाल, जानवरों के फर और अर्ध-पारदर्शी वस्तुओं जैसे जटिल विवरणों को आसानी से संभालता है।",
    "landing.remove.redesign.feat2Badge": "100% सुरक्षित",
    "landing.remove.redesign.feat2Title": "पूर्ण ऑफ़लाइन गोपनीयता",
    "landing.remove.redesign.feat2Desc": "एआई मॉडल सीधे आपके ब्राउज़र में लोड होता है। आपकी छवियां आपके कंप्यूटर को कभी नहीं छोड़ती हैं।",
    "landing.remove.redesign.feat3Badge": "बैच मोड",
    "landing.remove.redesign.feat3Title": "थोक प्रसंस्करण के लिए तैयार",
    "landing.remove.redesign.feat3Desc": "एक बार में 10 तस्वीरें खींचें और छोड़ें। सब कुछ एक ही ज़िप फ़ाइल में डाउनलोड करें।",
    "landing.remove.redesign.whoTag": "यह किसके लिए है",
    "landing.remove.redesign.whoTitle": "हर रचनात्मक ज़रूरत के लिए बिल्कुल सही",
    "landing.remove.redesign.whoDesc": "चाहे आप कार बेच रहे हों, पोस्टर डिजाइन कर रहे हों, या आधिकारिक दस्तावेज बना रहे हों।",
    "landing.remove.redesign.who1Title": "ई-कॉमर्स विक्रेता",
    "landing.remove.redesign.who1Desc": "उत्पाद सूचीकरण के लिए साफ सफेद पृष्ठभूमि बनाएं।",
    "landing.remove.redesign.who1Tags": "उत्पाद सूची",
    "landing.remove.redesign.who2Title": "ग्राफिक डिजाइनर",
    "landing.remove.redesign.who2Desc": "लोगो, हस्ताक्षर और संपत्ति तुरंत निकालें।",
    "landing.remove.redesign.who2Tags": "डिजाइन संपत्ति",
    "landing.remove.redesign.stepsTag": "यह कैसे काम करता है",
    "landing.remove.redesign.stepsTitle": "पारदर्शी पृष्ठभूमि के 3 चरण",
    "landing.remove.redesign.s1Title": "छवि अपलोड करें",
    "landing.remove.redesign.s1Desc": "अपनी तस्वीर खींचें और छोड़ें। पीएनजी, जेपीजी, या वेबपी।",
    "landing.remove.redesign.s2Title": "एआई प्रसंस्करण",
    "landing.remove.redesign.s2Desc": "स्थानीय एआई 1 सेकंड में मुख्य विषय का पता लगाता है।",
    "landing.remove.redesign.s3Title": "एचडी डाउनलोड करें",
    "landing.remove.redesign.s3Desc": "पारदर्शी पृष्ठभूमि के साथ अपनी कटआउट तस्वीर निर्यात करें।",
    "home.why.tag": "HELPMYIMG क्यों",
    "home.why.title": "क्यों HelpMyIMG रचनाकारों के लिए सबसे चतुर विकल्प है",
    "home.why.desc": "अधिकतम गोपनीयता, बिजली की तेज गति और शून्य लागत के लिए आधार से डिज़ाइन किया गया।",
    "home.why.c1.t": "तत्काल स्थानीय गति",
    "home.why.c1.d": "आपकी तस्वीरों को सीधे आपके डिवाइस की मेमोरी में शून्य विलंबता के साथ संसाधित किया जाता है।",
    "home.why.c1.b": "0ms सर्वर विलंब",
    "home.why.c2.t": "100% पूर्ण गोपनीयता",
    "home.why.c2.d": "आपके व्यक्तिगत चित्र और गोपनीय दस्तावेज़ कभी भी आपका कंप्यूटर नहीं छोड़ते हैं।",
    "home.why.c2.b": "शून्य क्लाउड स्टोरेज",
    "home.why.c3.t": "हमेशा के लिए नि:शुल्क और असीमित",
    "home.why.c3.d": "कोई सदस्यता नहीं, कोई वॉटरमार्क नहीं। उच्च-परिभाषा फोटो संपादन सभी के लिए सुलभ है।",
    "home.why.c3.b": "$0 / जीवन भर",
    "home.why.c4.t": "10 तक बैच पावर",
    "home.why.c4.d": "एक साथ 10 फ़ोटो खींचें और छोड़ें, और सेकंड में ज़िप संग्रह के रूप में निर्यात करें।",
    "home.why.c4.b": "10x काम की गति",
    "home.steps.tag": "यह कैसे काम करता है",
    "home.steps.title": "HelpMyIMG 3 आसान चरणों में कैसे काम करता है",
    "home.steps.desc": "किसी सॉफ़्टवेयर स्थापना की आवश्यकता नहीं है। सीधे अपने वेब ब्राउज़र से पेशेवर परिणाम प्राप्त करें।"
  },
  es: {
    "landing.compress.redesign.heroBadge": "COMPRESIÓN INTELIGENTE",
    "landing.compress.redesign.heroTitle": "Reduzca el tamaño del archivo de imagen hasta en un 90% al instante",
    "landing.compress.redesign.heroDesc": "Reduzca el tamaño de sus fotos sin perder calidad visual. Perfecto para sitios web y correos electrónicos.",
    "landing.compress.redesign.feat1Badge": "SIN PÉRDIDA DE CALIDAD",
    "landing.compress.redesign.feat1Title": "Optimización Inteligente",
    "landing.compress.redesign.feat1Desc": "Encuentra automáticamente el equilibrio perfecto entre el tamaño mínimo del archivo y la máxima calidad de imagen.",
    "landing.compress.redesign.feat2Badge": "100% PRIVADO",
    "landing.compress.redesign.feat2Title": "Cero Subidas",
    "landing.compress.redesign.feat2Desc": "La compresión se realiza directamente en su navegador web. Nada se envía a ningún servidor.",
    "landing.compress.redesign.feat3Badge": "CUALQUIER FORMATO",
    "landing.compress.redesign.feat3Title": "Amplio Soporte",
    "landing.compress.redesign.feat3Desc": "Funciona con los formatos estándar JPG y PNG, así como con los modernos formatos WEBP.",
    "landing.compress.redesign.whoTag": "PARA QUIÉN ES",
    "landing.compress.redesign.whoTitle": "Construido para Web y Medios",
    "landing.compress.redesign.whoDesc": "Perfecto para desarrolladores, diseñadores y administradores de redes sociales que necesitan imágenes optimizadas.",
    "landing.compress.redesign.who1Title": "Desarrolladores Web",
    "landing.compress.redesign.who1Desc": "Mejore las puntuaciones de PageSpeed y reduzca los tiempos de carga sin sacrificar la calidad de la imagen.",
    "landing.compress.redesign.who1Tags": "OPTIMIZACIÓN SEO",
    "landing.compress.redesign.who2Title": "Creadores de Contenido",
    "landing.compress.redesign.who2Desc": "Cumpla con los estrictos límites de tamaño de carga para plataformas como Discord o Twitter.",
    "landing.compress.redesign.who2Tags": "REDES SOCIALES",
    "landing.compress.redesign.stepsTag": "CÓMO FUNCIONA",
    "landing.compress.redesign.stepsTitle": "3 Pasos para Optimizar",
    "landing.compress.redesign.s1Title": "Subir Imágenes",
    "landing.compress.redesign.s1Desc": "Arrastre y suelte sus fotos en el espacio de trabajo de compresión.",
    "landing.compress.redesign.s2Title": "Establecer Nivel de Compresión",
    "landing.compress.redesign.s2Desc": "Ajuste el control deslizante de calidad para encontrar el equilibrio adecuado.",
    "landing.compress.redesign.s3Title": "Ahorrar Almacenamiento",
    "landing.compress.redesign.s3Desc": "Descargue sus imágenes optimizadas y disfrute de tamaños de archivo reducidos.",
    "landing.remove.redesign.heroBadge": "RECORTE IMPULSADO POR IA",
    "landing.remove.redesign.heroTitle": "Eliminar Fondo en 1 Segundo con Precisión Impecable",
    "landing.remove.redesign.heroDesc": "Impulsado por IA avanzada de WebAssembly, obtenga recortes de cabello perfectos y bordes suaves sin cargar sus fotos en un servidor.",
    "landing.remove.redesign.feat1Badge": "99.8% PRECISIÓN",
    "landing.remove.redesign.feat1Title": "Detección Impecable de Cabello y Bordes",
    "landing.remove.redesign.feat1Desc": "Nuestra red neuronal maneja fácilmente detalles complejos como cabello humano, pelaje de animales y objetos semitransparentes.",
    "landing.remove.redesign.feat2Badge": "100% SEGURO",
    "landing.remove.redesign.feat2Title": "Privacidad Offline Completa",
    "landing.remove.redesign.feat2Desc": "El modelo de IA se carga directamente en su navegador. Sus imágenes nunca salen de su computadora.",
    "landing.remove.redesign.feat3Badge": "MODO POR LOTES",
    "landing.remove.redesign.feat3Title": "Listo para Procesamiento Masivo",
    "landing.remove.redesign.feat3Desc": "Arrastre y suelte hasta 10 fotos a la vez y descárguelas todas en un archivo ZIP.",
    "landing.remove.redesign.whoTag": "PARA QUIÉN ES",
    "landing.remove.redesign.whoTitle": "Perfecto para Cada Necesidad Creativa",
    "landing.remove.redesign.whoDesc": "Ya sea que venda automóviles, diseñe carteles o cree documentos oficiales.",
    "landing.remove.redesign.who1Title": "Vendedores de E-Commerce",
    "landing.remove.redesign.who1Desc": "Cree fondos blancos limpios para listados de productos que se vendan solos.",
    "landing.remove.redesign.who1Tags": "LISTADOS DE PRODUCTOS",
    "landing.remove.redesign.who2Title": "Diseñadores Gráficos",
    "landing.remove.redesign.who2Desc": "Extraiga logotipos, firmas y activos al instante para sus diseños compuestos.",
    "landing.remove.redesign.who2Tags": "ACTIVOS DE DISEÑO",
    "landing.remove.redesign.stepsTag": "CÓMO FUNCIONA",
    "landing.remove.redesign.stepsTitle": "3 Pasos hacia Fondos Transparentes",
    "landing.remove.redesign.s1Title": "Subir Imagen",
    "landing.remove.redesign.s1Desc": "Arrastre y suelte su foto. Se admiten PNG, JPG o WEBP.",
    "landing.remove.redesign.s2Title": "Procesamiento de IA",
    "landing.remove.redesign.s2Desc": "La IA local detecta el sujeto principal en 1 segundo.",
    "landing.remove.redesign.s3Title": "Descarga HD",
    "landing.remove.redesign.s3Desc": "Exporte su foto recortada con un fondo transparente.",
    "home.why.tag": "POR QUÉ HELPMYIMG",
    "home.why.title": "Por Qué HelpMyIMG es la Opción Más Inteligente",
    "home.why.desc": "Diseñado desde cero para máxima privacidad, velocidad del rayo y costo cero.",
    "home.why.c1.t": "Velocidad Local Instantánea",
    "home.why.c1.d": "Sus fotos se procesan directamente dentro de la memoria de su dispositivo con latencia cero.",
    "home.why.c1.b": "0ms Retraso del Servidor",
    "home.why.c2.t": "100% Privacidad Absoluta",
    "home.why.c2.d": "Sus retratos personales y documentos confidenciales nunca salen de su computadora.",
    "home.why.c2.b": "Cero Almacenamiento en la Nube",
    "home.why.c3.t": "Siempre Gratis e Ilimitado",
    "home.why.c3.d": "Sin suscripciones, sin marcas de agua. Edición de fotos de alta definición accesible para todos.",
    "home.why.c3.b": "$0 / Por Vida",
    "home.why.c4.t": "Poder por Lotes hasta 10",
    "home.why.c4.d": "Arrastre hasta 10 fotos simultáneamente y expórtelas como un archivo ZIP en segundos.",
    "home.why.c4.b": "10x Velocidad de Trabajo",
    "home.steps.tag": "CÓMO FUNCIONA",
    "home.steps.title": "Cómo Funciona HelpMyIMG en 3 Sencillos Pasos",
    "home.steps.desc": "No se requiere instalación de software. Obtenga resultados profesionales desde su navegador web."
  },
  ja: {
    "landing.compress.redesign.heroBadge": "スマート圧縮",
    "landing.compress.redesign.heroTitle": "画像ファイルサイズを瞬時に最大90%縮小",
    "landing.compress.redesign.heroDesc": "視覚的な品質を損なうことなく、写真のサイズを縮小します。Webサイトや電子メールに最適です。",
    "landing.compress.redesign.feat1Badge": "品質の損失なし",
    "landing.compress.redesign.feat1Title": "スマート最適化",
    "landing.compress.redesign.feat1Desc": "最小ファイルサイズと最大画質との完璧なバランスを自動的に見つけます。",
    "landing.compress.redesign.feat2Badge": "100% プライベート",
    "landing.compress.redesign.feat2Title": "アップロードなし",
    "landing.compress.redesign.feat2Desc": "すべてのツールと同様に、圧縮はWebブラウザー内で直接行われます。サーバーには何も送信されません。",
    "landing.compress.redesign.feat3Badge": "あらゆるフォーマット",
    "landing.compress.redesign.feat3Title": "幅広いサポート",
    "landing.compress.redesign.feat3Desc": "標準のJPGおよびPNG形式に加えて、最新のWEBP形式で動作します。",
    "landing.compress.redesign.whoTag": "対象者",
    "landing.compress.redesign.whoTitle": "Webおよびメディア向けに構築",
    "landing.compress.redesign.whoDesc": "最適化された画像を必要とする開発者、デザイナー、ソーシャルメディアマネージャーに最適です。",
    "landing.compress.redesign.who1Title": "Web 開発者",
    "landing.compress.redesign.who1Desc": "画質を犠牲にすることなく、PageSpeed スコアを向上させ、読み込み時間を短縮します。",
    "landing.compress.redesign.who1Tags": "SEOの最適化",
    "landing.compress.redesign.who2Title": "コンテンツクリエイター",
    "landing.compress.redesign.who2Desc": "Discord や Twitter などのプラットフォームの厳しいアップロードサイズ制限を満たします。",
    "landing.compress.redesign.who2Tags": "ソーシャルメディア",
    "landing.compress.redesign.stepsTag": "使い方",
    "landing.compress.redesign.stepsTitle": "最適化のための 3 つのステップ",
    "landing.compress.redesign.s1Title": "画像のアップロード",
    "landing.compress.redesign.s1Desc": "写真を圧縮ワークスペースにドラッグ アンド ドロップします。",
    "landing.compress.redesign.s2Title": "圧縮レベルの設定",
    "landing.compress.redesign.s2Desc": "品質スライダーを調整して、適切なバランスを見つけます。",
    "landing.compress.redesign.s3Title": "ストレージの節約",
    "landing.compress.redesign.s3Desc": "最適化された画像をダウンロードし、ファイルサイズが縮小されたことをお楽しみください。",
    "landing.remove.redesign.heroBadge": "AI を活用した切り抜き",
    "landing.remove.redesign.heroTitle": "完璧な精度で1秒で背景を削除",
    "landing.remove.redesign.heroDesc": "高度な WebAssembly AI を搭載し、写真をサーバーにアップロードすることなく、完璧な髪の切り抜きと滑らかなエッジを実現します。",
    "landing.remove.redesign.feat1Badge": "99.8% の精度",
    "landing.remove.redesign.feat1Title": "完璧な髪とエッジの検出",
    "landing.remove.redesign.feat1Desc": "当社のニューラル ネットワークは、人間の髪の毛、動物の毛皮、半透明の物体などの複雑な詳細を簡単に処理します。",
    "landing.remove.redesign.feat2Badge": "100% 安全",
    "landing.remove.redesign.feat2Title": "完全なオフラインプライバシー",
    "landing.remove.redesign.feat2Desc": "AI モデルはブラウザに直接読み込まれます。あなたの画像があなたのコンピュータから離れることはありません。",
    "landing.remove.redesign.feat3Badge": "バッチモード",
    "landing.remove.redesign.feat3Title": "一括処理の準備完了",
    "landing.remove.redesign.feat3Desc": "一度に最大10枚の写真をドラッグアンドドロップします。1つのZIPファイルですべてをダウンロードします。",
    "landing.remove.redesign.whoTag": "対象者",
    "landing.remove.redesign.whoTitle": "あらゆる創造的なニーズに最適",
    "landing.remove.redesign.whoDesc": "車を販売している場合でも、ポスターをデザインしている場合でも、公式文書を作成している場合でも。",
    "landing.remove.redesign.who1Title": "Eコマースの売り手",
    "landing.remove.redesign.who1Desc": "自社で販売する商品リスト用のきれいな白い背景を作成します。",
    "landing.remove.redesign.who1Tags": "商品リスト",
    "landing.remove.redesign.who2Title": "グラフィック デザイナー",
    "landing.remove.redesign.who2Desc": "合成デザインのロゴ、署名、アセットを即座に抽出します。",
    "landing.remove.redesign.who2Tags": "デザイン アセット",
    "landing.remove.redesign.stepsTag": "使い方",
    "landing.remove.redesign.stepsTitle": "透明な背景への 3 つのステップ",
    "landing.remove.redesign.s1Title": "画像のアップロード",
    "landing.remove.redesign.s1Desc": "写真をドラッグアンドドロップします。PNG、JPG、またはWEBPがサポートされています。",
    "landing.remove.redesign.s2Title": "AI処理",
    "landing.remove.redesign.s2Desc": "ローカルAIが主要な被写体を1秒で検出します。",
    "landing.remove.redesign.s3Title": "HDダウンロード",
    "landing.remove.redesign.s3Desc": "透明な背景で切り抜かれた写真をエクスポートします。",
    "home.why.tag": "HELPMYIMG を選ぶ理由",
    "home.why.title": "HelpMyIMGがクリエイターや企業にとって最も賢い選択である理由",
    "home.why.desc": "最大のプライバシー、超高速、ゼロコストを実現するためにゼロから設計されています。",
    "home.why.c1.t": "インスタントなローカルスピード",
    "home.why.c1.d": "写真はデバイスのメモリ内で直接処理され、遅延はゼロです。ファイルアップロードの遅延はありません。",
    "home.why.c1.b": "0ms のサーバー遅延",
    "home.why.c2.t": "100% 絶対的なプライバシー",
    "home.why.c2.d": "あなたの個人的なポートレートや機密文書があなたのコンピューターから離れることはありません。",
    "home.why.c2.b": "クラウドストレージゼロ",
    "home.why.c3.t": "永久に無料で無制限",
    "home.why.c3.d": "サブスクリプションなし、透かしなし。誰もが利用できる高解像度の写真編集。",
    "home.why.c3.b": "生涯 $0",
    "home.why.c4.t": "最大10のバッチパワー",
    "home.why.c4.d": "最大10枚の写真を同時にドラッグアンドドロップし、背景を削除して、数秒でZIPとしてエクスポートします。",
    "home.why.c4.b": "10倍の作業速度",
    "home.steps.tag": "使い方",
    "home.steps.title": "HelpMyIMG が 3 つの簡単なステップで機能する仕組み",
    "home.steps.desc": "ソフトウェアのインストールは必要ありません。Web ブラウザーから直接、プロフェッショナルな結果を得ることができます。"
  }
};

const scriptDir = __dirname;
const localesDir = path.join(scriptDir, '../public/locales');

for (const [lang, kv] of Object.entries(translations)) {
  const filePath = path.join(localesDir, lang, 'translation.json');
  if (fs.existsSync(filePath)) {
    const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    for (const [key, val] of Object.entries(kv)) {
      data[key] = val;
    }
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
    console.log(`[${lang}] Injected translations chunk 5`);
  }
}
