const fs = require('fs');
const path = require('path');

const translations = {
  pt: {
    "landing.compress.redesign.heroBadge": "COMPRESSÃO INTELIGENTE",
    "landing.compress.redesign.heroTitle": "Reduza o tamanho do arquivo de imagem em até 90% instantaneamente",
    "landing.compress.redesign.heroDesc": "Diminua o tamanho das suas fotos sem perder qualidade visual. Perfeito para sites e e-mails.",
    "landing.compress.redesign.feat1Badge": "SEM PERDA DE QUALIDADE",
    "landing.compress.redesign.feat1Title": "Otimização Inteligente",
    "landing.compress.redesign.feat1Desc": "Encontra automaticamente o equilíbrio perfeito entre o tamanho mínimo do arquivo e a máxima qualidade de imagem.",
    "landing.compress.redesign.feat2Badge": "100% PRIVADO",
    "landing.compress.redesign.feat2Title": "Zero Upload",
    "landing.compress.redesign.feat2Desc": "A compressão acontece diretamente no seu navegador web. Nada é enviado para servidores.",
    "landing.compress.redesign.feat3Badge": "QUALQUER FORMATO",
    "landing.compress.redesign.feat3Title": "Amplo Suporte",
    "landing.compress.redesign.feat3Desc": "Funciona com os formatos padrão JPG e PNG, bem como com formatos WEBP modernos.",
    "landing.compress.redesign.whoTag": "PARA QUEM É",
    "landing.compress.redesign.whoTitle": "Construído para Web e Mídia",
    "landing.compress.redesign.whoDesc": "Perfeito para desenvolvedores, designers e gerentes de mídia social que precisam de imagens otimizadas.",
    "landing.compress.redesign.who1Title": "Desenvolvedores Web",
    "landing.compress.redesign.who1Desc": "Melhore as pontuações do PageSpeed e reduza o tempo de carregamento sem sacrificar a qualidade da imagem.",
    "landing.compress.redesign.who1Tags": "OTIMIZAÇÃO SEO",
    "landing.compress.redesign.who2Title": "Criadores de Conteúdo",
    "landing.compress.redesign.who2Desc": "Cumpra os rígidos limites de tamanho de upload para plataformas como Discord ou Twitter.",
    "landing.compress.redesign.who2Tags": "MÍDIA SOCIAL",
    "landing.compress.redesign.stepsTag": "COMO FUNCIONA",
    "landing.compress.redesign.stepsTitle": "3 Passos para Otimizar",
    "landing.compress.redesign.s1Title": "Carregar Imagens",
    "landing.compress.redesign.s1Desc": "Arraste e solte suas fotos na área de trabalho de compressão.",
    "landing.compress.redesign.s2Title": "Definir Nível de Compressão",
    "landing.compress.redesign.s2Desc": "Ajuste o controle deslizante de qualidade para encontrar o equilíbrio certo.",
    "landing.compress.redesign.s3Title": "Economize Armazenamento",
    "landing.compress.redesign.s3Desc": "Baixe suas imagens otimizadas e aproveite arquivos menores.",
    "landing.remove.redesign.heroBadge": "RECORTE COM IA",
    "landing.remove.redesign.heroTitle": "Remover Fundo em 1 Segundo com Precisão Impecável",
    "landing.remove.redesign.heroDesc": "Desenvolvido com IA WebAssembly avançada, obtenha recortes de cabelo perfeitos e bordas suaves sem nunca fazer upload de suas fotos para um servidor.",
    "landing.remove.redesign.feat1Badge": "PRECISÃO DE 99.8%",
    "landing.remove.redesign.feat1Title": "Detecção Impecável de Cabelo e Bordas",
    "landing.remove.redesign.feat1Desc": "Nossa rede neural lida facilmente com detalhes complexos como cabelo humano, pelo de animais e objetos semitransparentes.",
    "landing.remove.redesign.feat2Badge": "100% SEGURO",
    "landing.remove.redesign.feat2Title": "Privacidade Offline Total",
    "landing.remove.redesign.feat2Desc": "O modelo de IA é carregado diretamente no seu navegador. Suas imagens nunca saem do seu computador.",
    "landing.remove.redesign.feat3Badge": "MODO EM LOTE",
    "landing.remove.redesign.feat3Title": "Pronto para Processamento em Massa",
    "landing.remove.redesign.feat3Desc": "Arraste e solte até 10 fotos de uma vez. Baixe tudo em um arquivo ZIP.",
    "landing.remove.redesign.whoTag": "PARA QUEM É",
    "landing.remove.redesign.whoTitle": "Perfeito para Cada Necessidade Criativa",
    "landing.remove.redesign.whoDesc": "Esteja você vendendo carros, criando pôsteres ou fazendo documentos oficiais.",
    "landing.remove.redesign.who1Title": "Vendedores de E-Commerce",
    "landing.remove.redesign.who1Desc": "Crie fundos brancos limpos para listagens de produtos que vendem por si só.",
    "landing.remove.redesign.who1Tags": "LISTAGENS DE PRODUTOS",
    "landing.remove.redesign.who2Title": "Designers Gráficos",
    "landing.remove.redesign.who2Desc": "Extraia logotipos, assinaturas e ativos instantaneamente para seus designs compostos.",
    "landing.remove.redesign.who2Tags": "ATIVOS DE DESIGN",
    "landing.remove.redesign.stepsTag": "COMO FUNCIONA",
    "landing.remove.redesign.stepsTitle": "3 Passos para Fundos Transparentes",
    "landing.remove.redesign.s1Title": "Carregar Imagem",
    "landing.remove.redesign.s1Desc": "Arraste e solte sua foto. PNG, JPG ou WEBP são suportados.",
    "landing.remove.redesign.s2Title": "Processamento de IA",
    "landing.remove.redesign.s2Desc": "IA local detecta o assunto principal em 1 segundo.",
    "landing.remove.redesign.s3Title": "Download HD",
    "landing.remove.redesign.s3Desc": "Exporte sua foto recortada com um fundo transparente.",
    "home.why.tag": "POR QUE HELPMYIMG",
    "home.why.title": "Por que o HelpMyIMG é a Escolha Mais Inteligente",
    "home.why.desc": "Projetado do zero para máxima privacidade, velocidade relâmpago e custo zero.",
    "home.why.c1.t": "Velocidade Local Instantânea",
    "home.why.c1.d": "Suas fotos são processadas diretamente dentro da memória do seu dispositivo com latência zero.",
    "home.why.c1.b": "0ms Atraso do Servidor",
    "home.why.c2.t": "100% Privacidade Absoluta",
    "home.why.c2.d": "Seus retratos pessoais e documentos confidenciais nunca saem do seu computador.",
    "home.why.c2.b": "Zero Armazenamento em Nuvem",
    "home.why.c3.t": "Sempre Grátis e Ilimitado",
    "home.why.c3.d": "Sem assinaturas, sem marcas d'água. Edição de fotos em alta definição acessível a todos.",
    "home.why.c3.b": "$0 / Vida",
    "home.why.c4.t": "Poder em Lote de até 10",
    "home.why.c4.d": "Arraste até 10 fotos simultaneamente e exporte como um arquivo ZIP em segundos.",
    "home.why.c4.b": "10x Velocidade de Trabalho",
    "home.steps.tag": "COMO FUNCIONA",
    "home.steps.title": "Como o HelpMyIMG Funciona em 3 Etapas Simples",
    "home.steps.desc": "Nenhuma instalação de software é necessária. Obtenha resultados profissionais direto do seu navegador."
  },
  ru: {
    "landing.compress.redesign.heroBadge": "УМНОЕ СЖАТИЕ",
    "landing.compress.redesign.heroTitle": "Уменьшите размер файла изображения до 90% мгновенно",
    "landing.compress.redesign.heroDesc": "Уменьшите размер ваших фотографий без потери визуального качества. Идеально для сайтов и электронной почты.",
    "landing.compress.redesign.feat1Badge": "БЕЗ ПОТЕРИ КАЧЕСТВА",
    "landing.compress.redesign.feat1Title": "Умная оптимизация",
    "landing.compress.redesign.feat1Desc": "Автоматически находит идеальный баланс между минимальным размером файла и максимальным качеством изображения.",
    "landing.compress.redesign.feat2Badge": "100% КОНФИДЕНЦИАЛЬНО",
    "landing.compress.redesign.feat2Title": "Без загрузок",
    "landing.compress.redesign.feat2Desc": "Сжатие происходит прямо в вашем веб-браузере. Ничего не отправляется на серверы.",
    "landing.compress.redesign.feat3Badge": "ЛЮБОЙ ФОРМАТ",
    "landing.compress.redesign.feat3Title": "Широкая поддержка",
    "landing.compress.redesign.feat3Desc": "Работает со стандартными форматами JPG и PNG, а также с современными форматами WEBP.",
    "landing.compress.redesign.whoTag": "ДЛЯ КОГО",
    "landing.compress.redesign.whoTitle": "Создано для интернета и медиа",
    "landing.compress.redesign.whoDesc": "Идеально подходит для разработчиков, дизайнеров и менеджеров социальных сетей, которым нужны оптимизированные изображения.",
    "landing.compress.redesign.who1Title": "Веб-разработчики",
    "landing.compress.redesign.who1Desc": "Улучшите показатели PageSpeed и сократите время загрузки без ущерба для качества изображения.",
    "landing.compress.redesign.who1Tags": "СЕО ОПТИМИЗАЦИЯ",
    "landing.compress.redesign.who2Title": "Создатели контента",
    "landing.compress.redesign.who2Desc": "Соблюдайте строгие ограничения на размер загрузки для таких платформ, как Discord или Twitter.",
    "landing.compress.redesign.who2Tags": "СОЦИАЛЬНЫЕ МЕДИА",
    "landing.compress.redesign.stepsTag": "КАК ЭТО РАБОТАЕТ",
    "landing.compress.redesign.stepsTitle": "3 шага для оптимизации",
    "landing.compress.redesign.s1Title": "Загрузить изображения",
    "landing.compress.redesign.s1Desc": "Перетащите ваши фотографии в рабочую область сжатия.",
    "landing.compress.redesign.s2Title": "Установить уровень сжатия",
    "landing.compress.redesign.s2Desc": "Отрегулируйте ползунок качества, чтобы найти правильный баланс.",
    "landing.compress.redesign.s3Title": "Сэкономить память",
    "landing.compress.redesign.s3Desc": "Загрузите оптимизированные изображения и наслаждайтесь уменьшенным размером файла.",
    "landing.remove.redesign.heroBadge": "ВЫРЕЗАНИЕ С ИИ",
    "landing.remove.redesign.heroTitle": "Удалить фон за 1 секунду с безупречной точностью",
    "landing.remove.redesign.heroDesc": "Благодаря передовому искусственному интеллекту WebAssembly вы получите идеальные вырезы волос и ровные края без загрузки фотографий на сервер.",
    "landing.remove.redesign.feat1Badge": "ТОЧНОСТЬ 99.8%",
    "landing.remove.redesign.feat1Title": "Безупречное обнаружение волос и краев",
    "landing.remove.redesign.feat1Desc": "Наша нейронная сеть легко справляется со сложными деталями, такими как человеческие волосы, мех животных и полупрозрачные объекты.",
    "landing.remove.redesign.feat2Badge": "100% БЕЗОПАСНО",
    "landing.remove.redesign.feat2Title": "Полная автономная конфиденциальность",
    "landing.remove.redesign.feat2Desc": "Модель ИИ загружается прямо в ваш браузер. Ваши изображения никогда не покидают ваш компьютер.",
    "landing.remove.redesign.feat3Badge": "ПАКЕТНЫЙ РЕЖИМ",
    "landing.remove.redesign.feat3Title": "Готовность к массовой обработке",
    "landing.remove.redesign.feat3Desc": "Перетаскивайте до 10 фотографий за раз. Загрузите все в одном ZIP-архиве.",
    "landing.remove.redesign.whoTag": "ДЛЯ КОГО",
    "landing.remove.redesign.whoTitle": "Идеально подходит для любых творческих нужд",
    "landing.remove.redesign.whoDesc": "Продаете ли вы автомобили, разрабатываете постеры или создаете официальные документы.",
    "landing.remove.redesign.who1Title": "Продавцы электронной коммерции",
    "landing.remove.redesign.who1Desc": "Создавайте чистые белые фоны для списков продуктов, которые будут продаваться сами по себе.",
    "landing.remove.redesign.who1Tags": "СПИСКИ ПРОДУКТОВ",
    "landing.remove.redesign.who2Title": "Графические дизайнеры",
    "landing.remove.redesign.who2Desc": "Мгновенно извлекайте логотипы, подписи и ресурсы для ваших композитных дизайнов.",
    "landing.remove.redesign.who2Tags": "ДИЗАЙН РЕСУРСЫ",
    "landing.remove.redesign.stepsTag": "КАК ЭТО РАБОТАЕТ",
    "landing.remove.redesign.stepsTitle": "3 шага к прозрачным фонам",
    "landing.remove.redesign.s1Title": "Загрузить изображение",
    "landing.remove.redesign.s1Desc": "Перетащите ваше фото. Поддерживаются PNG, JPG или WEBP.",
    "landing.remove.redesign.s2Title": "Обработка ИИ",
    "landing.remove.redesign.s2Desc": "Локальный ИИ обнаруживает главный объект за 1 секунду.",
    "landing.remove.redesign.s3Title": "Скачать в HD",
    "landing.remove.redesign.s3Desc": "Экспортируйте вырезанную фотографию с прозрачным фоном.",
    "home.why.tag": "ПОЧЕМУ HELPMYIMG",
    "home.why.title": "Почему HelpMyIMG — самый разумный выбор",
    "home.why.desc": "Спроектировано с нуля для обеспечения максимальной конфиденциальности, молниеносной скорости и нулевой стоимости.",
    "home.why.c1.t": "Мгновенная локальная скорость",
    "home.why.c1.d": "Ваши фотографии обрабатываются прямо в памяти вашего устройства с нулевой задержкой.",
    "home.why.c1.b": "Задержка сервера 0 мс",
    "home.why.c2.t": "100% Абсолютная конфиденциальность",
    "home.why.c2.d": "Ваши личные портреты и конфиденциальные документы никогда не покидают ваш компьютер.",
    "home.why.c2.b": "Ноль облачного хранилища",
    "home.why.c3.t": "Всегда бесплатно и без ограничений",
    "home.why.c3.d": "Никаких подписок, никаких водяных знаков. Редактирование фотографий в высоком разрешении доступно каждому.",
    "home.why.c3.b": "$0 / Пожизненно",
    "home.why.c4.t": "Мощность пакета до 10",
    "home.why.c4.d": "Перетащите до 10 фотографий одновременно и экспортируйте в виде ZIP-архива за считанные секунды.",
    "home.why.c4.b": "Скорость работы 10x",
    "home.steps.tag": "КАК ЭТО РАБОТАЕТ",
    "home.steps.title": "Как HelpMyIMG работает за 3 простых шага",
    "home.steps.desc": "Установка программного обеспечения не требуется. Получайте профессиональные результаты прямо из веб-браузера."
  },
  ar: {
    "landing.compress.redesign.heroBadge": "ضغط ذكي",
    "landing.compress.redesign.heroTitle": "قم بتقليل حجم ملف الصورة بنسبة تصل إلى 90٪ على الفور",
    "landing.compress.redesign.heroDesc": "قم بتقليل حجم صورك دون فقد الجودة البصرية. مثالي لمواقع الويب ورسائل البريد الإلكتروني.",
    "landing.compress.redesign.feat1Badge": "لا فقدان للجودة",
    "landing.compress.redesign.feat1Title": "تحسين ذكي",
    "landing.compress.redesign.feat1Desc": "يجد التوازن المثالي بين الحد الأدنى لحجم الملف والحد الأقصى لجودة الصورة.",
    "landing.compress.redesign.feat2Badge": "100٪ خاص",
    "landing.compress.redesign.feat2Title": "بدون تحميل",
    "landing.compress.redesign.feat2Desc": "يتم الضغط مباشرة في متصفح الويب الخاص بك. لا يتم إرسال أي شيء إلى الخوادم.",
    "landing.compress.redesign.feat3Badge": "أي صيغة",
    "landing.compress.redesign.feat3Title": "دعم واسع",
    "landing.compress.redesign.feat3Desc": "يعمل مع صيغ JPG و PNG القياسية بالإضافة إلى صيغ WEBP الحديثة.",
    "landing.compress.redesign.whoTag": "لمن هذا",
    "landing.compress.redesign.whoTitle": "مصمم للويب والوسائط",
    "landing.compress.redesign.whoDesc": "مثالي للمطورين والمصممين ومديري وسائل التواصل الاجتماعي الذين يحتاجون إلى صور محسنة.",
    "landing.compress.redesign.who1Title": "مطورون الويب",
    "landing.compress.redesign.who1Desc": "حسِّن درجات PageSpeed وقلل من أوقات التحميل دون التضحية بجودة الصورة.",
    "landing.compress.redesign.who1Tags": "تحسين محركات البحث",
    "landing.compress.redesign.who2Title": "صناع المحتوى",
    "landing.compress.redesign.who2Desc": "تلبية حدود حجم التحميل الصارمة لمنصات مثل Discord أو Twitter.",
    "landing.compress.redesign.who2Tags": "وسائل التواصل الاجتماعي",
    "landing.compress.redesign.stepsTag": "كيف يعمل",
    "landing.compress.redesign.stepsTitle": "3 خطوات للتحسين",
    "landing.compress.redesign.s1Title": "تحميل الصور",
    "landing.compress.redesign.s1Desc": "قم بسحب وإسقاط صورك في مساحة عمل الضغط.",
    "landing.compress.redesign.s2Title": "تعيين مستوى الضغط",
    "landing.compress.redesign.s2Desc": "اضبط شريط تمرير الجودة للعثور على التوازن الصحيح.",
    "landing.compress.redesign.s3Title": "توفير التخزين",
    "landing.compress.redesign.s3Desc": "قم بتنزيل صورك المحسنة واستمتع بأحجام ملفات أصغر.",
    "landing.remove.redesign.heroBadge": "قص مدعوم بالذكاء الاصطناعي",
    "landing.remove.redesign.heroTitle": "قم بإزالة الخلفية في ثانية واحدة بدقة لا تشوبها شائبة",
    "landing.remove.redesign.heroDesc": "بدعم من ذكاء WebAssembly المتقدم ، احصل على قصات شعر مثالية وحواف ناعمة دون تحميل صورك على خادم مطلقًا.",
    "landing.remove.redesign.feat1Badge": "دقة 99.8٪",
    "landing.remove.redesign.feat1Title": "اكتشاف لا تشوبه شائبة للشعر والحواف",
    "landing.remove.redesign.feat1Desc": "تتعامل شبكتنا العصبية بسهولة مع التفاصيل المعقدة مثل شعر الإنسان وفراء الحيوانات والأشياء شبه الشفافة.",
    "landing.remove.redesign.feat2Badge": "100٪ آمن",
    "landing.remove.redesign.feat2Title": "خصوصية كاملة دون اتصال",
    "landing.remove.redesign.feat2Desc": "يتم تحميل نموذج الذكاء الاصطناعي مباشرة في متصفحك. صورك لا تغادر جهاز الكمبيوتر الخاص بك أبدا.",
    "landing.remove.redesign.feat3Badge": "وضع الدُفعة",
    "landing.remove.redesign.feat3Title": "جاهز للمعالجة بالجملة",
    "landing.remove.redesign.feat3Desc": "قم بسحب وإسقاط ما يصل إلى 10 صور في وقت واحد. قم بتنزيل كل شيء في ملف ZIP واحد.",
    "landing.remove.redesign.whoTag": "لمن هذا",
    "landing.remove.redesign.whoTitle": "مثالي لكل حاجة إبداعية",
    "landing.remove.redesign.whoDesc": "سواء كنت تبيع سيارات، أو تصمم ملصقات، أو تنشئ مستندات رسمية.",
    "landing.remove.redesign.who1Title": "بائعو التجارة الإلكترونية",
    "landing.remove.redesign.who1Desc": "قم بإنشاء خلفيات بيضاء نظيفة لقوائم المنتجات التي تبيع نفسها.",
    "landing.remove.redesign.who1Tags": "قوائم المنتجات",
    "landing.remove.redesign.who2Title": "مصممي الجرافيك",
    "landing.remove.redesign.who2Desc": "استخرج الشعارات والتوقيعات والأصول على الفور لتصميماتك المركبة.",
    "landing.remove.redesign.who2Tags": "أصول التصميم",
    "landing.remove.redesign.stepsTag": "كيف يعمل",
    "landing.remove.redesign.stepsTitle": "3 خطوات للخلفيات الشفافة",
    "landing.remove.redesign.s1Title": "تحميل صورة",
    "landing.remove.redesign.s1Desc": "قم بسحب وإسقاط صورتك. يتم دعم PNG أو JPG أو WEBP.",
    "landing.remove.redesign.s2Title": "معالجة الذكاء الاصطناعي",
    "landing.remove.redesign.s2Desc": "يكتشف الذكاء الاصطناعي المحلي الموضوع الرئيسي في ثانية واحدة.",
    "landing.remove.redesign.s3Title": "تنزيل HD",
    "landing.remove.redesign.s3Desc": "قم بتصدير صورتك المقصوصة بخلفية شفافة.",
    "home.why.tag": "لماذا HELPMYIMG",
    "home.why.title": "لماذا يعد HelpMyIMG الخيار الأذكى للمبدعين",
    "home.why.desc": "مصمم من الألف إلى الياء لتوفير أقصى درجات الخصوصية والسرعة الفائقة والتكلفة الصفرية.",
    "home.why.c1.t": "سرعة محلية فورية",
    "home.why.c1.d": "تتم معالجة صورك مباشرة داخل ذاكرة جهازك دون أي تأخير.",
    "home.why.c1.b": "0 مللي ثانية تأخير الخادم",
    "home.why.c2.t": "100٪ خصوصية مطلقة",
    "home.why.c2.d": "لا تغادر صورك الشخصية ووثائقك السرية جهاز الكمبيوتر الخاص بك أبدًا.",
    "home.why.c2.b": "لا توجد مساحة تخزين سحابية",
    "home.why.c3.t": "مجاني وغير محدود دائمًا",
    "home.why.c3.d": "لا اشتراكات ولا علامات مائية. تحرير الصور عالي الدقة متاح للجميع.",
    "home.why.c3.b": "$0 / مدى الحياة",
    "home.why.c4.t": "قوة الدفعة تصل إلى 10",
    "home.why.c4.d": "قم بسحب ما يصل إلى 10 صور في وقت واحد وتصديرها كملف ZIP في ثوانٍ.",
    "home.why.c4.b": "10 أضعاف سرعة العمل",
    "home.steps.tag": "كيف يعمل",
    "home.steps.title": "كيف يعمل HelpMyIMG في 3 خطوات بسيطة",
    "home.steps.desc": "لا يلزم تثبيت البرنامج. احصل على نتائج احترافية مباشرة من متصفح الويب الخاص بك."
  },
  fr: {
    "landing.compress.redesign.heroBadge": "COMPRESSION INTELLIGENTE",
    "landing.compress.redesign.heroTitle": "Réduisez la taille du fichier image jusqu'à 90% instantanément",
    "landing.compress.redesign.heroDesc": "Réduisez la taille de vos photos sans perdre en qualité visuelle. Parfait pour les sites Web et les e-mails.",
    "landing.compress.redesign.feat1Badge": "AUCUNE PERTE DE QUALITÉ",
    "landing.compress.redesign.feat1Title": "Optimisation intelligente",
    "landing.compress.redesign.feat1Desc": "Trouve automatiquement l'équilibre parfait entre la taille minimale du fichier et la qualité d'image maximale.",
    "landing.compress.redesign.feat2Badge": "100% PRIVÉ",
    "landing.compress.redesign.feat2Title": "Zéro téléchargement",
    "landing.compress.redesign.feat2Desc": "La compression se produit directement dans votre navigateur Web. Rien n'est envoyé aux serveurs.",
    "landing.compress.redesign.feat3Badge": "N'IMPORTE QUEL FORMAT",
    "landing.compress.redesign.feat3Title": "Support étendu",
    "landing.compress.redesign.feat3Desc": "Fonctionne avec les formats standard JPG et PNG ainsi que les formats WEBP modernes.",
    "landing.compress.redesign.whoTag": "POUR QUI C'EST",
    "landing.compress.redesign.whoTitle": "Conçu pour le Web et les médias",
    "landing.compress.redesign.whoDesc": "Parfait pour les développeurs, concepteurs et gestionnaires de médias sociaux qui ont besoin d'images optimisées.",
    "landing.compress.redesign.who1Title": "Développeurs Web",
    "landing.compress.redesign.who1Desc": "Améliorez les scores PageSpeed et réduisez les temps de chargement sans sacrifier la qualité de l'image.",
    "landing.compress.redesign.who1Tags": "OPTIMISATION SEO",
    "landing.compress.redesign.who2Title": "Créateurs de contenu",
    "landing.compress.redesign.who2Desc": "Respectez les limites de taille de téléchargement strictes pour des plateformes comme Discord ou Twitter.",
    "landing.compress.redesign.who2Tags": "MÉDIAS SOCIAUX",
    "landing.compress.redesign.stepsTag": "COMMENT ÇA MARCHE",
    "landing.compress.redesign.stepsTitle": "3 étapes vers l'optimisation",
    "landing.compress.redesign.s1Title": "Télécharger des images",
    "landing.compress.redesign.s1Desc": "Faites glisser et déposez vos photos dans l'espace de travail de compression.",
    "landing.compress.redesign.s2Title": "Définir le niveau de compression",
    "landing.compress.redesign.s2Desc": "Ajustez le curseur de qualité pour trouver le bon équilibre.",
    "landing.compress.redesign.s3Title": "Économiser du stockage",
    "landing.compress.redesign.s3Desc": "Téléchargez vos images optimisées et profitez de tailles de fichiers réduites.",
    "landing.remove.redesign.heroBadge": "DÉCOUPAGE PROPULSÉ PAR L'IA",
    "landing.remove.redesign.heroTitle": "Supprimer l'arrière-plan en 1 seconde avec une précision sans faille",
    "landing.remove.redesign.heroDesc": "Propulsé par l'IA avancée WebAssembly, obtenez des découpes de cheveux parfaites et des bords lisses sans jamais télécharger vos photos sur un serveur.",
    "landing.remove.redesign.feat1Badge": "PRÉCISION 99.8%",
    "landing.remove.redesign.feat1Title": "Détection sans faille des cheveux et des bords",
    "landing.remove.redesign.feat1Desc": "Notre réseau de neurones gère facilement des détails complexes comme les cheveux humains, la fourrure d'animaux et les objets semi-transparents.",
    "landing.remove.redesign.feat2Badge": "100% SÉCURISÉ",
    "landing.remove.redesign.feat2Title": "Confidentialité totale hors ligne",
    "landing.remove.redesign.feat2Desc": "Le modèle d'IA se charge directement dans votre navigateur. Vos images ne quittent jamais votre ordinateur.",
    "landing.remove.redesign.feat3Badge": "MODE PAR LOT",
    "landing.remove.redesign.feat3Title": "Prêt pour le traitement de masse",
    "landing.remove.redesign.feat3Desc": "Faites glisser et déposez jusqu'à 10 photos à la fois. Téléchargez tout dans un seul fichier ZIP.",
    "landing.remove.redesign.whoTag": "POUR QUI C'EST",
    "landing.remove.redesign.whoTitle": "Parfait pour chaque besoin créatif",
    "landing.remove.redesign.whoDesc": "Que vous vendiez des voitures, conceviez des affiches ou créiez des documents officiels.",
    "landing.remove.redesign.who1Title": "Vendeurs E-Commerce",
    "landing.remove.redesign.who1Desc": "Créez des arrière-plans blancs propres pour des listes de produits qui se vendent d'elles-mêmes.",
    "landing.remove.redesign.who1Tags": "LISTES DE PRODUITS",
    "landing.remove.redesign.who2Title": "Concepteurs graphiques",
    "landing.remove.redesign.who2Desc": "Extrayez des logos, des signatures et des actifs instantanément pour vos conceptions composites.",
    "landing.remove.redesign.who2Tags": "ACTIFS DE CONCEPTION",
    "landing.remove.redesign.stepsTag": "COMMENT ÇA MARCHE",
    "landing.remove.redesign.stepsTitle": "3 étapes vers des arrière-plans transparents",
    "landing.remove.redesign.s1Title": "Télécharger l'image",
    "landing.remove.redesign.s1Desc": "Faites glisser et déposez votre photo. PNG, JPG ou WEBP sont pris en charge.",
    "landing.remove.redesign.s2Title": "Traitement IA",
    "landing.remove.redesign.s2Desc": "L'IA locale détecte le sujet principal en 1 seconde.",
    "landing.remove.redesign.s3Title": "Téléchargement HD",
    "landing.remove.redesign.s3Desc": "Exportez votre photo découpée avec un arrière-plan transparent.",
    "home.why.tag": "POURQUOI HELPMYIMG",
    "home.why.title": "Pourquoi HelpMyIMG est le choix le plus intelligent",
    "home.why.desc": "Conçu de A à Z pour une confidentialité maximale, une vitesse fulgurante et un coût nul.",
    "home.why.c1.t": "Vitesse locale instantanée",
    "home.why.c1.d": "Vos photos sont traitées directement dans la mémoire de votre appareil avec une latence nulle.",
    "home.why.c1.b": "0 ms Retard de serveur",
    "home.why.c2.t": "100% Confidentialité absolue",
    "home.why.c2.d": "Vos portraits personnels et documents confidentiels ne quittent jamais votre ordinateur.",
    "home.why.c2.b": "Zéro stockage cloud",
    "home.why.c3.t": "Toujours gratuit et illimité",
    "home.why.c3.d": "Pas d'abonnements, pas de filigranes. L'édition de photos haute définition accessible à tous.",
    "home.why.c3.b": "0 $ / À vie",
    "home.why.c4.t": "Puissance par lot jusqu'à 10",
    "home.why.c4.d": "Faites glisser jusqu'à 10 photos simultanément et exportez-les sous forme d'archive ZIP en quelques secondes.",
    "home.why.c4.b": "10x Vitesse de travail",
    "home.steps.tag": "COMMENT ÇA MARCHE",
    "home.steps.title": "Comment HelpMyIMG fonctionne en 3 étapes simples",
    "home.steps.desc": "Aucune installation de logiciel n'est requise. Obtenez des résultats professionnels directement depuis votre navigateur Web."
  }
};

const scriptDir = __dirname;
const localesDir = path.join(scriptDir, '../public/locales');

for (const [lang, kv] of Object.entries(translations)) {
  const filePath = path.join(localesDir, lang, 'translation.json');
  if (fs.existsSync(filePath)) {
    const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    for (const [key, val] of Object.entries(kv)) {
      data[key] = val;
    }
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
    console.log(`[${lang}] Injected translations chunk 6`);
  }
}
