const fs = require('fs');
const path = require('path');

const localesDir = path.join(__dirname, '../public/locales');

const translations = {
  ar: {
    // COLOR
    "landing.color.redesign.heroBadge": "استوديو الألوان الفوري",
    "landing.color.redesign.heroTitle": "تغيير ألوان الخلفية في الوقت الفعلي",
    "landing.color.redesign.heroDesc": "قم بتطبيق ألوان ثابتة أو تدرجات أو رموز HEX مخصصة على الفور. مثالي لصور المنتجات، يعمل بالكامل في متصفحك.",
    "landing.color.redesign.feat1Title": "لوحة ألوان لا نهائية",
    "landing.color.redesign.feat1Desc": "اختر من لوحتنا المنسقة أو أدخل أي رمز HEX/RGB لمطابقة هوية علامتك التجارية.",
    "landing.color.redesign.feat2Title": "تنعيم الحواف",
    "landing.color.redesign.feat2Desc": "تمتزج الألوان بشكل طبيعي مع حواف صورتك، مع تجنب الهالات البكسلية القاسية.",
    "landing.color.redesign.feat3Title": "معاينة حية",
    "landing.color.redesign.feat3Desc": "شاهد تغيرات الألوان على الفور دون انتظار عمليات إعادة التحميل.",
    "landing.color.redesign.feat4Title": "خصوصية 100%",
    "landing.color.redesign.feat4Desc": "تتم المعالجة مباشرة على جهازك. لا توجد طلبات شبكة تعني عدم وجود مخاطر.",
    "landing.color.redesign.whoTag": "الاستخدامات المهنية",
    "landing.color.redesign.whoTitle": "مصمم للمبدعين",
    "landing.color.redesign.who1Title": "كتالوجات التجارة الإلكترونية",
    "landing.color.redesign.who1Desc": "توحيد خلفيات المنتجات بلون أبيض نقي أو رمز تجاري.",
    "landing.color.redesign.who2Title": "صور شخصية",
    "landing.color.redesign.who2Desc": "أضف خلفيات نابضة بالحياة إلى LinkedIn أو Twitter.",
    "landing.color.redesign.who3Title": "مواد التسويق",
    "landing.color.redesign.who3Desc": "قم بتجهيز الأصول الشفافة عن طريق تطبيق ألوان خضراء متطابقة.",
    "landing.color.redesign.stepsTitle": "تلوين في 3 خطوات",
    "landing.color.redesign.s1Title": "رفع الصورة",
    "landing.color.redesign.s1Desc": "تأكد من أن الصورة بخلفية شفافة أولاً.",
    "landing.color.redesign.s2Title": "اختر لوناً",
    "landing.color.redesign.s2Desc": "استخدم منتقي الألوان أو أدخل رمز HEX مخصص.",
    "landing.color.redesign.s3Title": "تصدير",
    "landing.color.redesign.s3Desc": "قم بتنزيل صورتك الملونة حديثاً بدقة كاملة.",
    // RESIZE
    "landing.resize.redesign.heroBadge": "قياس دقيق بالبكسل",
    "landing.resize.redesign.heroTitle": "تغيير حجم الصور بدقة مطلقة",
    "landing.resize.redesign.heroDesc": "قم بتغيير حجم صورك بأبعاد بكسل أو نسب مئوية دقيقة. مثالي لوسائل التواصل الاجتماعي والمواقع الإلكترونية.",
    "landing.resize.redesign.feat1Title": "أبعاد بكسل دقيقة",
    "landing.resize.redesign.feat1Desc": "تحكم كامل في حجم صورتك. أدخل قيم العرض والارتفاع المحددة.",
    "landing.resize.redesign.feat1Li1": "قفل نسبة العرض إلى الارتفاع",
    "landing.resize.redesign.feat1Li2": "عرض وارتفاع مخصص",
    "landing.resize.redesign.feat2Title": "تغيير الحجم بالنسبة المئوية",
    "landing.resize.redesign.feat2Desc": "استخدم شريط النسبة المئوية لتغيير الحجم بسرعة بشكل متناسب.",
    "landing.resize.redesign.feat2Li1": "أزرار 50% / 200% سريعة",
    "landing.resize.redesign.feat2Li2": "يحافظ على جودة الصورة",
    "landing.resize.redesign.socialTitle": "مثالي لكل منصة",
    "landing.resize.redesign.socialDesc": "استوف متطلبات التحميل الصارمة لوسائل التواصل الاجتماعي.",
    "landing.resize.redesign.stepsTag": "كيف تعمل",
    "landing.resize.redesign.stepsTitle": "تغيير الحجم في 3 خطوات",
    "landing.resize.redesign.s1Title": "رفع الصور",
    "landing.resize.redesign.s1Desc": "قم بإسقاط ما يصل إلى 10 صور.",
    "landing.resize.redesign.s2Title": "تحديد الأبعاد",
    "landing.resize.redesign.s2Desc": "أدخل العرض والارتفاع المستهدف.",
    "landing.resize.redesign.s3Title": "حفظ",
    "landing.resize.redesign.s3Desc": "قم بتنزيل الصور المعدلة على الفور.",
    // CROP
    "landing.crop.redesign.heroBadge": "تكوين ذكي",
    "landing.crop.redesign.heroTitle": "اقتطع الضوضاء.",
    "landing.crop.redesign.heroTitle2": "ركز على ما يهم.",
    "landing.crop.redesign.heroDesc": "قم بتأطير صورك بشكل مثالي باستخدام القص الحر أو الثابت.",
    "landing.crop.redesign.feat1Title": "تحديد حر",
    "landing.crop.redesign.feat1Desc": "اسحب حواف مربع القص بحرية لتأطير موضوعك بالضبط كما تريد.",
    "landing.crop.redesign.feat2Title": "نسب عرض إلى ارتفاع ثابتة",
    "landing.crop.redesign.feat2Desc": "هل تحتاج إلى مربع مثالي؟ اقفل نسبة العرض إلى الارتفاع للحفاظ على الأبعاد.",
    "landing.crop.redesign.feat3Title": "استخراج بدون فقدان",
    "landing.crop.redesign.feat3Desc": "نستخرج البكسلات أصلاً لضمان عدم وجود أي فقدان في الجودة.",
    "landing.crop.redesign.stepsTag": "كيفية القص",
    "landing.crop.redesign.stepsTitle": "تأطير مثالي في ثوانٍ",
    "landing.crop.redesign.s1Title": "رفع صورة",
    "landing.crop.redesign.s1Desc": "قم بسحب وإسقاط صورتك.",
    "landing.crop.redesign.s2Title": "اسحب المربع",
    "landing.crop.redesign.s2Desc": "استخدم المقابض لضبط منطقة القص.",
    "landing.crop.redesign.s3Title": "تطبيق وحفظ",
    "landing.crop.redesign.s3Desc": "اضغط على قص وقم بتنزيل الصورة."
  },
  cs: {
    // COLOR
    "landing.color.redesign.heroBadge": "OKAMŽITÉ BAREVNÉ STUDIO",
    "landing.color.redesign.heroTitle": "Změňte barvy pozadí v reálném čase",
    "landing.color.redesign.heroDesc": "Okamžitě aplikujte plné barvy, přechody nebo HEX kódy. Ideální pro produktové fotografie, běží plně v prohlížeči.",
    "landing.color.redesign.feat1Title": "Nekonečné plátno barev",
    "landing.color.redesign.feat1Desc": "Vyberte si z naší palety nebo zadejte libovolný HEX/RGB kód pro shodu s vaší značkou.",
    "landing.color.redesign.feat2Title": "Vyhlazení hran",
    "landing.color.redesign.feat2Desc": "Barvy se přirozeně prolínají s okraji objektu, čímž se vyhnete drsným pixelům.",
    "landing.color.redesign.feat3Title": "Živý náhled",
    "landing.color.redesign.feat3Desc": "Sledujte změny barev okamžitě bez čekání na server.",
    "landing.color.redesign.feat4Title": "100% soukromí",
    "landing.color.redesign.feat4Desc": "Zpracování probíhá přímo na vašem zařízení. Žádné síťové požadavky.",
    "landing.color.redesign.whoTag": "PROFESIONÁLNÍ POUŽITÍ",
    "landing.color.redesign.whoTitle": "Vytvořeno pro tvůrce",
    "landing.color.redesign.who1Title": "Katalogy e-shopů",
    "landing.color.redesign.who1Desc": "Standardizujte pozadí produktů čistě bílou nebo značkovou barvou.",
    "landing.color.redesign.who2Title": "Profilové portréty",
    "landing.color.redesign.who2Desc": "Přidejte zářivé pozadí na LinkedIn nebo Twitter.",
    "landing.color.redesign.who3Title": "Marketingové materiály",
    "landing.color.redesign.who3Desc": "Připravte transparentní aktiva aplikací klíčovacích barev.",
    "landing.color.redesign.stepsTitle": "Obarvěte ve 3 krocích",
    "landing.color.redesign.s1Title": "Nahrát obrázek",
    "landing.color.redesign.s1Desc": "Nejprve se ujistěte, že má obrázek průhledné pozadí.",
    "landing.color.redesign.s2Title": "Vybrat barvu",
    "landing.color.redesign.s2Desc": "Použijte výběr barev nebo zadejte HEX kód.",
    "landing.color.redesign.s3Title": "Exportovat",
    "landing.color.redesign.s3Desc": "Stáhněte si obarvený obrázek v plném rozlišení.",
    // RESIZE
    "landing.resize.redesign.heroBadge": "PŘESNÉ MĚŘÍTKO PIXELŮ",
    "landing.resize.redesign.heroTitle": "Změňte velikost obrázků s absolutní přesností",
    "landing.resize.redesign.heroDesc": "Změňte velikost fotografií o přesné pixely nebo procenta. Ideální pro sociální média a weby.",
    "landing.resize.redesign.feat1Title": "Přesné rozměry pixelů",
    "landing.resize.redesign.feat1Desc": "Převezměte plnou kontrolu nad velikostí obrázku. Zadejte specifické hodnoty šířky a výšky.",
    "landing.resize.redesign.feat1Li1": "Uzamknout poměr stran",
    "landing.resize.redesign.feat1Li2": "Vlastní šířka a výška",
    "landing.resize.redesign.feat2Title": "Procentuální změna velikosti",
    "landing.resize.redesign.feat2Desc": "Potřebujete dvojnásobnou nebo poloviční velikost? Rychle změňte měřítko.",
    "landing.resize.redesign.feat2Li1": "Rychlá tlačítka 50% / 200%",
    "landing.resize.redesign.feat2Li2": "Udržuje vizuální kvalitu",
    "landing.resize.redesign.socialTitle": "Ideální pro každou platformu",
    "landing.resize.redesign.socialDesc": "Splňte přísné požadavky na nahrávání bez potíží.",
    "landing.resize.redesign.stepsTag": "JAK TO FUNGUJE",
    "landing.resize.redesign.stepsTitle": "Změna velikosti ve 3 krocích",
    "landing.resize.redesign.s1Title": "Nahrát obrázky",
    "landing.resize.redesign.s1Desc": "Přetáhněte až 10 fotografií.",
    "landing.resize.redesign.s2Title": "Nastavit rozměry",
    "landing.resize.redesign.s2Desc": "Zadejte cílovou šířku a výšku.",
    "landing.resize.redesign.s3Title": "Uložit",
    "landing.resize.redesign.s3Desc": "Okamžitě stáhněte zmenšené fotografie.",
    // CROP
    "landing.crop.redesign.heroBadge": "CHYTRÁ KOMPOZICE",
    "landing.crop.redesign.heroTitle": "Ořízněte šum.",
    "landing.crop.redesign.heroTitle2": "Zaměřte se na to důležité.",
    "landing.crop.redesign.heroDesc": "Dokonale zarámujte své fotografie pomocí volného nebo pevného oříznutí.",
    "landing.crop.redesign.feat1Title": "Volný výběr",
    "landing.crop.redesign.feat1Desc": "Volně přetahujte okraje pro orámování objektu přesně tak, jak chcete.",
    "landing.crop.redesign.feat2Title": "Pevné poměry stran",
    "landing.crop.redesign.feat2Desc": "Potřebujete perfektní čtverec? Uzamkněte poměr pro zachování proporcí.",
    "landing.crop.redesign.feat3Title": "Bezztrátová extrakce",
    "landing.crop.redesign.feat3Desc": "Nativně extrahujeme pixely, což zajišťuje absolutně nulovou ztrátu kvality.",
    "landing.crop.redesign.stepsTag": "JAK OŘÍZNOUT",
    "landing.crop.redesign.stepsTitle": "Dokonalé orámování za sekundu",
    "landing.crop.redesign.s1Title": "Nahrát fotografii",
    "landing.crop.redesign.s1Desc": "Přetáhněte obrázek do pracovního prostoru.",
    "landing.crop.redesign.s2Title": "Přetáhnout pole",
    "landing.crop.redesign.s2Desc": "Upravte oblast oříznutí pomocí rohových úchytů.",
    "landing.crop.redesign.s3Title": "Použít a Uložit",
    "landing.crop.redesign.s3Desc": "Stiskněte oříznout a stáhněte si obrázek."
  },
  da: {
    // COLOR
    "landing.color.redesign.heroBadge": "ØJEBLIKKELIGT FARVESTUDIE",
    "landing.color.redesign.heroTitle": "Skift baggrundsfarver i realtid",
    "landing.color.redesign.heroDesc": "Anvend ensartede farver, gradienter eller HEX-koder øjeblikkeligt. Perfekt til produktfotografering.",
    "landing.color.redesign.feat1Title": "Uendeligt farvelærred",
    "landing.color.redesign.feat1Desc": "Vælg fra vores palet eller indtast enhver HEX/RGB for at matche dit brand.",
    "landing.color.redesign.feat2Title": "Kantudjævning",
    "landing.color.redesign.feat2Desc": "Farver blander sig naturligt med dine motivkanter og undgår pixelerede glorier.",
    "landing.color.redesign.feat3Title": "Live forhåndsvisning",
    "landing.color.redesign.feat3Desc": "Se farveændringer med det samme uden at vente.",
    "landing.color.redesign.feat4Title": "100% privat sandkasse",
    "landing.color.redesign.feat4Desc": "Behandling sker direkte på din enhed. Ingen server uploads.",
    "landing.color.redesign.whoTag": "PROFESSIONEL BRUG",
    "landing.color.redesign.whoTitle": "Bygget til skabere",
    "landing.color.redesign.who1Title": "E-handelskataloger",
    "landing.color.redesign.who1Desc": "Standardiser produktbaggrunde for konsekvente butikslister.",
    "landing.color.redesign.who2Title": "Profilportrætter",
    "landing.color.redesign.who2Desc": "Tilføj iøjnefaldende baggrunde til LinkedIn eller Twitter.",
    "landing.color.redesign.who3Title": "Marketingmaterialer",
    "landing.color.redesign.who3Desc": "Forbered transparente aktiver ved at anvende matchfarver.",
    "landing.color.redesign.stepsTitle": "Farvelæg i 3 trin",
    "landing.color.redesign.s1Title": "Upload billede",
    "landing.color.redesign.s1Desc": "Sørg for at billedet har en transparent baggrund først.",
    "landing.color.redesign.s2Title": "Vælg en farve",
    "landing.color.redesign.s2Desc": "Brug farvevælgeren eller indtast en HEX-kode.",
    "landing.color.redesign.s3Title": "Eksporter",
    "landing.color.redesign.s3Desc": "Download dit farvede billede i fuld opløsning.",
    // RESIZE
    "landing.resize.redesign.heroBadge": "PIXEL-PERFEKT SKALERING",
    "landing.resize.redesign.heroTitle": "Ændr størrelse med absolut præcision",
    "landing.resize.redesign.heroDesc": "Skaler dine billeder efter præcise pixeldimensioner eller procenter.",
    "landing.resize.redesign.feat1Title": "Eksakte pixeldimensioner",
    "landing.resize.redesign.feat1Desc": "Tag fuld kontrol over billedstørrelsen. Indtast specifik bredde og højde.",
    "landing.resize.redesign.feat1Li1": "Lås billedformat",
    "landing.resize.redesign.feat1Li2": "Brugerdefineret bredde og højde",
    "landing.resize.redesign.feat2Title": "Procentskalering",
    "landing.resize.redesign.feat2Desc": "Brug procent-skyderen til hurtigt at skalere billeder op eller ned.",
    "landing.resize.redesign.feat2Li1": "Hurtige 50% / 200% knapper",
    "landing.resize.redesign.feat2Li2": "Bevarer visuel kvalitet",
    "landing.resize.redesign.socialTitle": "Perfekt til enhver platform",
    "landing.resize.redesign.socialDesc": "Opfyld strenge krav til sociale medier uden besvær.",
    "landing.resize.redesign.stepsTag": "SÅDAN FUNGERER DET",
    "landing.resize.redesign.stepsTitle": "Ændr størrelse i 3 trin",
    "landing.resize.redesign.s1Title": "Upload billeder",
    "landing.resize.redesign.s1Desc": "Træk op til 10 fotos.",
    "landing.resize.redesign.s2Title": "Angiv dimensioner",
    "landing.resize.redesign.s2Desc": "Indtast din målbredde og -højde.",
    "landing.resize.redesign.s3Title": "Gem",
    "landing.resize.redesign.s3Desc": "Download øjeblikkeligt.",
    // CROP
    "landing.crop.redesign.heroBadge": "SMART KOMPOSITION",
    "landing.crop.redesign.heroTitle": "Beskær støjen.",
    "landing.crop.redesign.heroTitle2": "Fokuser på det vigtige.",
    "landing.crop.redesign.heroDesc": "Indram dine fotos perfekt med fri eller fast beskæring.",
    "landing.crop.redesign.feat1Title": "Fri markering",
    "landing.crop.redesign.feat1Desc": "Træk kanterne frit for at indramme dit motiv nøjagtigt.",
    "landing.crop.redesign.feat2Title": "Faste billedformater",
    "landing.crop.redesign.feat2Desc": "Lås beskæringsforholdet for at bevare præcise proportioner.",
    "landing.crop.redesign.feat3Title": "Tabsfri udtrækning",
    "landing.crop.redesign.feat3Desc": "Vi udtrækker pixels indbygget for at sikre nul kvalitetstab.",
    "landing.crop.redesign.stepsTag": "SÅDAN BESKÆRER DU",
    "landing.crop.redesign.stepsTitle": "Perfekt indramning",
    "landing.crop.redesign.s1Title": "Upload foto",
    "landing.crop.redesign.s1Desc": "Træk dit billede ind.",
    "landing.crop.redesign.s2Title": "Træk boksen",
    "landing.crop.redesign.s2Desc": "Juster beskæringsområdet.",
    "landing.crop.redesign.s3Title": "Anvend og gem",
    "landing.crop.redesign.s3Desc": "Download dit udtrukne billede."
  },
  de: {
    "landing.color.redesign.heroBadge": "SOFORTIGES FARBSTUDIO",
    "landing.color.redesign.heroTitle": "Hintergrundfarben in Echtzeit ändern",
    "landing.color.redesign.heroDesc": "Wenden Sie sofort einfarbige Hintergründe, Verläufe oder HEX-Codes an. Perfekt für Produktfotografie, vollständig im Browser.",
    "landing.color.redesign.feat1Title": "Unendliche Farbpalette",
    "landing.color.redesign.feat1Desc": "Wählen Sie aus unserer Palette oder geben Sie einen beliebigen HEX-Code ein, um Ihrer Marke zu entsprechen.",
    "landing.color.redesign.feat2Title": "Kanten-Glättung",
    "landing.color.redesign.feat2Desc": "Farben verschmelzen natürlich mit den Kanten Ihres Motivs, ohne verpixelte Ränder.",
    "landing.color.redesign.feat3Title": "Live-Vorschau",
    "landing.color.redesign.feat3Desc": "Sehen Sie Farbänderungen sofort, ohne Wartezeiten.",
    "landing.color.redesign.feat4Title": "100% Privat",
    "landing.color.redesign.feat4Desc": "Die Verarbeitung erfolgt direkt auf Ihrem Gerät. Keine Server-Uploads.",
    "landing.color.redesign.whoTag": "PROFESSIONELLE NUTZUNG",
    "landing.color.redesign.whoTitle": "Gebaut für Kreative",
    "landing.color.redesign.who1Title": "E-Commerce-Kataloge",
    "landing.color.redesign.who1Desc": "Standardisieren Sie Produkthintergründe für einheitliche Shop-Einträge.",
    "landing.color.redesign.who2Title": "Profilporträts",
    "landing.color.redesign.who2Desc": "Fügen Sie LinkedIn oder Twitter lebendige Hintergründe hinzu.",
    "landing.color.redesign.who3Title": "Marketingmaterial",
    "landing.color.redesign.who3Desc": "Bereiten Sie Assets vor, indem Sie Markenfarben anwenden.",
    "landing.color.redesign.stepsTitle": "In 3 Schritten färben",
    "landing.color.redesign.s1Title": "Bild hochladen",
    "landing.color.redesign.s1Desc": "Stellen Sie sicher, dass das Bild einen transparenten Hintergrund hat.",
    "landing.color.redesign.s2Title": "Farbe wählen",
    "landing.color.redesign.s2Desc": "Nutzen Sie den Farbwähler oder geben Sie einen HEX-Code ein.",
    "landing.color.redesign.s3Title": "Exportieren",
    "landing.color.redesign.s3Desc": "Laden Sie Ihr gefärbtes Bild in voller Auflösung herunter.",
    "landing.resize.redesign.heroBadge": "PIXELGENAUE SKALIERUNG",
    "landing.resize.redesign.heroTitle": "Bilder mit absoluter Präzision skalieren",
    "landing.resize.redesign.heroDesc": "Skalieren Sie Ihre Fotos um genaue Pixel oder Prozentsätze. Perfekt für Social Media.",
    "landing.resize.redesign.feat1Title": "Genaue Pixelabmessungen",
    "landing.resize.redesign.feat1Desc": "Übernehmen Sie die volle Kontrolle über die Bildgröße. Geben Sie bestimmte Breite und Höhe ein.",
    "landing.resize.redesign.feat1Li1": "Seitenverhältnis sperren",
    "landing.resize.redesign.feat1Li2": "Benutzerdefinierte Breite & Höhe",
    "landing.resize.redesign.feat2Title": "Prozentuale Skalierung",
    "landing.resize.redesign.feat2Desc": "Verwenden Sie den Prozent-Regler, um Bilder schnell proportional zu skalieren.",
    "landing.resize.redesign.feat2Li1": "Schnelle 50% / 200% Buttons",
    "landing.resize.redesign.feat2Li2": "Erhält die visuelle Qualität",
    "landing.resize.redesign.socialTitle": "Perfekt für jede Plattform",
    "landing.resize.redesign.socialDesc": "Erfüllen Sie strenge Upload-Anforderungen problemlos.",
    "landing.resize.redesign.stepsTag": "WIE ES FUNKTIONIERT",
    "landing.resize.redesign.stepsTitle": "Skalieren in 3 Schritten",
    "landing.resize.redesign.s1Title": "Bilder hochladen",
    "landing.resize.redesign.s1Desc": "Laden Sie bis zu 10 Fotos hoch.",
    "landing.resize.redesign.s2Title": "Dimensionen festlegen",
    "landing.resize.redesign.s2Desc": "Geben Sie Zielbreite und -höhe ein.",
    "landing.resize.redesign.s3Title": "Speichern",
    "landing.resize.redesign.s3Desc": "Laden Sie die skalierten Fotos herunter.",
    "landing.crop.redesign.heroBadge": "SMARTE KOMPOSITION",
    "landing.crop.redesign.heroTitle": "Schneiden Sie das Rauschen aus.",
    "landing.crop.redesign.heroTitle2": "Fokus auf das Wichtige.",
    "landing.crop.redesign.heroDesc": "Rahmen Sie Ihre Fotos perfekt ein mit freiem oder festem Zuschnitt.",
    "landing.crop.redesign.feat1Title": "Freie Auswahl",
    "landing.crop.redesign.feat1Desc": "Ziehen Sie die Kanten frei, um Ihr Motiv genau so einzurahmen, wie Sie möchten.",
    "landing.crop.redesign.feat2Title": "Feste Seitenverhältnisse",
    "landing.crop.redesign.feat2Desc": "Brauchen Sie ein perfektes Quadrat? Sperren Sie das Seitenverhältnis.",
    "landing.crop.redesign.feat3Title": "Verlustfreie Extraktion",
    "landing.crop.redesign.feat3Desc": "Wir extrahieren die Pixel nativ und stellen sicher, dass es keinen Qualitätsverlust gibt.",
    "landing.crop.redesign.stepsTag": "SO SCHNEIDEN SIE ZU",
    "landing.crop.redesign.stepsTitle": "Perfekte Einrahmung",
    "landing.crop.redesign.s1Title": "Foto hochladen",
    "landing.crop.redesign.s1Desc": "Ziehen Sie Ihr Bild in den Arbeitsbereich.",
    "landing.crop.redesign.s2Title": "Rahmen ziehen",
    "landing.crop.redesign.s2Desc": "Passen Sie den Schnittbereich an.",
    "landing.crop.redesign.s3Title": "Anwenden & Speichern",
    "landing.crop.redesign.s3Desc": "Klicken Sie auf Zuschneiden und laden Sie das Bild herunter."
  },
  el: {
    "landing.color.redesign.heroBadge": "ΑΜΕΣΟ ΣΤΟΥΝΤΙΟ ΧΡΩΜΑΤΩΝ",
    "landing.color.redesign.heroTitle": "Αλλαγή χρωμάτων φόντου σε πραγματικό χρόνο",
    "landing.color.redesign.heroDesc": "Εφαρμόστε συμπαγή χρώματα, διαβαθμίσεις ή κωδικούς HEX. Ιδανικό για φωτογραφίες προϊόντων.",
    "landing.color.redesign.feat1Title": "Άπειρος καμβάς χρωμάτων",
    "landing.color.redesign.feat1Desc": "Επιλέξτε από την παλέτα μας ή εισαγάγετε οποιονδήποτε κωδικό HEX/RGB.",
    "landing.color.redesign.feat2Title": "Εξομάλυνση άκρων",
    "landing.color.redesign.feat2Desc": "Τα χρώματα αναμειγνύονται φυσικά με τις άκρες του θέματός σας.",
    "landing.color.redesign.feat3Title": "Ζωντανή προεπισκόπηση",
    "landing.color.redesign.feat3Desc": "Δείτε τις αλλαγές χρωμάτων άμεσα χωρίς αναμονή.",
    "landing.color.redesign.feat4Title": "100% Ιδιωτικότητα",
    "landing.color.redesign.feat4Desc": "Η επεξεργασία γίνεται τοπικά στη συσκευή σας.",
    "landing.color.redesign.whoTag": "ΕΠΑΓΓΕΛΜΑΤΙΚΕΣ ΧΡΗΣΕΙΣ",
    "landing.color.redesign.whoTitle": "Φτιαγμένο για δημιουργούς",
    "landing.color.redesign.who1Title": "Κατάλογοι ηλεκτρονικού εμπορίου",
    "landing.color.redesign.who1Desc": "Ομογενοποιήστε τα φόντα των προϊόντων.",
    "landing.color.redesign.who2Title": "Πορτρέτα προφίλ",
    "landing.color.redesign.who2Desc": "Προσθέστε εντυπωσιακά φόντα στο LinkedIn ή στο Twitter.",
    "landing.color.redesign.who3Title": "Υλικό μάρκετινγκ",
    "landing.color.redesign.who3Desc": "Προετοιμάστε διαφανή στοιχεία.",
    "landing.color.redesign.stepsTitle": "Χρωματίστε σε 3 βήματα",
    "landing.color.redesign.s1Title": "Ανέβασμα εικόνας",
    "landing.color.redesign.s1Desc": "Βεβαιωθείτε ότι η εικόνα έχει διαφανές φόντο.",
    "landing.color.redesign.s2Title": "Επιλέξτε χρώμα",
    "landing.color.redesign.s2Desc": "Χρησιμοποιήστε τον επιλογέα ή εισαγάγετε κωδικό HEX.",
    "landing.color.redesign.s3Title": "Εξαγωγή",
    "landing.color.redesign.s3Desc": "Κατεβάστε την εικόνα σας.",
    "landing.resize.redesign.heroBadge": "ΑΚΡΙΒΗΣ ΚΛΙΜΑΚΩΣΗ",
    "landing.resize.redesign.heroTitle": "Αλλαγή μεγέθους εικόνων με απόλυτη ακρίβεια",
    "landing.resize.redesign.heroDesc": "Κλιμακώστε τις φωτογραφίες σας με ακριβείς διαστάσεις.",
    "landing.resize.redesign.feat1Title": "Ακριβείς διαστάσεις pixel",
    "landing.resize.redesign.feat1Desc": "Εισαγάγετε συγκεκριμένο πλάτος και ύψος.",
    "landing.resize.redesign.feat1Li1": "Κλείδωμα αναλογίας διαστάσεων",
    "landing.resize.redesign.feat1Li2": "Προσαρμοσμένο πλάτος & ύψος",
    "landing.resize.redesign.feat2Title": "Ποσοστιαία κλιμάκωση",
    "landing.resize.redesign.feat2Desc": "Κλιμακώστε γρήγορα τις εικόνες αναλογικά.",
    "landing.resize.redesign.feat2Li1": "Κουμπιά 50% / 200%",
    "landing.resize.redesign.feat2Li2": "Διατηρεί την οπτική ποιότητα",
    "landing.resize.redesign.socialTitle": "Ιδανικό για κάθε πλατφόρμα",
    "landing.resize.redesign.socialDesc": "Πληροίτε τις αυστηρές απαιτήσεις των κοινωνικών μέσων.",
    "landing.resize.redesign.stepsTag": "ΠΩΣ ΛΕΙΤΟΥΡΓΕΙ",
    "landing.resize.redesign.stepsTitle": "Αλλαγή μεγέθους σε 3 βήματα",
    "landing.resize.redesign.s1Title": "Ανέβασμα",
    "landing.resize.redesign.s1Desc": "Ανεβάστε τις φωτογραφίες.",
    "landing.resize.redesign.s2Title": "Διαστάσεις",
    "landing.resize.redesign.s2Desc": "Εισαγάγετε το πλάτος και το ύψος.",
    "landing.resize.redesign.s3Title": "Αποθήκευση",
    "landing.resize.redesign.s3Desc": "Κατεβάστε τις εικόνες.",
    "landing.crop.redesign.heroBadge": "ΕΞΥΠΝΗ ΣΥΝΘΕΣΗ",
    "landing.crop.redesign.heroTitle": "Περικόψτε τον θόρυβο.",
    "landing.crop.redesign.heroTitle2": "Εστιάστε στα σημαντικά.",
    "landing.crop.redesign.heroDesc": "Πλαισιώστε τέλεια τις φωτογραφίες σας.",
    "landing.crop.redesign.feat1Title": "Ελεύθερη επιλογή",
    "landing.crop.redesign.feat1Desc": "Σύρετε τις άκρες ελεύθερα.",
    "landing.crop.redesign.feat2Title": "Σταθερές αναλογίες",
    "landing.crop.redesign.feat2Desc": "Κλειδώστε την αναλογία διαστάσεων.",
    "landing.crop.redesign.feat3Title": "Εξαγωγή χωρίς απώλειες",
    "landing.crop.redesign.feat3Desc": "Μηδενική απώλεια ποιότητας.",
    "landing.crop.redesign.stepsTag": "ΠΩΣ ΝΑ ΠΕΡΙΚΟΨΕΤΕ",
    "landing.crop.redesign.stepsTitle": "Τέλειο καδράρισμα",
    "landing.crop.redesign.s1Title": "Ανέβασμα",
    "landing.crop.redesign.s1Desc": "Σύρετε την εικόνα σας.",
    "landing.crop.redesign.s2Title": "Σύρετε το πλαίσιο",
    "landing.crop.redesign.s2Desc": "Προσαρμόστε την περιοχή.",
    "landing.crop.redesign.s3Title": "Εφαρμογή & Αποθήκευση",
    "landing.crop.redesign.s3Desc": "Κατεβάστε την εικόνα."
  },
  es: {
    "landing.color.redesign.heroBadge": "ESTUDIO DE COLOR INSTANTÁNEO",
    "landing.color.redesign.heroTitle": "Transforma colores de fondo en tiempo real",
    "landing.color.redesign.heroDesc": "Aplica colores sólidos, degradados o códigos HEX al instante. Perfecto para fotografía de productos, todo en tu navegador.",
    "landing.color.redesign.feat1Title": "Lienzo de colores infinito",
    "landing.color.redesign.feat1Desc": "Elige de nuestra paleta o introduce un código HEX/RGB para coincidir con tu marca.",
    "landing.color.redesign.feat2Title": "Suavizado de bordes",
    "landing.color.redesign.feat2Desc": "Los colores se mezclan de forma natural con los bordes de tu sujeto, evitando halos pixelados.",
    "landing.color.redesign.feat3Title": "Vista previa en vivo",
    "landing.color.redesign.feat3Desc": "Mira los cambios de color al instante sin recargas.",
    "landing.color.redesign.feat4Title": "Privacidad 100%",
    "landing.color.redesign.feat4Desc": "El procesamiento ocurre en tu dispositivo. Sin subidas a servidores.",
    "landing.color.redesign.whoTag": "USOS PROFESIONALES",
    "landing.color.redesign.whoTitle": "Creado para creadores",
    "landing.color.redesign.who1Title": "Catálogos de E-Commerce",
    "landing.color.redesign.who1Desc": "Estandariza fondos de productos para catálogos consistentes.",
    "landing.color.redesign.who2Title": "Retratos de Perfil",
    "landing.color.redesign.who2Desc": "Añade fondos llamativos a LinkedIn o Twitter.",
    "landing.color.redesign.who3Title": "Materiales de Marketing",
    "landing.color.redesign.who3Desc": "Prepara recursos aplicando colores de marca.",
    "landing.color.redesign.stepsTitle": "Colorea en 3 pasos",
    "landing.color.redesign.s1Title": "Sube tu imagen",
    "landing.color.redesign.s1Desc": "Asegúrate de que tenga fondo transparente.",
    "landing.color.redesign.s2Title": "Elige un color",
    "landing.color.redesign.s2Desc": "Usa el selector o introduce tu código HEX.",
    "landing.color.redesign.s3Title": "Exporta",
    "landing.color.redesign.s3Desc": "Descarga tu imagen a máxima resolución.",
    "landing.resize.redesign.heroBadge": "ESCALADO PERFECTO AL PÍXEL",
    "landing.resize.redesign.heroTitle": "Redimensiona imágenes con precisión absoluta",
    "landing.resize.redesign.heroDesc": "Escala tus fotos por dimensiones de píxeles exactas o porcentajes. Perfecto para redes sociales.",
    "landing.resize.redesign.feat1Title": "Dimensiones exactas",
    "landing.resize.redesign.feat1Desc": "Toma control total del tamaño. Introduce valores específicos de ancho y alto.",
    "landing.resize.redesign.feat1Li1": "Bloquear proporción",
    "landing.resize.redesign.feat1Li2": "Ancho y alto personalizado",
    "landing.resize.redesign.feat2Title": "Escalado porcentual",
    "landing.resize.redesign.feat2Desc": "Usa el control deslizante para escalar fotos rápidamente de forma proporcional.",
    "landing.resize.redesign.feat2Li1": "Botones rápidos de 50% / 200%",
    "landing.resize.redesign.feat2Li2": "Mantiene la calidad visual",
    "landing.resize.redesign.socialTitle": "Perfecto para cada plataforma",
    "landing.resize.redesign.socialDesc": "Cumple los estrictos requisitos de subida sin problemas.",
    "landing.resize.redesign.stepsTag": "CÓMO FUNCIONA",
    "landing.resize.redesign.stepsTitle": "Redimensiona en 3 pasos",
    "landing.resize.redesign.s1Title": "Sube fotos",
    "landing.resize.redesign.s1Desc": "Sube hasta 10 fotos a la vez.",
    "landing.resize.redesign.s2Title": "Establece dimensiones",
    "landing.resize.redesign.s2Desc": "Introduce tu ancho y alto objetivo.",
    "landing.resize.redesign.s3Title": "Guarda",
    "landing.resize.redesign.s3Desc": "Descarga tus fotos al instante.",
    "landing.crop.redesign.heroBadge": "COMPOSICIÓN INTELIGENTE",
    "landing.crop.redesign.heroTitle": "Recorta el ruido.",
    "landing.crop.redesign.heroTitle2": "Céntrate en lo importante.",
    "landing.crop.redesign.heroDesc": "Enmarca tus fotos perfectamente con recortes libres o de proporción fija.",
    "landing.crop.redesign.feat1Title": "Selección libre",
    "landing.crop.redesign.feat1Desc": "Arrastra los bordes libremente para enmarcar a tu sujeto exactamente como quieres.",
    "landing.crop.redesign.feat2Title": "Proporciones fijas",
    "landing.crop.redesign.feat2Desc": "¿Necesitas un cuadrado perfecto? Bloquea la proporción.",
    "landing.crop.redesign.feat3Title": "Extracción sin pérdidas",
    "landing.crop.redesign.feat3Desc": "Extraemos los píxeles de forma nativa garantizando cero pérdida de calidad.",
    "landing.crop.redesign.stepsTag": "CÓMO RECORTAR",
    "landing.crop.redesign.stepsTitle": "Encuadre perfecto en segundos",
    "landing.crop.redesign.s1Title": "Sube tu foto",
    "landing.crop.redesign.s1Desc": "Arrastra y suelta tu imagen.",
    "landing.crop.redesign.s2Title": "Arrastra el cuadro",
    "landing.crop.redesign.s2Desc": "Ajusta el área de recorte.",
    "landing.crop.redesign.s3Title": "Aplica y Guarda",
    "landing.crop.redesign.s3Desc": "Haz clic en recortar y descarga la imagen."
  },
  fi: {
    "landing.color.redesign.heroBadge": "VÄLITÖN VÄRISTUDIO",
    "landing.color.redesign.heroTitle": "Muuta taustavärejä reaaliajassa",
    "landing.color.redesign.heroDesc": "Käytä tasaisia värejä, liukuvärejä tai HEX-koodeja välittömästi. Täydellinen tuotekuvaukseen.",
    "landing.color.redesign.feat1Title": "Loputon värikangas",
    "landing.color.redesign.feat1Desc": "Valitse paletistamme tai syötä mikä tahansa HEX-koodi brändiisi sopivaksi.",
    "landing.color.redesign.feat2Title": "Reunojen pehmennys",
    "landing.color.redesign.feat2Desc": "Värit sekoittuvat luonnollisesti kohteesi reunoihin ilman pikselöintiä.",
    "landing.color.redesign.feat3Title": "Live-esikatselu",
    "landing.color.redesign.feat3Desc": "Näe värimuutokset heti ilman odottelua.",
    "landing.color.redesign.feat4Title": "100% yksityinen",
    "landing.color.redesign.feat4Desc": "Käsittely tapahtuu suoraan laitteellasi. Ei palvelinlatauksia.",
    "landing.color.redesign.whoTag": "AMMATTIKÄYTTÖ",
    "landing.color.redesign.whoTitle": "Rakennettu luojille",
    "landing.color.redesign.who1Title": "Verkkokaupan tuoteluettelot",
    "landing.color.redesign.who1Desc": "Standardoi tuotteiden taustat johdonmukaisiksi.",
    "landing.color.redesign.who2Title": "Profiilikuvat",
    "landing.color.redesign.who2Desc": "Lisää silmiinpistäviä taustoja LinkedIniin tai Twitteriin.",
    "landing.color.redesign.who3Title": "Markkinointimateriaalit",
    "landing.color.redesign.who3Desc": "Valmistele läpinäkyvät materiaalit käyttämällä brändivärejä.",
    "landing.color.redesign.stepsTitle": "Väritä 3 vaiheessa",
    "landing.color.redesign.s1Title": "Lataa kuva",
    "landing.color.redesign.s1Desc": "Varmista, että kuvassa on läpinäkyvä tausta.",
    "landing.color.redesign.s2Title": "Valitse väri",
    "landing.color.redesign.s2Desc": "Käytä värivalitsinta tai syötä HEX-koodi.",
    "landing.color.redesign.s3Title": "Vie",
    "landing.color.redesign.s3Desc": "Lataa värjätty kuvasi täydellä resoluutiolla.",
    "landing.resize.redesign.heroBadge": "PIKSELEILLEEN TARKKA SKAALAUS",
    "landing.resize.redesign.heroTitle": "Muuta kokoa ehdottomalla tarkkuudella",
    "landing.resize.redesign.heroDesc": "Skaalaa kuviasi tarkan pikselikoon tai prosenttien mukaan.",
    "landing.resize.redesign.feat1Title": "Tarkat pikselimitat",
    "landing.resize.redesign.feat1Desc": "Ota täysi hallinta kuvan koosta. Syötä tietty leveys ja korkeus.",
    "landing.resize.redesign.feat1Li1": "Lukitse kuvasuhde",
    "landing.resize.redesign.feat1Li2": "Mukautettu leveys ja korkeus",
    "landing.resize.redesign.feat2Title": "Prosentuaalinen skaalaus",
    "landing.resize.redesign.feat2Desc": "Käytä prosenttiliukusäädintä kuvien nopeaan skaalaamiseen.",
    "landing.resize.redesign.feat2Li1": "Nopeat 50% / 200% painikkeet",
    "landing.resize.redesign.feat2Li2": "Säilyttää visuaalisen laadun",
    "landing.resize.redesign.socialTitle": "Täydellinen jokaiselle alustalle",
    "landing.resize.redesign.socialDesc": "Täytä sosiaalisen median tiukat vaatimukset helposti.",
    "landing.resize.redesign.stepsTag": "KUINKA SE TOIMII",
    "landing.resize.redesign.stepsTitle": "Muuta kokoa 3 vaiheessa",
    "landing.resize.redesign.s1Title": "Lataa kuvia",
    "landing.resize.redesign.s1Desc": "Pudota jopa 10 valokuvaa.",
    "landing.resize.redesign.s2Title": "Aseta mitat",
    "landing.resize.redesign.s2Desc": "Syötä kohdeleveys ja -korkeus.",
    "landing.resize.redesign.s3Title": "Tallenna",
    "landing.resize.redesign.s3Desc": "Lataa kuvat välittömästi.",
    "landing.crop.redesign.heroBadge": "ÄLYKÄS SOMMITTELU",
    "landing.crop.redesign.heroTitle": "Rajaa kohina pois.",
    "landing.crop.redesign.heroTitle2": "Keskity tärkeimpään.",
    "landing.crop.redesign.heroDesc": "Kehystä valokuvasi täydellisesti vapaalla tai kiinteällä rajauksella.",
    "landing.crop.redesign.feat1Title": "Vapaa valinta",
    "landing.crop.redesign.feat1Desc": "Vedä reunoja vapaasti kehystääksesi kohteen juuri haluamallasi tavalla.",
    "landing.crop.redesign.feat2Title": "Kiinteät kuvasuhteet",
    "landing.crop.redesign.feat2Desc": "Tarvitsetko täydellisen neliön? Lukitse kuvasuhde mittasuhteiden säilyttämiseksi.",
    "landing.crop.redesign.feat3Title": "Häviötön erotus",
    "landing.crop.redesign.feat3Desc": "Erotamme pikselit natiivisti varmistaen, ettei laatu kärsi lainkaan.",
    "landing.crop.redesign.stepsTag": "NÄIN RAJAAT",
    "landing.crop.redesign.stepsTitle": "Täydellinen kehystys",
    "landing.crop.redesign.s1Title": "Lataa kuva",
    "landing.crop.redesign.s1Desc": "Pudota kuvasi työtilaan.",
    "landing.crop.redesign.s2Title": "Vedä laatikkoa",
    "landing.crop.redesign.s2Desc": "Säädä rajausaluetta kahvoista.",
    "landing.crop.redesign.s3Title": "Käytä ja tallenna",
    "landing.crop.redesign.s3Desc": "Paina rajaa ja lataa kuvasi."
  },
  fr: {
    "landing.color.redesign.heroBadge": "STUDIO COULEUR INSTANTANÉ",
    "landing.color.redesign.heroTitle": "Transformez les couleurs d'arrière-plan",
    "landing.color.redesign.heroDesc": "Appliquez instantanément des couleurs unies, des dégradés ou des codes HEX. Parfait pour la photographie de produits.",
    "landing.color.redesign.feat1Title": "Palette de couleurs infinie",
    "landing.color.redesign.feat1Desc": "Choisissez dans notre palette ou entrez un code HEX pour correspondre à votre marque.",
    "landing.color.redesign.feat2Title": "Lissage des bords",
    "landing.color.redesign.feat2Desc": "Les couleurs se fondent naturellement avec les bords de votre sujet, évitant les halos pixélisés.",
    "landing.color.redesign.feat3Title": "Aperçu en direct",
    "landing.color.redesign.feat3Desc": "Voyez les changements de couleur instantanément sans rechargement.",
    "landing.color.redesign.feat4Title": "100% privé",
    "landing.color.redesign.feat4Desc": "Le traitement s'effectue directement sur votre appareil. Aucun téléchargement serveur.",
    "landing.color.redesign.whoTag": "USAGES PROFESSIONNELS",
    "landing.color.redesign.whoTitle": "Conçu pour les créateurs",
    "landing.color.redesign.who1Title": "Catalogues E-Commerce",
    "landing.color.redesign.who1Desc": "Standardisez les arrière-plans de produits de manière cohérente.",
    "landing.color.redesign.who2Title": "Portraits de profil",
    "landing.color.redesign.who2Desc": "Ajoutez des arrière-plans frappants sur LinkedIn ou Twitter.",
    "landing.color.redesign.who3Title": "Supports Marketing",
    "landing.color.redesign.who3Desc": "Préparez des éléments transparents avec vos couleurs.",
    "landing.color.redesign.stepsTitle": "Colorez en 3 étapes",
    "landing.color.redesign.s1Title": "Importer l'image",
    "landing.color.redesign.s1Desc": "Assurez-vous que l'image a un fond transparent.",
    "landing.color.redesign.s2Title": "Choisir la couleur",
    "landing.color.redesign.s2Desc": "Utilisez le sélecteur ou entrez votre code HEX.",
    "landing.color.redesign.s3Title": "Exporter",
    "landing.color.redesign.s3Desc": "Téléchargez votre image colorée en haute résolution.",
    "landing.resize.redesign.heroBadge": "MISE À L'ÉCHELLE PARFAITE",
    "landing.resize.redesign.heroTitle": "Redimensionnez avec une précision absolue",
    "landing.resize.redesign.heroDesc": "Redimensionnez vos photos par dimensions exactes ou pourcentages. Parfait pour les réseaux sociaux.",
    "landing.resize.redesign.feat1Title": "Dimensions exactes en pixels",
    "landing.resize.redesign.feat1Desc": "Prenez le contrôle total de la taille de l'image. Entrez des valeurs de largeur et de hauteur spécifiques.",
    "landing.resize.redesign.feat1Li1": "Verrouiller les proportions",
    "landing.resize.redesign.feat1Li2": "Largeur et hauteur personnalisées",
    "landing.resize.redesign.feat2Title": "Mise à l'échelle en pourcentage",
    "landing.resize.redesign.feat2Desc": "Utilisez le curseur pour mettre à l'échelle rapidement et proportionnellement.",
    "landing.resize.redesign.feat2Li1": "Boutons rapides 50% / 200%",
    "landing.resize.redesign.feat2Li2": "Maintient la qualité visuelle",
    "landing.resize.redesign.socialTitle": "Parfait pour chaque plateforme",
    "landing.resize.redesign.socialDesc": "Répondez aux exigences strictes des réseaux sociaux sans tracas.",
    "landing.resize.redesign.stepsTag": "COMMENT ÇA MARCHE",
    "landing.resize.redesign.stepsTitle": "Redimensionnez en 3 étapes",
    "landing.resize.redesign.s1Title": "Importer les photos",
    "landing.resize.redesign.s1Desc": "Déposez jusqu'à 10 photos.",
    "landing.resize.redesign.s2Title": "Définir les dimensions",
    "landing.resize.redesign.s2Desc": "Entrez votre largeur et hauteur.",
    "landing.resize.redesign.s3Title": "Sauvegarder",
    "landing.resize.redesign.s3Desc": "Téléchargez les photos redimensionnées.",
    "landing.crop.redesign.heroBadge": "COMPOSITION INTELLIGENTE",
    "landing.crop.redesign.heroTitle": "Recadrez le bruit.",
    "landing.crop.redesign.heroTitle2": "Concentrez-vous sur l'essentiel.",
    "landing.crop.redesign.heroDesc": "Encadrez parfaitement vos photos avec un recadrage libre ou fixe.",
    "landing.crop.redesign.feat1Title": "Sélection libre",
    "landing.crop.redesign.feat1Desc": "Faites glisser librement les bords pour encadrer votre sujet exactement comme vous le souhaitez.",
    "landing.crop.redesign.feat2Title": "Ratios fixes",
    "landing.crop.redesign.feat2Desc": "Besoin d'un carré parfait ? Verrouillez le ratio pour conserver les proportions.",
    "landing.crop.redesign.feat3Title": "Extraction sans perte",
    "landing.crop.redesign.feat3Desc": "Nous extrayons les pixels de manière native, garantissant aucune perte de qualité.",
    "landing.crop.redesign.stepsTag": "COMMENT RECADRER",
    "landing.crop.redesign.stepsTitle": "Cadrage parfait en quelques secondes",
    "landing.crop.redesign.s1Title": "Importer la photo",
    "landing.crop.redesign.s1Desc": "Déposez votre image dans l'espace de travail.",
    "landing.crop.redesign.s2Title": "Faire glisser la boîte",
    "landing.crop.redesign.s2Desc": "Ajustez la zone de recadrage.",
    "landing.crop.redesign.s3Title": "Appliquer et sauvegarder",
    "landing.crop.redesign.s3Desc": "Appuyez sur recadrer et téléchargez votre image."
  },
  he: {
    "landing.color.redesign.heroBadge": "סטודיו צבעים מיידי",
    "landing.color.redesign.heroTitle": "שנה צבעי רקע בזמן אמת",
    "landing.color.redesign.heroDesc": "החל צבעים אחידים, מעברי צבע או קודי HEX באופן מיידי. מושלם לצילומי מוצרים.",
    "landing.color.redesign.feat1Title": "קנבס צבעים אינסופי",
    "landing.color.redesign.feat1Desc": "בחר מהפלטה שלנו או הזן כל קוד HEX/RGB להתאמה למותג שלך.",
    "landing.color.redesign.feat2Title": "החלקת קצוות",
    "landing.color.redesign.feat2Desc": "צבעים משתלבים בטבעיות עם קצוות הנושא שלך, ומונעים הילות מפוקסלות.",
    "landing.color.redesign.feat3Title": "תצוגה מקדימה חיה",
    "landing.color.redesign.feat3Desc": "ראה שינויי צבע באופן מיידי ללא זמני המתנה.",
    "landing.color.redesign.feat4Title": "100% פרטיות",
    "landing.color.redesign.feat4Desc": "העיבוד מתבצע ישירות במכשיר שלך. ללא העלאות שרת.",
    "landing.color.redesign.whoTag": "שימושים מקצועיים",
    "landing.color.redesign.whoTitle": "נבנה עבור יוצרים",
    "landing.color.redesign.who1Title": "קטלוגים למסחר אלקטרוני",
    "landing.color.redesign.who1Desc": "תקן רקעי מוצרים עבור רשומות חנות עקביות.",
    "landing.color.redesign.who2Title": "דיוקנאות פרופיל",
    "landing.color.redesign.who2Desc": "הוסף רקעים בולטים ללינקדאין או לטוויטר.",
    "landing.color.redesign.who3Title": "חומרי שיווק",
    "landing.color.redesign.who3Desc": "הכן נכסים שקופים על ידי החלת צבעי מותג.",
    "landing.color.redesign.stepsTitle": "צבע ב-3 שלבים",
    "landing.color.redesign.s1Title": "העלאת תמונה",
    "landing.color.redesign.s1Desc": "ודא שלתמונה יש רקע שקוף תחילה.",
    "landing.color.redesign.s2Title": "בחר צבע",
    "landing.color.redesign.s2Desc": "השתמש בבוחר הצבעים או הזן קוד HEX משלך.",
    "landing.color.redesign.s3Title": "ייצוא",
    "landing.color.redesign.s3Desc": "הורד את התמונה הצבועה ברזולוציה מלאה.",
    "landing.resize.redesign.heroBadge": "קנה מידה מדויק",
    "landing.resize.redesign.heroTitle": "שנה גודל תמונות בדיוק מוחלט",
    "landing.resize.redesign.heroDesc": "הגדל את התמונות שלך לפי מידות פיקסלים מדויקות או אחוזים.",
    "landing.resize.redesign.feat1Title": "מידות פיקסלים מדויקות",
    "landing.resize.redesign.feat1Desc": "קח שליטה מלאה על גודל התמונה. הזן רוחב וגובה ספציפיים.",
    "landing.resize.redesign.feat1Li1": "נעילת יחס גובה-רוחב",
    "landing.resize.redesign.feat1Li2": "רוחב וגובה מותאמים אישית",
    "landing.resize.redesign.feat2Title": "שינוי גודל באחוזים",
    "landing.resize.redesign.feat2Desc": "השתמש במחוון האחוזים כדי לשנות גודל במהירות.",
    "landing.resize.redesign.feat2Li1": "כפתורים מהירים של 50% / 200%",
    "landing.resize.redesign.feat2Li2": "שומר על איכות ויזואלית",
    "landing.resize.redesign.socialTitle": "מושלם לכל פלטפורמה",
    "landing.resize.redesign.socialDesc": "עמוד בדרישות ההעלאה הנוקשות ללא טרחה.",
    "landing.resize.redesign.stepsTag": "איך זה עובד",
    "landing.resize.redesign.stepsTitle": "שינוי גודל ב-3 שלבים",
    "landing.resize.redesign.s1Title": "העלאת תמונות",
    "landing.resize.redesign.s1Desc": "גרור עד 10 תמונות.",
    "landing.resize.redesign.s2Title": "הגדרת מידות",
    "landing.resize.redesign.s2Desc": "הזן רוחב וגובה רצויים.",
    "landing.resize.redesign.s3Title": "שמירה",
    "landing.resize.redesign.s3Desc": "הורד את התמונות המוקטנות מיד.",
    "landing.crop.redesign.heroBadge": "קומפוזיציה חכמה",
    "landing.crop.redesign.heroTitle": "חתוך את הרעש.",
    "landing.crop.redesign.heroTitle2": "התמקד במה שחשוב.",
    "landing.crop.redesign.heroDesc": "מסגר את התמונות שלך בצורה מושלמת עם חיתוך חופשי או יחס קבוע.",
    "landing.crop.redesign.feat1Title": "בחירה חופשית",
    "landing.crop.redesign.feat1Desc": "גרור את קצוות החיתוך בחופשיות למסגור מדויק.",
    "landing.crop.redesign.feat2Title": "יחס גובה-רוחב קבוע",
    "landing.crop.redesign.feat2Desc": "צריך ריבוע מושלם? נעל את יחס הגובה-רוחב לשמירה על פרופורציות.",
    "landing.crop.redesign.feat3Title": "חילוץ ללא הפסד איכות",
    "landing.crop.redesign.feat3Desc": "אנו מחלצים את הפיקסלים באופן מקורי ומבטיחים אפס איבוד איכות.",
    "landing.crop.redesign.stepsTag": "איך לחתוך",
    "landing.crop.redesign.stepsTitle": "מסגור מושלם בשניות",
    "landing.crop.redesign.s1Title": "העלאת תמונה",
    "landing.crop.redesign.s1Desc": "גרור ושחרר את התמונה שלך.",
    "landing.crop.redesign.s2Title": "גרירת התיבה",
    "landing.crop.redesign.s2Desc": "התאם את אזור החיתוך.",
    "landing.crop.redesign.s3Title": "החל ושמור",
    "landing.crop.redesign.s3Desc": "לחץ על חיתוך והורד את התמונה."
  },
  hi: {
    "landing.color.redesign.heroBadge": "त्वरित रंग स्टूडियो",
    "landing.color.redesign.heroTitle": "वास्तविक समय में पृष्ठभूमि के रंग बदलें",
    "landing.color.redesign.heroDesc": "ठोस रंग, ग्रेडिएंट या HEX कोड तुरंत लागू करें। उत्पाद फोटोग्राफी के लिए बिल्कुल सही।",
    "landing.color.redesign.feat1Title": "अनंत रंग कैनवास",
    "landing.color.redesign.feat1Desc": "हमारे पैलेट से चुनें या अपने ब्रांड से मेल खाने के लिए कोई भी HEX/RGB कोड दर्ज करें।",
    "landing.color.redesign.feat2Title": "एज स्मूथिंग",
    "landing.color.redesign.feat2Desc": "रंग आपके विषय के किनारों के साथ स्वाभाविक रूप से मिश्रित होते हैं।",
    "landing.color.redesign.feat3Title": "लाइव प्रीव्यू",
    "landing.color.redesign.feat3Desc": "बिना रीलोड किए तुरंत रंग में बदलाव देखें।",
    "landing.color.redesign.feat4Title": "100% गोपनीयता",
    "landing.color.redesign.feat4Desc": "प्रसंस्करण सीधे आपके डिवाइस पर होता है। कोई सर्वर अपलोड नहीं।",
    "landing.color.redesign.whoTag": "पेशेवर उपयोग",
    "landing.color.redesign.whoTitle": "क्रिएटर्स के लिए बनाया गया",
    "landing.color.redesign.who1Title": "ई-कॉमर्स कैटलॉग",
    "landing.color.redesign.who1Desc": "उत्पाद पृष्ठभूमि को मानकीकृत करें।",
    "landing.color.redesign.who2Title": "प्रोफाइल पोर्ट्रेट",
    "landing.color.redesign.who2Desc": "लिंक्डइन या ट्विटर पर आकर्षक पृष्ठभूमि जोड़ें।",
    "landing.color.redesign.who3Title": "मार्केटिंग सामग्री",
    "landing.color.redesign.who3Desc": "ब्रांड रंगों को लागू करके पारदर्शी संपत्ति तैयार करें।",
    "landing.color.redesign.stepsTitle": "3 चरणों में रंग भरें",
    "landing.color.redesign.s1Title": "छवि अपलोड करें",
    "landing.color.redesign.s1Desc": "सुनिश्चित करें कि छवि में पारदर्शी पृष्ठभूमि है।",
    "landing.color.redesign.s2Title": "एक रंग चुनें",
    "landing.color.redesign.s2Desc": "रंग पिकर का उपयोग करें या अपना HEX कोड दर्ज करें।",
    "landing.color.redesign.s3Title": "निर्यात",
    "landing.color.redesign.s3Desc": "अपनी रंगीन छवि को पूर्ण रिज़ॉल्यूशन में डाउनलोड करें।",
    "landing.resize.redesign.heroBadge": "पिक्सेल-परफेक्ट स्केलिंग",
    "landing.resize.redesign.heroTitle": "पूर्ण सटीकता के साथ छवियों का आकार बदलें",
    "landing.resize.redesign.heroDesc": "सटीक पिक्सेल आयामों या प्रतिशत के अनुसार अपनी तस्वीरों को स्केल करें।",
    "landing.resize.redesign.feat1Title": "सटीक पिक्सेल आयाम",
    "landing.resize.redesign.feat1Desc": "छवि आकार पर पूर्ण नियंत्रण रखें। विशिष्ट चौड़ाई और ऊंचाई दर्ज करें।",
    "landing.resize.redesign.feat1Li1": "पहलू अनुपात लॉक करें",
    "landing.resize.redesign.feat1Li2": "कस्टम चौड़ाई और ऊंचाई",
    "landing.resize.redesign.feat2Title": "प्रतिशत स्केलिंग",
    "landing.resize.redesign.feat2Desc": "छवियों को तेजी से स्केल करने के लिए प्रतिशत स्लाइडर का उपयोग करें।",
    "landing.resize.redesign.feat2Li1": "त्वरित 50% / 200% बटन",
    "landing.resize.redesign.feat2Li2": "दृश्य गुणवत्ता बनाए रखता है",
    "landing.resize.redesign.socialTitle": "हर प्लेटफॉर्म के लिए बिल्कुल सही",
    "landing.resize.redesign.socialDesc": "बिना परेशानी के सोशल मीडिया अपलोड आवश्यकताओं को पूरा करें।",
    "landing.resize.redesign.stepsTag": "यह कैसे काम करता है",
    "landing.resize.redesign.stepsTitle": "3 चरणों में आकार बदलें",
    "landing.resize.redesign.s1Title": "तस्वीरें अपलोड करें",
    "landing.resize.redesign.s1Desc": "10 फ़ोटो तक छोड़ें।",
    "landing.resize.redesign.s2Title": "आयाम सेट करें",
    "landing.resize.redesign.s2Desc": "अपनी लक्षित चौड़ाई और ऊंचाई दर्ज करें।",
    "landing.resize.redesign.s3Title": "सहेजें",
    "landing.resize.redesign.s3Desc": "संशोधित फ़ोटो तुरंत डाउनलोड करें।",
    "landing.crop.redesign.heroBadge": "स्मार्ट रचना",
    "landing.crop.redesign.heroTitle": "शोर को काटें।",
    "landing.crop.redesign.heroTitle2": "महत्वपूर्ण चीज़ों पर ध्यान दें।",
    "landing.crop.redesign.heroDesc": "फ्रीफॉर्म या फिक्स्ड-रेशियो क्रॉपिंग के साथ अपनी तस्वीरों को पूरी तरह से फ्रेम करें।",
    "landing.crop.redesign.feat1Title": "फ्रीफॉर्म चयन",
    "landing.crop.redesign.feat1Desc": "अपने विषय को ठीक उसी तरह से फ्रेम करने के लिए क्रॉप बॉक्स के किनारों को स्वतंत्र रूप से खींचें।",
    "landing.crop.redesign.feat2Title": "निश्चित पहलू अनुपात",
    "landing.crop.redesign.feat2Desc": "क्या आपको एक आदर्श वर्ग की आवश्यकता है? अनुपात बनाए रखने के लिए पहलू अनुपात को लॉक करें।",
    "landing.crop.redesign.feat3Title": "दोषरहित निष्कर्षण",
    "landing.crop.redesign.feat3Desc": "हम मूल रूप से पिक्सेल निकालते हैं, जिससे शून्य गुणवत्ता हानि सुनिश्चित होती है।",
    "landing.crop.redesign.stepsTag": "क्रॉप कैसे करें",
    "landing.crop.redesign.stepsTitle": "सेकंड में बिल्कुल सही फ्रेमिंग",
    "landing.crop.redesign.s1Title": "फोटो अपलोड करें",
    "landing.crop.redesign.s1Desc": "अपनी छवि खींचें और छोड़ें।",
    "landing.crop.redesign.s2Title": "बॉक्स खींचें",
    "landing.crop.redesign.s2Desc": "क्रॉप क्षेत्र को समायोजित करें।",
    "landing.crop.redesign.s3Title": "लागू करें और सहेजें",
    "landing.crop.redesign.s3Desc": "क्रॉप दबाएं और अपनी छवि डाउनलोड करें।"
  },
  hu: {
    "landing.color.redesign.heroBadge": "AZONNALI SZÍN STÚDIÓ",
    "landing.color.redesign.heroTitle": "Háttérszínek cseréje valós időben",
    "landing.color.redesign.heroDesc": "Alkalmazzon egyszínű háttereket, színátmeneteket vagy HEX kódokat azonnal.",
    "landing.color.redesign.feat1Title": "Végtelen színvászon",
    "landing.color.redesign.feat1Desc": "Válasszon palettánkról, vagy adjon meg egy HEX kódot a márkájához.",
    "landing.color.redesign.feat2Title": "Élsimítás",
    "landing.color.redesign.feat2Desc": "A színek természetesen keverednek a téma széleivel.",
    "landing.color.redesign.feat3Title": "Élő előnézet",
    "landing.color.redesign.feat3Desc": "Nézze meg a színváltozásokat azonnal, várakozás nélkül.",
    "landing.color.redesign.feat4Title": "100% privát",
    "landing.color.redesign.feat4Desc": "A feldolgozás közvetlenül az eszközén történik.",
    "landing.color.redesign.whoTag": "PROFESSZIONÁLIS HASZNÁLAT",
    "landing.color.redesign.whoTitle": "Alkotóknak tervezve",
    "landing.color.redesign.who1Title": "E-kereskedelmi katalógusok",
    "landing.color.redesign.who1Desc": "Szabványosítsa a termékek hátterét.",
    "landing.color.redesign.who2Title": "Profil portrék",
    "landing.color.redesign.who2Desc": "Adjon lenyűgöző háttereket a LinkedInhez vagy a Twitterhez.",
    "landing.color.redesign.who3Title": "Marketing anyagok",
    "landing.color.redesign.who3Desc": "Készítsen átlátszó eszközöket a márka színeinek alkalmazásával.",
    "landing.color.redesign.stepsTitle": "Színezés 3 lépésben",
    "landing.color.redesign.s1Title": "Kép feltöltése",
    "landing.color.redesign.s1Desc": "Győződjön meg róla, hogy a kép átlátszó hátterű.",
    "landing.color.redesign.s2Title": "Szín kiválasztása",
    "landing.color.redesign.s2Desc": "Használja a színválasztót, vagy adjon meg egy HEX kódot.",
    "landing.color.redesign.s3Title": "Exportálás",
    "landing.color.redesign.s3Desc": "Töltse le a színezett képet teljes felbontásban.",
    "landing.resize.redesign.heroBadge": "PIXEL-PONTOS MÉRETEZÉS",
    "landing.resize.redesign.heroTitle": "Képek méretezése abszolút pontossággal",
    "landing.resize.redesign.heroDesc": "Méretezze át fényképeit pontos pixelméretekkel vagy százalékokkal.",
    "landing.resize.redesign.feat1Title": "Pontos pixelméretek",
    "landing.resize.redesign.feat1Desc": "Vegye át a teljes irányítást a képméret felett. Adjon meg egyedi szélességet és magasságot.",
    "landing.resize.redesign.feat1Li1": "Képarány zárolása",
    "landing.resize.redesign.feat1Li2": "Egyéni szélesség és magasság",
    "landing.resize.redesign.feat2Title": "Százalékos méretezés",
    "landing.resize.redesign.feat2Desc": "Használja a százalékos csúszkát a képek gyors méretezéséhez.",
    "landing.resize.redesign.feat2Li1": "Gyors 50% / 200% gombok",
    "landing.resize.redesign.feat2Li2": "Megtartja a vizuális minőséget",
    "landing.resize.redesign.socialTitle": "Tökéletes minden platformra",
    "landing.resize.redesign.socialDesc": "Feleljen meg a szigorú feltöltési követelményeknek gond nélkül.",
    "landing.resize.redesign.stepsTag": "HOGYAN MŰKÖDIK",
    "landing.resize.redesign.stepsTitle": "Méretezés 3 lépésben",
    "landing.resize.redesign.s1Title": "Fényképek feltöltése",
    "landing.resize.redesign.s1Desc": "Húzzon be akár 10 fényképet.",
    "landing.resize.redesign.s2Title": "Méretek beállítása",
    "landing.resize.redesign.s2Desc": "Adja meg a cél szélességet és magasságot.",
    "landing.resize.redesign.s3Title": "Mentés",
    "landing.resize.redesign.s3Desc": "Töltse le a méretezett képeket azonnal.",
    "landing.crop.redesign.heroBadge": "OKOS KOMPOZÍCIÓ",
    "landing.crop.redesign.heroTitle": "Vágja ki a zajt.",
    "landing.crop.redesign.heroTitle2": "Fókuszáljon a lényegre.",
    "landing.crop.redesign.heroDesc": "Keretezze be tökéletesen fényképeit szabad formájú vagy rögzített arányú vágással.",
    "landing.crop.redesign.feat1Title": "Szabad formájú kijelölés",
    "landing.crop.redesign.feat1Desc": "Húzza a vágókeret széleit szabadon a téma pontos bekeretezéséhez.",
    "landing.crop.redesign.feat2Title": "Rögzített képarányok",
    "landing.crop.redesign.feat2Desc": "Tökéletes négyzetre van szüksége? Zárolja a képarányt az arányok megőrzéséhez.",
    "landing.crop.redesign.feat3Title": "Veszteségmentes kinyerés",
    "landing.crop.redesign.feat3Desc": "A pixeleket natív módon nyerjük ki, biztosítva a nulla minőségromlást.",
    "landing.crop.redesign.stepsTag": "HOGYAN KELL VÁGNI",
    "landing.crop.redesign.stepsTitle": "Tökéletes keretezés másodpercek alatt",
    "landing.crop.redesign.s1Title": "Fénykép feltöltése",
    "landing.crop.redesign.s1Desc": "Húzza és ejtse a képet a munkaterületre.",
    "landing.crop.redesign.s2Title": "Húzza a keretet",
    "landing.crop.redesign.s2Desc": "Állítsa be a vágási területet a sarokfogantyúkkal.",
    "landing.crop.redesign.s3Title": "Alkalmaz és Ment",
    "landing.crop.redesign.s3Desc": "Kattintson a vágásra, és töltse le a képet."
  },
  id: {
    "landing.color.redesign.heroBadge": "STUDIO WARNA INSTAN",
    "landing.color.redesign.heroTitle": "Ubah Warna Latar Belakang secara Real-Time",
    "landing.color.redesign.heroDesc": "Terapkan warna solid, gradien, atau kode HEX khusus secara instan. Sempurna untuk fotografi produk.",
    "landing.color.redesign.feat1Title": "Kanvas Warna Tak Terbatas",
    "landing.color.redesign.feat1Desc": "Pilih dari palet warna pilihan kami, atau masukkan kode HEX/RGB yang sesuai dengan merek Anda.",
    "landing.color.redesign.feat2Title": "Penghalusan Tepi",
    "landing.color.redesign.feat2Desc": "Warna menyatu secara alami dengan tepi objek Anda, menghindari halo berpiksel kasar.",
    "landing.color.redesign.feat3Title": "Pratinjau Langsung",
    "landing.color.redesign.feat3Desc": "Lihat perubahan warna secara instan tanpa menunggu proses server.",
    "landing.color.redesign.feat4Title": "100% Pribadi",
    "landing.color.redesign.feat4Desc": "Pemrosesan dilakukan langsung di perangkat Anda. Tidak ada unggahan jaringan.",
    "landing.color.redesign.whoTag": "PENGGUNAAN PROFESIONAL",
    "landing.color.redesign.whoTitle": "Dibuat untuk Kreator",
    "landing.color.redesign.who1Title": "Katalog E-Commerce",
    "landing.color.redesign.who1Desc": "Standarkan latar belakang produk dengan warna putih bersih atau kode khusus.",
    "landing.color.redesign.who2Title": "Potret Profil",
    "landing.color.redesign.who2Desc": "Tambahkan latar belakang menarik ke LinkedIn atau Twitter.",
    "landing.color.redesign.who3Title": "Materi Pemasaran",
    "landing.color.redesign.who3Desc": "Siapkan aset transparan dengan menerapkan palet kampanye iklan yang cocok.",
    "landing.color.redesign.stepsTitle": "Warnai dalam 3 Langkah",
    "landing.color.redesign.s1Title": "Unggah Gambar",
    "landing.color.redesign.s1Desc": "Pastikan gambar Anda memiliki latar belakang transparan terlebih dahulu.",
    "landing.color.redesign.s2Title": "Pilih Warna",
    "landing.color.redesign.s2Desc": "Gunakan pemilih warna atau masukkan kode HEX khusus Anda.",
    "landing.color.redesign.s3Title": "Ekspor",
    "landing.color.redesign.s3Desc": "Unduh gambar berwarna baru Anda dalam resolusi penuh.",
    "landing.resize.redesign.heroBadge": "PENYESUAIAN SKALA AKURAT",
    "landing.resize.redesign.heroTitle": "Ubah Ukuran Gambar dengan Presisi Mutlak",
    "landing.resize.redesign.heroDesc": "Sesuaikan skala foto Anda dengan dimensi piksel atau persentase yang tepat.",
    "landing.resize.redesign.feat1Title": "Dimensi Piksel Tepat",
    "landing.resize.redesign.feat1Desc": "Kendalikan penuh ukuran gambar Anda. Masukkan nilai lebar dan tinggi spesifik.",
    "landing.resize.redesign.feat1Li1": "Kunci rasio aspek",
    "landing.resize.redesign.feat1Li2": "Lebar & tinggi khusus",
    "landing.resize.redesign.feat2Title": "Penskalaan Persentase",
    "landing.resize.redesign.feat2Desc": "Gunakan penggeser persentase untuk menyesuaikan ukuran gambar dengan cepat.",
    "landing.resize.redesign.feat2Li1": "Tombol cepat 50% / 200%",
    "landing.resize.redesign.feat2Li2": "Mempertahankan kualitas visual",
    "landing.resize.redesign.socialTitle": "Sempurna untuk Setiap Platform",
    "landing.resize.redesign.socialDesc": "Penuhi persyaratan unggahan yang ketat untuk media sosial tanpa repot.",
    "landing.resize.redesign.stepsTag": "CARA KERJANYA",
    "landing.resize.redesign.stepsTitle": "Ubah Ukuran dalam 3 Langkah",
    "landing.resize.redesign.s1Title": "Unggah Foto",
    "landing.resize.redesign.s1Desc": "Jatuhkan hingga 10 foto ke dalam alat.",
    "landing.resize.redesign.s2Title": "Atur Dimensi",
    "landing.resize.redesign.s2Desc": "Masukkan lebar dan tinggi target Anda.",
    "landing.resize.redesign.s3Title": "Simpan",
    "landing.resize.redesign.s3Desc": "Unduh foto yang telah diubah ukurannya secara instan.",
    "landing.crop.redesign.heroBadge": "KOMPOSISI CERDAS",
    "landing.crop.redesign.heroTitle": "Potong Kebisingan.",
    "landing.crop.redesign.heroTitle2": "Fokus pada yang Penting.",
    "landing.crop.redesign.heroDesc": "Bingkai foto Anda dengan sempurna dengan pemotongan rasio bebas atau tetap.",
    "landing.crop.redesign.feat1Title": "Pemilihan Bebas",
    "landing.crop.redesign.feat1Desc": "Tarik tepi kotak pemotongan secara bebas untuk membingkai subjek Anda.",
    "landing.crop.redesign.feat2Title": "Rasio Aspek Tetap",
    "landing.crop.redesign.feat2Desc": "Butuh persegi sempurna? Kunci rasio aspek untuk mempertahankan proporsi.",
    "landing.crop.redesign.feat3Title": "Ekstraksi Tanpa Kehilangan",
    "landing.crop.redesign.feat3Desc": "Kami mengekstrak piksel secara native memastikan nol kehilangan kualitas.",
    "landing.crop.redesign.stepsTag": "CARA MEMOTONG",
    "landing.crop.redesign.stepsTitle": "Pembingkaian Sempurna dalam Hitungan Detik",
    "landing.crop.redesign.s1Title": "Unggah Foto",
    "landing.crop.redesign.s1Desc": "Seret dan jatuhkan gambar Anda.",
    "landing.crop.redesign.s2Title": "Tarik Kotaknya",
    "landing.crop.redesign.s2Desc": "Sesuaikan area potongan menggunakan pegangan.",
    "landing.crop.redesign.s3Title": "Terapkan & Simpan",
    "landing.crop.redesign.s3Desc": "Tekan potong dan unduh gambar Anda."
  },
  it: {
    "landing.color.redesign.heroBadge": "STUDIO DEL COLORE ISTANTANEO",
    "landing.color.redesign.heroTitle": "Cambia i colori di sfondo in tempo reale",
    "landing.color.redesign.heroDesc": "Applica colori a tinta unita, gradienti o codici HEX all'istante. Perfetto per la fotografia di prodotti.",
    "landing.color.redesign.feat1Title": "Tela dei colori infinita",
    "landing.color.redesign.feat1Desc": "Scegli dalla nostra tavolozza o inserisci qualsiasi codice HEX per abbinarlo al tuo marchio.",
    "landing.color.redesign.feat2Title": "Smussatura dei bordi",
    "landing.color.redesign.feat2Desc": "I colori si fondono naturalmente con i bordi del soggetto, evitando aloni pixelati.",
    "landing.color.redesign.feat3Title": "Anteprima dal vivo",
    "landing.color.redesign.feat3Desc": "Guarda i cambiamenti di colore istantaneamente senza tempi di attesa.",
    "landing.color.redesign.feat4Title": "Privacy al 100%",
    "landing.color.redesign.feat4Desc": "L'elaborazione avviene direttamente sul tuo dispositivo. Nessun caricamento sul server.",
    "landing.color.redesign.whoTag": "USI PROFESSIONALI",
    "landing.color.redesign.whoTitle": "Costruito per i creatori",
    "landing.color.redesign.who1Title": "Cataloghi E-Commerce",
    "landing.color.redesign.who1Desc": "Standardizza gli sfondi dei prodotti per inserzioni coerenti.",
    "landing.color.redesign.who2Title": "Ritratti del profilo",
    "landing.color.redesign.who2Desc": "Aggiungi sfondi vivaci a LinkedIn o Twitter.",
    "landing.color.redesign.who3Title": "Materiali di marketing",
    "landing.color.redesign.who3Desc": "Prepara risorse trasparenti applicando i colori del marchio.",
    "landing.color.redesign.stepsTitle": "Colora in 3 passaggi",
    "landing.color.redesign.s1Title": "Carica l'immagine",
    "landing.color.redesign.s1Desc": "Assicurati che l'immagine abbia prima uno sfondo trasparente.",
    "landing.color.redesign.s2Title": "Scegli un colore",
    "landing.color.redesign.s2Desc": "Usa il selettore dei colori o inserisci un codice HEX.",
    "landing.color.redesign.s3Title": "Esporta",
    "landing.color.redesign.s3Desc": "Scarica la tua immagine colorata a piena risoluzione.",
    "landing.resize.redesign.heroBadge": "RIDIMENSIONAMENTO PERFETTO",
    "landing.resize.redesign.heroTitle": "Ridimensiona le immagini con assoluta precisione",
    "landing.resize.redesign.heroDesc": "Ridimensiona le tue foto in base a dimensioni pixel o percentuali esatte.",
    "landing.resize.redesign.feat1Title": "Dimensioni pixel esatte",
    "landing.resize.redesign.feat1Desc": "Prendi il pieno controllo delle dimensioni dell'immagine. Inserisci valori specifici di larghezza e altezza.",
    "landing.resize.redesign.feat1Li1": "Blocca le proporzioni",
    "landing.resize.redesign.feat1Li2": "Larghezza e altezza personalizzate",
    "landing.resize.redesign.feat2Title": "Ridimensionamento percentuale",
    "landing.resize.redesign.feat2Desc": "Usa il cursore percentuale per ridimensionare rapidamente le immagini.",
    "landing.resize.redesign.feat2Li1": "Pulsanti rapidi 50% / 200%",
    "landing.resize.redesign.feat2Li2": "Mantiene la qualità visiva",
    "landing.resize.redesign.socialTitle": "Perfetto per ogni piattaforma",
    "landing.resize.redesign.socialDesc": "Soddisfa i rigidi requisiti di caricamento dei social media senza problemi.",
    "landing.resize.redesign.stepsTag": "COME FUNZIONA",
    "landing.resize.redesign.stepsTitle": "Ridimensiona in 3 passaggi",
    "landing.resize.redesign.s1Title": "Carica le foto",
    "landing.resize.redesign.s1Desc": "Rilascia fino a 10 foto nello strumento.",
    "landing.resize.redesign.s2Title": "Imposta le dimensioni",
    "landing.resize.redesign.s2Desc": "Inserisci la larghezza e l'altezza target.",
    "landing.resize.redesign.s3Title": "Salva",
    "landing.resize.redesign.s3Desc": "Scarica immediatamente le foto ridimensionate.",
    "landing.crop.redesign.heroBadge": "COMPOSIZIONE INTELLIGENTE",
    "landing.crop.redesign.heroTitle": "Taglia il rumore.",
    "landing.crop.redesign.heroTitle2": "Concentrati su ciò che conta.",
    "landing.crop.redesign.heroDesc": "Incornicia le tue foto perfettamente con un ritaglio libero o a proporzioni fisse.",
    "landing.crop.redesign.feat1Title": "Selezione libera",
    "landing.crop.redesign.feat1Desc": "Trascina liberamente i bordi del riquadro di ritaglio per incorniciare il soggetto.",
    "landing.crop.redesign.feat2Title": "Proporzioni fisse",
    "landing.crop.redesign.feat2Desc": "Hai bisogno di un quadrato perfetto? Blocca le proporzioni per mantenerle.",
    "landing.crop.redesign.feat3Title": "Estrazione senza perdite",
    "landing.crop.redesign.feat3Desc": "Estraiamo i pixel nativamente garantendo zero perdite di qualità.",
    "landing.crop.redesign.stepsTag": "COME RITAGLIARE",
    "landing.crop.redesign.stepsTitle": "Inquadratura perfetta in pochi secondi",
    "landing.crop.redesign.s1Title": "Carica foto",
    "landing.crop.redesign.s1Desc": "Trascina e rilascia la tua immagine nello spazio di lavoro.",
    "landing.crop.redesign.s2Title": "Trascina il riquadro",
    "landing.crop.redesign.s2Desc": "Regola l'area di ritaglio utilizzando le maniglie.",
    "landing.crop.redesign.s3Title": "Applica e salva",
    "landing.crop.redesign.s3Desc": "Premi Ritaglia e scarica l'immagine estratta."
  },
  ja: {
    "landing.color.redesign.heroBadge": "インスタントカラースタジオ",
    "landing.color.redesign.heroTitle": "リアルタイムで背景色を変更",
    "landing.color.redesign.heroDesc": "単色、グラデーション、またはHEXコードを瞬時に適用します。商品写真に最適です。",
    "landing.color.redesign.feat1Title": "無限のカラーキャンバス",
    "landing.color.redesign.feat1Desc": "当社のパレットから選択するか、ブランドに合わせたHEXコードを入力してください。",
    "landing.color.redesign.feat2Title": "エッジスムージング",
    "landing.color.redesign.feat2Desc": "色は被写体のエッジと自然にブレンドし、ピクセル化された後光を避けます。",
    "landing.color.redesign.feat3Title": "ライブプレビュー",
    "landing.color.redesign.feat3Desc": "リロードを待たずに色の変化を瞬時に確認できます。",
    "landing.color.redesign.feat4Title": "100%プライベート",
    "landing.color.redesign.feat4Desc": "処理はデバイス上で直接行われます。サーバーのアップロードはありません。",
    "landing.color.redesign.whoTag": "プロフェッショナルな用途",
    "landing.color.redesign.whoTitle": "クリエイターのために構築",
    "landing.color.redesign.who1Title": "Eコマースカタログ",
    "landing.color.redesign.who1Desc": "一貫したストアリストのために製品の背景を標準化します。",
    "landing.color.redesign.who2Title": "プロフィールポートレート",
    "landing.color.redesign.who2Desc": "LinkedInやTwitterに鮮やかな背景を追加します。",
    "landing.color.redesign.who3Title": "マーケティング資料",
    "landing.color.redesign.who3Desc": "ブランドカラーを適用して透明なアセットを準備します。",
    "landing.color.redesign.stepsTitle": "3ステップで色付け",
    "landing.color.redesign.s1Title": "画像をアップロード",
    "landing.color.redesign.s1Desc": "最初に画像に透明な背景があることを確認してください。",
    "landing.color.redesign.s2Title": "色を選択",
    "landing.color.redesign.s2Desc": "カラーピッカーを使用するか、HEXコードを入力します。",
    "landing.color.redesign.s3Title": "エクスポート",
    "landing.color.redesign.s3Desc": "新しく色付けされた画像をフル解像度でダウンロードします。",
    "landing.resize.redesign.heroBadge": "ピクセルパーフェクトなスケーリング",
    "landing.resize.redesign.heroTitle": "絶対的な精度で画像のサイズを変更",
    "landing.resize.redesign.heroDesc": "正確なピクセル寸法またはパーセンテージで写真をスケーリングします。",
    "landing.resize.redesign.feat1Title": "正確なピクセル寸法",
    "landing.resize.redesign.feat1Desc": "画像サイズを完全に制御します。特定の幅と高さを入力します。",
    "landing.resize.redesign.feat1Li1": "アスペクト比をロック",
    "landing.resize.redesign.feat1Li2": "カスタムの幅と高さ",
    "landing.resize.redesign.feat2Title": "パーセンテージスケーリング",
    "landing.resize.redesign.feat2Desc": "パーセンテージスライダーを使用して画像をすばやくスケーリングします。",
    "landing.resize.redesign.feat2Li1": "クイック50% / 200%ボタン",
    "landing.resize.redesign.feat2Li2": "視覚的品質を維持",
    "landing.resize.redesign.socialTitle": "あらゆるプラットフォームに最適",
    "landing.resize.redesign.socialDesc": "ソーシャルメディアの厳しいアップロード要件を満たします。",
    "landing.resize.redesign.stepsTag": "仕組み",
    "landing.resize.redesign.stepsTitle": "3ステップでサイズ変更",
    "landing.resize.redesign.s1Title": "写真をアップロード",
    "landing.resize.redesign.s1Desc": "最大10枚の写真をドロップします。",
    "landing.resize.redesign.s2Title": "寸法を設定",
    "landing.resize.redesign.s2Desc": "ターゲットの幅と高さを入力します。",
    "landing.resize.redesign.s3Title": "保存",
    "landing.resize.redesign.s3Desc": "サイズ変更された写真をすぐにダウンロードします。",
    "landing.crop.redesign.heroBadge": "スマートな構図",
    "landing.crop.redesign.heroTitle": "ノイズを切り取る。",
    "landing.crop.redesign.heroTitle2": "重要なことに集中する。",
    "landing.crop.redesign.heroDesc": "自由形式または固定アスペクト比のトリミングで写真を完璧にフレームに収めます。",
    "landing.crop.redesign.feat1Title": "自由形式の選択",
    "landing.crop.redesign.feat1Desc": "クロップボックスの端を自由にドラッグして、被写体をフレーミングします。",
    "landing.crop.redesign.feat2Title": "固定アスペクト比",
    "landing.crop.redesign.feat2Desc": "完全な正方形が必要ですか？比率を維持するためにアスペクト比をロックします。",
    "landing.crop.redesign.feat3Title": "ロスレス抽出",
    "landing.crop.redesign.feat3Desc": "ピクセルをネイティブに抽出して、品質の低下をゼロにします。",
    "landing.crop.redesign.stepsTag": "トリミング方法",
    "landing.crop.redesign.stepsTitle": "数秒で完璧なフレーミング",
    "landing.crop.redesign.s1Title": "写真をアップロード",
    "landing.crop.redesign.s1Desc": "画像をワークスペースにドラッグアンドドロップします。",
    "landing.crop.redesign.s2Title": "ボックスをドラッグ",
    "landing.crop.redesign.s2Desc": "ハンドルを使用してトリミング領域を調整します。",
    "landing.crop.redesign.s3Title": "適用して保存",
    "landing.crop.redesign.s3Desc": "トリミングを押して、抽出した画像をダウンロードします。"
  },
  ko: {
    "landing.color.redesign.heroBadge": "인스턴트 컬러 스튜디오",
    "landing.color.redesign.heroTitle": "실시간으로 배경색 변경",
    "landing.color.redesign.heroDesc": "단색, 그라데이션 또는 HEX 코드를 즉시 적용하세요. 제품 사진에 완벽합니다.",
    "landing.color.redesign.feat1Title": "무한한 컬러 캔버스",
    "landing.color.redesign.feat1Desc": "팔레트에서 선택하거나 브랜드와 일치하는 HEX/RGB 코드를 입력하세요.",
    "landing.color.redesign.feat2Title": "가장자리 스무딩",
    "landing.color.redesign.feat2Desc": "색상이 피사체의 가장자리와 자연스럽게 혼합되어 픽셀 후광을 방지합니다.",
    "landing.color.redesign.feat3Title": "실시간 미리보기",
    "landing.color.redesign.feat3Desc": "서버 처리를 기다리지 않고 색상 변경 사항을 즉시 확인하세요.",
    "landing.color.redesign.feat4Title": "100% 프라이버시",
    "landing.color.redesign.feat4Desc": "처리는 장치에서 직접 렌더링됩니다. 서버 업로드가 없습니다.",
    "landing.color.redesign.whoTag": "전문적인 용도",
    "landing.color.redesign.whoTitle": "크리에이터를 위한 제작",
    "landing.color.redesign.who1Title": "전자상거래 카탈로그",
    "landing.color.redesign.who1Desc": "일관된 상점 목록을 위해 제품 배경을 표준화하세요.",
    "landing.color.redesign.who2Title": "프로필 초상화",
    "landing.color.redesign.who2Desc": "LinkedIn이나 Twitter에 시선을 사로잡는 배경을 추가하세요.",
    "landing.color.redesign.who3Title": "마케팅 자료",
    "landing.color.redesign.who3Desc": "광고 캠페인 팔레트를 적용하여 투명한 에셋을 준비하세요.",
    "landing.color.redesign.stepsTitle": "3단계로 채색하기",
    "landing.color.redesign.s1Title": "이미지 업로드",
    "landing.color.redesign.s1Desc": "먼저 이미지에 투명한 배경이 있는지 확인하세요.",
    "landing.color.redesign.s2Title": "색상 선택",
    "landing.color.redesign.s2Desc": "색상 선택기를 사용하거나 사용자 정의 HEX 코드를 입력하세요.",
    "landing.color.redesign.s3Title": "내보내기",
    "landing.color.redesign.s3Desc": "새로 채색된 이미지를 전체 해상도로 다운로드하세요.",
    "landing.resize.redesign.heroBadge": "픽셀 완벽 스케일링",
    "landing.resize.redesign.heroTitle": "절대적인 정밀도로 이미지 크기 조정",
    "landing.resize.redesign.heroDesc": "정확한 픽셀 치수나 백분율로 사진 크기를 조정하세요.",
    "landing.resize.redesign.feat1Title": "정확한 픽셀 치수",
    "landing.resize.redesign.feat1Desc": "이미지 크기를 완벽하게 제어하세요. 특정 너비와 높이를 입력하세요.",
    "landing.resize.redesign.feat1Li1": "종횡비 잠금",
    "landing.resize.redesign.feat1Li2": "사용자 지정 너비 및 높이",
    "landing.resize.redesign.feat2Title": "백분율 스케일링",
    "landing.resize.redesign.feat2Desc": "백분율 슬라이더를 사용하여 사진 크기를 빠르고 비례적으로 조정하세요.",
    "landing.resize.redesign.feat2Li1": "빠른 50% / 200% 버튼",
    "landing.resize.redesign.feat2Li2": "시각적 품질 유지",
    "landing.resize.redesign.socialTitle": "모든 플랫폼에 완벽함",
    "landing.resize.redesign.socialDesc": "소셜 미디어에 대한 엄격한 업로드 요구 사항을 쉽게 충족하세요.",
    "landing.resize.redesign.stepsTag": "작동 방식",
    "landing.resize.redesign.stepsTitle": "3단계로 크기 조정",
    "landing.resize.redesign.s1Title": "사진 업로드",
    "landing.resize.redesign.s1Desc": "최대 10장의 사진을 드롭하세요.",
    "landing.resize.redesign.s2Title": "치수 설정",
    "landing.resize.redesign.s2Desc": "목표 너비와 높이를 입력하세요.",
    "landing.resize.redesign.s3Title": "저장",
    "landing.resize.redesign.s3Desc": "크기가 조정된 사진을 즉시 다운로드하세요.",
    "landing.crop.redesign.heroBadge": "스마트 컴포지션",
    "landing.crop.redesign.heroTitle": "노이즈를 잘라내세요.",
    "landing.crop.redesign.heroTitle2": "중요한 것에 집중하세요.",
    "landing.crop.redesign.heroDesc": "자유형 또는 고정 비율 자르기로 사진을 완벽하게 구도 잡으세요.",
    "landing.crop.redesign.feat1Title": "자유형 선택",
    "landing.crop.redesign.feat1Desc": "자르기 상자의 가장자리를 자유롭게 드래그하여 피사체의 구도를 잡으세요.",
    "landing.crop.redesign.feat2Title": "고정 종횡비",
    "landing.crop.redesign.feat2Desc": "완벽한 사각형이 필요하신가요? 비율을 유지하려면 종횡비를 잠그세요.",
    "landing.crop.redesign.feat3Title": "무손실 추출",
    "landing.crop.redesign.feat3Desc": "우리는 기본적으로 픽셀을 추출하여 품질 손실이 전혀 발생하지 않도록 합니다.",
    "landing.crop.redesign.stepsTag": "자르는 방법",
    "landing.crop.redesign.stepsTitle": "몇 초 안에 완벽한 구도",
    "landing.crop.redesign.s1Title": "사진 업로드",
    "landing.crop.redesign.s1Desc": "이미지를 작업 영역으로 끌어다 놓으세요.",
    "landing.crop.redesign.s2Title": "상자 드래그",
    "landing.crop.redesign.s2Desc": "핸들을 사용하여 자르기 영역을 조정하세요.",
    "landing.crop.redesign.s3Title": "적용 및 저장",
    "landing.crop.redesign.s3Desc": "자르기를 누르고 추출된 이미지를 다운로드하세요."
  }
};

async function run() {
  for (const [lang, keys] of Object.entries(translations)) {
    const filePath = path.join(localesDir, lang, 'translation.json');
    if (!fs.existsSync(filePath)) continue;
    
    const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));

    for (const [key, value] of Object.entries(keys)) {
      data[key] = value;
    }
    
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
    console.log(`[${lang}] Successfully injected part 1`);
  }
}

run().catch(console.error);
