const fs = require('fs');
const path = require('path');
const localesDir = path.join(__dirname, '../public/locales');

const translations = {
  ms: {
    design: {
      heroBadge: "SUIT KREATIF",
      heroTitle: "Reka Visual Cantik.",
      heroTitle2: "Terus di Pelayar Anda.",
      heroDesc: "Penyunting imej lengkap dengan penapis profesional, alat teks, bentuk, dan keupayaan melukis. Tiada pemasangan perisian diperlukan.",
      feat1Title: "Tipografi Kaya",
      feat1Desc: "Tambah lapisan teks tersuai, pilih dari beratus-ratus fon web, dan gayakannya dengan bayang-bayang dan kecerunan.",
      feat2Title: "Penapis Pro",
      feat2Desc: "Gunakan pembetulan warna sinematik dan pelarasan profesional.",
      feat3Title: "Bentuk Vektor",
      feat3Desc: "Lukis bentuk geometri, anak panah, dan sempadan dengan tepat.",
      feat4Title: "Pengurusan Lapisan",
      feat4Desc: "Susun rekaan kompleks dengan mudah. Kumpulkan, sembunyikan, dan kunci berbilang lapisan.",
      stepsTag: "ALIRAN KERJA",
      stepsTitle: "Cipta dalam 3 Langkah",
      s1Title: "Mula Kanvas",
      s1Desc: "Buka kanvas kosong atau import foto.",
      s2Title: "Reka",
      s2Desc: "Tambah teks, grafik, dan gunakan penapis.",
      s3Title: "Eksport",
      s3Desc: "Muat turun karya agung anda."
    },
    rotate: {
      heroBadge: "KAWALAN RUANG",
      heroTitle: "Putar dan Terbalikkan.",
      heroTitle2: "Orientasi Sempurna.",
      heroDesc: "Betulkan foto senget, cipta kesan cermin, dan laraskan putaran imej dengan darjah yang tepat. Pantas, percuma, dan dalam pelayar anda.",
      feat1Title: "Pusingan 90° Pantas",
      feat1Desc: "Baiki foto dengan orientasi salah serta-merta. Putar ke kiri atau kanan dalam gandaan 90 darjah.",
      feat2Title: "Kesan Cermin",
      feat2Desc: "Terbalikkan imej secara mendatar untuk membetulkan swafoto, atau menegak untuk kesan pantulan.",
      feat3Title: "Perhalusi Ufuk",
      feat3Desc: "Ada foto landskap yang senget? Gunakan peluncur untuk meratakan ufuk.",
      stepsTag: "ALIRAN KERJA",
      stepsTitle: "Ubah Orientasi dalam 3 Langkah",
      s1Title: "Muat Naik",
      s1Desc: "Tambah imej yang ingin dibaiki.",
      s2Title: "Laras",
      s2Desc: "Gunakan butang putar dan terbalikkan.",
      s3Title: "Simpan",
      s3Desc: "Muat turun imej yang dibetulkan."
    },
    picker: {
      heroBadge: "KETEPATAN PIKSEL",
      heroTitle: "Ekstrak Warna Sempurna.",
      heroTitle2: "Bina Palet Menakjubkan.",
      heroDesc: "Muat naik imej dan lalukan kursor untuk mendapatkan kod HEX, RGB, dan HSL bagi mana-mana piksel.",
      feat1Title: "Perincian Mikroskopik",
      feat1Desc: "Kaca pembesar terbina dalam membolehkan anda zum pada piksel individu.",
      feat2Title: "Pelbagai Format",
      feat2Desc: "Dapatkan warna anda ditukar serta-merta ke format HEX, RGB, dan HSL. Klik untuk salin.",
      feat3Title: "Jana Palet Automatik",
      feat3Desc: "Algoritma AI kami menganalisis imej anda dan menjana palet 5 warna secara automatik.",
      stepsTag: "ALIRAN KERJA",
      stepsTitle: "Ekstrak dalam 3 Langkah",
      s1Title: "Muat Naik",
      s1Desc: "Muatkan imej rujukan anda.",
      s2Title: "Pilih",
      s2Desc: "Lalukan kursor pada mana-mana piksel dan klik.",
      s3Title: "Salin",
      s3Desc: "Salin nilai HEX/RGB serta-merta."
    }
  },
  nl: {
    design: {
      heroBadge: "CREATIEVE SUITE",
      heroTitle: "Ontwerp prachtige visuals.",
      heroTitle2: "Direct in je browser.",
      heroDesc: "Een complete beeldbewerker met professionele filters, teksthulpmiddelen, vormen en tekenmogelijkheden. Geen software-installatie vereist.",
      feat1Title: "Rijke typografie",
      feat1Desc: "Voeg aangepaste tekstlagen toe, kies uit honderden lettertypen en voorzie ze van schaduwen en gradiënten.",
      feat2Title: "Pro Filters",
      feat2Desc: "Pas filmische kleurcorrecties en professionele aanpassingen toe.",
      feat3Title: "Vormen (Vector)",
      feat3Desc: "Teken geometrische vormen, pijlen en randen met precisie.",
      feat4Title: "Lagenbeheer",
      feat4Desc: "Organiseer complexe ontwerpen moeiteloos. Stapel, groepeer en vergrendel meerdere lagen.",
      stepsTag: "WERKSTROOM",
      stepsTitle: "Creëer in 3 stappen",
      s1Title: "Start Canvas",
      s1Desc: "Open een leeg canvas of importeer een foto.",
      s2Title: "Ontwerp",
      s2Desc: "Voeg tekst, afbeeldingen en filters toe.",
      s3Title: "Exporteren",
      s3Desc: "Download je ultieme meesterwerk."
    },
    rotate: {
      heroBadge: "RUIMTELIJKE CONTROLE",
      heroTitle: "Roteren en spiegelen.",
      heroTitle2: "Perfecte oriëntatie.",
      heroDesc: "Corrigeer scheve foto's, creëer spiegeleffecten en verfijn de beeldrotatie in exacte graden. Snel en gratis in je browser.",
      feat1Title: "Snelle 90° draaiingen",
      feat1Desc: "Repareer foto's met een verkeerde oriëntatie direct. Roteer in stappen van 90 graden.",
      feat2Title: "Spiegeleffecten",
      feat2Desc: "Spiegel afbeeldingen horizontaal voor selfies of verticaal voor creatieve reflecties.",
      feat3Title: "Horizon verfijnen",
      feat3Desc: "Heb je een scheve landschapsfoto? Gebruik de schuifregelaar om de horizon recht te trekken.",
      stepsTag: "WERKSTROOM",
      stepsTitle: "Heroriënteren in 3 stappen",
      s1Title: "Uploaden",
      s1Desc: "Voeg de afbeeldingen toe die je wilt corrigeren.",
      s2Title: "Aanpassen",
      s2Desc: "Gebruik de roteer- en spiegelknoppen.",
      s3Title: "Opslaan",
      s3Desc: "Download de gecorrigeerde afbeeldingen."
    },
    picker: {
      heroBadge: "PIXEL PRECISIE",
      heroTitle: "Extraheer perfecte kleuren.",
      heroTitle2: "Bouw prachtige paletten.",
      heroDesc: "Upload een afbeelding en beweeg erover om HEX-, RGB- en HSL-codes te vinden. Genereer direct kleurenpaletten.",
      feat1Title: "Microscopisch detail",
      feat1Desc: "Met het ingebouwde vergrootglas kun je inzoomen op individuele pixels.",
      feat2Title: "Meerdere formaten",
      feat2Desc: "Krijg je kleuren geconverteerd in HEX, RGB en HSL. Klik om te kopiëren.",
      feat3Title: "Automatische paletten",
      feat3Desc: "Ons AI-algoritme analyseert je afbeelding en genereert een palet met 5 kleuren.",
      stepsTag: "WERKSTROOM",
      stepsTitle: "Extraheer in 3 stappen",
      s1Title: "Uploaden",
      s1Desc: "Laad je referentieafbeelding.",
      s2Title: "Kiezen",
      s2Desc: "Beweeg over een pixel en klik.",
      s3Title: "Kopiëren",
      s3Desc: "Kopieer de HEX/RGB-waarden direct."
    }
  },
  no: {
    design: {
      heroBadge: "KREATIV SUITE",
      heroTitle: "Design vakre visuelle elementer.",
      heroTitle2: "Rett i nettleseren din.",
      heroDesc: "En fullverdig bilderedigerer med profesjonelle filtre, tekstverktøy og tegnefunksjoner. Ingen programvareinstallasjon.",
      feat1Title: "Rik Typografi",
      feat1Desc: "Legg til tilpassede tekstlag, velg mellom hundrevis av skrifttyper, og bruk skygger og gradienter.",
      feat2Title: "Pro Filtre",
      feat2Desc: "Bruk filmaktig fargekorrigering og profesjonelle justeringer.",
      feat3Title: "Vektorformer",
      feat3Desc: "Tegn geometriske former, piler og grenser med presisjon.",
      feat4Title: "Lagstyring",
      feat4Desc: "Organiser komplekse design enkelt. Stabl, grupper og lås flere lag.",
      stepsTag: "ARBEIDSFLYT",
      stepsTitle: "Opprett i 3 trinn",
      s1Title: "Start Lerret",
      s1Desc: "Åpne et tomt lerret eller importer et bilde.",
      s2Title: "Design",
      s2Desc: "Legg til tekst, grafikk og filtre.",
      s3Title: "Eksporter",
      s3Desc: "Last ned ditt endelige mesterverk."
    },
    rotate: {
      heroBadge: "ROMLIG KONTROLL",
      heroTitle: "Roter og Vend.",
      heroTitle2: "Perfekt orientering.",
      heroDesc: "Korriger sideveis bilder, lag speileffekter og finjuster rotasjon.",
      feat1Title: "Raske 90° Svinger",
      feat1Desc: "Fiks bilder tatt i feil retning. Roter i trinn på 90 grader.",
      feat2Title: "Speileffekter",
      feat2Desc: "Vend bilder horisontalt for selfies, eller vertikalt for refleksjoner.",
      feat3Title: "Finjuster Horisonten",
      feat3Desc: "Har du et skjevt landskapsbilde? Bruk glidebryteren for å jevne ut horisonten.",
      stepsTag: "ARBEIDSFLYT",
      stepsTitle: "Omorienter i 3 trinn",
      s1Title: "Last opp",
      s1Desc: "Legg til bildene du vil fikse.",
      s2Title: "Juster",
      s2Desc: "Bruk rotasjons- og vendeknappene.",
      s3Title: "Lagre",
      s3Desc: "Last ned de korrigerte bildene."
    },
    picker: {
      heroBadge: "PIKSELPRESISJON",
      heroTitle: "Trekk ut perfekte farger.",
      heroTitle2: "Bygg fantastiske paletter.",
      heroDesc: "Last opp et bilde og hold over for å finne HEX-, RGB- og HSL-koder.",
      feat1Title: "Mikroskopisk detalj",
      feat1Desc: "Det innebygde forstørrelsesglasset lar deg zoome inn på enkeltpiksler.",
      feat2Title: "Flere formater",
      feat2Desc: "Få fargene dine konvertert til HEX, RGB og HSL. Klikk for å kopiere.",
      feat3Title: "Autogenerer Paletter",
      feat3Desc: "Vår AI-algoritme analyserer bildet og genererer en palett med 5 farger.",
      stepsTag: "ARBEIDSFLYT",
      stepsTitle: "Trekk ut i 3 trinn",
      s1Title: "Last opp",
      s1Desc: "Last inn referansebildet ditt.",
      s2Title: "Velg",
      s2Desc: "Hold over en piksel og klikk for å fange.",
      s3Title: "Kopier",
      s3Desc: "Kopier HEX/RGB-verdiene øyeblikkelig."
    }
  },
  pl: {
    design: {
      heroBadge: "PAKIET KREATYWNY",
      heroTitle: "Projektuj piękne grafiki.",
      heroTitle2: "Bezpośrednio w przeglądarce.",
      heroDesc: "W pełni wyposażony edytor z profesjonalnymi filtrami, narzędziami tekstowymi i możliwościami rysowania.",
      feat1Title: "Bogata Typografia",
      feat1Desc: "Dodawaj warstwy tekstowe, wybieraj setki czcionek, używaj cieni i gradientów.",
      feat2Title: "Filtry Pro",
      feat2Desc: "Zastosuj kinową korekcję kolorów i profesjonalne poprawki.",
      feat3Title: "Kształty Wektorowe",
      feat3Desc: "Rysuj kształty geometryczne i strzałki z precyzją.",
      feat4Title: "Zarządzanie Warstwami",
      feat4Desc: "Grupuj, ukrywaj i blokuj warstwy, aby organizować złożone projekty.",
      stepsTag: "PRZEPŁYW PRACY",
      stepsTitle: "Twórz w 3 Krokach",
      s1Title: "Start",
      s1Desc: "Otwórz puste płótno lub zaimportuj zdjęcie.",
      s2Title: "Projekt",
      s2Desc: "Dodaj tekst, grafikę i filtry.",
      s3Title: "Eksport",
      s3Desc: "Pobierz swoje dzieło."
    },
    rotate: {
      heroBadge: "KONTROLA PRZESTRZENNA",
      heroTitle: "Obracaj i Odbijaj.",
      heroTitle2: "Idealna Orientacja.",
      heroDesc: "Popraw zdjęcia, stwórz efekty lustrzane i precyzyjnie obracaj obrazy.",
      feat1Title: "Szybkie Obroty 90°",
      feat1Desc: "Obracaj w lewo lub w prawo o 90 stopni jednym kliknięciem.",
      feat2Title: "Efekty Lustrzane",
      feat2Desc: "Odbijaj w poziomie do selfie, lub w pionie do odbić.",
      feat3Title: "Poziomowanie Horyzontu",
      feat3Desc: "Krzywy krajobraz? Użyj suwaka, aby wyrównać horyzont.",
      stepsTag: "PRZEPŁYW PRACY",
      stepsTitle: "Zmień Orientację w 3 Krokach",
      s1Title: "Prześlij",
      s1Desc: "Dodaj zdjęcia do poprawy.",
      s2Title: "Dostosuj",
      s2Desc: "Użyj przycisków obrotu i odbicia.",
      s3Title: "Zapisz",
      s3Desc: "Pobierz poprawione zdjęcia."
    },
    picker: {
      heroBadge: "PRECYZJA PIKSELI",
      heroTitle: "Wybieraj idealne kolory.",
      heroTitle2: "Buduj wspaniałe palety.",
      heroDesc: "Prześlij zdjęcie i najedź, aby uzyskać kody HEX, RGB i HSL dowolnego piksela.",
      feat1Title: "Mikroskopijny Detal",
      feat1Desc: "Wbudowana lupa pozwala przybliżyć pojedyncze piksele.",
      feat2Title: "Wiele Formatów",
      feat2Desc: "Kody przekonwertowane do HEX, RGB, HSL. Kliknij, by skopiować.",
      feat3Title: "Automatyczne Palety",
      feat3Desc: "Algorytm AI analizuje obraz i generuje 5-kolorową paletę.",
      stepsTag: "PRZEPŁYW PRACY",
      stepsTitle: "Pobieraj w 3 Krokach",
      s1Title: "Prześlij",
      s1Desc: "Załaduj obraz referencyjny.",
      s2Title: "Wybierz",
      s2Desc: "Najedź i kliknij na piksel.",
      s3Title: "Kopiuj",
      s3Desc: "Skopiuj wartości natychmiast."
    }
  },
  pt: {
    design: {
      heroBadge: "SUÍTE CRIATIVA",
      heroTitle: "Crie visuais bonitos.",
      heroTitle2: "Direto no seu navegador.",
      heroDesc: "Um editor de imagens completo com filtros profissionais, ferramentas de texto e formas.",
      feat1Title: "Tipografia Rica",
      feat1Desc: "Adicione camadas de texto, escolha entre centenas de fontes e aplique sombras.",
      feat2Title: "Filtros Pro",
      feat2Desc: "Aplique correção de cor cinematográfica.",
      feat3Title: "Formas Vetoriais",
      feat3Desc: "Desenhe formas geométricas e setas com precisão.",
      feat4Title: "Gerenciamento de Camadas",
      feat4Desc: "Organize seus designs. Agrupe e bloqueie múltiplas camadas.",
      stepsTag: "FLUXO DE TRABALHO",
      stepsTitle: "Crie em 3 Passos",
      s1Title: "Iniciar Canvas",
      s1Desc: "Abra uma tela em branco ou importe uma foto.",
      s2Title: "Design",
      s2Desc: "Adicione textos, gráficos e filtros.",
      s3Title: "Exportar",
      s3Desc: "Baixe sua obra final."
    },
    rotate: {
      heroBadge: "CONTROLE ESPACIAL",
      heroTitle: "Gire e Espelhe.",
      heroTitle2: "Orientação Perfeita.",
      heroDesc: "Corrija fotos tortas, crie efeitos de espelho e ajuste a rotação com exatidão.",
      feat1Title: "Giros de 90° Rápidos",
      feat1Desc: "Rotacione em incrementos de 90 graus para consertar fotos deitadas.",
      feat2Title: "Efeitos de Espelho",
      feat2Desc: "Vire imagens horizontalmente (selfies) ou verticalmente (reflexos).",
      feat3Title: "Ajuste o Horizonte",
      feat3Desc: "Use o controle deslizante para nivelar o horizonte de paisagens tortas.",
      stepsTag: "FLUXO DE TRABALHO",
      stepsTitle: "Reoriente em 3 Passos",
      s1Title: "Enviar",
      s1Desc: "Adicione as imagens.",
      s2Title: "Ajustar",
      s2Desc: "Use os botões de giro.",
      s3Title: "Salvar",
      s3Desc: "Baixe a imagem corrigida."
    },
    picker: {
      heroBadge: "PRECISÃO DE PIXELS",
      heroTitle: "Extraia cores perfeitas.",
      heroTitle2: "Crie paletas incríveis.",
      heroDesc: "Faça upload e passe o mouse para pegar códigos HEX, RGB e HSL de qualquer pixel.",
      feat1Title: "Detalhe Microscópico",
      feat1Desc: "A lupa integrada permite dar zoom em pixels individuais.",
      feat2Title: "Vários Formatos",
      feat2Desc: "Suas cores instantaneamente em HEX, RGB e HSL. Clique para copiar.",
      feat3Title: "Gerador de Paletas IA",
      feat3Desc: "Nossa IA analisa sua imagem e gera uma paleta de 5 cores harmoniosa.",
      stepsTag: "FLUXO DE TRABALHO",
      stepsTitle: "Extraia em 3 Passos",
      s1Title: "Upload",
      s1Desc: "Carregue a imagem.",
      s2Title: "Escolher",
      s2Desc: "Passe o mouse e clique no pixel.",
      s3Title: "Copiar",
      s3Desc: "Copie o HEX/RGB instantaneamente."
    }
  },
  ro: {
    design: {
      heroBadge: "SUITĂ CREATIVĂ",
      heroTitle: "Proiectează imagini frumoase.",
      heroTitle2: "Direct în browserul tău.",
      heroDesc: "Un editor de imagini complet cu filtre profesionale, texte și desen.",
      feat1Title: "Tipografie Bogată",
      feat1Desc: "Alege din sute de fonturi și stilizează-le cu umbre și gradienți.",
      feat2Title: "Filtre Pro",
      feat2Desc: "Aplică corecții cinematografice de culoare.",
      feat3Title: "Forme Vectoriale",
      feat3Desc: "Desenează forme și săgeți cu precizie.",
      feat4Title: "Gestionare Straturi",
      feat4Desc: "Organizează, grupează și blochează multiple layere.",
      stepsTag: "FLUX DE LUCRU",
      stepsTitle: "Creează în 3 Pași",
      s1Title: "Pornește",
      s1Desc: "Deschide o pânză sau încarcă o fotografie.",
      s2Title: "Designează",
      s2Desc: "Adaugă text și grafică.",
      s3Title: "Exportă",
      s3Desc: "Descarcă capodopera finală."
    },
    rotate: {
      heroBadge: "CONTROL SPAȚIAL",
      heroTitle: "Rotește și Întoarce.",
      heroTitle2: "Orientare Perfectă.",
      heroDesc: "Corectează fotografiile, creează efecte de oglindă și ajustează rotația.",
      feat1Title: "Rotiri de 90° Rapide",
      feat1Desc: "Rotește la stânga sau la dreapta din 90 în 90 de grade.",
      feat2Title: "Efecte de Oglindă",
      feat2Desc: "Întoarce imaginile pe orizontală sau verticală.",
      feat3Title: "Nivelează Orizontul",
      feat3Desc: "Folosește cursorul pentru a îndrepta fotografiile peisaj.",
      stepsTag: "FLUX DE LUCRU",
      stepsTitle: "Reorientează în 3 Pași",
      s1Title: "Încarcă",
      s1Desc: "Adaugă imaginile tale.",
      s2Title: "Ajustează",
      s2Desc: "Folosește butoanele de rotire.",
      s3Title: "Salvează",
      s3Desc: "Descarcă imaginile corectate."
    },
    picker: {
      heroBadge: "PRECIZIE DE PIXEL",
      heroTitle: "Extrage culori perfecte.",
      heroTitle2: "Construiește palete uimitoare.",
      heroDesc: "Află codurile HEX, RGB și HSL pentru orice pixel dintr-o imagine.",
      feat1Title: "Detaliu Microscopic",
      feat1Desc: "Lupa încorporată îți permite să faci zoom la nivel de pixel.",
      feat2Title: "Formate Multiple",
      feat2Desc: "Culori convertite în HEX, RGB, HSL. Apasă pentru a copia.",
      feat3Title: "Palete Automate",
      feat3Desc: "Inteligența artificială analizează imaginea și extrage o paletă de 5 culori.",
      stepsTag: "FLUX DE LUCRU",
      stepsTitle: "Extrage în 3 Pași",
      s1Title: "Încarcă",
      s1Desc: "Adaugă imaginea de referință.",
      s2Title: "Alege",
      s2Desc: "Treci peste pixel și dă click.",
      s3Title: "Copiază",
      s3Desc: "Copiază valorile HEX instantaneu."
    }
  },
  ru: {
    design: {
      heroBadge: "КРЕАТИВНЫЙ НАБОР",
      heroTitle: "Создавайте красивый дизайн.",
      heroTitle2: "Прямо в вашем браузере.",
      heroDesc: "Полнофункциональный редактор изображений с профессиональными фильтрами, инструментами для текста, фигурами и рисованием.",
      feat1Title: "Богатая типографика",
      feat1Desc: "Добавляйте пользовательские текстовые слои, выбирайте из сотен веб-шрифтов, добавляйте тени и градиенты.",
      feat2Title: "Профессиональные фильтры",
      feat2Desc: "Применяйте кинематографическую цветокоррекцию.",
      feat3Title: "Векторные фигуры",
      feat3Desc: "С точностью рисуйте геометрические фигуры, стрелки и границы.",
      feat4Title: "Управление слоями",
      feat4Desc: "Упорядочивайте сложный дизайн. Группируйте, скрывайте и блокируйте слои.",
      stepsTag: "РАБОЧИЙ ПРОЦЕСС",
      stepsTitle: "Создайте за 3 шага",
      s1Title: "Начать",
      s1Desc: "Откройте пустой холст или импортируйте фото.",
      s2Title: "Дизайн",
      s2Desc: "Добавьте текст, графику и фильтры.",
      s3Title: "Экспорт",
      s3Desc: "Скачайте ваш шедевр."
    },
    rotate: {
      heroBadge: "ПРОСТРАНСТВЕННЫЙ КОНТРОЛЬ",
      heroTitle: "Вращение и отражение.",
      heroTitle2: "Идеальная ориентация.",
      heroDesc: "Исправляйте перевернутые фото, создавайте зеркальные эффекты и точно настраивайте поворот.",
      feat1Title: "Быстрые повороты на 90°",
      feat1Desc: "Моментально исправляйте фотографии. Поворачивайте влево или вправо на 90 градусов.",
      feat2Title: "Зеркальные эффекты",
      feat2Desc: "Отражайте изображения по горизонтали для селфи или по вертикали для творческих эффектов.",
      feat3Title: "Точная настройка горизонта",
      feat3Desc: "Завален горизонт? Используйте ползунок для выравнивания.",
      stepsTag: "РАБОЧИЙ ПРОЦЕСС",
      stepsTitle: "Ориентация за 3 шага",
      s1Title: "Загрузить",
      s1Desc: "Добавьте изображения, которые нужно исправить.",
      s2Title: "Настроить",
      s2Desc: "Используйте кнопки вращения и отражения.",
      s3Title: "Сохранить",
      s3Desc: "Скачайте исправленные изображения."
    },
    picker: {
      heroBadge: "ТОЧНОСТЬ ДО ПИКСЕЛЯ",
      heroTitle: "Извлекайте идеальные цвета.",
      heroTitle2: "Создавайте потрясающие палитры.",
      heroDesc: "Загрузите изображение и наведите курсор, чтобы узнать HEX, RGB и HSL коды любого пикселя.",
      feat1Title: "Микроскопические детали",
      feat1Desc: "Встроенная лупа позволяет рассмотреть отдельные пиксели.",
      feat2Title: "Множество форматов",
      feat2Desc: "Мгновенно получайте цвета в форматах HEX, RGB и HSL. Кликните, чтобы скопировать.",
      feat3Title: "Авто-генерация палитр",
      feat3Desc: "Наш ИИ-алгоритм анализирует изображение и автоматически генерирует гармоничную палитру из 5 цветов.",
      stepsTag: "РАБОЧИЙ ПРОЦЕСС",
      stepsTitle: "Извлечь за 3 шага",
      s1Title: "Загрузить",
      s1Desc: "Загрузите референсное изображение.",
      s2Title: "Выбрать",
      s2Desc: "Наведите курсор на любой пиксель и кликните.",
      s3Title: "Копировать",
      s3Desc: "Мгновенно скопируйте значения HEX/RGB."
    }
  },
  sv: {
    design: {
      heroBadge: "KREATIV SUIT",
      heroTitle: "Designa vackra bilder.",
      heroTitle2: "Direkt i din webbläsare.",
      heroDesc: "En fullfjädrad bildredigerare med pro-filter, textverktyg, former och ritmöjligheter. Ingen installation krävs.",
      feat1Title: "Rik Typografi",
      feat1Desc: "Lägg till egna textlager, välj från hundratals webbteckensnitt.",
      feat2Title: "Pro Filter",
      feat2Desc: "Använd filmisk färgkorrigering och professionella justeringar.",
      feat3Title: "Vektorformer",
      feat3Desc: "Rita geometriska former och pilar med precision.",
      feat4Title: "Lagerhantering",
      feat4Desc: "Organisera komplexa designer. Gruppera och lås flera lager.",
      stepsTag: "ARBETSFLÖDE",
      stepsTitle: "Skapa i 3 steg",
      s1Title: "Starta duken",
      s1Desc: "Öppna en blank duk eller importera ett foto.",
      s2Title: "Designa",
      s2Desc: "Lägg till text, grafik och filter.",
      s3Title: "Exportera",
      s3Desc: "Ladda ner ditt mästerverk."
    },
    rotate: {
      heroBadge: "RUMSLIG KONTROLL",
      heroTitle: "Rotera och Vänd.",
      heroTitle2: "Perfekt orientering.",
      heroDesc: "Korrigera sneda bilder, skapa spegeleffekter och finjustera rotation.",
      feat1Title: "Snabba 90° svängar",
      feat1Desc: "Åtgärda sneda bilder direkt. Rotera i steg om 90 grader.",
      feat2Title: "Spegeleffekter",
      feat2Desc: "Vänd bilder horisontellt för selfies eller vertikalt för reflektioner.",
      feat3Title: "Finjustera horisonten",
      feat3Desc: "Använd reglaget för att plana ut en lutande horisont.",
      stepsTag: "ARBETSFLÖDE",
      stepsTitle: "Ändra riktning i 3 steg",
      s1Title: "Ladda upp",
      s1Desc: "Lägg till bilderna du vill fixa.",
      s2Title: "Justera",
      s2Desc: "Använd rotera- och vändknapparna.",
      s3Title: "Spara",
      s3Desc: "Ladda ner de korrigerade bilderna."
    },
    picker: {
      heroBadge: "PIXELPRECISION",
      heroTitle: "Extrahera perfekta färger.",
      heroTitle2: "Bygg fantastiska paletter.",
      heroDesc: "Ladda upp en bild och hitta HEX, RGB och HSL-koder direkt.",
      feat1Title: "Mikroskopiska detaljer",
      feat1Desc: "Det inbyggda förstoringsglaset låter dig zooma in på pixlar.",
      feat2Title: "Flera format",
      feat2Desc: "Få dina färger i HEX, RGB och HSL. Klicka för att kopiera.",
      feat3Title: "Generera paletter",
      feat3Desc: "Vår AI analyserar bilden och skapar en femfärgs-palett.",
      stepsTag: "ARBETSFLÖDE",
      stepsTitle: "Extrahera i 3 steg",
      s1Title: "Ladda upp",
      s1Desc: "Ladda din referensbild.",
      s2Title: "Välj",
      s2Desc: "För musen över en pixel och klicka.",
      s3Title: "Kopiera",
      s3Desc: "Kopiera färgkoderna direkt."
    }
  },
  th: {
    design: {
      heroBadge: "ชุดเครื่องมือสร้างสรรค์",
      heroTitle: "ออกแบบภาพที่สวยงาม",
      heroTitle2: "จากเบราว์เซอร์ของคุณโดยตรง",
      heroDesc: "โปรแกรมแก้ไขภาพเต็มรูปแบบที่มีฟิลเตอร์ระดับมืออาชีพ เครื่องมือข้อความ รูปร่าง และการวาดภาพ",
      feat1Title: "ตัวอักษรที่หลากหลาย",
      feat1Desc: "เพิ่มเลเยอร์ข้อความ เลือกแบบอักษรนับร้อย พร้อมเพิ่มเงาและการไล่ระดับสี",
      feat2Title: "ฟิลเตอร์ระดับโปร",
      feat2Desc: "ใช้การปรับสีระดับภาพยนตร์และปรับแต่งแบบมืออาชีพ",
      feat3Title: "รูปร่างเวกเตอร์",
      feat3Desc: "วาดรูปทรงเรขาคณิต ลูกศร และเส้นขอบได้อย่างแม่นยำ",
      feat4Title: "การจัดการเลเยอร์",
      feat4Desc: "จัดระเบียบงานออกแบบที่ซับซ้อน จัดกลุ่ม ซ่อน และล็อกเลเยอร์",
      stepsTag: "ขั้นตอนการทำงาน",
      stepsTitle: "สร้างใน 3 ขั้นตอน",
      s1Title: "เริ่มต้นใช้งาน",
      s1Desc: "เปิดแคนวาสเปล่า หรือ นำเข้าภาพ",
      s2Title: "ออกแบบ",
      s2Desc: "เพิ่มข้อความ กราฟิก และฟิลเตอร์",
      s3Title: "ส่งออก",
      s3Desc: "ดาวน์โหลดผลงานชิ้นเอกของคุณ"
    },
    rotate: {
      heroBadge: "การควบคุมทิศทาง",
      heroTitle: "หมุนและพลิก",
      heroTitle2: "ทิศทางที่สมบูรณ์แบบ",
      heroDesc: "แก้ไขภาพที่ถ่ายกลับหัว สร้างเอฟเฟกต์สะท้อน และปรับองศาการหมุนภาพอย่างแม่นยำ",
      feat1Title: "หมุน 90° อย่างรวดเร็ว",
      feat1Desc: "แก้ไขภาพที่ผิดทิศทางได้ทันที หมุนซ้ายหรือขวาครั้งละ 90 องศา",
      feat2Title: "เอฟเฟกต์กระจก",
      feat2Desc: "พลิกภาพแนวนอนเพื่อแก้ไขเซลฟี่ หรือแนวตั้งเพื่อการสะท้อนที่สร้างสรรค์",
      feat3Title: "ปรับระดับขอบฟ้า",
      feat3Desc: "ภาพวิวเอียงเหรอ? ใช้แถบเลื่อนเพื่อปรับขอบฟ้าให้ตรง",
      stepsTag: "ขั้นตอนการทำงาน",
      stepsTitle: "ปรับทิศทางใน 3 ขั้นตอน",
      s1Title: "อัปโหลด",
      s1Desc: "เพิ่มรูปภาพที่ต้องการแก้ไข",
      s2Title: "ปรับ",
      s2Desc: "ใช้ปุ่มหมุนและพลิก",
      s3Title: "บันทึก",
      s3Desc: "ดาวน์โหลดภาพที่แก้ไขแล้ว"
    },
    picker: {
      heroBadge: "ความแม่นยำระดับพิกเซล",
      heroTitle: "ดึงสีที่สมบูรณ์แบบ",
      heroTitle2: "สร้างพาเลตสีที่น่าทึ่ง",
      heroDesc: "อัปโหลดรูปภาพและชี้เมาส์เพื่อดูรหัส HEX, RGB และ HSL ของพิกเซลใดก็ได้",
      feat1Title: "รายละเอียดระดับไมโคร",
      feat1Desc: "แว่นขยายในตัวช่วยให้คุณซูมดูพิกเซลทีละจุดได้",
      feat2Title: "หลากหลายรูปแบบ",
      feat2Desc: "แปลงสีของคุณเป็นรูปแบบ HEX, RGB และ HSL ทันที คลิกเพื่อคัดลอก",
      feat3Title: "สร้างพาเลตสีอัตโนมัติ",
      feat3Desc: "ระบบ AI ของเราจะวิเคราะห์ภาพของคุณและสร้างพาเลต 5 สีที่เข้ากันโดยอัตโนมัติ",
      stepsTag: "ขั้นตอนการทำงาน",
      stepsTitle: "แยกสีใน 3 ขั้นตอน",
      s1Title: "อัปโหลด",
      s1Desc: "โหลดรูปภาพอ้างอิงของคุณ",
      s2Title: "เลือก",
      s2Desc: "เลื่อนเมาส์ไปที่พิกเซลใดๆ แล้วคลิก",
      s3Title: "คัดลอก",
      s3Desc: "คัดลอกค่า HEX/RGB ทันที"
    }
  },
  tl: {
    design: {
      heroBadge: "CREATIVE SUITE",
      heroTitle: "Mag-disenyo ng magagandang visual.",
      heroTitle2: "Direkta sa iyong browser.",
      heroDesc: "Isang ganap na image editor na may pro filters, text tools, shapes, at drawing capabilities.",
      feat1Title: "Mayamang Tipograpiya",
      feat1Desc: "Magdagdag ng custom text layers, pumili mula sa daan-daang web fonts.",
      feat2Title: "Pro Filters",
      feat2Desc: "Ilapat ang cinematic color grading at propesyonal na adjustments.",
      feat3Title: "Vector Shapes",
      feat3Desc: "Gumuhit ng geometric shapes at mga arrow na may katumpakan.",
      feat4Title: "Pamamahala ng Layers",
      feat4Desc: "Ayusin ang mga komplikadong disenyo. I-group, itago, at i-lock ang mga layer.",
      stepsTag: "WORKFLOW",
      stepsTitle: "Lumikha sa 3 Hakbang",
      s1Title: "Magsimula",
      s1Desc: "Magbukas ng blangkong canvas o mag-import ng litrato.",
      s2Title: "Disenyo",
      s2Desc: "Magdagdag ng text, graphics, at filters.",
      s3Title: "I-export",
      s3Desc: "I-download ang iyong obra maestra."
    },
    rotate: {
      heroBadge: "SPATIAL CONTROL",
      heroTitle: "Ikot at I-flip.",
      heroTitle2: "Perpektong Oryentasyon.",
      heroDesc: "Ayusin ang tabinging mga larawan, gumawa ng mirror effects, at i-adjust ang pag-ikot nang eksakto.",
      feat1Title: "Mabilisang 90° Turns",
      feat1Desc: "Ayusin agad ang maling direksyon ng litrato sa pamamagitan ng pag-ikot.",
      feat2Title: "Mirror Effects",
      feat2Desc: "I-flip ang larawan pahalang para sa selfies, o patayo para sa repleksyon.",
      feat3Title: "I-adjust ang Horizon",
      feat3Desc: "May tabing tabing litrato ng tanawin? Gamitin ang slider upang pantayin.",
      stepsTag: "WORKFLOW",
      stepsTitle: "I-adjust sa 3 Hakbang",
      s1Title: "Mag-upload",
      s1Desc: "Idagdag ang larawang aayusin.",
      s2Title: "Ayusin",
      s2Desc: "Gamitin ang rotate at flip buttons.",
      s3Title: "I-save",
      s3Desc: "I-download ang mga naayos na larawan."
    },
    picker: {
      heroBadge: "PIXEL PRECISION",
      heroTitle: "Kumuha ng perpektong kulay.",
      heroTitle2: "Bumuo ng magagandang palette.",
      heroDesc: "Mag-upload ng larawan at i-hover para makuha ang HEX, RGB, at HSL codes.",
      feat1Title: "Microscopic na Detalye",
      feat1Desc: "Pinapayagan ka ng magnifying glass na i-zoom in ang mga indibidwal na pixel.",
      feat2Title: "Maramihang Formats",
      feat2Desc: "Makuha ang kulay mo sa HEX, RGB, at HSL. I-click para kopyahin.",
      feat3Title: "Awtomatikong Palettes",
      feat3Desc: "Inaanalisa ng AI namin ang larawan para gumawa ng 5-color palette.",
      stepsTag: "WORKFLOW",
      stepsTitle: "Kumuha sa 3 Hakbang",
      s1Title: "Mag-upload",
      s1Desc: "I-load ang iyong reference image.",
      s2Title: "Pumili",
      s2Desc: "I-hover sa anumang pixel at i-click.",
      s3Title: "Kopyahin",
      s3Desc: "Kopyahin agad ang HEX/RGB values."
    }
  },
  tr: {
    design: {
      heroBadge: "YARATICI PAKET",
      heroTitle: "Harika görseller tasarlayın.",
      heroTitle2: "Doğrudan tarayıcınızda.",
      heroDesc: "Profesyonel filtreler, metin araçları, şekiller ve çizim yetenekleri ile tam özellikli bir resim düzenleyici.",
      feat1Title: "Zengin Tipografi",
      feat1Desc: "Özel metin katmanları ekleyin, yüzlerce yazı tipinden seçim yapın ve gölgelerle şekillendirin.",
      feat2Title: "Pro Filtreler",
      feat2Desc: "Sinematik renk derecelendirme ve profesyonel ayarlamalar uygulayın.",
      feat3Title: "Vektör Şekilleri",
      feat3Desc: "Geometrik şekiller, oklar ve kenarlıkları hassasiyetle çizin.",
      feat4Title: "Katman Yönetimi",
      feat4Desc: "Karmaşık tasarımları kolayca düzenleyin. Çoklu katmanları gruplayın, gizleyin ve kilitleyin.",
      stepsTag: "İŞ AKIŞI",
      stepsTitle: "3 Adımda Oluşturun",
      s1Title: "Başlat",
      s1Desc: "Boş bir tuval açın veya bir fotoğraf içe aktarın.",
      s2Title: "Tasarla",
      s2Desc: "Metin, grafik ve filtre ekleyin.",
      s3Title: "Dışa Aktar",
      s3Desc: "Şaheserinizi indirin."
    },
    rotate: {
      heroBadge: "UZAYSAL KONTROL",
      heroTitle: "Döndür ve Çevir.",
      heroTitle2: "Mükemmel Yönlendirme.",
      heroDesc: "Yan çekilmiş fotoğrafları düzeltin, ayna efektleri oluşturun ve dönüşü ince ayarlayın.",
      feat1Title: "Hızlı 90° Dönüşler",
      feat1Desc: "Yanlış yöndeki fotoğrafları anında düzeltin. Sağa veya sola 90 derece döndürün.",
      feat2Title: "Ayna Efektleri",
      feat2Desc: "Selfie'leri düzeltmek için yatay, yansımalar için dikey çevirin.",
      feat3Title: "Ufuk Çizgisini Ayarla",
      feat3Desc: "Eğik bir manzara fotoğrafınız mı var? Ufuk çizgisini düzleştirmek için kaydırıcıyı kullanın.",
      stepsTag: "İŞ AKIŞI",
      stepsTitle: "3 Adımda Yönlendir",
      s1Title: "Yükle",
      s1Desc: "Düzeltmek istediğiniz resimleri ekleyin.",
      s2Title: "Ayarla",
      s2Desc: "Döndürme ve çevirme düğmelerini kullanın.",
      s3Title: "Kaydet",
      s3Desc: "Düzeltilmiş görüntüleri indirin."
    },
    picker: {
      heroBadge: "PİKSEL HASSASİYETİ",
      heroTitle: "Mükemmel renkleri çıkarın.",
      heroTitle2: "Harika paletler oluşturun.",
      heroDesc: "Bir resim yükleyin ve herhangi bir pikselin HEX, RGB ve HSL kodlarını öğrenmek için üzerine gelin.",
      feat1Title: "Mikroskobik Detay",
      feat1Desc: "Dahili büyüteç, tekil piksellere yakınlaştırmanıza olanak tanır.",
      feat2Title: "Çoklu Formatlar",
      feat2Desc: "Renklerinizi anında HEX, RGB ve HSL formatlarında alın. Kopyalamak için tıklayın.",
      feat3Title: "Otomatik Palet Oluşturucu",
      feat3Desc: "Yapay zeka algoritmamız resminizi analiz eder ve otomatik olarak 5 renkli bir palet oluşturur.",
      stepsTag: "İŞ AKIŞI",
      stepsTitle: "3 Adımda Çıkarın",
      s1Title: "Yükle",
      s1Desc: "Referans resminizi yükleyin.",
      s2Title: "Seç",
      s2Desc: "Bir pikselin üzerine gelin ve tıklayın.",
      s3Title: "Kopyala",
      s3Desc: "HEX/RGB değerlerini anında kopyalayın."
    }
  },
  uk: {
    design: {
      heroBadge: "КРЕАТИВНИЙ НАБІР",
      heroTitle: "Створюйте красивий дизайн.",
      heroTitle2: "Прямо у вашому браузері.",
      heroDesc: "Повнофункціональний редактор зображень з професійними фільтрами, текстовими інструментами, фігурами та малюванням.",
      feat1Title: "Багата типографіка",
      feat1Desc: "Додавайте власні текстові шари, обирайте із сотень веб-шрифтів.",
      feat2Title: "Професійні фільтри",
      feat2Desc: "Застосовуйте кінематографічну корекцію кольорів.",
      feat3Title: "Векторні фігури",
      feat3Desc: "З точністю малюйте геометричні фігури, стрілки та межі.",
      feat4Title: "Управління шарами",
      feat4Desc: "Впорядковуйте складний дизайн. Групуйте, приховуйте та блокуйте шари.",
      stepsTag: "РОБОЧИЙ ПРОЦЕС",
      stepsTitle: "Створіть за 3 кроки",
      s1Title: "Почати",
      s1Desc: "Відкрийте порожнє полотно або імпортуйте фото.",
      s2Title: "Дизайн",
      s2Desc: "Додайте текст, графіку та фільтри.",
      s3Title: "Експорт",
      s3Desc: "Завантажте свій шедевр."
    },
    rotate: {
      heroBadge: "ПРОСТОРОВИЙ КОНТРОЛЬ",
      heroTitle: "Обертання та віддзеркалення.",
      heroTitle2: "Ідеальна орієнтація.",
      heroDesc: "Виправляйте перевернуті фото, створюйте дзеркальні ефекти та точно налаштовуйте обертання.",
      feat1Title: "Швидкі обертання на 90°",
      feat1Desc: "Миттєво виправляйте фотографії. Обертайте вліво або вправо на 90 градусів.",
      feat2Title: "Дзеркальні ефекти",
      feat2Desc: "Віддзеркалюйте зображення горизонтально для селфі або вертикально.",
      feat3Title: "Точне налаштування горизонту",
      feat3Desc: "Завалений горизонт? Використовуйте повзунок для вирівнювання.",
      stepsTag: "РОБОЧИЙ ПРОЦЕС",
      stepsTitle: "Орієнтація за 3 кроки",
      s1Title: "Завантажити",
      s1Desc: "Додайте зображення, які потрібно виправити.",
      s2Title: "Налаштувати",
      s2Desc: "Використовуйте кнопки обертання та віддзеркалення.",
      s3Title: "Зберегти",
      s3Desc: "Завантажте виправлені зображення."
    },
    picker: {
      heroBadge: "ТОЧНІСТЬ ДО ПІКСЕЛЯ",
      heroTitle: "Витягуйте ідеальні кольори.",
      heroTitle2: "Створюйте чудові палітри.",
      heroDesc: "Завантажте зображення та наведіть курсор, щоб дізнатися коди HEX, RGB та HSL.",
      feat1Title: "Мікроскопічні деталі",
      feat1Desc: "Вбудована лупа дозволяє роздивитися окремі пікселі.",
      feat2Title: "Безліч форматів",
      feat2Desc: "Миттєво отримуйте кольори у форматах HEX, RGB та HSL. Натисніть, щоб скопіювати.",
      feat3Title: "Автоматичні палітри",
      feat3Desc: "Наш ШІ-алгоритм аналізує зображення і автоматично генерує палітру з 5 кольорів.",
      stepsTag: "РОБОЧИЙ ПРОЦЕС",
      stepsTitle: "Витягти за 3 кроки",
      s1Title: "Завантажити",
      s1Desc: "Завантажте референсне зображення.",
      s2Title: "Вибрати",
      s2Desc: "Наведіть курсор на піксель і натисніть.",
      s3Title: "Копіювати",
      s3Desc: "Миттєво скопіюйте значення HEX/RGB."
    }
  },
  vi: {
    design: {
      heroBadge: "BỘ CÔNG CỤ SÁNG TẠO",
      heroTitle: "Thiết kế hình ảnh tuyệt đẹp.",
      heroTitle2: "Ngay trong trình duyệt của bạn.",
      heroDesc: "Trình chỉnh sửa ảnh đầy đủ tính năng với bộ lọc chuyên nghiệp, công cụ văn bản, hình khối và vẽ. Không cần cài đặt phần mềm.",
      feat1Title: "Kiểu chữ phong phú",
      feat1Desc: "Thêm các lớp văn bản tùy chỉnh, chọn từ hàng trăm phông chữ web và tạo bóng đổ.",
      feat2Title: "Bộ lọc Pro",
      feat2Desc: "Áp dụng phân loại màu điện ảnh và các điều chỉnh chuyên nghiệp.",
      feat3Title: "Hình khối Vector",
      feat3Desc: "Vẽ các hình học, mũi tên và viền với độ chính xác cao.",
      feat4Title: "Quản lý Lớp (Layer)",
      feat4Desc: "Dễ dàng sắp xếp các thiết kế phức tạp. Nhóm, ẩn và khóa nhiều lớp.",
      stepsTag: "QUY TRÌNH",
      stepsTitle: "Tạo trong 3 bước",
      s1Title: "Bắt đầu",
      s1Desc: "Mở khung vẽ trống hoặc nhập ảnh.",
      s2Title: "Thiết kế",
      s2Desc: "Thêm văn bản, đồ họa và bộ lọc.",
      s3Title: "Xuất file",
      s3Desc: "Tải xuống kiệt tác của bạn."
    },
    rotate: {
      heroBadge: "KIỂM SOÁT KHÔNG GIAN",
      heroTitle: "Xoay và Lật ảnh.",
      heroTitle2: "Định hướng hoàn hảo.",
      heroDesc: "Sửa ảnh chụp ngang, tạo hiệu ứng phản chiếu và tinh chỉnh xoay ảnh theo độ chính xác.",
      feat1Title: "Xoay 90° nhanh chóng",
      feat1Desc: "Khắc phục ngay lập tức ảnh sai hướng. Xoay trái hoặc phải theo từng bước 90 độ.",
      feat2Title: "Hiệu ứng gương",
      feat2Desc: "Lật ngang ảnh để sửa ảnh tự chụp hoặc lật dọc để tạo hiệu ứng phản chiếu sáng tạo.",
      feat3Title: "Tinh chỉnh đường chân trời",
      feat3Desc: "Ảnh phong cảnh bị nghiêng? Sử dụng thanh trượt để san bằng đường chân trời.",
      stepsTag: "QUY TRÌNH",
      stepsTitle: "Định hướng lại trong 3 bước",
      s1Title: "Tải lên",
      s1Desc: "Thêm hình ảnh bạn muốn sửa.",
      s2Title: "Điều chỉnh",
      s2Desc: "Sử dụng nút xoay và lật.",
      s3Title: "Lưu lại",
      s3Desc: "Tải xuống hình ảnh đã sửa."
    },
    picker: {
      heroBadge: "ĐỘ CHÍNH XÁC PIXEL",
      heroTitle: "Trích xuất màu sắc hoàn hảo.",
      heroTitle2: "Tạo bảng màu tuyệt đẹp.",
      heroDesc: "Tải ảnh lên và di chuột để xác định mã HEX, RGB và HSL của bất kỳ pixel nào.",
      feat1Title: "Chi tiết siêu nhỏ",
      feat1Desc: "Kính lúp tích hợp cho phép bạn phóng to từng pixel riêng lẻ.",
      feat2Title: "Nhiều định dạng",
      feat2Desc: "Màu của bạn ngay lập tức được chuyển đổi sang định dạng HEX, RGB và HSL. Bấm để sao chép.",
      feat3Title: "Tự động tạo bảng màu",
      feat3Desc: "Thuật toán AI của chúng tôi phân tích ảnh của bạn và tự động tạo bảng 5 màu hài hòa.",
      stepsTag: "QUY TRÌNH",
      stepsTitle: "Trích xuất trong 3 bước",
      s1Title: "Tải lên",
      s1Desc: "Tải hình ảnh tham chiếu của bạn.",
      s2Title: "Chọn",
      s2Desc: "Di chuột qua pixel và nhấp để lấy.",
      s3Title: "Sao chép",
      s3Desc: "Sao chép giá trị HEX/RGB ngay lập tức."
    }
  },
  zh: {
    design: {
      heroBadge: "创意套件",
      heroTitle: "设计精美的视觉效果。",
      heroTitle2: "就在您的浏览器中。",
      heroDesc: "全功能图像编辑器，包含专业滤镜、文本工具、形状和绘图功能。无需安装软件。",
      feat1Title: "丰富的排版",
      feat1Desc: "添加自定义文本图层，从数百种网页字体中选择，并添加阴影和渐变。",
      feat2Title: "专业滤镜",
      feat2Desc: "应用电影级调色和专业色彩调整。",
      feat3Title: "矢量形状",
      feat3Desc: "精确绘制几何形状、箭头和边框。",
      feat4Title: "图层管理",
      feat4Desc: "轻松组织复杂的设计。堆叠、分组、隐藏和锁定多个图层。",
      stepsTag: "工作流程",
      stepsTitle: "只需3步即可创建",
      s1Title: "开始画布",
      s1Desc: "打开空白画布或导入照片。",
      s2Title: "设计",
      s2Desc: "添加文本、图形并应用滤镜。",
      s3Title: "导出",
      s3Desc: "下载您的最终杰作。"
    },
    rotate: {
      heroBadge: "空间控制",
      heroTitle: "旋转和翻转。",
      heroTitle2: "完美的出图方向。",
      heroDesc: "校正横向照片，创建镜像效果，并精确微调图像旋转。快速，免费。",
      feat1Title: "快速90°旋转",
      feat1Desc: "立即修复方向错误的照片。以90度为增量向左或向右旋转。",
      feat2Title: "镜像效果",
      feat2Desc: "水平翻转图像以修复自拍，或垂直翻转以获得创意的倒影效果。",
      feat3Title: "微调地平线",
      feat3Desc: "有一张歪斜的风景照？使用滑块来拉平地平线。",
      stepsTag: "工作流程",
      stepsTitle: "只需3步即可调整",
      s1Title: "上传",
      s1Desc: "添加您要修复的图像。",
      s2Title: "调整",
      s2Desc: "使用旋转和翻转按钮。",
      s3Title: "保存",
      s3Desc: "下载校正后的图像。"
    },
    picker: {
      heroBadge: "像素精度",
      heroTitle: "提取完美的色彩。",
      heroTitle2: "构建令人惊叹的色板。",
      heroDesc: "上传图像并悬停，即可精确获取任何像素的HEX、RGB和HSL代码。立即生成调色板。",
      feat1Title: "微观细节",
      feat1Desc: "内置的放大镜可让您放大单个像素。",
      feat2Title: "多种格式",
      feat2Desc: "将颜色立即转换为HEX、RGB和HSL格式。点击复制。",
      feat3Title: "自动生成色板",
      feat3Desc: "我们的AI算法会分析您的图像，并自动生成由5种颜色组成的调色板。",
      stepsTag: "工作流程",
      stepsTitle: "只需3步即可提取",
      s1Title: "上传",
      s1Desc: "加载您的参考图像。",
      s2Title: "选择",
      s2Desc: "将鼠标悬停在任何像素上并点击即可捕获。",
      s3Title: "复制",
      s3Desc: "立即复制HEX/RGB值。"
    }
  }
};

const keys = ['ms','nl','no','pl','pt','ro','ru','sv','th','tl','tr','uk','vi','zh'];

keys.forEach(lang => {
  const filePath = path.join(localesDir, lang, 'translation.json');
  if (fs.existsSync(filePath)) {
    const content = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    
    if (!content.landing) content.landing = {};
    
    // Inject design
    if (!content.landing.design) content.landing.design = {};
    content.landing.design.redesign = translations[lang].design;

    // Inject rotate
    if (!content.landing.rotate) content.landing.rotate = {};
    content.landing.rotate.redesign = translations[lang].rotate;

    // Inject picker
    if (!content.landing.picker) content.landing.picker = {};
    content.landing.picker.redesign = translations[lang].picker;

    fs.writeFileSync(filePath, JSON.stringify(content, null, 2));
    console.log(`[${lang}] Successfully injected DRP part 2`);
  }
});
