const fs = require('fs');
const path = require('path');

const translations = {
  id: {
    "landing.global.faq.title": "Pertanyaan yang Sering Diajukan",
    "landing.global.faq.desc": "Semua yang perlu Anda ketahui tentang mesin pemrosesan lokal kami.",
    "landing.remove.faq1.q": "Apakah penghapusan latar belakang benar-benar diproses offline?",
    "landing.remove.faq1.a": "Ya. Model AI kami dimuat ke dalam memori browser Anda, sehingga seluruh deteksi latar belakang terjadi di CPU/GPU Anda, memastikan privasi penuh.",
    "landing.remove.faq2.q": "Apakah resolusi gambar akan berkurang?",
    "landing.remove.faq2.a": "Tidak, kami mempertahankan resolusi gambar asli Anda. Potongan dihasilkan dan digabungkan dengan piksel definisi tinggi asli Anda.",
    "landing.remove.faq3.q": "Apakah ini berfungsi dengan baik untuk tepi rambut yang rumit?",
    "landing.remove.faq3.a": "Tentu saja. Model AI WebAssembly secara khusus dilatih untuk menangani detail halus seperti rambut, bulu, dan objek semi-transparan.",
    "landing.remove.faq4.q": "Apakah ada batasan berapa banyak gambar yang bisa saya proses?",
    "landing.remove.faq4.a": "Karena semuanya berjalan di perangkat Anda sendiri, kami tidak memiliki biaya server. Oleh karena itu, Anda dapat memproses gambar tanpa batas sepenuhnya gratis.",
    "landing.compress.faq1.q": "Bagaimana cara kerja kompresi offline?",
    "landing.compress.faq1.a": "Kami menggunakan rendering Canvas lokal dan algoritma kompresi WebAssembly untuk mengecilkan ukuran file langsung di browser Anda tanpa unggahan jaringan apa pun.",
    "landing.compress.faq2.q": "Bisakah saya mengompres banyak foto sekaligus?",
    "landing.compress.faq2.a": "Ya, Anda dapat menjatuhkan hingga 10 foto secara bersamaan. Mesin lokal akan mengompresnya sekaligus dan mengekspornya sebagai satu file ZIP.",
    "landing.compress.faq3.q": "Apakah kualitasnya akan terlihat menurun?",
    "landing.compress.faq3.a": "Algoritma kami menggunakan kompresi tanpa kehilangan secara visual, yang berarti ukuran file menyusut hingga 90% sementara kualitas visualnya tetap identik bagi mata manusia.",
    "landing.compress.faq4.q": "Apakah ini aman untuk foto ID rahasia?",
    "landing.compress.faq4.a": "100% aman. Foto ID dan paspor Anda tidak pernah meninggalkan perangkat Anda. Kompresi terjadi sepenuhnya di dalam kotak pasir yang aman di browser web Anda."
  },
  zh: {
    "landing.global.faq.title": "常见问题解答",
    "landing.global.faq.desc": "关于我们本地处理引擎您需要知道的一切。",
    "landing.remove.faq1.q": "背景去除真的是离线处理的吗？",
    "landing.remove.faq1.a": "是的。我们的 AI 模型会加载到您浏览器的内存中，因此整个背景检测都在您的 CPU/GPU 上发生，确保完全的隐私。",
    "landing.remove.faq2.q": "图像分辨率会降低吗？",
    "landing.remove.faq2.a": "不会，我们保留您原始的图像分辨率。抠图会生成并与您原始的高清像素合并。",
    "landing.remove.faq3.q": "它处理复杂的头发边缘效果好吗？",
    "landing.remove.faq3.a": "绝对好。WebAssembly AI 模型经过专门训练，可以抠出头发、毛皮和半透明物体等精细细节。",
    "landing.remove.faq4.q": "我可以处理的图像数量有限制吗？",
    "landing.remove.faq4.a": "由于一切都在您自己的设备上运行，我们没有任何服务器成本。因此，您可以完全免费地处理无限量的图像。",
    "landing.compress.faq1.q": "离线压缩是如何工作的？",
    "landing.compress.faq1.a": "我们使用本地 Canvas 渲染和 WebAssembly 压缩算法直接在您的浏览器上缩小文件大小，没有任何网络上传。",
    "landing.compress.faq2.q": "我可以批量压缩照片吗？",
    "landing.compress.faq2.a": "可以，您最多可以同时拖放 10 张照片。本地引擎会一次性压缩它们，并将它们导出为一个 ZIP 文件。",
    "landing.compress.faq3.q": "质量会明显下降吗？",
    "landing.compress.faq3.a": "我们的算法使用感知无损压缩，这意味着文件大小最多缩小 90%，而视觉质量对人眼来说保持不变。",
    "landing.compress.faq4.q": "这对于机密证件照安全吗？",
    "landing.compress.faq4.a": "100% 安全。您的身份证和护照照片永远不会离开您的设备。压缩完全在您网络浏览器的安全沙盒中进行。"
  },
  hi: {
    "landing.global.faq.title": "अक्सर पूछे जाने वाले प्रश्न",
    "landing.global.faq.desc": "हमारे स्थानीय प्रसंस्करण इंजन के बारे में वह सब कुछ जो आपको जानना आवश्यक है।",
    "landing.remove.faq1.q": "क्या पृष्ठभूमि हटाना वास्तव में ऑफ़लाइन संसाधित होता है?",
    "landing.remove.faq1.a": "हाँ। हमारा एआई मॉडल आपके ब्राउज़र की मेमोरी में लोड होता है, इसलिए पूरी पृष्ठभूमि का पता लगाना आपके सीपीयू/जीपीयू पर होता है, जिससे पूर्ण गोपनीयता सुनिश्चित होती है।",
    "landing.remove.faq2.q": "क्या छवि रिज़ॉल्यूशन कम हो जाएगा?",
    "landing.remove.faq2.a": "नहीं, हम आपकी मूल छवि रिज़ॉल्यूशन को सुरक्षित रखते हैं। कटआउट उत्पन्न होता है और आपके मूल हाई-डेफिनिशन पिक्सल के साथ जुड़ जाता है।",
    "landing.remove.faq3.q": "क्या यह बालों के जटिल किनारों के साथ अच्छा काम करता है?",
    "landing.remove.faq3.a": "बिल्कुल। वेबअसेंबली एआई मॉडल विशेष रूप से बालों, फर और अर्ध-पारदर्शी वस्तुओं जैसे बारीक विवरणों को निकालने के लिए प्रशिक्षित है।",
    "landing.remove.faq4.q": "क्या मैं कितनी छवियों को संसाधित कर सकता हूं इसकी कोई सीमा है?",
    "landing.remove.faq4.a": "चूंकि सब कुछ आपके अपने डिवाइस पर चलता है, इसलिए हमारे लिए सर्वर की शून्य लागत है। इसलिए, आप पूरी तरह से मुफ्त में असीमित छवियों को संसाधित कर सकते हैं।",
    "landing.compress.faq1.q": "ऑफ़लाइन संपीड़न कैसे काम करता है?",
    "landing.compress.faq1.a": "हम किसी भी नेटवर्क अपलोड के बिना सीधे आपके ब्राउज़र पर फ़ाइल का आकार कम करने के लिए स्थानीय कैनवास रेंडरिंग और वेबअसेंबली संपीड़न एल्गोरिदम का उपयोग करते हैं।",
    "landing.compress.faq2.q": "क्या मैं तस्वीरों के बैचों को संपीड़ित कर सकता हूं?",
    "landing.compress.faq2.a": "हां, आप एक साथ 10 फ़ोटो छोड़ सकते हैं। स्थानीय इंजन उन सभी को एक ही बार में संपीड़ित करेगा और उन्हें एक ज़िप फ़ाइल के रूप में निर्यात करेगा।",
    "landing.compress.faq3.q": "क्या गुणवत्ता स्पष्ट रूप से कम हो जाएगी?",
    "landing.compress.faq3.a": "हमारे एल्गोरिदम अवधारणात्मक रूप से दोषरहित संपीड़न का उपयोग करते हैं, जिसका अर्थ है कि फ़ाइल का आकार 90% तक सिकुड़ जाता है जबकि दृश्य गुणवत्ता मानव आंख के समान ही रहती है।",
    "landing.compress.faq4.q": "क्या यह गोपनीय आईडी तस्वीरों के लिए सुरक्षित है?",
    "landing.compress.faq4.a": "100% सुरक्षित। आपकी आईडी और पासपोर्ट तस्वीरें कभी भी आपका डिवाइस नहीं छोड़ती हैं। संपीड़न पूरी तरह से आपके वेब ब्राउज़र के सुरक्षित सैंडबॉक्स के अंदर होता है।"
  },
  es: {
    "landing.global.faq.title": "Preguntas Frecuentes",
    "landing.global.faq.desc": "Todo lo que necesita saber sobre nuestro motor de procesamiento local.",
    "landing.remove.faq1.q": "¿La eliminación del fondo realmente se procesa fuera de línea?",
    "landing.remove.faq1.a": "Sí. Nuestro modelo de IA se carga en la memoria de su navegador, por lo que toda la detección de fondo ocurre en su CPU/GPU, asegurando total privacidad.",
    "landing.remove.faq2.q": "¿Se reducirá la resolución de la imagen?",
    "landing.remove.faq2.a": "No, preservamos la resolución original de su imagen. El recorte se genera y se fusiona con sus píxeles originales de alta definición.",
    "landing.remove.faq3.q": "¿Funciona bien con bordes complejos de cabello?",
    "landing.remove.faq3.a": "Absolutamente. El modelo de IA de WebAssembly está entrenado específicamente para extraer detalles finos como cabello, pelaje y objetos semitransparentes.",
    "landing.remove.faq4.q": "¿Hay un límite en la cantidad de imágenes que puedo procesar?",
    "landing.remove.faq4.a": "Dado que todo se ejecuta en su propio dispositivo, no hay costos de servidor para nosotros. Por lo tanto, puede procesar imágenes ilimitadas completamente gratis.",
    "landing.compress.faq1.q": "¿Cómo funciona la compresión sin conexión?",
    "landing.compress.faq1.a": "Utilizamos renderizado local de Canvas y algoritmos de compresión de WebAssembly para reducir el tamaño del archivo directamente en su navegador sin ninguna carga de red.",
    "landing.compress.faq2.q": "¿Puedo comprimir lotes de fotos?",
    "landing.compress.faq2.a": "Sí, puede soltar hasta 10 fotos simultáneamente. El motor local las comprimirá todas a la vez y las exportará como un único archivo ZIP.",
    "landing.compress.faq3.q": "¿Se degradará visiblemente la calidad?",
    "landing.compress.faq3.a": "Nuestros algoritmos utilizan una compresión perceptiblemente sin pérdidas, lo que significa que el tamaño del archivo se reduce hasta en un 90% mientras la calidad visual permanece idéntica al ojo humano.",
    "landing.compress.faq4.q": "¿Es seguro para fotos de identificación confidenciales?",
    "landing.compress.faq4.a": "100% seguro. Sus fotos de identificación y pasaporte nunca salen de su dispositivo. La compresión ocurre completamente dentro de la caja de arena segura de su navegador web."
  },
  ja: {
    "landing.global.faq.title": "よくある質問",
    "landing.global.faq.desc": "当社のローカル処理エンジンについて知っておくべきことすべて。",
    "landing.remove.faq1.q": "背景の削除は本当にオフラインで処理されますか？",
    "landing.remove.faq1.a": "はい。当社のAIモデルはブラウザのメモリに読み込まれるため、背景検出全体がCPU/GPU上で行われ、完全なプライバシーが確保されます。",
    "landing.remove.faq2.q": "画像の解像度は下がりますか？",
    "landing.remove.faq2.a": "いいえ、元の画像解像度を保持します。切り抜きが生成され、元の高精細ピクセルと結合されます。",
    "landing.remove.faq3.q": "複雑な髪の境界でもうまく機能しますか？",
    "landing.remove.faq3.a": "もちろんです。WebAssembly AIモデルは、髪の毛、毛皮、半透明のオブジェクトなどの細かいディテールを切り抜くために特別にトレーニングされています。",
    "landing.remove.faq4.q": "処理できる画像数に制限はありますか？",
    "landing.remove.faq4.a": "すべてご自身のデバイス上で実行されるため、当社側のサーバーコストはゼロです。したがって、無制限の画像を完全無料で処理できます。",
    "landing.compress.faq1.q": "オフライン圧縮はどのように機能しますか？",
    "landing.compress.faq1.a": "ローカルのCanvasレンダリングとWebAssembly圧縮アルゴリズムを使用して、ネットワークにアップロードすることなく、ブラウザ上で直接ファイルサイズを縮小します。",
    "landing.compress.faq2.q": "写真を一括で圧縮できますか？",
    "landing.compress.faq2.a": "はい、最大10枚の写真を同時にドロップできます。ローカルエンジンはそれらを一度に圧縮し、単一のZIPファイルとしてエクスポートします。",
    "landing.compress.faq3.q": "品質は目に見えて低下しますか？",
    "landing.compress.faq3.a": "当社のアルゴリズムは知覚的にロスレスな圧縮を使用します。つまり、ファイルサイズは最大90%縮小しますが、視覚的な品質は人間の目には同じままです。",
    "landing.compress.faq4.q": "機密のID写真でも安全ですか？",
    "landing.compress.faq4.a": "100%安全です。IDやパスポートの写真がデバイスから離れることはありません。圧縮はすべてWebブラウザの安全なサンドボックス内で行われます。"
  },
  pt: {
    "landing.global.faq.title": "Perguntas Frequentes",
    "landing.global.faq.desc": "Tudo o que você precisa saber sobre nosso mecanismo de processamento local.",
    "landing.remove.faq1.q": "A remoção do fundo é realmente processada offline?",
    "landing.remove.faq1.a": "Sim. Nosso modelo de IA é carregado na memória do seu navegador, para que toda a detecção de fundo ocorra na sua CPU/GPU, garantindo total privacidade.",
    "landing.remove.faq2.q": "A resolução da imagem será reduzida?",
    "landing.remove.faq2.a": "Não, nós preservamos a resolução original da sua imagem. O recorte é gerado e mesclado com os pixels originais de alta definição.",
    "landing.remove.faq3.q": "Funciona bem com bordas de cabelo complexas?",
    "landing.remove.faq3.a": "Absolutamente. O modelo de IA WebAssembly é treinado especificamente para separar detalhes finos como cabelo, pelos e objetos semitransparentes.",
    "landing.remove.faq4.q": "Existe um limite de quantas imagens posso processar?",
    "landing.remove.faq4.a": "Como tudo é executado no seu próprio dispositivo, não temos custos com servidores. Portanto, você pode processar imagens ilimitadas totalmente de graça.",
    "landing.compress.faq1.q": "Como funciona a compressão offline?",
    "landing.compress.faq1.a": "Usamos renderização Canvas local e algoritmos de compressão WebAssembly para reduzir o tamanho do arquivo diretamente no seu navegador, sem nenhum upload para a rede.",
    "landing.compress.faq2.q": "Posso comprimir lotes de fotos?",
    "landing.compress.faq2.a": "Sim, você pode soltar até 10 fotos simultaneamente. O mecanismo local vai comprimir todas de uma vez e exportá-las como um único arquivo ZIP.",
    "landing.compress.faq3.q": "A qualidade será visivelmente degradada?",
    "landing.compress.faq3.a": "Nossos algoritmos usam compressão perceptivelmente sem perdas, o que significa que o tamanho do arquivo encolhe em até 90% enquanto a qualidade visual permanece idêntica ao olho humano.",
    "landing.compress.faq4.q": "Isso é seguro para fotos de identificação confidenciais?",
    "landing.compress.faq4.a": "100% seguro. Suas fotos de identidade e passaporte nunca saem do seu dispositivo. A compressão acontece inteiramente dentro da sandbox segura do seu navegador da web."
  },
  ru: {
    "landing.global.faq.title": "Часто задаваемые вопросы",
    "landing.global.faq.desc": "Все, что вам нужно знать о нашем движке локальной обработки.",
    "landing.remove.faq1.q": "Удаление фона действительно происходит в автономном режиме?",
    "landing.remove.faq1.a": "Да. Наша модель ИИ загружается в память вашего браузера, поэтому все обнаружение фона происходит на вашем CPU/GPU, обеспечивая полную конфиденциальность.",
    "landing.remove.faq2.q": "Будет ли снижено разрешение изображения?",
    "landing.remove.faq2.a": "Нет, мы сохраняем исходное разрешение вашего изображения. Вырез создается и объединяется с вашими исходными пикселями высокой четкости.",
    "landing.remove.faq3.q": "Хорошо ли это работает со сложными краями волос?",
    "landing.remove.faq3.a": "Абсолютно. Модель ИИ WebAssembly специально обучена выделять мелкие детали, такие как волосы, мех и полупрозрачные объекты.",
    "landing.remove.faq4.q": "Есть ли ограничение на количество обрабатываемых изображений?",
    "landing.remove.faq4.a": "Поскольку все работает на вашем собственном устройстве, для нас нет затрат на сервер. Поэтому вы можете обрабатывать неограниченное количество изображений совершенно бесплатно.",
    "landing.compress.faq1.q": "Как работает автономное сжатие?",
    "landing.compress.faq1.a": "Мы используем локальный рендеринг Canvas и алгоритмы сжатия WebAssembly для уменьшения размера файла прямо в вашем браузере без каких-либо сетевых загрузок.",
    "landing.compress.faq2.q": "Могу ли я сжимать партии фотографий?",
    "landing.compress.faq2.a": "Да, вы можете одновременно перетащить до 10 фотографий. Локальный движок сожмет их все сразу и экспортирует как один ZIP-файл.",
    "landing.compress.faq3.q": "Будет ли качество заметно ухудшено?",
    "landing.compress.faq3.a": "Наши алгоритмы используют визуально сжатие без потерь, что означает, что размер файла уменьшается до 90%, в то время как визуальное качество остается идентичным для человеческого глаза.",
    "landing.compress.faq4.q": "Безопасно ли это для конфиденциальных фотографий на документы?",
    "landing.compress.faq4.a": "100% безопасно. Ваши фотографии для документов и паспорта никогда не покидают ваше устройство. Сжатие происходит полностью внутри безопасной песочницы вашего веб-браузера."
  },
  ar: {
    "landing.global.faq.title": "الأسئلة الشائعة",
    "landing.global.faq.desc": "كل ما تحتاج لمعرفته حول محرك المعالجة المحلي الخاص بنا.",
    "landing.remove.faq1.q": "هل تتم إزالة الخلفية حقًا في وضع عدم الاتصال؟",
    "landing.remove.faq1.a": "نعم. يتم تحميل نموذج الذكاء الاصطناعي الخاص بنا في ذاكرة متصفحك، لذلك يتم اكتشاف الخلفية بالكامل على وحدة المعالجة المركزية / وحدة معالجة الرسومات الخاصة بك، مما يضمن الخصوصية الكاملة.",
    "landing.remove.faq2.q": "هل سيتم تقليل دقة الصورة؟",
    "landing.remove.faq2.a": "لا، نحن نحافظ على دقة صورتك الأصلية. يتم إنشاء القصاصة ودمجها مع وحدات البكسل الأصلية عالية الدقة.",
    "landing.remove.faq3.q": "هل يعمل بشكل جيد مع حواف الشعر المعقدة؟",
    "landing.remove.faq3.a": "بالتأكيد. يتم تدريب نموذج الذكاء الاصطناعي WebAssembly خصيصًا لفصل التفاصيل الدقيقة مثل الشعر والفراء والأشياء شبه الشفافة.",
    "landing.remove.faq4.q": "هل هناك حد لعدد الصور التي يمكنني معالجتها؟",
    "landing.remove.faq4.a": "نظرًا لأن كل شيء يعمل على جهازك الخاص، فلا توجد تكاليف خادم بالنسبة لنا. لذلك، يمكنك معالجة عدد غير محدود من الصور مجانًا تمامًا.",
    "landing.compress.faq1.q": "كيف يعمل الضغط دون اتصال؟",
    "landing.compress.faq1.a": "نستخدم عرض Canvas المحلي وخوارزميات ضغط WebAssembly لتقليص حجم الملف مباشرة على متصفحك دون أي تحميلات على الشبكة.",
    "landing.compress.faq2.q": "هل يمكنني ضغط دفعات من الصور؟",
    "landing.compress.faq2.a": "نعم، يمكنك إفلات ما يصل إلى 10 صور في وقت واحد. سيقوم المحرك المحلي بضغطها جميعًا مرة واحدة وتصديرها كملف ZIP واحد.",
    "landing.compress.faq3.q": "هل ستتدهور الجودة بشكل واضح؟",
    "landing.compress.faq3.a": "تستخدم خوارزمياتنا ضغطًا غير مفقود إدراكيًا، مما يعني أن حجم الملف يتقلص بنسبة تصل إلى 90٪ بينما تظل الجودة البصرية متطابقة مع العين البشرية.",
    "landing.compress.faq4.q": "هل هذا آمن لصور الهوية السرية؟",
    "landing.compress.faq4.a": "100٪ آمن. صور هويتك وجواز سفرك لا تغادر جهازك أبدًا. يحدث الضغط بالكامل داخل بيئة الاختبار المعزولة الآمنة لمتصفح الويب الخاص بك."
  },
  fr: {
    "landing.global.faq.title": "Foire aux questions",
    "landing.global.faq.desc": "Tout ce que vous devez savoir sur notre moteur de traitement local.",
    "landing.remove.faq1.q": "La suppression de l'arrière-plan est-elle vraiment traitée hors ligne ?",
    "landing.remove.faq1.a": "Oui. Notre modèle d'IA est chargé dans la mémoire de votre navigateur, de sorte que toute la détection d'arrière-plan se produit sur votre CPU/GPU, garantissant une confidentialité totale.",
    "landing.remove.faq2.q": "La résolution de l'image sera-t-elle réduite ?",
    "landing.remove.faq2.a": "Non, nous préservons la résolution d'origine de votre image. La découpe est générée et fusionnée avec vos pixels haute définition d'origine.",
    "landing.remove.faq3.q": "Cela fonctionne-t-il bien avec des bords de cheveux complexes ?",
    "landing.remove.faq3.a": "Absolument. Le modèle d'IA WebAssembly est spécifiquement formé pour détourer les détails fins comme les cheveux, la fourrure et les objets semi-transparents.",
    "landing.remove.faq4.q": "Y a-t-il une limite au nombre d'images que je peux traiter ?",
    "landing.remove.faq4.a": "Étant donné que tout s'exécute sur votre propre appareil, nous n'avons aucun coût de serveur. Par conséquent, vous pouvez traiter un nombre illimité d'images de manière totalement gratuite.",
    "landing.compress.faq1.q": "Comment fonctionne la compression hors ligne ?",
    "landing.compress.faq1.a": "Nous utilisons le rendu Canvas local et les algorithmes de compression WebAssembly pour réduire la taille du fichier directement sur votre navigateur sans aucun téléchargement sur le réseau.",
    "landing.compress.faq2.q": "Puis-je compresser des lots de photos ?",
    "landing.compress.faq2.a": "Oui, vous pouvez déposer jusqu'à 10 photos simultanément. Le moteur local les compressera toutes en même temps et les exportera sous la forme d'un seul fichier ZIP.",
    "landing.compress.faq3.q": "La qualité sera-t-elle visiblement dégradée ?",
    "landing.compress.faq3.a": "Nos algorithmes utilisent une compression perceptuellement sans perte, ce qui signifie que la taille du fichier diminue jusqu'à 90 % tandis que la qualité visuelle reste identique à l'œil humain.",
    "landing.compress.faq4.q": "Est-ce sûr pour les photos d'identité confidentielles ?",
    "landing.compress.faq4.a": "100 % sûr. Vos photos d'identité et de passeport ne quittent jamais votre appareil. La compression s'effectue entièrement dans le bac à sable sécurisé de votre navigateur Web."
  },
  de: {
    "landing.global.faq.title": "Häufig gestellte Fragen",
    "landing.global.faq.desc": "Alles, was Sie über unsere lokale Verarbeitungs-Engine wissen müssen.",
    "landing.remove.faq1.q": "Wird die Hintergrundentfernung wirklich offline verarbeitet?",
    "landing.remove.faq1.a": "Ja. Unser KI-Modell wird in den Speicher Ihres Browsers geladen, sodass die gesamte Hintergrunderkennung auf Ihrer CPU/GPU stattfindet und vollständige Privatsphäre gewährleistet ist.",
    "landing.remove.faq2.q": "Wird die Bildauflösung verringert?",
    "landing.remove.faq2.a": "Nein, wir erhalten Ihre ursprüngliche Bildauflösung. Der Ausschnitt wird generiert und mit Ihren ursprünglichen hochauflösenden Pixeln zusammengeführt.",
    "landing.remove.faq3.q": "Funktioniert es gut bei komplexen Haaransätzen?",
    "landing.remove.faq3.a": "Absolut. Das WebAssembly-KI-Modell ist speziell darauf trainiert, feine Details wie Haare, Fell und halbtransparente Objekte freizustellen.",
    "landing.remove.faq4.q": "Gibt es ein Limit, wie viele Bilder ich verarbeiten kann?",
    "landing.remove.faq4.a": "Da alles auf Ihrem eigenen Gerät ausgeführt wird, entstehen uns keine Serverkosten. Daher können Sie unbegrenzt Bilder völlig kostenlos verarbeiten.",
    "landing.compress.faq1.q": "Wie funktioniert die Offline-Komprimierung?",
    "landing.compress.faq1.a": "Wir verwenden lokales Canvas-Rendering und WebAssembly-Komprimierungsalgorithmen, um die Dateigröße direkt in Ihrem Browser ohne Netzwerk-Uploads zu verkleinern.",
    "landing.compress.faq2.q": "Kann ich ganze Stapel von Fotos komprimieren?",
    "landing.compress.faq2.a": "Ja, Sie können bis zu 10 Fotos gleichzeitig ablegen. Die lokale Engine komprimiert sie alle auf einmal und exportiert sie als einzelne ZIP-Datei.",
    "landing.compress.faq3.q": "Wird die Qualität sichtbar beeinträchtigt?",
    "landing.compress.faq3.a": "Unsere Algorithmen verwenden eine wahrnehmungsverlustfreie Komprimierung, d. h. die Dateigröße schrumpft um bis zu 90 %, während die visuelle Qualität für das menschliche Auge identisch bleibt.",
    "landing.compress.faq4.q": "Ist dies für vertrauliche Ausweisfotos sicher?",
    "landing.compress.faq4.a": "100 % sicher. Ihre Ausweis- und Passfotos verlassen Ihr Gerät nie. Die Komprimierung erfolgt vollständig innerhalb der sicheren Sandbox Ihres Webbrowsers."
  },
  ko: {
    "landing.global.faq.title": "자주 묻는 질문",
    "landing.global.faq.desc": "당사의 로컬 처리 엔진에 대해 알아야 할 모든 것.",
    "landing.remove.faq1.q": "배경 제거가 정말 오프라인으로 처리되나요?",
    "landing.remove.faq1.a": "네. 당사의 AI 모델은 브라우저의 메모리에 로드되므로 전체 배경 감지가 CPU/GPU에서 이루어져 완전한 개인 정보 보호를 보장합니다.",
    "landing.remove.faq2.q": "이미지 해상도가 낮아지나요?",
    "landing.remove.faq2.a": "아니요, 원래 이미지 해상도를 보존합니다. 컷아웃이 생성되어 원래의 고화질 픽셀과 병합됩니다.",
    "landing.remove.faq3.q": "복잡한 머리카락 가장자리에서도 잘 작동하나요?",
    "landing.remove.faq3.a": "물론입니다. WebAssembly AI 모델은 머리카락, 털, 반투명한 물체와 같은 미세한 디테일을 분리하도록 특별히 훈련되었습니다.",
    "landing.remove.faq4.q": "처리할 수 있는 이미지 수에 제한이 있나요?",
    "landing.remove.faq4.a": "모든 것이 귀하의 기기에서 실행되므로 저희에게는 서버 비용이 발생하지 않습니다. 따라서 무제한의 이미지를 완전히 무료로 처리할 수 있습니다.",
    "landing.compress.faq1.q": "오프라인 압축은 어떻게 작동하나요?",
    "landing.compress.faq1.a": "네트워크 업로드 없이 브라우저에서 직접 파일 크기를 줄이기 위해 로컬 Canvas 렌더링 및 WebAssembly 압축 알고리즘을 사용합니다.",
    "landing.compress.faq2.q": "사진을 일괄 압축할 수 있나요?",
    "landing.compress.faq2.a": "네, 최대 10장의 사진을 동시에 드롭할 수 있습니다. 로컬 엔진은 사진을 한 번에 모두 압축하여 단일 ZIP 파일로 내보냅니다.",
    "landing.compress.faq3.q": "품질이 눈에 띄게 저하되나요?",
    "landing.compress.faq3.a": "당사의 알고리즘은 지각적으로 무손실 압축을 사용합니다. 즉, 파일 크기는 최대 90%까지 줄어들지만 시각적 품질은 육안으로 볼 때 동일하게 유지됩니다.",
    "landing.compress.faq4.q": "기밀 신분증 사진에 사용해도 안전한가요?",
    "landing.compress.faq4.a": "100% 안전합니다. 신분증 및 여권 사진은 절대 귀하의 기기를 벗어나지 않습니다. 압축은 전적으로 웹 브라우저의 안전한 샌드박스 내부에서 이루어집니다."
  },
  it: {
    "landing.global.faq.title": "Domande Frequenti",
    "landing.global.faq.desc": "Tutto quello che devi sapere sul nostro motore di elaborazione locale.",
    "landing.remove.faq1.q": "La rimozione dello sfondo viene elaborata davvero offline?",
    "landing.remove.faq1.a": "Sì. Il nostro modello AI viene caricato nella memoria del tuo browser, quindi l'intero rilevamento dello sfondo avviene sulla tua CPU/GPU, garantendo una privacy totale.",
    "landing.remove.faq2.q": "La risoluzione dell'immagine verrà ridotta?",
    "landing.remove.faq2.a": "No, manteniamo la risoluzione originale della tua immagine. Il ritaglio viene generato e unito ai tuoi pixel originali ad alta definizione.",
    "landing.remove.faq3.q": "Funziona bene con i bordi complessi dei capelli?",
    "landing.remove.faq3.a": "Assolutamente. Il modello AI WebAssembly è specificamente addestrato per scontornare dettagli fini come capelli, pelliccia e oggetti semitrasparenti.",
    "landing.remove.faq4.q": "C'è un limite al numero di immagini che posso elaborare?",
    "landing.remove.faq4.a": "Poiché tutto viene eseguito sul tuo dispositivo, non abbiamo costi per i server. Pertanto, puoi elaborare immagini illimitate in modo completamente gratuito.",
    "landing.compress.faq1.q": "Come funziona la compressione offline?",
    "landing.compress.faq1.a": "Utilizziamo il rendering Canvas locale e algoritmi di compressione WebAssembly per ridurre le dimensioni del file direttamente sul tuo browser senza alcun caricamento di rete.",
    "landing.compress.faq2.q": "Posso comprimere lotti di foto?",
    "landing.compress.faq2.a": "Sì, puoi rilasciare fino a 10 foto contemporaneamente. Il motore locale le comprimerà tutte in una volta e le esporterà come un singolo file ZIP.",
    "landing.compress.faq3.q": "La qualità subirà un degrado visibile?",
    "landing.compress.faq3.a": "I nostri algoritmi utilizzano una compressione visivamente senza perdite, il che significa che le dimensioni del file si riducono fino al 90% mentre la qualità visiva rimane identica all'occhio umano.",
    "landing.compress.faq4.q": "È sicuro per fototessera riservate?",
    "landing.compress.faq4.a": "Sicuro al 100%. Le tue foto per documenti e passaporti non lasciano mai il tuo dispositivo. La compressione avviene interamente all'interno della sandbox sicura del tuo browser web."
  },
  tr: {
    "landing.global.faq.title": "Sıkça Sorulan Sorular",
    "landing.global.faq.desc": "Yerel işleme motorumuz hakkında bilmeniz gereken her şey.",
    "landing.remove.faq1.q": "Arka plan kaldırma gerçekten çevrimdışı olarak mı işleniyor?",
    "landing.remove.faq1.a": "Evet. Yapay zeka modelimiz tarayıcınızın belleğine yüklenir, bu nedenle tüm arka plan algılama işlemi CPU/GPU'nuzda gerçekleşerek tam gizlilik sağlar.",
    "landing.remove.faq2.q": "Görüntü çözünürlüğü düşecek mi?",
    "landing.remove.faq2.a": "Hayır, orijinal görüntü çözünürlüğünüzü koruyoruz. Kesik alan oluşturulur ve orijinal yüksek çözünürlüklü piksellerinizle birleştirilir.",
    "landing.remove.faq3.q": "Karmaşık saç kenarlarında iyi çalışır mı?",
    "landing.remove.faq3.a": "Kesinlikle. WebAssembly yapay zeka modeli, saç, kürk ve yarı saydam nesneler gibi ince detayları ayırmak için özel olarak eğitilmiştir.",
    "landing.remove.faq4.q": "İşleyebileceğim görüntü sayısında bir sınır var mı?",
    "landing.remove.faq4.a": "Her şey kendi cihazınızda çalıştığı için bizim için sıfır sunucu maliyeti var. Bu nedenle, sınırsız görüntüyü tamamen ücretsiz olarak işleyebilirsiniz.",
    "landing.compress.faq1.q": "Çevrimdışı sıkıştırma nasıl çalışır?",
    "landing.compress.faq1.a": "Herhangi bir ağ yüklemesi olmadan dosya boyutunu doğrudan tarayıcınızda küçültmek için yerel Canvas oluşturma ve WebAssembly sıkıştırma algoritmaları kullanıyoruz.",
    "landing.compress.faq2.q": "Fotoğraf gruplarını sıkıştırabilir miyim?",
    "landing.compress.faq2.a": "Evet, aynı anda 10 adede kadar fotoğraf bırakabilirsiniz. Yerel motor hepsini aynı anda sıkıştıracak ve tek bir ZIP dosyası olarak dışa aktaracaktır.",
    "landing.compress.faq3.q": "Kalite gözle görülür şekilde bozulacak mı?",
    "landing.compress.faq3.a": "Algoritmalarımız algısal olarak kayıpsız sıkıştırma kullanır; bu, dosya boyutu %90'a kadar küçülürken görsel kalitenin insan gözüyle aynı kalması anlamına gelir.",
    "landing.compress.faq4.q": "Bu, gizli kimlik fotoğrafları için güvenli mi?",
    "landing.compress.faq4.a": "%100 güvenli. Kimlik ve pasaport fotoğraflarınız cihazınızdan asla ayrılmaz. Sıkıştırma işlemi tamamen web tarayıcınızın güvenli korumalı alanında gerçekleşir."
  },
  vi: {
    "landing.global.faq.title": "Câu hỏi thường gặp",
    "landing.global.faq.desc": "Mọi điều bạn cần biết về công cụ xử lý cục bộ của chúng tôi.",
    "landing.remove.faq1.q": "Việc xóa nền có thực sự được xử lý ngoại tuyến không?",
    "landing.remove.faq1.a": "Có. Mô hình AI của chúng tôi được tải vào bộ nhớ trình duyệt của bạn, do đó toàn bộ quá trình phát hiện nền sẽ diễn ra trên CPU/GPU của bạn, đảm bảo quyền riêng tư hoàn toàn.",
    "landing.remove.faq2.q": "Độ phân giải hình ảnh có bị giảm không?",
    "landing.remove.faq2.a": "Không, chúng tôi giữ nguyên độ phân giải hình ảnh gốc của bạn. Phần cắt ra được tạo và hợp nhất với các pixel độ nét cao ban đầu của bạn.",
    "landing.remove.faq3.q": "Nó có hoạt động tốt với các cạnh tóc phức tạp không?",
    "landing.remove.faq3.a": "Hoàn toàn. Mô hình WebAssembly AI được đào tạo đặc biệt để tách các chi tiết nhỏ như tóc, lông thú và các vật thể bán trong suốt.",
    "landing.remove.faq4.q": "Có giới hạn về số lượng hình ảnh tôi có thể xử lý không?",
    "landing.remove.faq4.a": "Vì mọi thứ chạy trên thiết bị của riêng bạn nên chúng tôi không mất phí máy chủ. Do đó, bạn có thể xử lý hình ảnh không giới hạn hoàn toàn miễn phí.",
    "landing.compress.faq1.q": "Nén ngoại tuyến hoạt động như thế nào?",
    "landing.compress.faq1.a": "Chúng tôi sử dụng kết xuất Canvas cục bộ và thuật toán nén WebAssembly để thu nhỏ kích thước tệp trực tiếp trên trình duyệt của bạn mà không cần tải lên mạng.",
    "landing.compress.faq2.q": "Tôi có thể nén hàng loạt ảnh không?",
    "landing.compress.faq2.a": "Có, bạn có thể thả tối đa 10 bức ảnh cùng một lúc. Công cụ cục bộ sẽ nén tất cả chúng cùng một lúc và xuất chúng dưới dạng một tệp ZIP duy nhất.",
    "landing.compress.faq3.q": "Chất lượng có bị giảm sút rõ rệt không?",
    "landing.compress.faq3.a": "Các thuật toán của chúng tôi sử dụng tính năng nén không mất dữ liệu theo cảm nhận, nghĩa là kích thước tệp thu nhỏ tới 90% trong khi chất lượng hình ảnh vẫn giống hệt với mắt người.",
    "landing.compress.faq4.q": "Điều này có an toàn cho ảnh ID bí mật không?",
    "landing.compress.faq4.a": "An toàn 100%. Ảnh ID và hộ chiếu của bạn không bao giờ rời khỏi thiết bị của bạn. Quá trình nén diễn ra hoàn toàn bên trong hộp cát an toàn của trình duyệt web của bạn."
  },
  th: {
    "landing.global.faq.title": "คำถามที่พบบ่อย",
    "landing.global.faq.desc": "ทุกสิ่งที่คุณจำเป็นต้องรู้เกี่ยวกับเอ็นจิ้นการประมวลผลในพื้นที่ของเรา",
    "landing.remove.faq1.q": "การลบพื้นหลังได้รับการประมวลผลแบบออฟไลน์จริงหรือ",
    "landing.remove.faq1.a": "ใช่ โมเดล AI ของเราถูกโหลดเข้าสู่หน่วยความจำของเบราว์เซอร์ของคุณ ดังนั้นการตรวจจับพื้นหลังทั้งหมดจึงเกิดขึ้นบน CPU/GPU ของคุณ เพื่อความเป็นส่วนตัวอย่างสมบูรณ์",
    "landing.remove.faq2.q": "ความละเอียดของภาพจะลดลงหรือไม่",
    "landing.remove.faq2.a": "ไม่ เรายังคงความละเอียดของภาพต้นฉบับของคุณไว้ คัตเอาต์ถูกสร้างขึ้นและรวมเข้ากับพิกเซลความละเอียดสูงดั้งเดิมของคุณ",
    "landing.remove.faq3.q": "ใช้ได้ดีกับขอบผมที่ซับซ้อนหรือไม่",
    "landing.remove.faq3.a": "แน่นอน โมเดล AI ของ WebAssembly ได้รับการฝึกอบรมมาโดยเฉพาะเพื่อตัดรายละเอียดที่ละเอียดอ่อน เช่น เส้นผม ขน และวัตถุกึ่งโปร่งใส",
    "landing.remove.faq4.q": "มีการจำกัดจำนวนภาพที่ฉันสามารถประมวลผลได้หรือไม่",
    "landing.remove.faq4.a": "เนื่องจากทุกอย่างทำงานบนอุปกรณ์ของคุณเอง จึงไม่มีค่าใช้จ่ายเซิร์ฟเวอร์สำหรับเรา ดังนั้นคุณสามารถประมวลผลภาพได้ไม่จำกัดจำนวนฟรีอย่างสมบูรณ์",
    "landing.compress.faq1.q": "การบีบอัดแบบออฟไลน์ทำงานอย่างไร",
    "landing.compress.faq1.a": "เราใช้การเรนเดอร์ Canvas ในพื้นที่และอัลกอริธึมการบีบอัด WebAssembly เพื่อลดขนาดไฟล์โดยตรงบนเบราว์เซอร์ของคุณโดยไม่ต้องอัปโหลดเครือข่าย",
    "landing.compress.faq2.q": "ฉันสามารถบีบอัดรูปภาพเป็นชุดได้หรือไม่",
    "landing.compress.faq2.a": "ได้ คุณสามารถวางรูปภาพได้สูงสุด 10 รูปพร้อมกัน เอ็นจิ้นในพื้นที่จะบีบอัดรูปภาพทั้งหมดในครั้งเดียวและส่งออกเป็นไฟล์ ZIP ไฟล์เดียว",
    "landing.compress.faq3.q": "คุณภาพจะลดลงอย่างเห็นได้ชัดหรือไม่",
    "landing.compress.faq3.a": "อัลกอริธึมของเราใช้การบีบอัดแบบไม่สูญเสียการรับรู้ ซึ่งหมายความว่าขนาดไฟล์จะลดลงมากถึง 90% ในขณะที่คุณภาพของภาพยังคงเหมือนเดิมสำหรับสายตามนุษย์",
    "landing.compress.faq4.q": "วิธีนี้ปลอดภัยสำหรับรูปถ่าย ID ที่เป็นความลับหรือไม่",
    "landing.compress.faq4.a": "ปลอดภัย 100% รูปถ่าย ID และพาสปอร์ตของคุณจะไม่ออกจากอุปกรณ์ของคุณเลย การบีบอัดจะเกิดขึ้นทั้งหมดภายในแซนด์บ็อกซ์ที่ปลอดภัยของเว็บเบราว์เซอร์ของคุณ"
  }
};

const scriptDir = __dirname;
const localesDir = path.join(scriptDir, '../public/locales');

for (const [lang, kv] of Object.entries(translations)) {
  const filePath = path.join(localesDir, lang, 'translation.json');
  if (fs.existsSync(filePath)) {
    const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    for (const [key, val] of Object.entries(kv)) {
      data[key] = val;
    }
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
    console.log(`[${lang}] Injected FAQ translations part 1`);
  }
}
