const fs = require('fs');
const path = require('path');

const localesDir = path.join(__dirname, '../public/locales');

const translations = {
  ms: {
    "landing.color.redesign.heroBadge": "STUDIO WARNA SEGERA",
    "landing.color.redesign.heroTitle": "Ubah Warna Latar Belakang dalam Masa Nyata",
    "landing.color.redesign.heroDesc": "Gunakan warna pepejal, kecerunan atau kod HEX dengan serta-merta. Sempurna untuk fotografi produk.",
    "landing.color.redesign.feat1Title": "Kanvas Warna Tanpa Had",
    "landing.color.redesign.feat1Desc": "Pilih dari palet kami atau masukkan sebarang kod HEX/RGB untuk memadankan jenama anda.",
    "landing.color.redesign.feat2Title": "Pelancaran Tepi",
    "landing.color.redesign.feat2Desc": "Warna bercampur secara semula jadi dengan tepi subjek anda, mengelakkan halo berpixsel.",
    "landing.color.redesign.feat3Title": "Pratonton Langsung",
    "landing.color.redesign.feat3Desc": "Lihat perubahan warna serta-merta tanpa menunggu masa muat semula.",
    "landing.color.redesign.feat4Title": "100% Peribadi",
    "landing.color.redesign.feat4Desc": "Pemprosesan dilakukan terus pada peranti anda. Tiada muat naik pelayan.",
    "landing.color.redesign.whoTag": "KEGUNAAN PROFESIONAL",
    "landing.color.redesign.whoTitle": "Dibina untuk Pencipta",
    "landing.color.redesign.who1Title": "Katalog E-Dagang",
    "landing.color.redesign.who1Desc": "Standardkan latar belakang produk untuk penyenaraian kedai yang konsisten.",
    "landing.color.redesign.who2Title": "Potret Profil",
    "landing.color.redesign.who2Desc": "Tambah latar belakang menarik ke LinkedIn atau Twitter.",
    "landing.color.redesign.who3Title": "Bahan Pemasaran",
    "landing.color.redesign.who3Desc": "Sediakan aset telus dengan menggunakan warna jenama.",
    "landing.color.redesign.stepsTitle": "Warnakan dalam 3 Langkah",
    "landing.color.redesign.s1Title": "Muat Naik Imej",
    "landing.color.redesign.s1Desc": "Pastikan imej anda mempunyai latar belakang telus terlebih dahulu.",
    "landing.color.redesign.s2Title": "Pilih Warna",
    "landing.color.redesign.s2Desc": "Gunakan pemilih warna atau masukkan kod HEX anda.",
    "landing.color.redesign.s3Title": "Eksport",
    "landing.color.redesign.s3Desc": "Muat turun imej berwarna anda dalam resolusi penuh.",
    "landing.resize.redesign.heroBadge": "SKALA PIKSEL SEMPURNA",
    "landing.resize.redesign.heroTitle": "Ubah Saiz Imej dengan Ketepatan Mutlak",
    "landing.resize.redesign.heroDesc": "Skalakan foto anda dengan dimensi atau peratusan piksel yang tepat.",
    "landing.resize.redesign.feat1Title": "Dimensi Piksel Tepat",
    "landing.resize.redesign.feat1Desc": "Ambil kawalan penuh ke atas saiz imej. Masukkan nilai lebar dan tinggi yang khusus.",
    "landing.resize.redesign.feat1Li1": "Kunci nisbah aspek",
    "landing.resize.redesign.feat1Li2": "Lebar & tinggi tersuai",
    "landing.resize.redesign.feat2Title": "Skala Peratusan",
    "landing.resize.redesign.feat2Desc": "Gunakan peluncur peratusan untuk menskalakan gambar dengan cepat.",
    "landing.resize.redesign.feat2Li1": "Butang pantas 50% / 200%",
    "landing.resize.redesign.feat2Li2": "Mengekalkan kualiti visual",
    "landing.resize.redesign.socialTitle": "Sempurna untuk Setiap Platform",
    "landing.resize.redesign.socialDesc": "Penuhi syarat muat naik media sosial yang ketat tanpa masalah.",
    "landing.resize.redesign.stepsTag": "BAGAIMANA IA BERFUNGSI",
    "landing.resize.redesign.stepsTitle": "Ubah Saiz dalam 3 Langkah",
    "landing.resize.redesign.s1Title": "Muat Naik Foto",
    "landing.resize.redesign.s1Desc": "Jatuhkan sehingga 10 gambar.",
    "landing.resize.redesign.s2Title": "Tetapkan Dimensi",
    "landing.resize.redesign.s2Desc": "Masukkan lebar dan tinggi sasaran anda.",
    "landing.resize.redesign.s3Title": "Simpan",
    "landing.resize.redesign.s3Desc": "Muat turun foto yang diubah saiz serta-merta.",
    "landing.crop.redesign.heroBadge": "KOMPOSISI PINTAR",
    "landing.crop.redesign.heroTitle": "Potong Bunyi Bising.",
    "landing.crop.redesign.heroTitle2": "Fokus pada yang Penting.",
    "landing.crop.redesign.heroDesc": "Bingkaikan foto anda dengan sempurna dengan potongan bebas atau nisbah tetap.",
    "landing.crop.redesign.feat1Title": "Pemilihan Bebas",
    "landing.crop.redesign.feat1Desc": "Tarik tepi kotak potong dengan bebas untuk membingkai subjek anda.",
    "landing.crop.redesign.feat2Title": "Nisbah Aspek Tetap",
    "landing.crop.redesign.feat2Desc": "Perlukan segi empat sama sempurna? Kunci nisbah aspek untuk mengekalkan perkadaran.",
    "landing.crop.redesign.feat3Title": "Pengekstrakan Tanpa Hilang",
    "landing.crop.redesign.feat3Desc": "Kami mengekstrak piksel secara asli untuk memastikan tiada kehilangan kualiti.",
    "landing.crop.redesign.stepsTag": "CARA MEMOTONG",
    "landing.crop.redesign.stepsTitle": "Pembingkaian Sempurna dalam Beberapa Saat",
    "landing.crop.redesign.s1Title": "Muat Naik Foto",
    "landing.crop.redesign.s1Desc": "Seret dan lepaskan imej anda.",
    "landing.crop.redesign.s2Title": "Tarik Kotak",
    "landing.crop.redesign.s2Desc": "Laraskan kawasan pemotongan menggunakan pemegang.",
    "landing.crop.redesign.s3Title": "Guna dan Simpan",
    "landing.crop.redesign.s3Desc": "Tekan potong dan muat turun imej anda."
  },
  nl: {
    "landing.color.redesign.heroBadge": "DIRECTE KLEURENSTUDIO",
    "landing.color.redesign.heroTitle": "Achtergrondkleuren in real-time wijzigen",
    "landing.color.redesign.heroDesc": "Pas direct effen kleuren, verlopen of HEX-codes toe. Perfect voor productfotografie.",
    "landing.color.redesign.feat1Title": "Oneindig kleurenpalet",
    "landing.color.redesign.feat1Desc": "Kies uit ons palet of voer een HEX-code in die bij uw merk past.",
    "landing.color.redesign.feat2Title": "Randverzachting",
    "landing.color.redesign.feat2Desc": "Kleuren vloeien natuurlijk over in de randen van uw onderwerp.",
    "landing.color.redesign.feat3Title": "Live Voorbeeld",
    "landing.color.redesign.feat3Desc": "Zie kleurveranderingen direct zonder wachttijden.",
    "landing.color.redesign.feat4Title": "100% Privé",
    "landing.color.redesign.feat4Desc": "Verwerking gebeurt direct op uw apparaat. Geen server uploads.",
    "landing.color.redesign.whoTag": "PROFESSIONEEL GEBRUIK",
    "landing.color.redesign.whoTitle": "Gebouwd voor makers",
    "landing.color.redesign.who1Title": "E-commerce Catalogus",
    "landing.color.redesign.who1Desc": "Standaardiseer productachtergronden.",
    "landing.color.redesign.who2Title": "Profielportretten",
    "landing.color.redesign.who2Desc": "Voeg opvallende achtergronden toe voor LinkedIn.",
    "landing.color.redesign.who3Title": "Marketingmateriaal",
    "landing.color.redesign.who3Desc": "Bereid transparante assets voor met merkkleuren.",
    "landing.color.redesign.stepsTitle": "Inkleuren in 3 stappen",
    "landing.color.redesign.s1Title": "Upload afbeelding",
    "landing.color.redesign.s1Desc": "Zorg eerst voor een transparante achtergrond.",
    "landing.color.redesign.s2Title": "Kies een kleur",
    "landing.color.redesign.s2Desc": "Gebruik de kleurkiezer of voer uw HEX-code in.",
    "landing.color.redesign.s3Title": "Exporteren",
    "landing.color.redesign.s3Desc": "Download uw gekleurde afbeelding.",
    "landing.resize.redesign.heroBadge": "PIXELPERFECT SCHALEN",
    "landing.resize.redesign.heroTitle": "Formaat afbeeldingen met absolute precisie wijzigen",
    "landing.resize.redesign.heroDesc": "Schaal foto's met exacte pixelafmetingen of percentages.",
    "landing.resize.redesign.feat1Title": "Exacte pixelafmetingen",
    "landing.resize.redesign.feat1Desc": "Neem volledige controle over de afbeeldingsgrootte.",
    "landing.resize.redesign.feat1Li1": "Beeldverhouding vergrendelen",
    "landing.resize.redesign.feat1Li2": "Aangepaste breedte en hoogte",
    "landing.resize.redesign.feat2Title": "Procentueel schalen",
    "landing.resize.redesign.feat2Desc": "Gebruik de procentuele schuifregelaar om snel te schalen.",
    "landing.resize.redesign.feat2Li1": "Snelle 50% / 200% knoppen",
    "landing.resize.redesign.feat2Li2": "Behoudt visuele kwaliteit",
    "landing.resize.redesign.socialTitle": "Perfect voor elk platform",
    "landing.resize.redesign.socialDesc": "Voldoe aan de uploadvereisten van sociale media.",
    "landing.resize.redesign.stepsTag": "HOE HET WERKT",
    "landing.resize.redesign.stepsTitle": "Formaat wijzigen in 3 stappen",
    "landing.resize.redesign.s1Title": "Foto's uploaden",
    "landing.resize.redesign.s1Desc": "Zet tot 10 foto's neer.",
    "landing.resize.redesign.s2Title": "Dimensies instellen",
    "landing.resize.redesign.s2Desc": "Voer uw doelhoogte en -breedte in.",
    "landing.resize.redesign.s3Title": "Opslaan",
    "landing.resize.redesign.s3Desc": "Download de geschaalde foto's direct.",
    "landing.crop.redesign.heroBadge": "SLIMME COMPOSITIE",
    "landing.crop.redesign.heroTitle": "Snijd de ruis weg.",
    "landing.crop.redesign.heroTitle2": "Focus op wat belangrijk is.",
    "landing.crop.redesign.heroDesc": "Kader uw foto's perfect in met vrije of vaste uitsneden.",
    "landing.crop.redesign.feat1Title": "Vrije selectie",
    "landing.crop.redesign.feat1Desc": "Sleep de randen vrij om uw onderwerp te kadreren.",
    "landing.crop.redesign.feat2Title": "Vaste beeldverhouding",
    "landing.crop.redesign.feat2Desc": "Een perfect vierkant nodig? Vergrendel de verhouding.",
    "landing.crop.redesign.feat3Title": "Verliesvrije extractie",
    "landing.crop.redesign.feat3Desc": "We extraheren pixels zonder kwaliteitsverlies.",
    "landing.crop.redesign.stepsTag": "HOE TE BIJSNIJDEN",
    "landing.crop.redesign.stepsTitle": "Perfect kadreren in seconden",
    "landing.crop.redesign.s1Title": "Foto uploaden",
    "landing.crop.redesign.s1Desc": "Sleep uw afbeelding naar de werkruimte.",
    "landing.crop.redesign.s2Title": "Sleep de box",
    "landing.crop.redesign.s2Desc": "Pas het uitsnedegebied aan.",
    "landing.crop.redesign.s3Title": "Toepassen & Opslaan",
    "landing.crop.redesign.s3Desc": "Druk op bijsnijden en download uw afbeelding."
  },
  no: {
    "landing.color.redesign.heroBadge": "ØYEBLIKKELIG FARGESSTUDIO",
    "landing.color.redesign.heroTitle": "Endre bakgrunnsfarger i sanntid",
    "landing.color.redesign.heroDesc": "Bruk solide farger, gradienter eller HEX-koder øyeblikkelig.",
    "landing.color.redesign.feat1Title": "Uendelig fargelerret",
    "landing.color.redesign.feat1Desc": "Velg fra paletten vår eller angi en HEX-kode for å matche merkevaren din.",
    "landing.color.redesign.feat2Title": "Kantutjevning",
    "landing.color.redesign.feat2Desc": "Farger blander seg naturlig med kantene på motivet ditt.",
    "landing.color.redesign.feat3Title": "Live forhåndsvisning",
    "landing.color.redesign.feat3Desc": "Se fargeendringer øyeblikkelig uten ventetid.",
    "landing.color.redesign.feat4Title": "100% Privat",
    "landing.color.redesign.feat4Desc": "Behandling skjer direkte på enheten din.",
    "landing.color.redesign.whoTag": "PROFESJONELL BRUK",
    "landing.color.redesign.whoTitle": "Bygget for skapere",
    "landing.color.redesign.who1Title": "E-handelskataloger",
    "landing.color.redesign.who1Desc": "Standardiser produktbakgrunner for konsekvente oppføringer.",
    "landing.color.redesign.who2Title": "Profilportretter",
    "landing.color.redesign.who2Desc": "Legg til slående bakgrunner på LinkedIn.",
    "landing.color.redesign.who3Title": "Markedsføringsmateriell",
    "landing.color.redesign.who3Desc": "Forbered gjennomsiktige eiendeler ved å bruke merkefarger.",
    "landing.color.redesign.stepsTitle": "Fargelegg i 3 trinn",
    "landing.color.redesign.s1Title": "Last opp bilde",
    "landing.color.redesign.s1Desc": "Forsikre deg om at bildet har en gjennomsiktig bakgrunn først.",
    "landing.color.redesign.s2Title": "Velg farge",
    "landing.color.redesign.s2Desc": "Bruk fargevelgeren eller angi HEX-koden.",
    "landing.color.redesign.s3Title": "Eksporter",
    "landing.color.redesign.s3Desc": "Last ned det fargede bildet ditt.",
    "landing.resize.redesign.heroBadge": "PIKSELPERFEKT SKALERING",
    "landing.resize.redesign.heroTitle": "Endre størrelse med absolutt presisjon",
    "landing.resize.redesign.heroDesc": "Skaler bildene dine med nøyaktige pikseldimensjoner eller prosenter.",
    "landing.resize.redesign.feat1Title": "Nøyaktige pikseldimensjoner",
    "landing.resize.redesign.feat1Desc": "Ta full kontroll over bildestørrelsen.",
    "landing.resize.redesign.feat1Li1": "Lås sideforhold",
    "landing.resize.redesign.feat1Li2": "Egendefinert bredde og høyde",
    "landing.resize.redesign.feat2Title": "Prosentvis skalering",
    "landing.resize.redesign.feat2Desc": "Bruk prosentglideren til å skalere bilder raskt.",
    "landing.resize.redesign.feat2Li1": "Raske 50% / 200% knapper",
    "landing.resize.redesign.feat2Li2": "Opprettholder visuell kvalitet",
    "landing.resize.redesign.socialTitle": "Perfekt for hver plattform",
    "landing.resize.redesign.socialDesc": "Oppfyll strenge opplastingskrav for sosiale medier.",
    "landing.resize.redesign.stepsTag": "SLIK FUNGERER DET",
    "landing.resize.redesign.stepsTitle": "Endre størrelse i 3 trinn",
    "landing.resize.redesign.s1Title": "Last opp bilder",
    "landing.resize.redesign.s1Desc": "Slipp opptil 10 bilder.",
    "landing.resize.redesign.s2Title": "Angi dimensjoner",
    "landing.resize.redesign.s2Desc": "Angi målbredde og -høyde.",
    "landing.resize.redesign.s3Title": "Lagre",
    "landing.resize.redesign.s3Desc": "Last ned bildene øyeblikkelig.",
    "landing.crop.redesign.heroBadge": "SMART KOMPOSISJON",
    "landing.crop.redesign.heroTitle": "Kutt ut støyen.",
    "landing.crop.redesign.heroTitle2": "Fokuser på det viktige.",
    "landing.crop.redesign.heroDesc": "Ramme inn bildene dine perfekt med fri eller fast beskjæring.",
    "landing.crop.redesign.feat1Title": "Fri markering",
    "landing.crop.redesign.feat1Desc": "Dra kantene fritt for å ramme inn motivet ditt.",
    "landing.crop.redesign.feat2Title": "Faste sideforhold",
    "landing.crop.redesign.feat2Desc": "Trenger du en perfekt firkant? Lås sideforholdet.",
    "landing.crop.redesign.feat3Title": "Tapsfri utvinning",
    "landing.crop.redesign.feat3Desc": "Vi trekker ut piksler innfødt og sikrer null tap av kvalitet.",
    "landing.crop.redesign.stepsTag": "SLIK BESKJÆRER DU",
    "landing.crop.redesign.stepsTitle": "Perfekt innramming på sekunder",
    "landing.crop.redesign.s1Title": "Last opp bilde",
    "landing.crop.redesign.s1Desc": "Dra bildet inn i arbeidsområdet.",
    "landing.crop.redesign.s2Title": "Dra boksen",
    "landing.crop.redesign.s2Desc": "Juster beskjæringsområdet.",
    "landing.crop.redesign.s3Title": "Bruk og lagre",
    "landing.crop.redesign.s3Desc": "Trykk på beskjær og last ned."
  },
  pl: {
    "landing.color.redesign.heroBadge": "BŁYSKAWICZNE STUDIO KOLORÓW",
    "landing.color.redesign.heroTitle": "Zmień kolory tła w czasie rzeczywistym",
    "landing.color.redesign.heroDesc": "Zastosuj jednolite kolory, gradienty lub kody HEX natychmiast. Idealne do fotografii produktowej.",
    "landing.color.redesign.feat1Title": "Nieskończona paleta kolorów",
    "landing.color.redesign.feat1Desc": "Wybierz z naszej palety lub wprowadź dowolny kod HEX, aby dopasować go do swojej marki.",
    "landing.color.redesign.feat2Title": "Wygładzanie krawędzi",
    "landing.color.redesign.feat2Desc": "Kolory naturalnie łączą się z krawędziami obiektu, unikając pikselowatego halo.",
    "landing.color.redesign.feat3Title": "Podgląd na żywo",
    "landing.color.redesign.feat3Desc": "Zobacz zmiany kolorów natychmiast, bez czekania.",
    "landing.color.redesign.feat4Title": "100% Prywatności",
    "landing.color.redesign.feat4Desc": "Przetwarzanie odbywa się na Twoim urządzeniu. Bez przesyłania na serwer.",
    "landing.color.redesign.whoTag": "ZASTOSOWANIE PROFESJONALNE",
    "landing.color.redesign.whoTitle": "Zbudowane dla twórców",
    "landing.color.redesign.who1Title": "Katalogi e-commerce",
    "landing.color.redesign.who1Desc": "Standaryzuj tła produktów dla spójnych ofert sklepowych.",
    "landing.color.redesign.who2Title": "Portrety profilowe",
    "landing.color.redesign.who2Desc": "Dodaj uderzające tła do LinkedIn lub Twittera.",
    "landing.color.redesign.who3Title": "Materiały marketingowe",
    "landing.color.redesign.who3Desc": "Przygotuj przezroczyste zasoby, stosując kolory marki.",
    "landing.color.redesign.stepsTitle": "Pokoloruj w 3 krokach",
    "landing.color.redesign.s1Title": "Prześlij obraz",
    "landing.color.redesign.s1Desc": "Najpierw upewnij się, że obraz ma przezroczyste tło.",
    "landing.color.redesign.s2Title": "Wybierz kolor",
    "landing.color.redesign.s2Desc": "Użyj próbnika lub wprowadź kod HEX.",
    "landing.color.redesign.s3Title": "Eksport",
    "landing.color.redesign.s3Desc": "Pobierz pokolorowany obraz w pełnej rozdzielczości.",
    "landing.resize.redesign.heroBadge": "IDEALNE SKALOWANIE PIKSELI",
    "landing.resize.redesign.heroTitle": "Zmieniaj rozmiar zdjęć z absolutną precyzją",
    "landing.resize.redesign.heroDesc": "Skaluj swoje zdjęcia według dokładnych wymiarów pikseli lub procentów.",
    "landing.resize.redesign.feat1Title": "Dokładne wymiary w pikselach",
    "landing.resize.redesign.feat1Desc": "Przejmij pełną kontrolę nad rozmiarem obrazu. Wprowadź określoną szerokość i wysokość.",
    "landing.resize.redesign.feat1Li1": "Zablokuj proporcje",
    "landing.resize.redesign.feat1Li2": "Niestandardowa szerokość i wysokość",
    "landing.resize.redesign.feat2Title": "Skalowanie procentowe",
    "landing.resize.redesign.feat2Desc": "Użyj suwaka procentowego, aby szybko skalować obrazy.",
    "landing.resize.redesign.feat2Li1": "Szybkie przyciski 50% / 200%",
    "landing.resize.redesign.feat2Li2": "Zachowuje jakość wizualną",
    "landing.resize.redesign.socialTitle": "Idealne dla każdej platformy",
    "landing.resize.redesign.socialDesc": "Bez problemu spełniaj surowe wymagania mediów społecznościowych.",
    "landing.resize.redesign.stepsTag": "JAK TO DZIAŁA",
    "landing.resize.redesign.stepsTitle": "Zmień rozmiar w 3 krokach",
    "landing.resize.redesign.s1Title": "Prześlij zdjęcia",
    "landing.resize.redesign.s1Desc": "Upuść do 10 zdjęć.",
    "landing.resize.redesign.s2Title": "Ustaw wymiary",
    "landing.resize.redesign.s2Desc": "Wprowadź docelową szerokość i wysokość.",
    "landing.resize.redesign.s3Title": "Zapisz",
    "landing.resize.redesign.s3Desc": "Pobierz zmienione zdjęcia natychmiast.",
    "landing.crop.redesign.heroBadge": "INTELIGENTNA KOMPOZYCJA",
    "landing.crop.redesign.heroTitle": "Wytnij szum.",
    "landing.crop.redesign.heroTitle2": "Skup się na tym, co ważne.",
    "landing.crop.redesign.heroDesc": "Kadruj swoje zdjęcia idealnie za pomocą swobodnego lub proporcjonalnego kadrowania.",
    "landing.crop.redesign.feat1Title": "Swobodny wybór",
    "landing.crop.redesign.feat1Desc": "Przeciągaj krawędzie swobodnie, aby wykadrować obiekt dokładnie tak, jak chcesz.",
    "landing.crop.redesign.feat2Title": "Stałe proporcje",
    "landing.crop.redesign.feat2Desc": "Potrzebujesz idealnego kwadratu? Zablokuj proporcje, aby zachować wymiary.",
    "landing.crop.redesign.feat3Title": "Bezstratne wyodrębnianie",
    "landing.crop.redesign.feat3Desc": "Natywnie wyodrębniamy piksele, zapewniając brak utraty jakości.",
    "landing.crop.redesign.stepsTag": "JAK KADROWAĆ",
    "landing.crop.redesign.stepsTitle": "Idealne kadrowanie w kilka sekund",
    "landing.crop.redesign.s1Title": "Prześlij zdjęcie",
    "landing.crop.redesign.s1Desc": "Przeciągnij i upuść obraz do obszaru roboczego.",
    "landing.crop.redesign.s2Title": "Przeciągnij pole",
    "landing.crop.redesign.s2Desc": "Dostosuj obszar kadrowania za pomocą uchwytów.",
    "landing.crop.redesign.s3Title": "Zastosuj i Zapisz",
    "landing.crop.redesign.s3Desc": "Naciśnij kadruj i pobierz obraz."
  },
  pt: {
    "landing.color.redesign.heroBadge": "ESTÚDIO DE CORES INSTANTÂNEO",
    "landing.color.redesign.heroTitle": "Mude as Cores de Fundo em Tempo Real",
    "landing.color.redesign.heroDesc": "Aplique cores sólidas, gradientes ou códigos HEX instantaneamente. Perfeito para fotografia de produtos.",
    "landing.color.redesign.feat1Title": "Tela de Cores Infinita",
    "landing.color.redesign.feat1Desc": "Escolha da nossa paleta ou insira qualquer código HEX para combinar com sua marca.",
    "landing.color.redesign.feat2Title": "Suavização de Bordas",
    "landing.color.redesign.feat2Desc": "As cores se misturam naturalmente com as bordas do seu objeto, evitando halos pixelados.",
    "landing.color.redesign.feat3Title": "Visualização ao Vivo",
    "landing.color.redesign.feat3Desc": "Veja as alterações de cor instantaneamente sem tempos de espera.",
    "landing.color.redesign.feat4Title": "100% Privado",
    "landing.color.redesign.feat4Desc": "O processamento é feito diretamente no seu dispositivo. Sem uploads de servidor.",
    "landing.color.redesign.whoTag": "USOS PROFISSIONAIS",
    "landing.color.redesign.whoTitle": "Construído para Criadores",
    "landing.color.redesign.who1Title": "Catálogos de E-Commerce",
    "landing.color.redesign.who1Desc": "Padronize fundos de produtos para listagens consistentes na loja.",
    "landing.color.redesign.who2Title": "Retratos de Perfil",
    "landing.color.redesign.who2Desc": "Adicione fundos vibrantes ao LinkedIn ou Twitter.",
    "landing.color.redesign.who3Title": "Materiais de Marketing",
    "landing.color.redesign.who3Desc": "Prepare ativos transparentes aplicando as cores da marca.",
    "landing.color.redesign.stepsTitle": "Colorir em 3 Passos",
    "landing.color.redesign.s1Title": "Enviar Imagem",
    "landing.color.redesign.s1Desc": "Certifique-se de que a imagem tenha um fundo transparente primeiro.",
    "landing.color.redesign.s2Title": "Escolher uma Cor",
    "landing.color.redesign.s2Desc": "Use o seletor de cores ou insira um código HEX.",
    "landing.color.redesign.s3Title": "Exportar",
    "landing.color.redesign.s3Desc": "Baixe sua imagem colorida em resolução máxima.",
    "landing.resize.redesign.heroBadge": "DIMENSIONAMENTO PERFEITO",
    "landing.resize.redesign.heroTitle": "Redimensione Imagens com Precisão Absoluta",
    "landing.resize.redesign.heroDesc": "Dimensione suas fotos por dimensões exatas de pixels ou porcentagens.",
    "landing.resize.redesign.feat1Title": "Dimensões Exatas em Pixels",
    "landing.resize.redesign.feat1Desc": "Assuma o controle total sobre o tamanho da imagem. Insira largura e altura específicas.",
    "landing.resize.redesign.feat1Li1": "Bloquear proporção",
    "landing.resize.redesign.feat1Li2": "Largura e altura personalizadas",
    "landing.resize.redesign.feat2Title": "Dimensionamento Percentual",
    "landing.resize.redesign.feat2Desc": "Use o controle deslizante de porcentagem para redimensionar imagens rapidamente.",
    "landing.resize.redesign.feat2Li1": "Botões rápidos de 50% / 200%",
    "landing.resize.redesign.feat2Li2": "Mantém a qualidade visual",
    "landing.resize.redesign.socialTitle": "Perfeito para Cada Plataforma",
    "landing.resize.redesign.socialDesc": "Atenda aos rígidos requisitos de upload de mídia social sem complicações.",
    "landing.resize.redesign.stepsTag": "COMO FUNCIONA",
    "landing.resize.redesign.stepsTitle": "Redimensionar em 3 Passos",
    "landing.resize.redesign.s1Title": "Enviar Fotos",
    "landing.resize.redesign.s1Desc": "Solte até 10 fotos.",
    "landing.resize.redesign.s2Title": "Definir Dimensões",
    "landing.resize.redesign.s2Desc": "Insira sua largura e altura alvo.",
    "landing.resize.redesign.s3Title": "Salvar",
    "landing.resize.redesign.s3Desc": "Baixe as fotos redimensionadas instantaneamente.",
    "landing.crop.redesign.heroBadge": "COMPOSIÇÃO INTELIGENTE",
    "landing.crop.redesign.heroTitle": "Corte o Ruído.",
    "landing.crop.redesign.heroTitle2": "Concentre-se no que Importa.",
    "landing.crop.redesign.heroDesc": "Enquadre perfeitamente suas fotos com corte de forma livre ou proporção fixa.",
    "landing.crop.redesign.feat1Title": "Seleção Livre",
    "landing.crop.redesign.feat1Desc": "Arraste livremente as bordas da caixa de corte para enquadrar o assunto.",
    "landing.crop.redesign.feat2Title": "Proporções Fixas",
    "landing.crop.redesign.feat2Desc": "Precisa de um quadrado perfeito? Bloqueie a proporção para mantê-la.",
    "landing.crop.redesign.feat3Title": "Extração sem Perdas",
    "landing.crop.redesign.feat3Desc": "Extraímos os pixels nativamente, garantindo zero perda de qualidade.",
    "landing.crop.redesign.stepsTag": "COMO CORTAR",
    "landing.crop.redesign.stepsTitle": "Enquadramento Perfeito em Segundos",
    "landing.crop.redesign.s1Title": "Enviar Foto",
    "landing.crop.redesign.s1Desc": "Arraste e solte sua imagem no espaço de trabalho.",
    "landing.crop.redesign.s2Title": "Arrastar a Caixa",
    "landing.crop.redesign.s2Desc": "Ajuste a área de corte usando as alças.",
    "landing.crop.redesign.s3Title": "Aplicar e Salvar",
    "landing.crop.redesign.s3Desc": "Pressione cortar e baixe a imagem extraída."
  },
  ro: {
    "landing.color.redesign.heroBadge": "STUDIO DE CULORI INSTANT",
    "landing.color.redesign.heroTitle": "Schimbă Culorile de Fundal în Timp Real",
    "landing.color.redesign.heroDesc": "Aplică culori solide, gradiente sau coduri HEX instantaneu. Perfect pentru fotografii de produse.",
    "landing.color.redesign.feat1Title": "Pânză de Culori Infinită",
    "landing.color.redesign.feat1Desc": "Alege din paleta noastră sau introdu un cod HEX pentru a se potrivi mărcii tale.",
    "landing.color.redesign.feat2Title": "Netezirea Marginilor",
    "landing.color.redesign.feat2Desc": "Culorile se îmbină natural cu marginile subiectului, evitând halourile pixelate.",
    "landing.color.redesign.feat3Title": "Previzualizare Live",
    "landing.color.redesign.feat3Desc": "Vezi schimbările de culoare instantaneu fără timpi de așteptare.",
    "landing.color.redesign.feat4Title": "100% Privat",
    "landing.color.redesign.feat4Desc": "Procesarea se face direct pe dispozitivul tău. Fără încărcări pe server.",
    "landing.color.redesign.whoTag": "UTILIZĂRI PROFESIONALE",
    "landing.color.redesign.whoTitle": "Construit pentru Creatori",
    "landing.color.redesign.who1Title": "Cataloage E-Commerce",
    "landing.color.redesign.who1Desc": "Standardizează fundalurile produselor pentru listări consistente.",
    "landing.color.redesign.who2Title": "Portrete de Profil",
    "landing.color.redesign.who2Desc": "Adaugă fundaluri izbitoare pe LinkedIn sau Twitter.",
    "landing.color.redesign.who3Title": "Materiale de Marketing",
    "landing.color.redesign.who3Desc": "Pregătește active transparente aplicând culorile mărcii.",
    "landing.color.redesign.stepsTitle": "Colorează în 3 Pași",
    "landing.color.redesign.s1Title": "Încarcă Imaginea",
    "landing.color.redesign.s1Desc": "Asigură-te că imaginea are un fundal transparent mai întâi.",
    "landing.color.redesign.s2Title": "Alege o Culoare",
    "landing.color.redesign.s2Desc": "Folosește selectorul de culori sau introdu un cod HEX.",
    "landing.color.redesign.s3Title": "Export",
    "landing.color.redesign.s3Desc": "Descarcă imaginea colorată la rezoluție maximă.",
    "landing.resize.redesign.heroBadge": "SCALARE PERFECTĂ A PIXELILOR",
    "landing.resize.redesign.heroTitle": "Redimensionează Imagini cu Precizie Absolută",
    "landing.resize.redesign.heroDesc": "Scalează-ți fotografiile cu dimensiuni exacte ale pixelilor sau procente.",
    "landing.resize.redesign.feat1Title": "Dimensiuni Exacte ale Pixelilor",
    "landing.resize.redesign.feat1Desc": "Preia controlul complet asupra dimensiunii imaginii. Introdu lățimea și înălțimea specifice.",
    "landing.resize.redesign.feat1Li1": "Blochează raportul de aspect",
    "landing.resize.redesign.feat1Li2": "Lățime și înălțime personalizate",
    "landing.resize.redesign.feat2Title": "Scalare Procentuală",
    "landing.resize.redesign.feat2Desc": "Folosește glisorul procentual pentru a scala imaginile rapid.",
    "landing.resize.redesign.feat2Li1": "Butoane rapide de 50% / 200%",
    "landing.resize.redesign.feat2Li2": "Menține calitatea vizuală",
    "landing.resize.redesign.socialTitle": "Perfect pentru Fiecare Platformă",
    "landing.resize.redesign.socialDesc": "Îndeplinește cu ușurință cerințele stricte de încărcare pe rețelele sociale.",
    "landing.resize.redesign.stepsTag": "CUM FUNCȚIONEAZĂ",
    "landing.resize.redesign.stepsTitle": "Redimensionează în 3 Pași",
    "landing.resize.redesign.s1Title": "Încarcă Fotografii",
    "landing.resize.redesign.s1Desc": "Trage până la 10 fotografii.",
    "landing.resize.redesign.s2Title": "Setează Dimensiunile",
    "landing.resize.redesign.s2Desc": "Introdu lățimea și înălțimea țintă.",
    "landing.resize.redesign.s3Title": "Salvează",
    "landing.resize.redesign.s3Desc": "Descarcă fotografiile redimensionate instantaneu.",
    "landing.crop.redesign.heroBadge": "COMPOZIȚIE INTELIGENTĂ",
    "landing.crop.redesign.heroTitle": "Taie Zgomotul.",
    "landing.crop.redesign.heroTitle2": "Concentrează-te pe ce Contează.",
    "landing.crop.redesign.heroDesc": "Încadrează-ți fotografiile perfect cu decupare liberă sau cu raport fix.",
    "landing.crop.redesign.feat1Title": "Selecție Liberă",
    "landing.crop.redesign.feat1Desc": "Trage liber marginile casetei de decupare pentru a-ți încadra subiectul.",
    "landing.crop.redesign.feat2Title": "Raporturi de Aspect Fixe",
    "landing.crop.redesign.feat2Desc": "Ai nevoie de un pătrat perfect? Blochează raportul de aspect.",
    "landing.crop.redesign.feat3Title": "Extracție Fără Pierderi",
    "landing.crop.redesign.feat3Desc": "Extragem pixelii nativ, asigurând pierdere de calitate zero.",
    "landing.crop.redesign.stepsTag": "CUM SĂ DECUPEZI",
    "landing.crop.redesign.stepsTitle": "Încadrare Perfectă în Câteva Secunde",
    "landing.crop.redesign.s1Title": "Încarcă Fotografia",
    "landing.crop.redesign.s1Desc": "Trage și plasează imaginea.",
    "landing.crop.redesign.s2Title": "Trage Caseta",
    "landing.crop.redesign.s2Desc": "Ajustează zona de decupare.",
    "landing.crop.redesign.s3Title": "Aplică și Salvează",
    "landing.crop.redesign.s3Desc": "Apasă decupare și descarcă imaginea."
  },
  ru: {
    "landing.color.redesign.heroBadge": "МГНОВЕННАЯ ЦВЕТНАЯ СТУДИЯ",
    "landing.color.redesign.heroTitle": "Изменение цвета фона в реальном времени",
    "landing.color.redesign.heroDesc": "Мгновенно применяйте сплошные цвета, градиенты или HEX-коды. Идеально для предметной фотографии.",
    "landing.color.redesign.feat1Title": "Бесконечный цветовой холст",
    "landing.color.redesign.feat1Desc": "Выберите из нашей палитры или введите любой HEX-код для соответствия вашему бренду.",
    "landing.color.redesign.feat2Title": "Сглаживание краев",
    "landing.color.redesign.feat2Desc": "Цвета естественно сливаются с краями вашего объекта, избегая пиксельных ореолов.",
    "landing.color.redesign.feat3Title": "Предпросмотр в реальном времени",
    "landing.color.redesign.feat3Desc": "Смотрите изменения цвета мгновенно без ожидания.",
    "landing.color.redesign.feat4Title": "100% Конфиденциально",
    "landing.color.redesign.feat4Desc": "Обработка происходит прямо на вашем устройстве. Никаких загрузок на сервер.",
    "landing.color.redesign.whoTag": "ПРОФЕССИОНАЛЬНОЕ ИСПОЛЬЗОВАНИЕ",
    "landing.color.redesign.whoTitle": "Создано для творцов",
    "landing.color.redesign.who1Title": "Каталоги E-Commerce",
    "landing.color.redesign.who1Desc": "Стандартизируйте фоны продуктов для единообразия магазина.",
    "landing.color.redesign.who2Title": "Профильные портреты",
    "landing.color.redesign.who2Desc": "Добавьте яркие фоны для LinkedIn или Twitter.",
    "landing.color.redesign.who3Title": "Маркетинговые материалы",
    "landing.color.redesign.who3Desc": "Подготовьте прозрачные ассеты, применяя цвета бренда.",
    "landing.color.redesign.stepsTitle": "Раскрасьте в 3 шага",
    "landing.color.redesign.s1Title": "Загрузить изображение",
    "landing.color.redesign.s1Desc": "Убедитесь, что у изображения сначала есть прозрачный фон.",
    "landing.color.redesign.s2Title": "Выбрать цвет",
    "landing.color.redesign.s2Desc": "Используйте палитру или введите HEX-код.",
    "landing.color.redesign.s3Title": "Экспорт",
    "landing.color.redesign.s3Desc": "Скачайте раскрашенное изображение в полном разрешении.",
    "landing.resize.redesign.heroBadge": "ИДЕАЛЬНОЕ МАСШТАБИРОВАНИЕ",
    "landing.resize.redesign.heroTitle": "Изменение размера с абсолютной точностью",
    "landing.resize.redesign.heroDesc": "Масштабируйте свои фотографии с точными размерами в пикселях или процентах.",
    "landing.resize.redesign.feat1Title": "Точные размеры в пикселях",
    "landing.resize.redesign.feat1Desc": "Возьмите полный контроль над размером изображения. Введите конкретную ширину и высоту.",
    "landing.resize.redesign.feat1Li1": "Блокировка соотношения сторон",
    "landing.resize.redesign.feat1Li2": "Пользовательская ширина и высота",
    "landing.resize.redesign.feat2Title": "Процентное масштабирование",
    "landing.resize.redesign.feat2Desc": "Используйте ползунок процентов для быстрого масштабирования.",
    "landing.resize.redesign.feat2Li1": "Быстрые кнопки 50% / 200%",
    "landing.resize.redesign.feat2Li2": "Сохраняет визуальное качество",
    "landing.resize.redesign.socialTitle": "Идеально для любой платформы",
    "landing.resize.redesign.socialDesc": "Без проблем выполняйте строгие требования социальных сетей.",
    "landing.resize.redesign.stepsTag": "КАК ЭТО РАБОТАЕТ",
    "landing.resize.redesign.stepsTitle": "Изменить размер в 3 шага",
    "landing.resize.redesign.s1Title": "Загрузить фото",
    "landing.resize.redesign.s1Desc": "Перетащите до 10 фотографий.",
    "landing.resize.redesign.s2Title": "Установить размеры",
    "landing.resize.redesign.s2Desc": "Введите целевую ширину и высоту.",
    "landing.resize.redesign.s3Title": "Сохранить",
    "landing.resize.redesign.s3Desc": "Мгновенно скачайте фото.",
    "landing.crop.redesign.heroBadge": "УМНАЯ КОМПОЗИЦИЯ",
    "landing.crop.redesign.heroTitle": "Отрежьте лишнее.",
    "landing.crop.redesign.heroTitle2": "Сфокусируйтесь на главном.",
    "landing.crop.redesign.heroDesc": "Идеально кадрируйте свои фотографии со свободной или фиксированной обрезкой.",
    "landing.crop.redesign.feat1Title": "Свободное выделение",
    "landing.crop.redesign.feat1Desc": "Свободно перетаскивайте края, чтобы кадрировать объект точно так, как вы хотите.",
    "landing.crop.redesign.feat2Title": "Фиксированные пропорции",
    "landing.crop.redesign.feat2Desc": "Нужен идеальный квадрат? Зафиксируйте пропорции.",
    "landing.crop.redesign.feat3Title": "Извлечение без потерь",
    "landing.crop.redesign.feat3Desc": "Мы извлекаем пиксели нативно, обеспечивая отсутствие потери качества.",
    "landing.crop.redesign.stepsTag": "КАК ОБРЕЗАТЬ",
    "landing.crop.redesign.stepsTitle": "Идеальное кадрирование за секунды",
    "landing.crop.redesign.s1Title": "Загрузить фото",
    "landing.crop.redesign.s1Desc": "Перетащите ваше изображение.",
    "landing.crop.redesign.s2Title": "Перетащить рамку",
    "landing.crop.redesign.s2Desc": "Отрегулируйте область обрезки.",
    "landing.crop.redesign.s3Title": "Применить и Сохранить",
    "landing.crop.redesign.s3Desc": "Нажмите обрезать и скачайте изображение."
  },
  sv: {
    "landing.color.redesign.heroBadge": "DIREKT FÄRGSTUDIO",
    "landing.color.redesign.heroTitle": "Ändra bakgrundsfärger i realtid",
    "landing.color.redesign.heroDesc": "Använd solida färger, övertoningar eller HEX-koder direkt. Perfekt för produktfotografering.",
    "landing.color.redesign.feat1Title": "Oändlig färgpalett",
    "landing.color.redesign.feat1Desc": "Välj från vår palett eller ange en HEX-kod för att matcha ditt varumärke.",
    "landing.color.redesign.feat2Title": "Kantutjämning",
    "landing.color.redesign.feat2Desc": "Färgerna smälter naturligt in i motivets kanter och undviker pixlade halos.",
    "landing.color.redesign.feat3Title": "Live-förhandsvisning",
    "landing.color.redesign.feat3Desc": "Se färgförändringar direkt utan väntetider.",
    "landing.color.redesign.feat4Title": "100% Privat",
    "landing.color.redesign.feat4Desc": "Bearbetningen sker direkt på din enhet. Inga serveruppladdningar.",
    "landing.color.redesign.whoTag": "PROFESSIONELL ANVÄNDNING",
    "landing.color.redesign.whoTitle": "Byggd för skapare",
    "landing.color.redesign.who1Title": "E-handelskataloger",
    "landing.color.redesign.who1Desc": "Standardisera produktbakgrunder för konsekventa butikslistor.",
    "landing.color.redesign.who2Title": "Profilporträtt",
    "landing.color.redesign.who2Desc": "Lägg till slående bakgrunder till LinkedIn eller Twitter.",
    "landing.color.redesign.who3Title": "Marknadsföringsmaterial",
    "landing.color.redesign.who3Desc": "Förbered transparenta tillgångar genom att tillämpa varumärkesfärger.",
    "landing.color.redesign.stepsTitle": "Färglägg i 3 steg",
    "landing.color.redesign.s1Title": "Ladda upp bild",
    "landing.color.redesign.s1Desc": "Se till att bilden har en transparent bakgrund först.",
    "landing.color.redesign.s2Title": "Välj färg",
    "landing.color.redesign.s2Desc": "Använd färgväljaren eller ange en HEX-kod.",
    "landing.color.redesign.s3Title": "Exportera",
    "landing.color.redesign.s3Desc": "Ladda ner din färgade bild i full upplösning.",
    "landing.resize.redesign.heroBadge": "PIXELPERFEKT SKALNING",
    "landing.resize.redesign.heroTitle": "Ändra storlek med absolut precision",
    "landing.resize.redesign.heroDesc": "Skala dina foton efter exakta pixeldimensioner eller procenttal.",
    "landing.resize.redesign.feat1Title": "Exakta pixeldimensioner",
    "landing.resize.redesign.feat1Desc": "Ta full kontroll över bildstorleken. Ange specifik bredd och höjd.",
    "landing.resize.redesign.feat1Li1": "Lås bildförhållande",
    "landing.resize.redesign.feat1Li2": "Anpassad bredd och höjd",
    "landing.resize.redesign.feat2Title": "Procentskalning",
    "landing.resize.redesign.feat2Desc": "Använd procentskjutreglaget för att snabbt skala bilder.",
    "landing.resize.redesign.feat2Li1": "Snabba 50% / 200% knappar",
    "landing.resize.redesign.feat2Li2": "Bibehåller visuell kvalitet",
    "landing.resize.redesign.socialTitle": "Perfekt för varje plattform",
    "landing.resize.redesign.socialDesc": "Uppfyll stränga uppladdningskrav för sociala medier utan problem.",
    "landing.resize.redesign.stepsTag": "HUR DET FUNGERAR",
    "landing.resize.redesign.stepsTitle": "Ändra storlek i 3 steg",
    "landing.resize.redesign.s1Title": "Ladda upp foton",
    "landing.resize.redesign.s1Desc": "Släpp upp till 10 foton.",
    "landing.resize.redesign.s2Title": "Ställ in dimensioner",
    "landing.resize.redesign.s2Desc": "Ange din målbredd och höjd.",
    "landing.resize.redesign.s3Title": "Spara",
    "landing.resize.redesign.s3Desc": "Ladda ner de storleksändrade fotona direkt.",
    "landing.crop.redesign.heroBadge": "SMART KOMPOSITION",
    "landing.crop.redesign.heroTitle": "Klipp bort bruset.",
    "landing.crop.redesign.heroTitle2": "Fokusera på det viktiga.",
    "landing.crop.redesign.heroDesc": "Rama in dina foton perfekt med fri eller fast beskärning.",
    "landing.crop.redesign.feat1Title": "Fritt val",
    "landing.crop.redesign.feat1Desc": "Dra kanterna fritt för att rama in ditt motiv precis som du vill.",
    "landing.crop.redesign.feat2Title": "Fasta bildförhållanden",
    "landing.crop.redesign.feat2Desc": "Behöver du en perfekt fyrkant? Lås bildförhållandet.",
    "landing.crop.redesign.feat3Title": "Förlustfri extrahering",
    "landing.crop.redesign.feat3Desc": "Vi extraherar pixlarna inbyggt och säkerställer noll kvalitetsförlust.",
    "landing.crop.redesign.stepsTag": "HUR MAN BESKÄR",
    "landing.crop.redesign.stepsTitle": "Perfekt inramning på sekunder",
    "landing.crop.redesign.s1Title": "Ladda upp foto",
    "landing.crop.redesign.s1Desc": "Dra och släpp din bild.",
    "landing.crop.redesign.s2Title": "Dra rutan",
    "landing.crop.redesign.s2Desc": "Justera beskärningsområdet.",
    "landing.crop.redesign.s3Title": "Tillämpa och spara",
    "landing.crop.redesign.s3Desc": "Tryck på beskär och ladda ner bilden."
  },
  th: {
    "landing.color.redesign.heroBadge": "สตูดิโอสีสำเร็จรูป",
    "landing.color.redesign.heroTitle": "เปลี่ยนสีพื้นหลังแบบเรียลไทม์",
    "landing.color.redesign.heroDesc": "ใช้สีทึบ การไล่ระดับสี หรือรหัส HEX ทันที เหมาะอย่างยิ่งสำหรับการถ่ายภาพผลิตภัณฑ์",
    "landing.color.redesign.feat1Title": "ผ้าใบสีที่ไม่มีที่สิ้นสุด",
    "landing.color.redesign.feat1Desc": "เลือกจากจานสีของเราหรือป้อนรหัส HEX เพื่อให้ตรงกับแบรนด์ของคุณ",
    "landing.color.redesign.feat2Title": "การปรับขอบให้เรียบ",
    "landing.color.redesign.feat2Desc": "สีกลมกลืนกับขอบวัตถุของคุณอย่างเป็นธรรมชาติ หลีกเลี่ยงรัศมีแบบพิกเซล",
    "landing.color.redesign.feat3Title": "พรีวิวสด",
    "landing.color.redesign.feat3Desc": "ดูการเปลี่ยนแปลงสีทันทีโดยไม่ต้องรอ",
    "landing.color.redesign.feat4Title": "ความเป็นส่วนตัว 100%",
    "landing.color.redesign.feat4Desc": "การประมวลผลทำได้โดยตรงบนอุปกรณ์ของคุณ ไม่มีการอัปโหลดเซิร์ฟเวอร์",
    "landing.color.redesign.whoTag": "การใช้งานระดับมืออาชีพ",
    "landing.color.redesign.whoTitle": "สร้างมาเพื่อนักสร้างสรรค์",
    "landing.color.redesign.who1Title": "แคตตาล็อกอีคอมเมิร์ซ",
    "landing.color.redesign.who1Desc": "สร้างมาตรฐานพื้นหลังผลิตภัณฑ์สำหรับรายชื่อร้านค้าที่สม่ำเสมอ",
    "landing.color.redesign.who2Title": "ภาพพอร์ตเทรตโปรไฟล์",
    "landing.color.redesign.who2Desc": "เพิ่มพื้นหลังที่โดดเด่นให้กับ LinkedIn หรือ Twitter",
    "landing.color.redesign.who3Title": "สื่อการตลาด",
    "landing.color.redesign.who3Desc": "เตรียมเนื้อหาที่โปร่งใสโดยใช้สีของแบรนด์",
    "landing.color.redesign.stepsTitle": "ระบายสีใน 3 ขั้นตอน",
    "landing.color.redesign.s1Title": "อัปโหลดภาพ",
    "landing.color.redesign.s1Desc": "ตรวจสอบให้แน่ใจว่าภาพมีพื้นหลังโปร่งใสก่อน",
    "landing.color.redesign.s2Title": "เลือกสี",
    "landing.color.redesign.s2Desc": "ใช้ตัวเลือกสีหรือป้อนรหัส HEX ของคุณ",
    "landing.color.redesign.s3Title": "ส่งออก",
    "landing.color.redesign.s3Desc": "ดาวน์โหลดภาพสีของคุณในความละเอียดเต็ม",
    "landing.resize.redesign.heroBadge": "การปรับขนาดพิกเซลที่สมบูรณ์แบบ",
    "landing.resize.redesign.heroTitle": "ปรับขนาดภาพด้วยความแม่นยำสูงสุด",
    "landing.resize.redesign.heroDesc": "ปรับขนาดภาพถ่ายของคุณตามขนาดพิกเซลที่แน่นอนหรือเปอร์เซ็นต์",
    "landing.resize.redesign.feat1Title": "ขนาดพิกเซลที่แน่นอน",
    "landing.resize.redesign.feat1Desc": "ควบคุมขนาดภาพอย่างสมบูรณ์ ป้อนความกว้างและความสูงเฉพาะ",
    "landing.resize.redesign.feat1Li1": "ล็อกอัตราส่วนภาพ",
    "landing.resize.redesign.feat1Li2": "ความกว้างและความสูงที่กำหนดเอง",
    "landing.resize.redesign.feat2Title": "การปรับขนาดเปอร์เซ็นต์",
    "landing.resize.redesign.feat2Desc": "ใช้แถบเลื่อนเปอร์เซ็นต์เพื่อปรับขนาดภาพอย่างรวดเร็ว",
    "landing.resize.redesign.feat2Li1": "ปุ่มด่วน 50% / 200%",
    "landing.resize.redesign.feat2Li2": "รักษาคุณภาพของภาพ",
    "landing.resize.redesign.socialTitle": "เหมาะสำหรับทุกแพลตฟอร์ม",
    "landing.resize.redesign.socialDesc": "ตรงตามข้อกำหนดการอัปโหลดโซเชียลมีเดียที่เข้มงวดโดยไม่ต้องยุ่งยาก",
    "landing.resize.redesign.stepsTag": "มันทำงานอย่างไร",
    "landing.resize.redesign.stepsTitle": "ปรับขนาดใน 3 ขั้นตอน",
    "landing.resize.redesign.s1Title": "อัปโหลดรูปภาพ",
    "landing.resize.redesign.s1Desc": "วางภาพถ่ายสูงสุด 10 ภาพ",
    "landing.resize.redesign.s2Title": "ตั้งค่าขนาด",
    "landing.resize.redesign.s2Desc": "ป้อนความกว้างและความสูงเป้าหมายของคุณ",
    "landing.resize.redesign.s3Title": "บันทึก",
    "landing.resize.redesign.s3Desc": "ดาวน์โหลดภาพที่ปรับขนาดได้ทันที",
    "landing.crop.redesign.heroBadge": "องค์ประกอบที่ชาญฉลาด",
    "landing.crop.redesign.heroTitle": "ตัดเสียงรบกวนออก",
    "landing.crop.redesign.heroTitle2": "มุ่งเน้นไปที่สิ่งที่สำคัญ",
    "landing.crop.redesign.heroDesc": "จัดกรอบภาพถ่ายของคุณอย่างสมบูรณ์แบบด้วยการครอบตัดแบบอิสระหรือแบบอัตราส่วนคงที่",
    "landing.crop.redesign.feat1Title": "การเลือกอิสระ",
    "landing.crop.redesign.feat1Desc": "ลากขอบกล่องครอบตัดอย่างอิสระเพื่อกำหนดกรอบหัวเรื่องของคุณ",
    "landing.crop.redesign.feat2Title": "อัตราส่วนภาพคงที่",
    "landing.crop.redesign.feat2Desc": "ต้องการสี่เหลี่ยมจัตุรัสที่สมบูรณ์แบบหรือไม่? ล็อกอัตราส่วน",
    "landing.crop.redesign.feat3Title": "การสกัดแบบไม่สูญเสีย",
    "landing.crop.redesign.feat3Desc": "เราดึงพิกเซลโดยธรรมชาติเพื่อให้แน่ใจว่าคุณภาพจะไม่ลดลงเลย",
    "landing.crop.redesign.stepsTag": "วิธีการครอบตัด",
    "landing.crop.redesign.stepsTitle": "การจัดกรอบที่สมบูรณ์แบบในไม่กี่วินาที",
    "landing.crop.redesign.s1Title": "อัปโหลดรูปภาพ",
    "landing.crop.redesign.s1Desc": "ลากและวางภาพของคุณ",
    "landing.crop.redesign.s2Title": "ลากกล่อง",
    "landing.crop.redesign.s2Desc": "ปรับพื้นที่ครอบตัด",
    "landing.crop.redesign.s3Title": "ใช้ & บันทึก",
    "landing.crop.redesign.s3Desc": "กดครอบตัดแล้วดาวน์โหลดภาพ"
  },
  tl: {
    "landing.color.redesign.heroBadge": "INSTANT COLOR STUDIO",
    "landing.color.redesign.heroTitle": "Baguhin ang Mga Kulay ng Background sa Real-Time",
    "landing.color.redesign.heroDesc": "Maglapat ng mga solidong kulay, gradient, o HEX code kaagad. Perpekto para sa photography ng produkto.",
    "landing.color.redesign.feat1Title": "Walang Hanggan na Canvas ng Kulay",
    "landing.color.redesign.feat1Desc": "Pumili mula sa aming palette o maglagay ng HEX code upang tumugma sa iyong brand.",
    "landing.color.redesign.feat2Title": "Edge Smoothing",
    "landing.color.redesign.feat2Desc": "Ang mga kulay ay natural na humahalo sa mga gilid ng iyong paksa.",
    "landing.color.redesign.feat3Title": "Live Preview",
    "landing.color.redesign.feat3Desc": "Makita agad ang mga pagbabago sa kulay nang walang paghihintay.",
    "landing.color.redesign.feat4Title": "100% Pribado",
    "landing.color.redesign.feat4Desc": "Ang pagpoproseso ay ginagawa mismo sa iyong device.",
    "landing.color.redesign.whoTag": "MGA PROPESYONAL NA PAGGAMIT",
    "landing.color.redesign.whoTitle": "Binuo para sa mga Tagalikha",
    "landing.color.redesign.who1Title": "E-Commerce Catalogs",
    "landing.color.redesign.who1Desc": "I-standardize ang mga background para sa pare-parehong listahan ng tindahan.",
    "landing.color.redesign.who2Title": "Profile Portraits",
    "landing.color.redesign.who2Desc": "Magdagdag ng kapansin-pansing background sa LinkedIn o Twitter.",
    "landing.color.redesign.who3Title": "Marketing Materials",
    "landing.color.redesign.who3Desc": "Maghanda ng mga transparent na asset gamit ang mga kulay ng brand.",
    "landing.color.redesign.stepsTitle": "Kulayan sa 3 Hakbang",
    "landing.color.redesign.s1Title": "Mag-upload ng Larawan",
    "landing.color.redesign.s1Desc": "Siguraduhing may transparent na background muna ang larawan.",
    "landing.color.redesign.s2Title": "Pumili ng Kulay",
    "landing.color.redesign.s2Desc": "Gumamit ng color picker o ilagay ang iyong HEX code.",
    "landing.color.redesign.s3Title": "I-export",
    "landing.color.redesign.s3Desc": "I-download ang iyong kinulayang larawan nang buong resolution.",
    "landing.resize.redesign.heroBadge": "PIXEL-PERFECT SCALING",
    "landing.resize.redesign.heroTitle": "I-resize ang Mga Larawan nang may Lubos na Katumpakan",
    "landing.resize.redesign.heroDesc": "I-scale ang iyong mga larawan ayon sa eksaktong sukat ng pixel o porsyento.",
    "landing.resize.redesign.feat1Title": "Eksaktong Sukat sa Pixel",
    "landing.resize.redesign.feat1Desc": "Ganap na kontrolin ang laki ng larawan. Maglagay ng tiyak na lapad at taas.",
    "landing.resize.redesign.feat1Li1": "I-lock ang aspect ratio",
    "landing.resize.redesign.feat1Li2": "Custom na lapad at taas",
    "landing.resize.redesign.feat2Title": "Percentage Scaling",
    "landing.resize.redesign.feat2Desc": "Gamitin ang percentage slider upang mabilis na i-scale ang mga larawan.",
    "landing.resize.redesign.feat2Li1": "Mabilis na 50% / 200% buttons",
    "landing.resize.redesign.feat2Li2": "Pinapanatili ang kalidad",
    "landing.resize.redesign.socialTitle": "Perpekto para sa Bawat Platform",
    "landing.resize.redesign.socialDesc": "Matugunan nang madali ang mahigpit na mga kinakailangan sa social media.",
    "landing.resize.redesign.stepsTag": "PAANO ITO GUMAGANA",
    "landing.resize.redesign.stepsTitle": "I-resize sa 3 Hakbang",
    "landing.resize.redesign.s1Title": "Mag-upload ng Larawan",
    "landing.resize.redesign.s1Desc": "Mag-drop ng hanggang 10 larawan.",
    "landing.resize.redesign.s2Title": "Itakda ang Dimensyon",
    "landing.resize.redesign.s2Desc": "Ilagay ang target na lapad at taas.",
    "landing.resize.redesign.s3Title": "I-save",
    "landing.resize.redesign.s3Desc": "I-download ang mga na-resize na larawan agad.",
    "landing.crop.redesign.heroBadge": "SMART COMPOSITION",
    "landing.crop.redesign.heroTitle": "Alisin ang Ingay.",
    "landing.crop.redesign.heroTitle2": "Tumutok sa Mahalaga.",
    "landing.crop.redesign.heroDesc": "I-frame ang iyong mga larawan nang perpekto gamit ang freeform o fixed-ratio crop.",
    "landing.crop.redesign.feat1Title": "Libreng Pagpili",
    "landing.crop.redesign.feat1Desc": "I-drag nang malaya ang mga gilid para i-frame ang iyong paksa.",
    "landing.crop.redesign.feat2Title": "Fixed Aspect Ratio",
    "landing.crop.redesign.feat2Desc": "Kailangan ng perpektong parisukat? I-lock ang aspect ratio.",
    "landing.crop.redesign.feat3Title": "Lossless Extraction",
    "landing.crop.redesign.feat3Desc": "Tinitiyak namin na walang pagkawala ng kalidad.",
    "landing.crop.redesign.stepsTag": "PAANO MAG-CROP",
    "landing.crop.redesign.stepsTitle": "Perpektong Framing sa Ilang Segundo",
    "landing.crop.redesign.s1Title": "Mag-upload ng Larawan",
    "landing.crop.redesign.s1Desc": "I-drag at i-drop ang iyong larawan.",
    "landing.crop.redesign.s2Title": "I-drag ang Kahon",
    "landing.crop.redesign.s2Desc": "I-adjust ang crop area.",
    "landing.crop.redesign.s3Title": "I-apply at I-save",
    "landing.crop.redesign.s3Desc": "Pindutin ang crop at i-download ang larawan."
  },
  tr: {
    "landing.color.redesign.heroBadge": "ANINDA RENK STÜDYOSU",
    "landing.color.redesign.heroTitle": "Arka Plan Renklerini Gerçek Zamanlı Değiştirin",
    "landing.color.redesign.heroDesc": "Düz renkleri, degradeleri veya HEX kodlarını anında uygulayın. Ürün fotoğrafçılığı için mükemmel.",
    "landing.color.redesign.feat1Title": "Sonsuz Renk Tuvali",
    "landing.color.redesign.feat1Desc": "Paletimizden seçin veya markanıza uyması için herhangi bir HEX kodu girin.",
    "landing.color.redesign.feat2Title": "Kenar Yumuşatma",
    "landing.color.redesign.feat2Desc": "Renkler, öznenizin kenarlarıyla doğal bir şekilde karışarak pikselli haleleri önler.",
    "landing.color.redesign.feat3Title": "Canlı Önizleme",
    "landing.color.redesign.feat3Desc": "Renk değişikliklerini bekleme süreleri olmadan anında görün.",
    "landing.color.redesign.feat4Title": "%100 Gizlilik",
    "landing.color.redesign.feat4Desc": "İşlem doğrudan cihazınızda yapılır. Sunucu yüklemesi yok.",
    "landing.color.redesign.whoTag": "PROFESYONEL KULLANIMLAR",
    "landing.color.redesign.whoTitle": "Yaratıcılar için Üretildi",
    "landing.color.redesign.who1Title": "E-Ticaret Katalogları",
    "landing.color.redesign.who1Desc": "Tutarlı mağaza listeleri için ürün arka planlarını standartlaştırın.",
    "landing.color.redesign.who2Title": "Profil Portreleri",
    "landing.color.redesign.who2Desc": "LinkedIn veya Twitter'a çarpıcı arka planlar ekleyin.",
    "landing.color.redesign.who3Title": "Pazarlama Materyalleri",
    "landing.color.redesign.who3Desc": "Marka renklerini uygulayarak şeffaf varlıklar hazırlayın.",
    "landing.color.redesign.stepsTitle": "3 Adımda Renklendir",
    "landing.color.redesign.s1Title": "Görsel Yükle",
    "landing.color.redesign.s1Desc": "Önce görselinizin şeffaf bir arka plana sahip olduğundan emin olun.",
    "landing.color.redesign.s2Title": "Renk Seçin",
    "landing.color.redesign.s2Desc": "Renk seçiciyi kullanın veya HEX kodunuzu girin.",
    "landing.color.redesign.s3Title": "Dışa Aktar",
    "landing.color.redesign.s3Desc": "Renklendirilmiş görselinizi tam çözünürlükte indirin.",
    "landing.resize.redesign.heroBadge": "MÜKEMMEL ÖLÇEKLENDİRME",
    "landing.resize.redesign.heroTitle": "Görselleri Mutlak Hassasiyetle Yeniden Boyutlandırın",
    "landing.resize.redesign.heroDesc": "Fotoğraflarınızı tam piksel boyutlarına veya yüzdelere göre ölçeklendirin.",
    "landing.resize.redesign.feat1Title": "Kesin Piksel Boyutları",
    "landing.resize.redesign.feat1Desc": "Görsel boyutunda tam kontrol sağlayın. Belirli genişlik ve yükseklik girin.",
    "landing.resize.redesign.feat1Li1": "En boy oranını kilitle",
    "landing.resize.redesign.feat1Li2": "Özel genişlik ve yükseklik",
    "landing.resize.redesign.feat2Title": "Yüzde Ölçeklendirme",
    "landing.resize.redesign.feat2Desc": "Görselleri hızlı bir şekilde ölçeklendirmek için yüzde kaydırıcısını kullanın.",
    "landing.resize.redesign.feat2Li1": "Hızlı %50 / %200 düğmeleri",
    "landing.resize.redesign.feat2Li2": "Görsel kaliteyi korur",
    "landing.resize.redesign.socialTitle": "Her Platform İçin Mükemmel",
    "landing.resize.redesign.socialDesc": "Sosyal medya yükleme gereksinimlerini sorunsuzca karşılayın.",
    "landing.resize.redesign.stepsTag": "NASIL ÇALIŞIR",
    "landing.resize.redesign.stepsTitle": "3 Adımda Yeniden Boyutlandır",
    "landing.resize.redesign.s1Title": "Fotoğraf Yükle",
    "landing.resize.redesign.s1Desc": "10 adede kadar fotoğraf bırakın.",
    "landing.resize.redesign.s2Title": "Boyutları Ayarla",
    "landing.resize.redesign.s2Desc": "Hedef genişlik ve yüksekliğinizi girin.",
    "landing.resize.redesign.s3Title": "Kaydet",
    "landing.resize.redesign.s3Desc": "Yeniden boyutlandırılan fotoğrafları anında indirin.",
    "landing.crop.redesign.heroBadge": "AKILLI KOMPOZİSYON",
    "landing.crop.redesign.heroTitle": "Gürültüyü kesin.",
    "landing.crop.redesign.heroTitle2": "Önemli olana odaklanın.",
    "landing.crop.redesign.heroDesc": "Serbest biçimli veya sabit oranlı kırpma ile fotoğraflarınızı mükemmel şekilde çerçeveleyin.",
    "landing.crop.redesign.feat1Title": "Serbest Seçim",
    "landing.crop.redesign.feat1Desc": "Öznenizi tam olarak çerçevelemek için kırpma kutusunun kenarlarını serbestçe sürükleyin.",
    "landing.crop.redesign.feat2Title": "Sabit En Boy Oranları",
    "landing.crop.redesign.feat2Desc": "Mükemmel bir kareye mi ihtiyacınız var? Oranları korumak için oranı kilitleyin.",
    "landing.crop.redesign.feat3Title": "Kayıpsız Çıkarma",
    "landing.crop.redesign.feat3Desc": "Kaliteden ödün vermediğinden emin olmak için pikselleri yerel olarak çıkarıyoruz.",
    "landing.crop.redesign.stepsTag": "NASIL KIRPILIR",
    "landing.crop.redesign.stepsTitle": "Saniyeler İçinde Mükemmel Çerçeveleme",
    "landing.crop.redesign.s1Title": "Fotoğraf Yükle",
    "landing.crop.redesign.s1Desc": "Görselinizi çalışma alanına sürükleyip bırakın.",
    "landing.crop.redesign.s2Title": "Kutuyu Sürükle",
    "landing.crop.redesign.s2Desc": "Tutamakları kullanarak kırpma alanını ayarlayın.",
    "landing.crop.redesign.s3Title": "Uygula ve Kaydet",
    "landing.crop.redesign.s3Desc": "Kırp'a basın ve görselinizi indirin."
  },
  uk: {
    "landing.color.redesign.heroBadge": "МИТТЄВА КОЛЬОРОВА СТУДІЯ",
    "landing.color.redesign.heroTitle": "Зміна кольору фону в реальному часі",
    "landing.color.redesign.heroDesc": "Миттєво застосовуйте суцільні кольори, градієнти або HEX-коди. Ідеально для предметної фотографії.",
    "landing.color.redesign.feat1Title": "Нескінченне кольорове полотно",
    "landing.color.redesign.feat1Desc": "Оберіть з нашої палітри або введіть будь-який HEX-код для вашого бренду.",
    "landing.color.redesign.feat2Title": "Згладжування країв",
    "landing.color.redesign.feat2Desc": "Кольори природно зливаються з краями вашого об'єкта, уникаючи піксельних ореолів.",
    "landing.color.redesign.feat3Title": "Попередній перегляд наживо",
    "landing.color.redesign.feat3Desc": "Бачте зміни кольору миттєво без очікування.",
    "landing.color.redesign.feat4Title": "100% Конфіденційно",
    "landing.color.redesign.feat4Desc": "Обробка відбувається прямо на вашому пристрої. Жодних завантажень на сервер.",
    "landing.color.redesign.whoTag": "ПРОФЕСІЙНЕ ВИКОРИСТАННЯ",
    "landing.color.redesign.whoTitle": "Створено для творців",
    "landing.color.redesign.who1Title": "Каталоги E-Commerce",
    "landing.color.redesign.who1Desc": "Стандартизуйте фони продуктів для одноманітності магазину.",
    "landing.color.redesign.who2Title": "Профільні портрети",
    "landing.color.redesign.who2Desc": "Додайте яскраві фони для LinkedIn або Twitter.",
    "landing.color.redesign.who3Title": "Маркетингові матеріали",
    "landing.color.redesign.who3Desc": "Підготуйте прозорі активи, застосовуючи кольори бренду.",
    "landing.color.redesign.stepsTitle": "Розфарбуйте за 3 кроки",
    "landing.color.redesign.s1Title": "Завантажити зображення",
    "landing.color.redesign.s1Desc": "Спочатку переконайтеся, що зображення має прозорий фон.",
    "landing.color.redesign.s2Title": "Вибрати колір",
    "landing.color.redesign.s2Desc": "Використовуйте палітру або введіть HEX-код.",
    "landing.color.redesign.s3Title": "Експорт",
    "landing.color.redesign.s3Desc": "Завантажте розфарбоване зображення у повній роздільній здатності.",
    "landing.resize.redesign.heroBadge": "ІДЕАЛЬНЕ МАСШТАБУВАННЯ",
    "landing.resize.redesign.heroTitle": "Зміна розміру з абсолютною точністю",
    "landing.resize.redesign.heroDesc": "Масштабуйте свої фотографії за точними розмірами в пікселях або відсотках.",
    "landing.resize.redesign.feat1Title": "Точні розміри в пікселях",
    "landing.resize.redesign.feat1Desc": "Візьміть повний контроль над розміром зображення. Введіть ширину та висоту.",
    "landing.resize.redesign.feat1Li1": "Блокування співвідношення сторін",
    "landing.resize.redesign.feat1Li2": "Власна ширина та висота",
    "landing.resize.redesign.feat2Title": "Відсоткове масштабування",
    "landing.resize.redesign.feat2Desc": "Використовуйте повзунок відсотків для швидкого масштабування.",
    "landing.resize.redesign.feat2Li1": "Швидкі кнопки 50% / 200%",
    "landing.resize.redesign.feat2Li2": "Зберігає візуальну якість",
    "landing.resize.redesign.socialTitle": "Ідеально для будь-якої платформи",
    "landing.resize.redesign.socialDesc": "Без проблем виконуйте суворі вимоги соціальних мереж.",
    "landing.resize.redesign.stepsTag": "ЯК ЦЕ ПРАЦЮЄ",
    "landing.resize.redesign.stepsTitle": "Змінити розмір за 3 кроки",
    "landing.resize.redesign.s1Title": "Завантажити фото",
    "landing.resize.redesign.s1Desc": "Перетягніть до 10 фотографій.",
    "landing.resize.redesign.s2Title": "Встановити розміри",
    "landing.resize.redesign.s2Desc": "Введіть цільову ширину та висоту.",
    "landing.resize.redesign.s3Title": "Зберегти",
    "landing.resize.redesign.s3Desc": "Миттєво завантажте фото.",
    "landing.crop.redesign.heroBadge": "РОЗУМНА КОМПОЗИЦІЯ",
    "landing.crop.redesign.heroTitle": "Відріжте зайве.",
    "landing.crop.redesign.heroTitle2": "Сфокусуйтеся на головному.",
    "landing.crop.redesign.heroDesc": "Ідеально кадруйте свої фотографії з вільним або фіксованим обрізанням.",
    "landing.crop.redesign.feat1Title": "Вільне виділення",
    "landing.crop.redesign.feat1Desc": "Вільно перетягуйте краї, щоб кадрувати об'єкт так, як ви хочете.",
    "landing.crop.redesign.feat2Title": "Фіксовані пропорції",
    "landing.crop.redesign.feat2Desc": "Потрібен ідеальний квадрат? Зафіксуйте пропорції.",
    "landing.crop.redesign.feat3Title": "Вилучення без втрат",
    "landing.crop.redesign.feat3Desc": "Ми витягуємо пікселі нативно, забезпечуючи відсутність втрати якості.",
    "landing.crop.redesign.stepsTag": "ЯК ОБРІЗАТИ",
    "landing.crop.redesign.stepsTitle": "Ідеальне кадрування за секунди",
    "landing.crop.redesign.s1Title": "Завантажити фото",
    "landing.crop.redesign.s1Desc": "Перетягніть ваше зображення.",
    "landing.crop.redesign.s2Title": "Перетягнути рамку",
    "landing.crop.redesign.s2Desc": "Відрегулюйте область обрізання.",
    "landing.crop.redesign.s3Title": "Застосувати та Зберегти",
    "landing.crop.redesign.s3Desc": "Натисніть обрізати і завантажте зображення."
  },
  vi: {
    "landing.color.redesign.heroBadge": "STUDIO MÀU SẮC TỨC THÌ",
    "landing.color.redesign.heroTitle": "Thay đổi Màu nền trong Thời gian Thực",
    "landing.color.redesign.heroDesc": "Áp dụng màu đồng nhất, dải màu hoặc mã HEX ngay lập tức. Hoàn hảo cho chụp ảnh sản phẩm.",
    "landing.color.redesign.feat1Title": "Bảng Màu Vô Tận",
    "landing.color.redesign.feat1Desc": "Chọn từ bảng màu của chúng tôi hoặc nhập bất kỳ mã HEX nào để phù hợp với thương hiệu.",
    "landing.color.redesign.feat2Title": "Làm Mịn Cạnh",
    "landing.color.redesign.feat2Desc": "Màu sắc hòa trộn tự nhiên với các cạnh của đối tượng, tránh viền pixel.",
    "landing.color.redesign.feat3Title": "Xem Trước Trực Tiếp",
    "landing.color.redesign.feat3Desc": "Xem các thay đổi màu sắc ngay lập tức mà không phải chờ đợi.",
    "landing.color.redesign.feat4Title": "100% Riêng tư",
    "landing.color.redesign.feat4Desc": "Xử lý trực tiếp trên thiết bị của bạn. Không tải lên máy chủ.",
    "landing.color.redesign.whoTag": "SỬ DỤNG CHUYÊN NGHIỆP",
    "landing.color.redesign.whoTitle": "Được xây dựng cho Người sáng tạo",
    "landing.color.redesign.who1Title": "Danh mục E-Commerce",
    "landing.color.redesign.who1Desc": "Tiêu chuẩn hóa nền sản phẩm cho các danh sách cửa hàng nhất quán.",
    "landing.color.redesign.who2Title": "Ảnh Hồ sơ",
    "landing.color.redesign.who2Desc": "Thêm hình nền nổi bật cho LinkedIn hoặc Twitter.",
    "landing.color.redesign.who3Title": "Tài liệu Tiếp thị",
    "landing.color.redesign.who3Desc": "Chuẩn bị tài sản trong suốt bằng cách áp dụng màu sắc thương hiệu.",
    "landing.color.redesign.stepsTitle": "Tô màu trong 3 Bước",
    "landing.color.redesign.s1Title": "Tải Ảnh Lên",
    "landing.color.redesign.s1Desc": "Đảm bảo ảnh có nền trong suốt trước tiên.",
    "landing.color.redesign.s2Title": "Chọn Màu",
    "landing.color.redesign.s2Desc": "Sử dụng bảng chọn màu hoặc nhập mã HEX của bạn.",
    "landing.color.redesign.s3Title": "Xuất",
    "landing.color.redesign.s3Desc": "Tải xuống hình ảnh màu của bạn ở độ phân giải đầy đủ.",
    "landing.resize.redesign.heroBadge": "ĐỔI KÍCH THƯỚC HOÀN HẢO",
    "landing.resize.redesign.heroTitle": "Đổi Kích Thước Ảnh với Độ Chính Xác Tuyệt Đối",
    "landing.resize.redesign.heroDesc": "Chỉnh tỷ lệ ảnh theo kích thước pixel hoặc phần trăm chính xác.",
    "landing.resize.redesign.feat1Title": "Kích Thước Pixel Chính Xác",
    "landing.resize.redesign.feat1Desc": "Kiểm soát hoàn toàn kích thước hình ảnh. Nhập chiều rộng và chiều cao cụ thể.",
    "landing.resize.redesign.feat1Li1": "Khóa tỷ lệ khung hình",
    "landing.resize.redesign.feat1Li2": "Chiều rộng & chiều cao tùy chỉnh",
    "landing.resize.redesign.feat2Title": "Chỉnh Tỷ Lệ Phần Trăm",
    "landing.resize.redesign.feat2Desc": "Sử dụng thanh trượt phần trăm để đổi kích thước ảnh nhanh chóng.",
    "landing.resize.redesign.feat2Li1": "Nút nhanh 50% / 200%",
    "landing.resize.redesign.feat2Li2": "Duy trì chất lượng hình ảnh",
    "landing.resize.redesign.socialTitle": "Hoàn Hảo Cho Mọi Nền Tảng",
    "landing.resize.redesign.socialDesc": "Đáp ứng các yêu cầu tải lên mạng xã hội nghiêm ngặt mà không gặp rắc rối.",
    "landing.resize.redesign.stepsTag": "CÁCH HOẠT ĐỘNG",
    "landing.resize.redesign.stepsTitle": "Đổi Kích Thước Trong 3 Bước",
    "landing.resize.redesign.s1Title": "Tải Ảnh Lên",
    "landing.resize.redesign.s1Desc": "Kéo thả tối đa 10 ảnh.",
    "landing.resize.redesign.s2Title": "Đặt Kích Thước",
    "landing.resize.redesign.s2Desc": "Nhập chiều rộng và chiều cao mục tiêu.",
    "landing.resize.redesign.s3Title": "Lưu",
    "landing.resize.redesign.s3Desc": "Tải xuống các ảnh đã đổi kích thước ngay lập tức.",
    "landing.crop.redesign.heroBadge": "BỐ CỤC THÔNG MINH",
    "landing.crop.redesign.heroTitle": "Cắt Bỏ Sự Lộn Xộn.",
    "landing.crop.redesign.heroTitle2": "Tập Trung Vào Trọng Tâm.",
    "landing.crop.redesign.heroDesc": "Đóng khung ảnh của bạn một cách hoàn hảo với cắt tự do hoặc tỷ lệ cố định.",
    "landing.crop.redesign.feat1Title": "Lựa Chọn Tự Do",
    "landing.crop.redesign.feat1Desc": "Kéo các cạnh của hộp cắt tự do để đóng khung đối tượng của bạn.",
    "landing.crop.redesign.feat2Title": "Tỷ Lệ Khung Hình Cố Định",
    "landing.crop.redesign.feat2Desc": "Cần một hình vuông hoàn hảo? Khóa tỷ lệ khung hình.",
    "landing.crop.redesign.feat3Title": "Trích Xuất Không Mất Chất Lượng",
    "landing.crop.redesign.feat3Desc": "Chúng tôi trích xuất pixel tự nhiên đảm bảo chất lượng không suy giảm.",
    "landing.crop.redesign.stepsTag": "CÁCH CẮT ẢNH",
    "landing.crop.redesign.stepsTitle": "Đóng Khung Hoàn Hảo Trong Giây Lát",
    "landing.crop.redesign.s1Title": "Tải Ảnh",
    "landing.crop.redesign.s1Desc": "Kéo và thả hình ảnh của bạn.",
    "landing.crop.redesign.s2Title": "Kéo Khung",
    "landing.crop.redesign.s2Desc": "Điều chỉnh vùng cắt ảnh.",
    "landing.crop.redesign.s3Title": "Áp Dụng & Lưu",
    "landing.crop.redesign.s3Desc": "Nhấn cắt và tải xuống hình ảnh."
  },
  zh: {
    "landing.color.redesign.heroBadge": "即时色彩工作室",
    "landing.color.redesign.heroTitle": "实时更改背景颜色",
    "landing.color.redesign.heroDesc": "即时应用纯色、渐变或十六进制颜色代码。非常适合产品摄影，完全在您的浏览器中运行。",
    "landing.color.redesign.feat1Title": "无限色彩画布",
    "landing.color.redesign.feat1Desc": "从我们的调色板中选择或输入任何 HEX/RGB 代码以匹配您的品牌。",
    "landing.color.redesign.feat2Title": "边缘平滑",
    "landing.color.redesign.feat2Desc": "颜色自然融入拍摄对象的边缘，避免像素化光环。",
    "landing.color.redesign.feat3Title": "实时预览",
    "landing.color.redesign.feat3Desc": "无需等待即可立即看到颜色变化。",
    "landing.color.redesign.feat4Title": "100% 隐私",
    "landing.color.redesign.feat4Desc": "处理直接在您的设备上呈现。没有服务器上传。",
    "landing.color.redesign.whoTag": "专业用途",
    "landing.color.redesign.whoTitle": "为创作者打造",
    "landing.color.redesign.who1Title": "电商目录",
    "landing.color.redesign.who1Desc": "标准化产品背景以获得一致的商店列表。",
    "landing.color.redesign.who2Title": "个人头像",
    "landing.color.redesign.who2Desc": "为 LinkedIn 或 Twitter 添加引人注目的背景。",
    "landing.color.redesign.who3Title": "营销材料",
    "landing.color.redesign.who3Desc": "通过应用品牌色彩来准备透明资产。",
    "landing.color.redesign.stepsTitle": "3步填色",
    "landing.color.redesign.s1Title": "上传图片",
    "landing.color.redesign.s1Desc": "首先确保您的图像具有透明背景。",
    "landing.color.redesign.s2Title": "选择颜色",
    "landing.color.redesign.s2Desc": "使用拾色器或输入您的十六进制代码。",
    "landing.color.redesign.s3Title": "导出",
    "landing.color.redesign.s3Desc": "以全分辨率下载新着色的图像。",
    "landing.resize.redesign.heroBadge": "像素级完美缩放",
    "landing.resize.redesign.heroTitle": "以绝对的精度调整图像大小",
    "landing.resize.redesign.heroDesc": "按精确的像素尺寸或百分比缩放您的照片。",
    "landing.resize.redesign.feat1Title": "精确的像素尺寸",
    "landing.resize.redesign.feat1Desc": "完全控制图像大小。输入特定的宽度和高度。",
    "landing.resize.redesign.feat1Li1": "锁定纵横比",
    "landing.resize.redesign.feat1Li2": "自定义宽度和高度",
    "landing.resize.redesign.feat2Title": "百分比缩放",
    "landing.resize.redesign.feat2Desc": "使用百分比滑块快速成比例地缩放图像。",
    "landing.resize.redesign.feat2Li1": "快速 50% / 200% 按钮",
    "landing.resize.redesign.feat2Li2": "保持视觉质量",
    "landing.resize.redesign.socialTitle": "完美适用于每个平台",
    "landing.resize.redesign.socialDesc": "轻松满足社交媒体严格的上传要求。",
    "landing.resize.redesign.stepsTag": "工作原理",
    "landing.resize.redesign.stepsTitle": "3步调整大小",
    "landing.resize.redesign.s1Title": "上传照片",
    "landing.resize.redesign.s1Desc": "最多放入 10 张照片。",
    "landing.resize.redesign.s2Title": "设置尺寸",
    "landing.resize.redesign.s2Desc": "输入您的目标宽度和高度。",
    "landing.resize.redesign.s3Title": "保存",
    "landing.resize.redesign.s3Desc": "立即下载调整大小的照片。",
    "landing.crop.redesign.heroBadge": "智能构图",
    "landing.crop.redesign.heroTitle": "剪去噪音。",
    "landing.crop.redesign.heroTitle2": "专注于重要的事情。",
    "landing.crop.redesign.heroDesc": "使用自由格式或固定比例裁剪完美构图您的照片。",
    "landing.crop.redesign.feat1Title": "自由选择",
    "landing.crop.redesign.feat1Desc": "自由拖动裁剪框边缘以完全按照您的意愿构图。",
    "landing.crop.redesign.feat2Title": "固定长宽比",
    "landing.crop.redesign.feat2Desc": "需要一个完美的正方形？锁定纵横比以保持比例。",
    "landing.crop.redesign.feat3Title": "无损提取",
    "landing.crop.redesign.feat3Desc": "我们原生提取像素，确保质量零损失。",
    "landing.crop.redesign.stepsTag": "如何裁剪",
    "landing.crop.redesign.stepsTitle": "几秒钟内完美取景",
    "landing.crop.redesign.s1Title": "上传照片",
    "landing.crop.redesign.s1Desc": "拖放您的图像。",
    "landing.crop.redesign.s2Title": "拖动框",
    "landing.crop.redesign.s2Desc": "调整裁剪区域。",
    "landing.crop.redesign.s3Title": "应用并保存",
    "landing.crop.redesign.s3Desc": "点击裁剪并下载图像。"
  }
};

async function run() {
  for (const [lang, keys] of Object.entries(translations)) {
    const filePath = path.join(localesDir, lang, 'translation.json');
    if (!fs.existsSync(filePath)) continue;
    
    const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));

    for (const [key, value] of Object.entries(keys)) {
      data[key] = value;
    }
    
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
    console.log(`[${lang}] Successfully injected part 2`);
  }
}

run().catch(console.error);
