const fs = require('fs');
const path = require('path');

const translations = {
  sv: {
    "landing.compress.redesign.heroBadge": "SMART KOMPRIMERING",
    "landing.compress.redesign.heroTitle": "Krymp bildfilstorleken med upp till 90 % direkt",
    "landing.compress.redesign.heroDesc": "Minska storleken på dina foton utan att förlora visuell kvalitet. Perfekt för webbplatser och e-post.",
    "landing.compress.redesign.feat1Badge": "INGEN KVALITETSFÖRLUST",
    "landing.compress.redesign.feat1Title": "Smart optimering",
    "landing.compress.redesign.feat1Desc": "Hittar automatiskt den perfekta balansen mellan minimal filstorlek och maximal bildkvalitet.",
    "landing.compress.redesign.feat2Badge": "100 % PRIVAT",
    "landing.compress.redesign.feat2Title": "Inga uppladdningar",
    "landing.compress.redesign.feat2Desc": "Liksom alla våra verktyg sker komprimeringen direkt i din webbläsare. Inget skickas till någon server.",
    "landing.compress.redesign.feat3Badge": "VALFRITT FORMAT",
    "landing.compress.redesign.feat3Title": "Brett stöd",
    "landing.compress.redesign.feat3Desc": "Fungerar med standard JPG- och PNG-format samt moderna WEBP-format.",
    "landing.compress.redesign.whoTag": "VEM ÄR DET FÖR",
    "landing.compress.redesign.whoTitle": "Byggt för webb och media",
    "landing.compress.redesign.whoDesc": "Perfekt för utvecklare, designers och sociala medier-ansvariga som behöver optimerade bilder.",
    "landing.compress.redesign.who1Title": "Webbutvecklare",
    "landing.compress.redesign.who1Desc": "Förbättra PageSpeed-poäng och minska laddningstider utan att offra bildkvalitet.",
    "landing.compress.redesign.who1Tags": "SEO-OPTIMERING",
    "landing.compress.redesign.who2Title": "Innehållsskapare",
    "landing.compress.redesign.who2Desc": "Möt strikta uppladdningsgränser för plattformar som Discord eller Twitter.",
    "landing.compress.redesign.who2Tags": "SOCIALA MEDIER",
    "landing.compress.redesign.stepsTag": "HUR DET FUNGERAR",
    "landing.compress.redesign.stepsTitle": "3 steg för optimering",
    "landing.compress.redesign.s1Title": "Ladda upp bilder",
    "landing.compress.redesign.s1Desc": "Dra och släpp dina foton till komprimeringsarbetsytan.",
    "landing.compress.redesign.s2Title": "Ställ in komprimeringsnivå",
    "landing.compress.redesign.s2Desc": "Justera kvalitetsreglaget för att hitta rätt balans.",
    "landing.compress.redesign.s3Title": "Spara lagringsutrymme",
    "landing.compress.redesign.s3Desc": "Ladda ner dina optimerade bilder och njut av minskade filstorlekar.",
    "landing.remove.redesign.heroBadge": "AI-DRIVEN UTSKÄRNING",
    "landing.remove.redesign.heroTitle": "Ta bort bakgrunden på 1 sekund med felfri precision",
    "landing.remove.redesign.heroDesc": "Driven av avancerad WebAssembly AI, få perfekta hårutskärningar och jämna kanter.",
    "landing.remove.redesign.feat1Badge": "99,8 % NOGGRANNHET",
    "landing.remove.redesign.feat1Title": "Felfri hår- och kantdetektering",
    "landing.remove.redesign.feat1Desc": "Vårt neurala nätverk hanterar enkelt komplexa detaljer som människohår och djurpäls.",
    "landing.remove.redesign.feat2Badge": "100 % SÄKERT",
    "landing.remove.redesign.feat2Title": "Komplett offline-integritet",
    "landing.remove.redesign.feat2Desc": "AI-modellen laddas direkt i din webbläsare. Dina bilder lämnar aldrig din dator.",
    "landing.remove.redesign.feat3Badge": "BATCHLÄGE",
    "landing.remove.redesign.feat3Title": "Klar för massbearbetning",
    "landing.remove.redesign.feat3Desc": "Dra och släpp upp till 10 foton samtidigt och ladda ner allt i en ZIP-fil.",
    "landing.remove.redesign.whoTag": "VEM ÄR DET FÖR",
    "landing.remove.redesign.whoTitle": "Perfekt för alla kreativa behov",
    "landing.remove.redesign.whoDesc": "Oavsett om du säljer bilar, designar affischer eller skapar officiella dokument.",
    "landing.remove.redesign.who1Title": "E-handelssäljare",
    "landing.remove.redesign.who1Desc": "Skapa rena vita bakgrunder för produktlistor.",
    "landing.remove.redesign.who1Tags": "PRODUKTLISTOR",
    "landing.remove.redesign.who2Title": "Grafiska designers",
    "landing.remove.redesign.who2Desc": "Extrahera logotyper, signaturer och tillgångar omedelbart.",
    "landing.remove.redesign.who2Tags": "DESIGNA TILLGÅNGAR",
    "landing.remove.redesign.stepsTag": "HUR DET FUNGERAR",
    "landing.remove.redesign.stepsTitle": "3 steg till transparenta bakgrunder",
    "landing.remove.redesign.s1Title": "Ladda upp bild",
    "landing.remove.redesign.s1Desc": "Dra och släpp ditt foto. PNG, JPG eller WEBP.",
    "landing.remove.redesign.s2Title": "AI-bearbetning",
    "landing.remove.redesign.s2Desc": "Den lokala AI:n upptäcker huvudmotivet på 1 sekund.",
    "landing.remove.redesign.s3Title": "Ladda ner HD",
    "landing.remove.redesign.s3Desc": "Exportera ditt utskurna foto med en transparent bakgrund.",
    "home.why.tag": "VARFÖR HELPMYIMG",
    "home.why.title": "Varför HelpMyIMG är det smartaste valet",
    "home.why.desc": "Designad från grunden för maximal integritet, blixtsnabb hastighet och noll kostnad.",
    "home.why.c1.t": "Omedelbar lokal hastighet",
    "home.why.c1.d": "Dina foton bearbetas direkt i enhetens minne med noll fördröjning.",
    "home.why.c1.b": "0ms Serverfördröjning",
    "home.why.c2.t": "100 % Absolut integritet",
    "home.why.c2.d": "Dina personliga porträtt och konfidentiella dokument lämnar aldrig datorn.",
    "home.why.c2.b": "Ingen molnlagring",
    "home.why.c3.t": "För alltid gratis och obegränsat",
    "home.why.c3.d": "Inga prenumerationer, inga vattenstämplar. HD-fotoredigering tillgänglig för alla.",
    "home.why.c3.b": "$0 / Livstid",
    "home.why.c4.t": "Batchkraft upp till 10",
    "home.why.c4.d": "Dra upp till 10 foton samtidigt och exportera som ett ZIP-arkiv på några sekunder.",
    "home.why.c4.b": "10x Arbetshastighet",
    "home.steps.tag": "HUR DET FUNGERAR",
    "home.steps.title": "Så fungerar HelpMyIMG i 3 enkla steg",
    "home.steps.desc": "Ingen programvaruinstallation krävs. Få professionella resultat från webbläsaren."
  },
  th: {
    "landing.compress.redesign.heroBadge": "การบีบอัดอัจฉริยะ",
    "landing.compress.redesign.heroTitle": "ย่อขนาดไฟล์รูปภาพสูงสุด 90% ทันที",
    "landing.compress.redesign.heroDesc": "ลดขนาดรูปภาพของคุณโดยไม่สูญเสียคุณภาพ สมบูรณ์แบบสำหรับเว็บไซต์และอีเมล",
    "landing.compress.redesign.feat1Badge": "ไม่สูญเสียคุณภาพ",
    "landing.compress.redesign.feat1Title": "การเพิ่มประสิทธิภาพ",
    "landing.compress.redesign.feat1Desc": "ค้นหาความสมดุลที่สมบูรณ์แบบระหว่างขนาดไฟล์ที่เล็กที่สุดและคุณภาพสูงสุดโดยอัตโนมัติ",
    "landing.compress.redesign.feat2Badge": "ส่วนตัว 100%",
    "landing.compress.redesign.feat2Title": "ไม่มีการอัปโหลด",
    "landing.compress.redesign.feat2Desc": "การบีบอัดจะเกิดขึ้นในเบราว์เซอร์ของคุณ ไม่มีอะไรส่งไปที่เซิร์ฟเวอร์",
    "landing.compress.redesign.feat3Badge": "รูปแบบใดก็ได้",
    "landing.compress.redesign.feat3Title": "การสนับสนุนที่กว้างขวาง",
    "landing.compress.redesign.feat3Desc": "ทำงานร่วมกับรูปแบบมาตรฐาน JPG และ PNG รวมถึง WEBP สมัยใหม่",
    "landing.compress.redesign.whoTag": "สำหรับใคร",
    "landing.compress.redesign.whoTitle": "สร้างมาเพื่อเว็บและสื่อ",
    "landing.compress.redesign.whoDesc": "เหมาะสำหรับนักพัฒนา นักออกแบบ และผู้จัดการโซเชียลมีเดีย",
    "landing.compress.redesign.who1Title": "นักพัฒนาเว็บ",
    "landing.compress.redesign.who1Desc": "ปรับปรุงคะแนน PageSpeed และลดเวลาในการโหลดโดยไม่ลดคุณภาพของภาพ",
    "landing.compress.redesign.who1Tags": "การปรับ SEO",
    "landing.compress.redesign.who2Title": "ผู้สร้างเนื้อหา",
    "landing.compress.redesign.who2Desc": "ปฏิบัติตามขีดจำกัดขนาดการอัปโหลดที่เข้มงวดสำหรับแพลตฟอร์มเช่น Discord",
    "landing.compress.redesign.who2Tags": "สื่อสังคม",
    "landing.compress.redesign.stepsTag": "มันทำงานอย่างไร",
    "landing.compress.redesign.stepsTitle": "3 ขั้นตอนในการเพิ่มประสิทธิภาพ",
    "landing.compress.redesign.s1Title": "อัปโหลดรูปภาพ",
    "landing.compress.redesign.s1Desc": "ลากและวางรูปภาพของคุณลงในพื้นที่ทำงาน",
    "landing.compress.redesign.s2Title": "ตั้งระดับการบีบอัด",
    "landing.compress.redesign.s2Desc": "ปรับแถบเลื่อนคุณภาพเพื่อค้นหาความสมดุลที่เหมาะสม",
    "landing.compress.redesign.s3Title": "ประหยัดพื้นที่จัดเก็บ",
    "landing.compress.redesign.s3Desc": "ดาวน์โหลดรูปภาพที่ปรับให้เหมาะสมและเพลิดเพลินกับขนาดไฟล์ที่ลดลง",
    "landing.remove.redesign.heroBadge": "การตัดภาพด้วย AI",
    "landing.remove.redesign.heroTitle": "ลบพื้นหลังใน 1 วินาทีด้วยความแม่นยำไร้ที่ติ",
    "landing.remove.redesign.heroDesc": "รับการตัดผมที่สมบูรณ์แบบโดยไม่ต้องอัปโหลดรูปภาพไปยังเซิร์ฟเวอร์",
    "landing.remove.redesign.feat1Badge": "ความแม่นยำ 99.8%",
    "landing.remove.redesign.feat1Title": "การตรวจจับขอบที่สมบูรณ์แบบ",
    "landing.remove.redesign.feat1Desc": "เครือข่ายของเราจัดการรายละเอียดที่ซับซ้อน เช่น เส้นผมของมนุษย์ หรือขนของสัตว์ได้อย่างง่ายดาย",
    "landing.remove.redesign.feat2Badge": "ปลอดภัย 100%",
    "landing.remove.redesign.feat2Title": "ความเป็นส่วนตัวแบบออฟไลน์",
    "landing.remove.redesign.feat2Desc": "โมเดล AI โหลดลงในเบราว์เซอร์ของคุณโดยตรง รูปภาพไม่เคยออกจากคอมพิวเตอร์ของคุณ",
    "landing.remove.redesign.feat3Badge": "โหมดแบตช์",
    "landing.remove.redesign.feat3Title": "พร้อมสำหรับการประมวลผลจำนวนมาก",
    "landing.remove.redesign.feat3Desc": "ลากและวางรูปภาพสูงสุด 10 รูปพร้อมกัน และดาวน์โหลดทุกอย่างในไฟล์ ZIP",
    "landing.remove.redesign.whoTag": "สำหรับใคร",
    "landing.remove.redesign.whoTitle": "สมบูรณ์แบบสำหรับทุกความต้องการ",
    "landing.remove.redesign.whoDesc": "ไม่ว่าคุณจะขายรถยนต์ ออกแบบโปสเตอร์ หรือสร้างเอกสารทางการ",
    "landing.remove.redesign.who1Title": "ผู้ขายอีคอมเมิร์ซ",
    "landing.remove.redesign.who1Desc": "สร้างพื้นหลังสีขาวสะอาดตาสำหรับรายชื่อผลิตภัณฑ์",
    "landing.remove.redesign.who1Tags": "รายการสินค้า",
    "landing.remove.redesign.who2Title": "นักออกแบบกราฟิก",
    "landing.remove.redesign.who2Desc": "แยกโลโก้ ลายเซ็น และทรัพย์สินทันที",
    "landing.remove.redesign.who2Tags": "สินทรัพย์การออกแบบ",
    "landing.remove.redesign.stepsTag": "มันทำงานอย่างไร",
    "landing.remove.redesign.stepsTitle": "3 ขั้นตอนสำหรับพื้นหลังโปร่งใส",
    "landing.remove.redesign.s1Title": "อัปโหลดรูปภาพ",
    "landing.remove.redesign.s1Desc": "ลากและวางรูปภาพ PNG, JPG หรือ WEBP",
    "landing.remove.redesign.s2Title": "การประมวลผล AI",
    "landing.remove.redesign.s2Desc": "AI ในพื้นที่จะตรวจจับวัตถุหลักใน 1 วินาที",
    "landing.remove.redesign.s3Title": "ดาวน์โหลด HD",
    "landing.remove.redesign.s3Desc": "ส่งออกรูปภาพที่ตัดออกมาพร้อมพื้นหลังโปร่งใส",
    "home.why.tag": "ทำไมถึงเป็น HELPMYIMG",
    "home.why.title": "เหตุใด HelpMyIMG จึงเป็นตัวเลือกที่ฉลาดที่สุดสำหรับผู้สร้าง",
    "home.why.desc": "ออกแบบมาตั้งแต่ต้นเพื่อความเป็นส่วนตัวสูงสุด ความเร็วที่รวดเร็วปานสายฟ้าแลบ และไม่มีค่าใช้จ่ายใดๆ",
    "home.why.c1.t": "ความเร็วทันทีในเครื่อง",
    "home.why.c1.d": "รูปภาพของคุณได้รับการประมวลผลโดยตรงในหน่วยความจำอุปกรณ์โดยไม่มีความล่าช้า",
    "home.why.c1.b": "เซิร์ฟเวอร์ล่าช้า 0ms",
    "home.why.c2.t": "ความเป็นส่วนตัวสัมบูรณ์ 100%",
    "home.why.c2.d": "รูปภาพบุคคลและเอกสารที่เป็นความลับของคุณไม่เคยออกจากคอมพิวเตอร์",
    "home.why.c2.b": "ไม่มีที่เก็บข้อมูลบนคลาวด์",
    "home.why.c3.t": "ฟรีและไม่จำกัดตลอดไป",
    "home.why.c3.d": "ไม่มีการสมัครสมาชิก ไม่มีลายน้ำ การแก้ไขภาพถ่ายความละเอียดสูงเข้าถึงได้ทุกคน",
    "home.why.c3.b": "$0 / ตลอดชีวิต",
    "home.why.c4.t": "พลังงานเป็นชุดสูงถึง 10",
    "home.why.c4.d": "ลากและวางรูปภาพสูงสุด 10 ภาพพร้อมกันและส่งออกเป็นไฟล์ ZIP ในไม่กี่วินาที",
    "home.why.c4.b": "ความเร็วในการทำงาน 10x",
    "home.steps.tag": "มันทำงานอย่างไร",
    "home.steps.title": "HelpMyIMG ทำงานอย่างไรใน 3 ขั้นตอนง่ายๆ",
    "home.steps.desc": "ไม่จำเป็นต้องติดตั้งซอฟต์แวร์ รับผลลัพธ์ระดับมืออาชีพโดยตรงจากเบราว์เซอร์ของคุณ"
  },
  tl: {
    "landing.compress.redesign.heroBadge": "SMART COMPRESSION",
    "landing.compress.redesign.heroTitle": "Paliitin ang Laki ng File ng Larawan nang hanggang 90% Agad",
    "landing.compress.redesign.heroDesc": "Bawasan ang laki ng iyong mga larawan nang hindi nawawala ang visual na kalidad. Perpekto para sa mga website at e-mail.",
    "landing.compress.redesign.feat1Badge": "WALANG PAGKAWALA NG KALIDAD",
    "landing.compress.redesign.feat1Title": "Smart na Pag-optimize",
    "landing.compress.redesign.feat1Desc": "Awtomatikong hinahanap ang perpektong balanse sa pagitan ng minimal na laki ng file at maximum na kalidad ng imahe.",
    "landing.compress.redesign.feat2Badge": "100% PRIBADO",
    "landing.compress.redesign.feat2Title": "Walang Upload",
    "landing.compress.redesign.feat2Desc": "Tulad ng lahat ng aming tool, ang compression ay nangyayari sa iyong web browser. Walang napupunta sa anumang server.",
    "landing.compress.redesign.feat3Badge": "KAHIT ANONG FORMAT",
    "landing.compress.redesign.feat3Title": "Malawak na Suporta",
    "landing.compress.redesign.feat3Desc": "Gumagana sa karaniwang mga format na JPG at PNG, pati na rin sa modernong WEBP format.",
    "landing.compress.redesign.whoTag": "PARA KANINO ITO",
    "landing.compress.redesign.whoTitle": "Ginawa para sa Web at Media",
    "landing.compress.redesign.whoDesc": "Perpekto para sa mga developer, designer, at social media manager na nangangailangan ng optimized na mga larawan.",
    "landing.compress.redesign.who1Title": "Mga Web Developer",
    "landing.compress.redesign.who1Desc": "Pabutihin ang mga score sa PageSpeed at bawasan ang mga oras ng pag-load nang hindi sinasakripisyo ang kalidad ng imahe.",
    "landing.compress.redesign.who1Tags": "SEO OPTIMIZATION",
    "landing.compress.redesign.who2Title": "Mga Content Creator",
    "landing.compress.redesign.who2Desc": "Matugunan ang mahigpit na mga limitasyon sa laki ng pag-upload para sa mga platform tulad ng Discord o Twitter.",
    "landing.compress.redesign.who2Tags": "SOCIAL MEDIA",
    "landing.compress.redesign.stepsTag": "PAANO ITO GUMAGANA",
    "landing.compress.redesign.stepsTitle": "3 Hakbang sa Pag-optimize",
    "landing.compress.redesign.s1Title": "I-upload ang mga Larawan",
    "landing.compress.redesign.s1Desc": "I-drag at i-drop ang iyong mga larawan sa compression workspace.",
    "landing.compress.redesign.s2Title": "Itakda ang Antas ng Compression",
    "landing.compress.redesign.s2Desc": "Ayusin ang slider ng kalidad upang mahanap ang tamang balanse.",
    "landing.compress.redesign.s3Title": "I-save ang Imbakan",
    "landing.compress.redesign.s3Desc": "I-download ang iyong mga na-optimize na larawan at tamasahin ang pinababang laki ng file.",
    "landing.remove.redesign.heroBadge": "AI POWERED CUTOUT",
    "landing.remove.redesign.heroTitle": "Alisin ang Background sa 1 Segundo nang may Walang Kamali-maling Katumpakan",
    "landing.remove.redesign.heroDesc": "Pinapatakbo ng advanced WebAssembly AI, kumuha ng perpektong paggupit ng buhok nang hindi kailanman nag-a-upload ng iyong mga larawan.",
    "landing.remove.redesign.feat1Badge": "99.8% KATUMPAKAN",
    "landing.remove.redesign.feat1Title": "Walang Kapintasang Pagtukoy sa Buhok at Gilid",
    "landing.remove.redesign.feat1Desc": "Ang aming neural network ay madaling nangangasiwa sa mga kumplikadong detalye tulad ng buhok ng tao at balahibo ng hayop.",
    "landing.remove.redesign.feat2Badge": "100% LIGTAS",
    "landing.remove.redesign.feat2Title": "Kumpletong Offline na Pagkapribado",
    "landing.remove.redesign.feat2Desc": "Ang modelo ng AI ay direktang naglo-load sa iyong browser. Hindi kailanman iniiwan ng iyong mga larawan ang iyong computer.",
    "landing.remove.redesign.feat3Badge": "BATCH MODE",
    "landing.remove.redesign.feat3Title": "Handa na para sa Maramihang Pagproseso",
    "landing.remove.redesign.feat3Desc": "I-drag at i-drop ang hanggang 10 larawan nang sabay-sabay at i-download ang lahat sa isang ZIP file.",
    "landing.remove.redesign.whoTag": "PARA KANINO ITO",
    "landing.remove.redesign.whoTitle": "Perpekto para sa Bawat Malikhaing Pangangailangan",
    "landing.remove.redesign.whoDesc": "Nagbebenta ka man ng mga sasakyan, nagdidisenyo ng mga poster, o gumagawa ng mga opisyal na dokumento.",
    "landing.remove.redesign.who1Title": "Mga Nagbebenta sa E-Commerce",
    "landing.remove.redesign.who1Desc": "Lumikha ng malinis na puting background para sa mga listahan ng produkto.",
    "landing.remove.redesign.who1Tags": "MGA LISTAHAN NG PRODUKTO",
    "landing.remove.redesign.who2Title": "Mga Graphic Designer",
    "landing.remove.redesign.who2Desc": "I-extract ang mga logo, pirma, at asset kaagad.",
    "landing.remove.redesign.who2Tags": "MGA DESIGN ASSET",
    "landing.remove.redesign.stepsTag": "PAANO ITO GUMAGANA",
    "landing.remove.redesign.stepsTitle": "3 Hakbang sa Mga Transparent na Background",
    "landing.remove.redesign.s1Title": "I-upload ang Larawan",
    "landing.remove.redesign.s1Desc": "I-drag at i-drop ang iyong larawan. PNG, JPG, o WEBP.",
    "landing.remove.redesign.s2Title": "Pagpoproseso ng AI",
    "landing.remove.redesign.s2Desc": "Nakita ng lokal na AI ang pangunahing paksa sa loob ng 1 segundo.",
    "landing.remove.redesign.s3Title": "I-download ang HD",
    "landing.remove.redesign.s3Desc": "I-export ang iyong ginupit na larawan na may transparent na background.",
    "home.why.tag": "BAKIT HELPMYIMG",
    "home.why.title": "Kung Bakit Ang HelpMyIMG Ay Ang Pinakamatalinong Pagpipilian",
    "home.why.desc": "Dinisenyo mula sa ibaba pataas para sa maximum na privacy, napakabilis na bilis, at walang gastos.",
    "home.why.c1.t": "Instant na Lokal na Bilis",
    "home.why.c1.d": "Ang iyong mga larawan ay pinoproseso nang direkta sa memorya ng iyong device na may walang latency.",
    "home.why.c1.b": "0ms Server Delay",
    "home.why.c2.t": "100% Ganap na Privacy",
    "home.why.c2.d": "Ang iyong mga personal na portrait at kumpidensyal na dokumento ay hindi kailanman iniiwan ang iyong computer.",
    "home.why.c2.b": "Walang Cloud Storage",
    "home.why.c3.t": "Habambuhay na Libre at Walang Limitasyon",
    "home.why.c3.d": "Walang mga subscription, walang mga watermark. High-definition na pag-edit ng larawan na maa-access ng lahat.",
    "home.why.c3.b": "$0 / Habambuhay",
    "home.why.c4.t": "Batch Power hanggang 10",
    "home.why.c4.d": "I-drag at i-drop ang hanggang 10 larawan at i-export bilang ZIP archive sa ilang segundo.",
    "home.why.c4.b": "10x Bilis ng Trabaho",
    "home.steps.tag": "PAANO ITO GUMAGANA",
    "home.steps.title": "Kung Paano Gumagana ang HelpMyIMG sa 3 Simpleng Hakbang",
    "home.steps.desc": "Walang kinakailangang pag-install ng software. Kumuha ng mga propesyonal na resulta nang direkta mula sa iyong web browser."
  },
  tr: {
    "landing.compress.redesign.heroBadge": "AKILLI SIKIŞTIRMA",
    "landing.compress.redesign.heroTitle": "Görüntü Dosya Boyutunu Anında %90'a Kadar Küçültün",
    "landing.compress.redesign.heroDesc": "Görsel kaliteyi kaybetmeden fotoğraflarınızın boyutunu küçültün. Web siteleri, e-postalar için mükemmeldir.",
    "landing.compress.redesign.feat1Badge": "KALİTE KAYBI YOK",
    "landing.compress.redesign.feat1Title": "Akıllı Optimizasyon",
    "landing.compress.redesign.feat1Desc": "Minimum dosya boyutu ile maksimum görüntü kalitesi arasındaki mükemmel dengeyi otomatik olarak bulur.",
    "landing.compress.redesign.feat2Badge": "%100 GİZLİ",
    "landing.compress.redesign.feat2Title": "Yükleme Yok",
    "landing.compress.redesign.feat2Desc": "Tüm araçlarımızda olduğu gibi sıkıştırma doğrudan web tarayıcınızda gerçekleşir. Sunucuya hiçbir şey gitmez.",
    "landing.compress.redesign.feat3Badge": "HERHANGİ BİR FORMAT",
    "landing.compress.redesign.feat3Title": "Geniş Destek",
    "landing.compress.redesign.feat3Desc": "Standart JPG ve PNG formatlarının yanı sıra modern WEBP formatlarıyla çalışır.",
    "landing.compress.redesign.whoTag": "KİMLER İÇİN",
    "landing.compress.redesign.whoTitle": "Web ve Medya İçin Üretildi",
    "landing.compress.redesign.whoDesc": "Geliştiriciler, tasarımcılar ve sosyal medya yöneticileri için mükemmeldir.",
    "landing.compress.redesign.who1Title": "Web Geliştiricileri",
    "landing.compress.redesign.who1Desc": "Görüntü kalitesinden ödün vermeden PageSpeed ​​puanlarını iyileştirin ve yükleme sürelerini kısaltın.",
    "landing.compress.redesign.who1Tags": "SEO OPTİMİZASYONU",
    "landing.compress.redesign.who2Title": "İçerik Oluşturucular",
    "landing.compress.redesign.who2Desc": "Discord veya Twitter gibi platformlar için katı yükleme boyutu sınırlarını karşılayın.",
    "landing.compress.redesign.who2Tags": "SOSYAL MEDYA",
    "landing.compress.redesign.stepsTag": "NASIL ÇALIŞIR",
    "landing.compress.redesign.stepsTitle": "Optimizasyon için 3 Adım",
    "landing.compress.redesign.s1Title": "Resimleri Yükle",
    "landing.compress.redesign.s1Desc": "Fotoğraflarınızı sıkıştırma çalışma alanına sürükleyip bırakın.",
    "landing.compress.redesign.s2Title": "Sıkıştırma Düzeyini Ayarla",
    "landing.compress.redesign.s2Desc": "Doğru dengeyi bulmak için kalite kaydırıcısını ayarlayın.",
    "landing.compress.redesign.s3Title": "Depolamadan Tasarruf Edin",
    "landing.compress.redesign.s3Desc": "Optimize edilmiş görüntülerinizi indirin ve küçültülmüş dosya boyutlarının keyfini çıkarın.",
    "landing.remove.redesign.heroBadge": "YAPAY ZEKA DESTEKLİ KESİM",
    "landing.remove.redesign.heroTitle": "Kusursuz Hassasiyetle Arka Planı 1 Saniyede Kaldırın",
    "landing.remove.redesign.heroDesc": "Gelişmiş WebAssembly AI ile desteklenen fotoğraflarınızı hiçbir zaman sunucuya yüklemeden mükemmel kesimler elde edin.",
    "landing.remove.redesign.feat1Badge": "%99.8 DOĞRULUK",
    "landing.remove.redesign.feat1Title": "Kusursuz Saç ve Kenar Tespiti",
    "landing.remove.redesign.feat1Desc": "Sinir ağımız insan saçı, hayvan kürkü ve yarı saydam nesneler gibi karmaşık ayrıntıları kolayca işler.",
    "landing.remove.redesign.feat2Badge": "%100 GÜVENLİ",
    "landing.remove.redesign.feat2Title": "Tam Çevrimdışı Gizlilik",
    "landing.remove.redesign.feat2Desc": "AI modeli doğrudan tarayıcınıza yüklenir. Görüntüleriniz asla bilgisayarınızdan ayrılmaz.",
    "landing.remove.redesign.feat3Badge": "TOPLU MODU",
    "landing.remove.redesign.feat3Title": "Toplu İşleme Hazır",
    "landing.remove.redesign.feat3Desc": "Aynı anda 10 fotoğrafa kadar sürükleyip bırakın ve her şeyi tek bir ZIP dosyasında indirin.",
    "landing.remove.redesign.whoTag": "KİMLER İÇİN",
    "landing.remove.redesign.whoTitle": "Her Türlü Yaratıcı İhtiyaç İçin Mükemmel",
    "landing.remove.redesign.whoDesc": "İster araba satıyor olun, ister afiş tasarlıyor olun, ister resmi belgeler oluşturuyor olun.",
    "landing.remove.redesign.who1Title": "E-Ticaret Satıcıları",
    "landing.remove.redesign.who1Desc": "Ürün listelemeleri için temiz beyaz arka planlar oluşturun.",
    "landing.remove.redesign.who1Tags": "ÜRÜN LİSTELERİ",
    "landing.remove.redesign.who2Title": "Grafik Tasarımcıları",
    "landing.remove.redesign.who2Desc": "Logoları, imzaları ve varlıkları anında çıkarın.",
    "landing.remove.redesign.who2Tags": "TASARIM VARLIKLARI",
    "landing.remove.redesign.stepsTag": "NASIL ÇALIŞIR",
    "landing.remove.redesign.stepsTitle": "Şeffaf Arka Planlara 3 Adım",
    "landing.remove.redesign.s1Title": "Görüntü Yükle",
    "landing.remove.redesign.s1Desc": "Fotoğrafınızı sürükleyip bırakın. PNG, JPG veya WEBP.",
    "landing.remove.redesign.s2Title": "Yapay Zeka İşleme",
    "landing.remove.redesign.s2Desc": "Yerel yapay zeka ana konuyu 1 saniyede algılar.",
    "landing.remove.redesign.s3Title": "HD İndir",
    "landing.remove.redesign.s3Desc": "Kesilen fotoğrafınızı şeffaf bir arka planla dışa aktarın.",
    "home.why.tag": "NEDEN HELPMYIMG",
    "home.why.title": "HelpMyIMG Neden İçerik Üreticileri İçin En Akıllı Seçimdir?",
    "home.why.desc": "Maksimum gizlilik, ışık hızı ve sıfır maliyet için sıfırdan tasarlandı.",
    "home.why.c1.t": "Anında Yerel Hız",
    "home.why.c1.d": "Fotoğraflarınız sıfır gecikmeyle doğrudan cihazınızın belleğinde işlenir.",
    "home.why.c1.b": "0ms Sunucu Gecikmesi",
    "home.why.c2.t": "%100 Mutlak Gizlilik",
    "home.why.c2.d": "Kişisel portreleriniz ve gizli belgeleriniz bilgisayarınızı asla terk etmez.",
    "home.why.c2.b": "Sıfır Bulut Depolama",
    "home.why.c3.t": "Sonsuza Kadar Ücretsiz ve Sınırsız",
    "home.why.c3.d": "Abonelik yok, filigran yok. Herkesin erişebileceği yüksek çözünürlüklü fotoğraf düzenleme.",
    "home.why.c3.b": "$0 / Ömür Boyu",
    "home.why.c4.t": "10'a Kadar Toplu Güç",
    "home.why.c4.d": "Aynı anda 10 fotoğrafa kadar sürükleyip bırakın ve saniyeler içinde ZIP olarak dışa aktarın.",
    "home.why.c4.b": "10x Çalışma Hızı",
    "home.steps.tag": "NASIL ÇALIŞIR",
    "home.steps.title": "HelpMyIMG 3 Basit Adımda Nasıl Çalışır?",
    "home.steps.desc": "Yazılım kurulumu gerekmez. Doğrudan web tarayıcınızdan profesyonel sonuçlar alın."
  },
  uk: {
    "landing.compress.redesign.heroBadge": "РОЗУМНЕ СТИСНЕННЯ",
    "landing.compress.redesign.heroTitle": "Миттєво зменшіть розмір файлу зображення до 90%",
    "landing.compress.redesign.heroDesc": "Зменшіть розмір ваших фотографій без втрати візуальної якості. Ідеально підходить для веб-сайтів і електронної пошти.",
    "landing.compress.redesign.feat1Badge": "БЕЗ ВТРАТИ ЯКОСТІ",
    "landing.compress.redesign.feat1Title": "Розумна оптимізація",
    "landing.compress.redesign.feat1Desc": "Автоматично знаходить ідеальний баланс між мінімальним розміром файлу та максимальною якістю зображення.",
    "landing.compress.redesign.feat2Badge": "100% ПРИВАТНО",
    "landing.compress.redesign.feat2Title": "Жодних завантажень на сервер",
    "landing.compress.redesign.feat2Desc": "Як і в усіх наших інструментах, стиснення відбувається прямо у вашому браузері. Нічого не йде на жоден сервер.",
    "landing.compress.redesign.feat3Badge": "БУДЬ-ЯКИЙ ФОРМАТ",
    "landing.compress.redesign.feat3Title": "Широка підтримка",
    "landing.compress.redesign.feat3Desc": "Працює зі стандартними форматами JPG і PNG, а також сучасними форматами WEBP.",
    "landing.compress.redesign.whoTag": "ДЛЯ КОГО ЦЕ",
    "landing.compress.redesign.whoTitle": "Створено для Інтернету та Медіа",
    "landing.compress.redesign.whoDesc": "Ідеально підходить для розробників, дизайнерів та менеджерів соціальних мереж.",
    "landing.compress.redesign.who1Title": "Веб-розробники",
    "landing.compress.redesign.who1Desc": "Покращуйте оцінки PageSpeed і зменшуйте час завантаження без шкоди для якості зображення.",
    "landing.compress.redesign.who1Tags": "ОПТИМІЗАЦІЯ SEO",
    "landing.compress.redesign.who2Title": "Творці контенту",
    "landing.compress.redesign.who2Desc": "Дотримуйтесь суворих обмежень щодо розміру завантаження для таких платформ, як Discord або Twitter.",
    "landing.compress.redesign.who2Tags": "СОЦІАЛЬНІ МЕРЕЖІ",
    "landing.compress.redesign.stepsTag": "ЯК ЦЕ ПРАЦЮЄ",
    "landing.compress.redesign.stepsTitle": "3 кроки до оптимізації",
    "landing.compress.redesign.s1Title": "Завантажте зображення",
    "landing.compress.redesign.s1Desc": "Перетягніть ваші фотографії у робочу область стиснення.",
    "landing.compress.redesign.s2Title": "Встановіть рівень стиснення",
    "landing.compress.redesign.s2Desc": "Відрегулюйте повзунок якості, щоб знайти правильний баланс.",
    "landing.compress.redesign.s3Title": "Збережіть пам'ять",
    "landing.compress.redesign.s3Desc": "Завантажте оптимізовані зображення та насолоджуйтеся зменшеним розміром файлів.",
    "landing.remove.redesign.heroBadge": "ВИРІЗАННЯ ЗА ДОПОМОГОЮ ШІ",
    "landing.remove.redesign.heroTitle": "Видаліть фон за 1 секунду з бездоганною точністю",
    "landing.remove.redesign.heroDesc": "Отримайте ідеальні вирізи волосся та гладкі краї без завантаження ваших фотографій на сервер.",
    "landing.remove.redesign.feat1Badge": "99.8% ТОЧНІСТЬ",
    "landing.remove.redesign.feat1Title": "Бездоганне виявлення волосся та країв",
    "landing.remove.redesign.feat1Desc": "Наша нейронна мережа легко справляється зі складними деталями, такими як людське волосся та хутро тварин.",
    "landing.remove.redesign.feat2Badge": "100% БЕЗПЕЧНО",
    "landing.remove.redesign.feat2Title": "Повна конфіденційність офлайн",
    "landing.remove.redesign.feat2Desc": "Модель ШІ завантажується безпосередньо у ваш браузер. Ваші зображення ніколи не залишають ваш комп'ютер.",
    "landing.remove.redesign.feat3Badge": "ПАКЕТНИЙ РЕЖИМ",
    "landing.remove.redesign.feat3Title": "Готовність до масової обробки",
    "landing.remove.redesign.feat3Desc": "Перетягніть до 10 фотографій одночасно і завантажте все в ZIP-файлі.",
    "landing.remove.redesign.whoTag": "ДЛЯ КОГО ЦЕ",
    "landing.remove.redesign.whoTitle": "Ідеально підходить для будь-яких творчих потреб",
    "landing.remove.redesign.whoDesc": "Незалежно від того, чи ви продаєте автомобілі, розробляєте плакати або створюєте офіційні документи.",
    "landing.remove.redesign.who1Title": "Продавці електронної комерції",
    "landing.remove.redesign.who1Desc": "Створюйте чисті білі фони для списків продуктів.",
    "landing.remove.redesign.who1Tags": "СПИСКИ ПРОДУКТІВ",
    "landing.remove.redesign.who2Title": "Графічні дизайнери",
    "landing.remove.redesign.who2Desc": "Витягуйте логотипи, підписи та активи миттєво.",
    "landing.remove.redesign.who2Tags": "АКТИВИ ДИЗАЙНУ",
    "landing.remove.redesign.stepsTag": "ЯК ЦЕ ПРАЦЮЄ",
    "landing.remove.redesign.stepsTitle": "3 кроки до прозорого фону",
    "landing.remove.redesign.s1Title": "Завантажити зображення",
    "landing.remove.redesign.s1Desc": "Перетягніть свою фотографію. PNG, JPG або WEBP.",
    "landing.remove.redesign.s2Title": "Обробка ШІ",
    "landing.remove.redesign.s2Desc": "Локальний ШІ виявляє головний об'єкт за 1 секунду.",
    "landing.remove.redesign.s3Title": "Завантажити HD",
    "landing.remove.redesign.s3Desc": "Експортуйте вашу вирізану фотографію з прозорим фоном.",
    "home.why.tag": "ЧОМУ HELPMYIMG",
    "home.why.title": "Чому HelpMyIMG є найрозумнішим вибором для творців",
    "home.why.desc": "Розроблено з нуля для максимальної конфіденційності, блискавичної швидкості та нульових витрат.",
    "home.why.c1.t": "Миттєва локальна швидкість",
    "home.why.c1.d": "Ваші фотографії обробляються безпосередньо в пам'яті вашого пристрою без затримок.",
    "home.why.c1.b": "0ms Затримка сервера",
    "home.why.c2.t": "100% Абсолютна конфіденційність",
    "home.why.c2.d": "Ваші особисті портрети та конфіденційні документи ніколи не залишають комп'ютер.",
    "home.why.c2.b": "Жодного хмарного сховища",
    "home.why.c3.t": "Завжди безкоштовно та без обмежень",
    "home.why.c3.d": "Жодних підписок, жодних водяних знаків. Редагування фотографій у високій роздільній здатності доступне всім.",
    "home.why.c3.b": "$0 / Назавжди",
    "home.why.c4.t": "Пакетна потужність до 10",
    "home.why.c4.d": "Перетягніть до 10 фотографій одночасно і експортуйте у форматі ZIP за лічені секунди.",
    "home.why.c4.b": "10x Швидкість роботи",
    "home.steps.tag": "ЯК ЦЕ ПРАЦЮЄ",
    "home.steps.title": "Як HelpMyIMG працює за 3 прості кроки",
    "home.steps.desc": "Встановлення програмного забезпечення не потрібне. Отримуйте професійні результати прямо з браузера."
  },
  vi: {
    "landing.compress.redesign.heroBadge": "NÉN THÔNG MINH",
    "landing.compress.redesign.heroTitle": "Giảm dung lượng tệp hình ảnh lên đến 90% ngay lập tức",
    "landing.compress.redesign.heroDesc": "Giảm dung lượng ảnh của bạn mà không làm giảm chất lượng hình ảnh. Hoàn hảo cho các trang web và email.",
    "landing.compress.redesign.feat1Badge": "KHÔNG GIẢM CHẤT LƯỢNG",
    "landing.compress.redesign.feat1Title": "Tối ưu hóa thông minh",
    "landing.compress.redesign.feat1Desc": "Tự động tìm kiếm sự cân bằng hoàn hảo giữa kích thước tệp tối thiểu và chất lượng hình ảnh tối đa.",
    "landing.compress.redesign.feat2Badge": "100% RIÊNG TƯ",
    "landing.compress.redesign.feat2Title": "Không tải lên máy chủ",
    "landing.compress.redesign.feat2Desc": "Như tất cả các công cụ của chúng tôi, quá trình nén diễn ra ngay trong trình duyệt web của bạn.",
    "landing.compress.redesign.feat3Badge": "BẤT KỲ ĐỊNH DẠNG NÀO",
    "landing.compress.redesign.feat3Title": "Hỗ trợ rộng rãi",
    "landing.compress.redesign.feat3Desc": "Hoạt động với các định dạng JPG và PNG tiêu chuẩn, cũng như định dạng WEBP siêu hiệu quả.",
    "landing.compress.redesign.whoTag": "DÀNH CHO AI",
    "landing.compress.redesign.whoTitle": "Xây dựng cho Web & Phương tiện",
    "landing.compress.redesign.whoDesc": "Hoàn hảo cho các nhà phát triển, nhà thiết kế và người quản lý mạng xã hội.",
    "landing.compress.redesign.who1Title": "Nhà phát triển web",
    "landing.compress.redesign.who1Desc": "Cải thiện điểm số PageSpeed và giảm thời gian tải mà không làm giảm chất lượng hình ảnh.",
    "landing.compress.redesign.who1Tags": "TỐI ƯU HÓA SEO",
    "landing.compress.redesign.who2Title": "Người sáng tạo nội dung",
    "landing.compress.redesign.who2Desc": "Đáp ứng các giới hạn kích thước tải lên nghiêm ngặt cho các nền tảng như Discord hoặc Twitter.",
    "landing.compress.redesign.who2Tags": "MẠNG XÃ HỘI",
    "landing.compress.redesign.stepsTag": "CÁCH THỨC HOẠT ĐỘNG",
    "landing.compress.redesign.stepsTitle": "3 Bước để Tối ưu hóa",
    "landing.compress.redesign.s1Title": "Tải lên hình ảnh",
    "landing.compress.redesign.s1Desc": "Kéo và thả ảnh của bạn vào không gian làm việc nén.",
    "landing.compress.redesign.s2Title": "Đặt Mức độ Nén",
    "landing.compress.redesign.s2Desc": "Điều chỉnh thanh trượt chất lượng để tìm sự cân bằng phù hợp.",
    "landing.compress.redesign.s3Title": "Tiết kiệm dung lượng",
    "landing.compress.redesign.s3Desc": "Tải xuống hình ảnh đã tối ưu hóa và tận hưởng kích thước tệp giảm.",
    "landing.remove.redesign.heroBadge": "CẮT XÉN BẰNG AI",
    "landing.remove.redesign.heroTitle": "Xóa Nền trong 1 Giây với Độ Chính Xác Hoàn Hảo",
    "landing.remove.redesign.heroDesc": "Được hỗ trợ bởi WebAssembly AI, có được các phần cắt tóc hoàn hảo và các cạnh mịn màng.",
    "landing.remove.redesign.feat1Badge": "ĐỘ CHÍNH XÁC 99.8%",
    "landing.remove.redesign.feat1Title": "Phát hiện tóc và cạnh hoàn hảo",
    "landing.remove.redesign.feat1Desc": "Mạng nơ-ron của chúng tôi dễ dàng xử lý các chi tiết phức tạp như tóc người và lông động vật.",
    "landing.remove.redesign.feat2Badge": "100% AN TOÀN",
    "landing.remove.redesign.feat2Title": "Bảo mật ngoại tuyến hoàn toàn",
    "landing.remove.redesign.feat2Desc": "Mô hình AI tải trực tiếp vào trình duyệt của bạn. Hình ảnh của bạn không bao giờ rời khỏi máy tính.",
    "landing.remove.redesign.feat3Badge": "CHẾ ĐỘ HÀNG LOẠT",
    "landing.remove.redesign.feat3Title": "Sẵn sàng cho xử lý hàng loạt",
    "landing.remove.redesign.feat3Desc": "Kéo và thả tối đa 10 ảnh cùng một lúc và tải xuống tất cả trong một tệp ZIP.",
    "landing.remove.redesign.whoTag": "DÀNH CHO AI",
    "landing.remove.redesign.whoTitle": "Hoàn hảo cho mọi nhu cầu sáng tạo",
    "landing.remove.redesign.whoDesc": "Cho dù bạn đang bán ô tô, thiết kế áp phích hay tạo tài liệu chính thức.",
    "landing.remove.redesign.who1Title": "Người bán hàng thương mại điện tử",
    "landing.remove.redesign.who1Desc": "Tạo nền trắng sạch cho danh sách sản phẩm.",
    "landing.remove.redesign.who1Tags": "DANH SÁCH SẢN PHẨM",
    "landing.remove.redesign.who2Title": "Nhà thiết kế đồ họa",
    "landing.remove.redesign.who2Desc": "Trích xuất biểu trưng, chữ ký và tài sản ngay lập tức.",
    "landing.remove.redesign.who2Tags": "TÀI SẢN THIẾT KẾ",
    "landing.remove.redesign.stepsTag": "CÁCH THỨC HOẠT ĐỘNG",
    "landing.remove.redesign.stepsTitle": "3 Bước để có Nền trong suốt",
    "landing.remove.redesign.s1Title": "Tải lên hình ảnh",
    "landing.remove.redesign.s1Desc": "Kéo và thả ảnh của bạn. PNG, JPG hoặc WEBP.",
    "landing.remove.redesign.s2Title": "Xử lý AI",
    "landing.remove.redesign.s2Desc": "AI cục bộ phát hiện chủ thể chính trong 1 giây.",
    "landing.remove.redesign.s3Title": "Tải xuống HD",
    "landing.remove.redesign.s3Desc": "Xuất ảnh đã cắt với nền trong suốt.",
    "home.why.tag": "TẠI SAO LÀ HELPMYIMG",
    "home.why.title": "Tại sao HelpMyIMG là Lựa chọn Thông minh nhất",
    "home.why.desc": "Được thiết kế từ đầu để đảm bảo quyền riêng tư tối đa, tốc độ cực nhanh và chi phí bằng không.",
    "home.why.c1.t": "Tốc độ cục bộ tức thì",
    "home.why.c1.d": "Ảnh của bạn được xử lý trực tiếp trong bộ nhớ thiết bị mà không có độ trễ.",
    "home.why.c1.b": "0ms Độ trễ máy chủ",
    "home.why.c2.t": "100% Quyền riêng tư tuyệt đối",
    "home.why.c2.d": "Ảnh chân dung cá nhân và tài liệu bí mật của bạn không bao giờ rời khỏi máy tính.",
    "home.why.c2.b": "Không lưu trữ đám mây",
    "home.why.c3.t": "Mãi mãi Miễn phí & Không giới hạn",
    "home.why.c3.d": "Không cần đăng ký, không có hình mờ. Chỉnh sửa ảnh độ nét cao dễ tiếp cận cho tất cả.",
    "home.why.c3.b": "$0 / Trọn đời",
    "home.why.c4.t": "Sức mạnh hàng loạt lên đến 10",
    "home.why.c4.d": "Kéo và thả tối đa 10 ảnh đồng thời và xuất dưới dạng tệp ZIP trong vài giây.",
    "home.why.c4.b": "10x Tốc độ Công việc",
    "home.steps.tag": "CÁCH THỨC HOẠT ĐỘNG",
    "home.steps.title": "Cách HelpMyIMG hoạt động trong 3 bước đơn giản",
    "home.steps.desc": "Không cần cài đặt phần mềm. Nhận kết quả chuyên nghiệp trực tiếp từ trình duyệt của bạn."
  }
};

const scriptDir = __dirname;
const localesDir = path.join(scriptDir, '../public/locales');

for (const [lang, kv] of Object.entries(translations)) {
  const filePath = path.join(localesDir, lang, 'translation.json');
  if (fs.existsSync(filePath)) {
    const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    for (const [key, val] of Object.entries(kv)) {
      data[key] = val;
    }
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
    console.log(`[${lang}] Injected translations chunk 3`);
  }
}
