const fs = require('fs');
const path = require('path');

const translations = {
  pl: {
    "landing.global.faq.title": "Często Zadawane Pytania",
    "landing.global.faq.desc": "Wszystko, co musisz wiedzieć o naszym lokalnym silniku przetwarzania.",
    "landing.remove.faq1.q": "Czy usuwanie tła jest naprawdę przetwarzane offline?",
    "landing.remove.faq1.a": "Tak. Nasz model AI jest ładowany do pamięci Twojej przeglądarki, więc całe wykrywanie tła odbywa się na Twoim CPU/GPU, zapewniając całkowitą prywatność.",
    "landing.remove.faq2.q": "Czy rozdzielczość obrazu zostanie zmniejszona?",
    "landing.remove.faq2.a": "Nie, zachowujemy oryginalną rozdzielczość Twojego obrazu. Wycięcie jest generowane i łączone z Twoimi oryginalnymi pikselami o wysokiej rozdzielczości.",
    "landing.remove.faq3.q": "Czy dobrze radzi sobie ze skomplikowanymi krawędziami włosów?",
    "landing.remove.faq3.a": "Oczywiście. Model AI WebAssembly został specjalnie wytrenowany do matowania drobnych szczegółów, takich jak włosy, futro i obiekty półprzezroczyste.",
    "landing.remove.faq4.q": "Czy istnieje limit liczby obrazów, które mogę przetworzyć?",
    "landing.remove.faq4.a": "Ponieważ wszystko działa na Twoim własnym urządzeniu, nie ponosimy żadnych kosztów serwera. Dlatego możesz przetwarzać nieograniczoną liczbę obrazów całkowicie za darmo.",
    "landing.compress.faq1.q": "Jak działa kompresja offline?",
    "landing.compress.faq1.a": "Używamy lokalnego renderowania Canvas i algorytmów kompresji WebAssembly, aby zmniejszyć rozmiar pliku bezpośrednio w Twojej przeglądarce bez przesyłania przez sieć.",
    "landing.compress.faq2.q": "Czy mogę kompresować partie zdjęć?",
    "landing.compress.faq2.a": "Tak, możesz upuścić do 10 zdjęć jednocześnie. Lokalny silnik skompresuje je wszystkie naraz i wyeksportuje jako pojedynczy plik ZIP.",
    "landing.compress.faq3.q": "Czy jakość zostanie widocznie pogorszona?",
    "landing.compress.faq3.a": "Nasze algorytmy używają kompresji bezstratnej percepcyjnie, co oznacza, że rozmiar pliku zmniejsza się o 90%, podczas gdy jakość wizualna pozostaje identyczna dla ludzkiego oka.",
    "landing.compress.faq4.q": "Czy to bezpieczne dla poufnych zdjęć do dokumentów tożsamości?",
    "landing.compress.faq4.a": "W 100% bezpieczne. Twoje zdjęcia do dowodu i paszportu nigdy nie opuszczają Twojego urządzenia. Kompresja odbywa się w całości wewnątrz bezpiecznej piaskownicy Twojej przeglądarki."
  },
  nl: {
    "landing.global.faq.title": "Veelgestelde Vragen",
    "landing.global.faq.desc": "Alles wat u moet weten over onze lokale verwerkingsengine.",
    "landing.remove.faq1.q": "Wordt de achtergrondverwijdering echt offline verwerkt?",
    "landing.remove.faq1.a": "Ja. Ons AI-model wordt in het geheugen van uw browser geladen, dus de volledige achtergronddetectie vindt plaats op uw CPU/GPU, wat volledige privacy garandeert.",
    "landing.remove.faq2.q": "Wordt de beeldresolutie verlaagd?",
    "landing.remove.faq2.a": "Nee, we behouden de oorspronkelijke beeldresolutie. De uitsnede wordt gegenereerd en samengevoegd met uw originele high-definition pixels.",
    "landing.remove.faq3.q": "Werkt het goed met complexe haarranden?",
    "landing.remove.faq3.a": "Absoluut. Het WebAssembly AI-model is specifiek getraind om fijne details zoals haar, vacht en semi-transparante objecten uit te snijden.",
    "landing.remove.faq4.q": "Is er een limiet aan het aantal afbeeldingen dat ik kan verwerken?",
    "landing.remove.faq4.a": "Aangezien alles op uw eigen apparaat draait, hebben we nul serverkosten. Daarom kunt u onbeperkt afbeeldingen volledig gratis verwerken.",
    "landing.compress.faq1.q": "Hoe werkt offline compressie?",
    "landing.compress.faq1.a": "We gebruiken lokale Canvas-weergave en WebAssembly-compressie-algoritmen om de bestandsgrootte direct in uw browser te verkleinen zonder netwerk-uploads.",
    "landing.compress.faq2.q": "Kan ik batches foto's comprimeren?",
    "landing.compress.faq2.a": "Ja, u kunt tot 10 foto's tegelijkertijd neerzetten. De lokale engine comprimeert ze allemaal tegelijk en exporteert ze als een enkel ZIP-bestand.",
    "landing.compress.faq3.q": "Zal de kwaliteit zichtbaar verslechteren?",
    "landing.compress.faq3.a": "Onze algoritmen gebruiken perceptueel verliesvrije compressie, wat betekent dat de bestandsgrootte tot 90% krimpt, terwijl de visuele kwaliteit voor het menselijk oog identiek blijft.",
    "landing.compress.faq4.q": "Is dit veilig voor vertrouwelijke pasfoto's?",
    "landing.compress.faq4.a": "100% veilig. Uw identiteits- en pasfoto's verlaten uw apparaat nooit. De compressie gebeurt volledig binnen de veilige sandbox van uw webbrowser."
  },
  sv: {
    "landing.global.faq.title": "Vanliga Frågor",
    "landing.global.faq.desc": "Allt du behöver veta om vår lokala bearbetningsmotor.",
    "landing.remove.faq1.q": "Behandlas bakgrundsborttagningen verkligen offline?",
    "landing.remove.faq1.a": "Ja. Vår AI-modell laddas in i din webbläsares minne, så hela bakgrundsdetekteringen sker på din CPU/GPU, vilket säkerställer fullständig integritet.",
    "landing.remove.faq2.q": "Kommer bildupplösningen att minskas?",
    "landing.remove.faq2.a": "Nej, vi bevarar din ursprungliga bildupplösning. Utskärningen genereras och slås samman med dina ursprungliga högupplösta pixlar.",
    "landing.remove.faq3.q": "Fungerar det bra med komplexa hårkanter?",
    "landing.remove.faq3.a": "Absolut. WebAssembly AI-modellen är specifikt tränad för att frilägga fina detaljer som hår, päls och halvgenomskinliga objekt.",
    "landing.remove.faq4.q": "Finns det en gräns för hur många bilder jag kan bearbeta?",
    "landing.remove.faq4.a": "Eftersom allt körs på din egen enhet har vi noll serverkostnader. Därför kan du bearbeta obegränsat med bilder helt gratis.",
    "landing.compress.faq1.q": "Hur fungerar offline-komprimering?",
    "landing.compress.faq1.a": "Vi använder lokal Canvas-rendering och WebAssembly-komprimeringsalgoritmer för att krympa filstorleken direkt i din webbläsare utan några nätverksuppladdningar.",
    "landing.compress.faq2.q": "Kan jag komprimera partier av foton?",
    "landing.compress.faq2.a": "Ja, du kan släppa upp till 10 foton samtidigt. Den lokala motorn kommer att komprimera dem alla på en gång och exportera dem som en enda ZIP-fil.",
    "landing.compress.faq3.q": "Kommer kvaliteten att försämras synligt?",
    "landing.compress.faq3.a": "Våra algoritmer använder perceptuellt förlustfri komprimering, vilket innebär att filstorleken krymper med upp till 90 % medan den visuella kvaliteten förblir identisk för det mänskliga ögat.",
    "landing.compress.faq4.q": "Är detta säkert för konfidentiella ID-foton?",
    "landing.compress.faq4.a": "100 % säkert. Dina ID- och passfoton lämnar aldrig din enhet. Komprimeringen sker helt inuti din webbläsares säkra sandlåda."
  },
  ms: {
    "landing.global.faq.title": "Soalan Lazim",
    "landing.global.faq.desc": "Semua yang anda perlu tahu mengenai enjin pemprosesan tempatan kami.",
    "landing.remove.faq1.q": "Adakah pembuangan latar belakang benar-benar diproses di luar talian?",
    "landing.remove.faq1.a": "Ya. Model AI kami dimuatkan ke dalam memori pelayar anda, jadi keseluruhan pengesanan latar belakang berlaku pada CPU/GPU anda, memastikan privasi yang lengkap.",
    "landing.remove.faq2.q": "Adakah resolusi imej akan dikurangkan?",
    "landing.remove.faq2.a": "Tidak, kami mengekalkan resolusi imej asal anda. Potongan tersebut dijana dan digabungkan dengan piksel definisi tinggi asal anda.",
    "landing.remove.faq3.q": "Adakah ia berfungsi dengan baik dengan tepi rambut yang kompleks?",
    "landing.remove.faq3.a": "Tentu sekali. Model AI WebAssembly dilatih khusus untuk memotong butiran halus seperti rambut, bulu, dan objek separuh lutsinar.",
    "landing.remove.faq4.q": "Adakah terdapat had kepada bilangan imej yang boleh saya proses?",
    "landing.remove.faq4.a": "Memandangkan semuanya berjalan pada peranti anda sendiri, tiada kos pelayan bagi pihak kami. Oleh itu, anda boleh memproses imej tanpa had secara percuma sepenuhnya.",
    "landing.compress.faq1.q": "Bagaimanakah pemampatan luar talian berfungsi?",
    "landing.compress.faq1.a": "Kami menggunakan pemaparan Canvas tempatan dan algoritma pemampatan WebAssembly untuk mengecilkan saiz fail terus pada pelayar anda tanpa sebarang muat naik rangkaian.",
    "landing.compress.faq2.q": "Bolehkah saya memampatkan kumpulan foto?",
    "landing.compress.faq2.a": "Ya, anda boleh menjatuhkan sehingga 10 foto serentak. Enjin tempatan akan memampatkannya semua sekaligus dan mengeksportnya sebagai fail ZIP tunggal.",
    "landing.compress.faq3.q": "Adakah kualitinya akan merosot dengan ketara?",
    "landing.compress.faq3.a": "Algoritma kami menggunakan pemampatan tanpa kehilangan secara visual, yang bermaksud saiz fail menyusut sehingga 90% manakala kualiti visual kekal sama kepada mata manusia.",
    "landing.compress.faq4.q": "Adakah ini selamat untuk foto ID sulit?",
    "landing.compress.faq4.a": "100% selamat. Foto ID dan pasport anda tidak pernah meninggalkan peranti anda. Pemampatan berlaku sepenuhnya di dalam kotak pasir pelayar web anda yang selamat."
  },
  tl: {
    "landing.global.faq.title": "Mga Madalas Itanong",
    "landing.global.faq.desc": "Lahat ng kailangan mong malaman tungkol sa aming lokal na makina ng pagproseso.",
    "landing.remove.faq1.q": "Ang pag-alis ba ng background ay talagang pinoproseso offline?",
    "landing.remove.faq1.a": "Oo. Nilo-load ang aming modelo ng AI sa memorya ng iyong browser, kaya ang buong pagtuklas sa background ay nagaganap sa iyong CPU/GPU, tinitiyak ang kumpletong pagkapribado.",
    "landing.remove.faq2.q": "Mababawasan ba ang resolusyon ng larawan?",
    "landing.remove.faq2.a": "Hindi, pinapanatili namin ang orihinal mong resolusyon ng larawan. Ang cutout ay nabuo at pinagsama sa iyong orihinal na high-definition pixels.",
    "landing.remove.faq3.q": "Maayos ba itong gumagana sa kumplikadong mga gilid ng buhok?",
    "landing.remove.faq3.a": "Syempre. Ang modelong AI ng WebAssembly ay partikular na sinanay para mag-cut out ng maliliit na detalye tulad ng buhok, balahibo, at semi-transparent na bagay.",
    "landing.remove.faq4.q": "May limitasyon ba kung gaano karaming mga imahe ang maaari kong iproseso?",
    "landing.remove.faq4.a": "Dahil ang lahat ay tumatakbo sa sarili mong device, walang gastos sa server para sa amin. Samakatuwid, maaari kang magproseso ng walang limitasyong mga imahe ng libre.",
    "landing.compress.faq1.q": "Paano gumagana ang offline na compression?",
    "landing.compress.faq1.a": "Gumagamit kami ng lokal na Canvas rendering at WebAssembly compression algorithms upang paliitin ang laki ng file nang direkta sa iyong browser nang walang anumang network uploads.",
    "landing.compress.faq2.q": "Maaari ko bang i-compress ang mga batch ng larawan?",
    "landing.compress.faq2.a": "Oo, maaari kang mag-drop ng hanggang 10 larawan nang sabay-sabay. Iko-compress ng lokal na engine ang lahat ng ito nang sabay-sabay at i-export ang mga ito bilang isang ZIP file.",
    "landing.compress.faq3.q": "Kapansin-pansin bang bababa ang kalidad?",
    "landing.compress.faq3.a": "Gumagamit ang aming mga algorithm ng perceptually lossless compression, na nangangahulugang ang laki ng file ay lumiliit ng hanggang 90% habang ang visual na kalidad ay nananatiling magkapareho sa mata ng tao.",
    "landing.compress.faq4.q": "Ligtas ba ito para sa mga kumpidensyal na larawan ng ID?",
    "landing.compress.faq4.a": "100% ligtas. Hindi kailanman iniiwan ng iyong mga larawan sa ID at pasaporte ang iyong device. Ang pag-compress ay nangyayari nang buo sa loob ng secure na sandbox ng iyong web browser."
  },
  uk: {
    "landing.global.faq.title": "Поширені запитання",
    "landing.global.faq.desc": "Усе, що вам потрібно знати про наш механізм локальної обробки.",
    "landing.remove.faq1.q": "Чи дійсно видалення фону відбувається в автономному режимі?",
    "landing.remove.faq1.a": "Так. Наша модель ШІ завантажується в пам'ять вашого браузера, тому повне виявлення фону відбувається на вашому CPU/GPU, що гарантує повну конфіденційність.",
    "landing.remove.faq2.q": "Чи зменшиться роздільна здатність зображення?",
    "landing.remove.faq2.a": "Ні, ми зберігаємо початкову роздільну здатність вашого зображення. Виріз генерується та об'єднується з вашими вихідними пікселями високої чіткості.",
    "landing.remove.faq3.q": "Чи добре він працює зі складними краями волосся?",
    "landing.remove.faq3.a": "Абсолютно. Модель ШІ WebAssembly спеціально навчена виділяти дрібні деталі, такі як волосся, хутро та напівпрозорі об'єкти.",
    "landing.remove.faq4.q": "Чи є обмеження на кількість зображень, які я можу обробити?",
    "landing.remove.faq4.a": "Оскільки все працює на вашому власному пристрої, для нас немає витрат на сервер. Тому ви можете обробляти необмежену кількість зображень абсолютно безкоштовно.",
    "landing.compress.faq1.q": "Як працює автономне стиснення?",
    "landing.compress.faq1.a": "Ми використовуємо локальний рендеринг Canvas та алгоритми стиснення WebAssembly для зменшення розміру файлу безпосередньо у вашому браузері без будь-яких мережевих завантажень.",
    "landing.compress.faq2.q": "Чи можу я стискати партії фотографій?",
    "landing.compress.faq2.a": "Так, ви можете одночасно перетягнути до 10 фотографій. Локальний механізм стисне їх усі відразу та експортує як єдиний ZIP-файл.",
    "landing.compress.faq3.q": "Чи помітно погіршиться якість?",
    "landing.compress.faq3.a": "Наші алгоритми використовують візуально стиснення без втрат, що означає, що розмір файлу зменшується до 90%, тоді як візуальна якість залишається ідентичною для людського ока.",
    "landing.compress.faq4.q": "Чи безпечно це для конфіденційних фотографій на документи?",
    "landing.compress.faq4.a": "100% безпечно. Ваші фотографії для документів і паспорта ніколи не залишають ваш пристрій. Стиснення відбувається повністю всередині безпечної пісочниці вашого веб-браузера."
  },
  ro: {
    "landing.global.faq.title": "Întrebări Frecvente",
    "landing.global.faq.desc": "Tot ce trebuie să știți despre motorul nostru local de procesare.",
    "landing.remove.faq1.q": "Eliminarea fundalului este cu adevărat procesată offline?",
    "landing.remove.faq1.a": "Da. Modelul nostru AI este încărcat în memoria browserului dvs., astfel încât întreaga detectare a fundalului se întâmplă pe CPU/GPU-ul dvs., asigurând confidențialitate completă.",
    "landing.remove.faq2.q": "Se va reduce rezoluția imaginii?",
    "landing.remove.faq2.a": "Nu, vă păstrăm rezoluția originală a imaginii. Decupajul este generat și îmbinat cu pixelii originali de înaltă definiție.",
    "landing.remove.faq3.q": "Funcționează bine cu marginile complexe ale părului?",
    "landing.remove.faq3.a": "Absolut. Modelul WebAssembly AI este special antrenat pentru a decupa detalii fine, cum ar fi părul, blana și obiectele semitransparente.",
    "landing.remove.faq4.q": "Există o limită la câte imagini pot procesa?",
    "landing.remove.faq4.a": "Deoarece totul rulează pe propriul dispozitiv, nu avem costuri de server. Prin urmare, puteți procesa imagini nelimitate complet gratuit.",
    "landing.compress.faq1.q": "Cum funcționează compresia offline?",
    "landing.compress.faq1.a": "Folosim randare locală Canvas și algoritmi de compresie WebAssembly pentru a micșora dimensiunea fișierului direct pe browserul dvs., fără nicio încărcare în rețea.",
    "landing.compress.faq2.q": "Pot comprima loturi de fotografii?",
    "landing.compress.faq2.a": "Da, puteți plasa până la 10 fotografii simultan. Motorul local le va comprima pe toate simultan și le va exporta ca un singur fișier ZIP.",
    "landing.compress.faq3.q": "Calitatea va fi degradată vizibil?",
    "landing.compress.faq3.a": "Algoritmii noștri utilizează compresia perceptiv fără pierderi, ceea ce înseamnă că dimensiunea fișierului se micșorează cu până la 90%, în timp ce calitatea vizuală rămâne identică cu ochiul uman.",
    "landing.compress.faq4.q": "Este sigur pentru fotografiile de identitate confidențiale?",
    "landing.compress.faq4.a": "100% sigur. Fotografiile dvs. de buletin și pașaport nu părăsesc niciodată dispozitivul dvs. Compresia se întâmplă în întregime în interiorul sandboxului securizat al browserului dvs. web."
  },
  el: {
    "landing.global.faq.title": "Συχνές Ερωτήσεις",
    "landing.global.faq.desc": "Όλα όσα πρέπει να γνωρίζετε για την τοπική μηχανή επεξεργασίας μας.",
    "landing.remove.faq1.q": "Είναι η αφαίρεση του φόντου πραγματικά offline επεξεργασία;",
    "landing.remove.faq1.a": "Ναι. Το μοντέλο AI μας φορτώνεται στη μνήμη του προγράμματος περιήγησής σας, οπότε ολόκληρη η ανίχνευση φόντου συμβαίνει στην CPU / GPU σας, εξασφαλίζοντας πλήρη ιδιωτικότητα.",
    "landing.remove.faq2.q": "Θα μειωθεί η ανάλυση της εικόνας;",
    "landing.remove.faq2.a": "Όχι, διατηρούμε την αρχική ανάλυση της εικόνας σας. Η αποκοπή δημιουργείται και συγχωνεύεται με τα αρχικά σας pixel υψηλής ευκρίνειας.",
    "landing.remove.faq3.q": "Λειτουργεί καλά με πολύπλοκες άκρες μαλλιών;",
    "landing.remove.faq3.a": "Απολύτως. Το μοντέλο WebAssembly AI έχει εκπαιδευτεί ειδικά για να κόβει λεπτές λεπτομέρειες όπως μαλλιά, γούνα και ημιδιαφανή αντικείμενα.",
    "landing.remove.faq4.q": "Υπάρχει όριο στο πόσες εικόνες μπορώ να επεξεργαστώ;",
    "landing.remove.faq4.a": "Δεδομένου ότι όλα τρέχουν στη δική σας συσκευή, υπάρχουν μηδενικά έξοδα διακομιστή για εμάς. Επομένως, μπορείτε να επεξεργαστείτε απεριόριστες εικόνες εντελώς δωρεάν.",
    "landing.compress.faq1.q": "Πώς λειτουργεί η συμπίεση offline;",
    "landing.compress.faq1.a": "Χρησιμοποιούμε τοπική απόδοση Canvas και αλγόριθμους συμπίεσης WebAssembly για να συρρικνώσουμε το μέγεθος του αρχείου απευθείας στο πρόγραμμα περιήγησής σας χωρίς μεταφορτώσεις δικτύου.",
    "landing.compress.faq2.q": "Μπορώ να συμπιέσω παρτίδες φωτογραφιών;",
    "landing.compress.faq2.a": "Ναι, μπορείτε να ρίξετε έως και 10 φωτογραφίες ταυτόχρονα. Ο τοπικός κινητήρας θα τα συμπιέσει όλα ταυτόχρονα και θα τα εξαγάγει ως ένα ενιαίο αρχείο ZIP.",
    "landing.compress.faq3.q": "Θα υποβαθμιστεί ορατά η ποιότητα;",
    "landing.compress.faq3.a": "Οι αλγόριθμοί μας χρησιμοποιούν αντιληπτά συμπίεση χωρίς απώλειες, πράγμα που σημαίνει ότι το μέγεθος του αρχείου συρρικνώνεται έως και 90% ενώ η οπτική ποιότητα παραμένει πανομοιότυπη με το ανθρώπινο μάτι.",
    "landing.compress.faq4.q": "Είναι αυτό ασφαλές για εμπιστευτικές φωτογραφίες ταυτότητας;",
    "landing.compress.faq4.a": "100% ασφαλές. Οι φωτογραφίες της ταυτότητας και του διαβατηρίου σας δεν εγκαταλείπουν ποτέ τη συσκευή σας. Η συμπίεση συμβαίνει εξ ολοκλήρου μέσα στο ασφαλές sandbox του προγράμματος περιήγησής σας."
  },
  cs: {
    "landing.global.faq.title": "Často Kladené Otázky",
    "landing.global.faq.desc": "Vše, co potřebujete vědět o našem modulu místního zpracování.",
    "landing.remove.faq1.q": "Je odstranění pozadí skutečně zpracováváno offline?",
    "landing.remove.faq1.a": "Ano. Náš model AI je načten do paměti vašeho prohlížeče, takže celá detekce pozadí probíhá na vašem CPU/GPU, což zajišťuje úplné soukromí.",
    "landing.remove.faq2.q": "Sníží se rozlišení obrázku?",
    "landing.remove.faq2.a": "Ne, zachováme vaše původní rozlišení obrázku. Výřez je vygenerován a sloučen s vašimi původními pixely s vysokým rozlišením.",
    "landing.remove.faq3.q": "Funguje to dobře se složitými okraji vlasů?",
    "landing.remove.faq3.a": "Rozhodně. Model WebAssembly AI je speciálně trénován pro oddělení jemných detailů, jako jsou vlasy, srst a poloprůhledné předměty.",
    "landing.remove.faq4.q": "Existuje limit počtu obrázků, které mohu zpracovat?",
    "landing.remove.faq4.a": "Vzhledem k tomu, že vše běží na vašem vlastním zařízení, jsou pro nás nulové náklady na server. Můžete tedy zpracovávat neomezený počet obrázků zcela zdarma.",
    "landing.compress.faq1.q": "Jak funguje komprese offline?",
    "landing.compress.faq1.a": "Ke zmenšení velikosti souboru přímo ve vašem prohlížeči bez jakéhokoli odesílání do sítě používáme místní vykreslování Canvas a kompresní algoritmy WebAssembly.",
    "landing.compress.faq2.q": "Mohu komprimovat dávky fotografií?",
    "landing.compress.faq2.a": "Ano, můžete najednou vložit až 10 fotografií. Místní modul je všechny zkomprimuje najednou a exportuje jako jeden soubor ZIP.",
    "landing.compress.faq3.q": "Bude kvalita viditelně zhoršena?",
    "landing.compress.faq3.a": "Naše algoritmy používají percepčně bezztrátovou kompresi, což znamená, že se velikost souboru zmenší až o 90 %, zatímco vizuální kvalita zůstává pro lidské oko totožná.",
    "landing.compress.faq4.q": "Je to bezpečné pro důvěrné průkazové fotografie?",
    "landing.compress.faq4.a": "100% bezpečné. Vaše průkazové a pasové fotografie nikdy neopustí vaše zařízení. Komprese probíhá výhradně v zabezpečeném karanténním prostoru vašeho webového prohlížeče."
  },
  hu: {
    "landing.global.faq.title": "Gyakran Ismételt Kérdések",
    "landing.global.faq.desc": "Minden, amit tudnia kell a helyi feldolgozó motorunkról.",
    "landing.remove.faq1.q": "A háttér eltávolítását tényleg offline dolgozzák fel?",
    "landing.remove.faq1.a": "Igen. AI-modellünk betöltődik a böngésző memóriájába, így a teljes háttérészlelés a CPU/GPU-ján történik, teljes magánéletet biztosítva.",
    "landing.remove.faq2.q": "Csökken a kép felbontása?",
    "landing.remove.faq2.a": "Nem, megőrizzük az eredeti képfelbontást. A kivágás generálódik és egyesül az eredeti nagy felbontású pixelekkel.",
    "landing.remove.faq3.q": "Jól működik összetett hajszéleknél?",
    "landing.remove.faq3.a": "Abszolút. A WebAssembly AI-modellt kifejezetten finom részletek, például haj, szőrzet és félig átlátszó tárgyak kivágására oktatták.",
    "landing.remove.faq4.q": "Van korlátja annak, hogy hány képet dolgozhatok fel?",
    "landing.remove.faq4.a": "Mivel minden a saját eszközén fut, számunkra nincsenek szerverköltségek. Ezért korlátlan számú képet dolgozhat fel teljesen ingyenesen.",
    "landing.compress.faq1.q": "Hogyan működik az offline tömörítés?",
    "landing.compress.faq1.a": "Helyi Canvas-megjelenítést és WebAssembly-tömörítési algoritmusokat használunk, hogy a fájlméretet közvetlenül a böngészőjében, hálózati feltöltések nélkül csökkentsük.",
    "landing.compress.faq2.q": "Tömöríthetek fényképekből álló kötegeket?",
    "landing.compress.faq2.a": "Igen, akár 10 fényképet is bedobhat egyszerre. A helyi motor mindet egyszerre tömöríti, és egyetlen ZIP-fájlként exportálja őket.",
    "landing.compress.faq3.q": "A minőség láthatóan romlik?",
    "landing.compress.faq3.a": "Algoritmusaink vizuálisan veszteségmentes tömörítést használnak, ami azt jelenti, hogy a fájl mérete akár 90%-kal is csökken, miközben a vizuális minőség az emberi szem számára változatlan marad.",
    "landing.compress.faq4.q": "Biztonságos ez a bizalmas igazolványképekhez?",
    "landing.compress.faq4.a": "100%-ban biztonságos. Az igazolvány- és útlevélképek soha nem hagyják el az eszközét. A tömörítés teljes egészében a webböngésző biztonságos tesztkörnyezetében (sandbox) történik."
  },
  da: {
    "landing.global.faq.title": "Ofte Stillede Spørgsmål",
    "landing.global.faq.desc": "Alt du behøver at vide om vores lokale behandlingsmotor.",
    "landing.remove.faq1.q": "Bliver baggrundsfjernelsen virkelig behandlet offline?",
    "landing.remove.faq1.a": "Ja. Vores AI-model indlæses i din browsers hukommelse, så hele baggrundsregistreringen sker på din CPU/GPU, hvilket sikrer komplet privatliv.",
    "landing.remove.faq2.q": "Bliver billedopløsningen reduceret?",
    "landing.remove.faq2.a": "Nej, vi bevarer din oprindelige billedopløsning. Udskæringen genereres og flettes med dine oprindelige højopløselige pixels.",
    "landing.remove.faq3.q": "Fungerer det godt med komplekse hårkanter?",
    "landing.remove.faq3.a": "Absolut. WebAssembly AI-modellen er specifikt trænet til at frilægge fine detaljer som hår, pels og halvgennemsigtige objekter.",
    "landing.remove.faq4.q": "Er der en grænse for, hvor mange billeder jeg kan behandle?",
    "landing.remove.faq4.a": "Da alt kører på din egen enhed, har vi ingen serveromkostninger. Derfor kan du behandle ubegrænsede billeder helt gratis.",
    "landing.compress.faq1.q": "Hvordan fungerer offline-komprimering?",
    "landing.compress.faq1.a": "Vi bruger lokal Canvas-rendering og WebAssembly-komprimeringsalgoritmer til at krympe filstørrelsen direkte i din browser uden nogen netværksuploads.",
    "landing.compress.faq2.q": "Kan jeg komprimere batches af fotos?",
    "landing.compress.faq2.a": "Ja, du kan slippe op til 10 fotos samtidigt. Den lokale motor vil komprimere dem alle på én gang og eksportere dem som en enkelt ZIP-fil.",
    "landing.compress.faq3.q": "Bliver kvaliteten synligt forringet?",
    "landing.compress.faq3.a": "Vores algoritmer bruger perceptuelt tabsfri komprimering, hvilket betyder, at filstørrelsen krymper med op til 90 %, mens den visuelle kvalitet forbliver identisk for det blotte øje.",
    "landing.compress.faq4.q": "Er dette sikkert for fortrolige ID-fotos?",
    "landing.compress.faq4.a": "100 % sikkert. Dine ID- og pasfotos forlader aldrig din enhed. Komprimeringen sker udelukkende inde i din webbrowsers sikre sandkasse."
  },
  fi: {
    "landing.global.faq.title": "Usein Kysytyt Kysymykset",
    "landing.global.faq.desc": "Kaikki mitä sinun tarvitsee tietää paikallisesta käsittelymoottoristamme.",
    "landing.remove.faq1.q": "Käsitelläänkö taustan poisto todella offline-tilassa?",
    "landing.remove.faq1.a": "Kyllä. Tekoälymallimme ladataan selaimesi muistiin, joten koko taustan havaitseminen tapahtuu CPU:llasi/GPU:llasi varmistaen täydellisen yksityisyyden.",
    "landing.remove.faq2.q": "Pieneneekö kuvan resoluutio?",
    "landing.remove.faq2.a": "Ei, säilytämme alkuperäisen kuvaresoluution. Leikkaus luodaan ja yhdistetään alkuperäisiin teräväpiirtopikseleihisi.",
    "landing.remove.faq3.q": "Toimiiko se hyvin monimutkaisilla hiusten reunoilla?",
    "landing.remove.faq3.a": "Ehdottomasti. WebAssembly AI -malli on erityisesti koulutettu irrottamaan hienoja yksityiskohtia, kuten hiuksia, turkista ja puoliläpinäkyviä esineitä.",
    "landing.remove.faq4.q": "Onko olemassa raja, kuinka monta kuvaa voin käsitellä?",
    "landing.remove.faq4.a": "Koska kaikki toimii omalla laitteellasi, meillä ei ole palvelinkustannuksia. Siksi voit käsitellä rajattomasti kuvia täysin ilmaiseksi.",
    "landing.compress.faq1.q": "Miten offline-pakkaus toimii?",
    "landing.compress.faq1.a": "Käytämme paikallista Canvas-renderointia ja WebAssembly-pakkausalgoritmeja tiedostokoon pienentämiseksi suoraan selaimessasi ilman verkkolatauksia.",
    "landing.compress.faq2.q": "Voinko pakata eriä valokuvia?",
    "landing.compress.faq2.a": "Kyllä, voit pudottaa enintään 10 valokuvaa kerrallaan. Paikallinen moottori pakkaa ne kaikki kerralla ja vie ne yhtenä ZIP-tiedostona.",
    "landing.compress.faq3.q": "Heikkeneekö laatu näkyvästi?",
    "landing.compress.faq3.a": "Algoritmimme käyttävät havainnollisesti häviötöntä pakkausta, mikä tarkoittaa, että tiedostokoko pienenee jopa 90 % visuaalisen laadun pysyessä samana ihmissilmälle.",
    "landing.compress.faq4.q": "Onko tämä turvallista luottamuksellisille henkilökuville?",
    "landing.compress.faq4.a": "100 % turvallista. Henkilöllisyystodistus- ja passikuvasi eivät koskaan lähde laitteeltasi. Pakkaus tapahtuu kokonaan selaimesi turvallisessa hiekkalaatikossa."
  },
  no: {
    "landing.global.faq.title": "Ofte Stilte Spørsmål",
    "landing.global.faq.desc": "Alt du trenger å vite om vår lokale behandlingsmotor.",
    "landing.remove.faq1.q": "Blir bakgrunnsfjerningen virkelig behandlet offline?",
    "landing.remove.faq1.a": "Ja. AI-modellen vår lastes inn i nettleserens minne, så hele bakgrunnsdeteksjonen skjer på CPU-en/GPU-en din, og sikrer fullstendig personvern.",
    "landing.remove.faq2.q": "Vil bildeoppløsningen reduseres?",
    "landing.remove.faq2.a": "Nei, vi bevarer den opprinnelige bildeoppløsningen. Utskjæringen genereres og slås sammen med dine opprinnelige høyoppløselige piksler.",
    "landing.remove.faq3.q": "Fungerer det bra med komplekse hårkanter?",
    "landing.remove.faq3.a": "Absolutt. WebAssembly AI-modellen er spesifikt trent for å frilegge fine detaljer som hår, pels og halvveis gjennomsiktige objekter.",
    "landing.remove.faq4.q": "Er det en grense for hvor mange bilder jeg kan behandle?",
    "landing.remove.faq4.a": "Siden alt kjøres på din egen enhet, har vi null serverkostnader. Derfor kan du behandle et ubegrenset antall bilder helt gratis.",
    "landing.compress.faq1.q": "Hvordan fungerer offline-komprimering?",
    "landing.compress.faq1.a": "Vi bruker lokal Canvas-gjengivelse og WebAssembly-komprimeringsalgoritmer for å krympe filstørrelsen direkte i nettleseren din uten noen nettverksopplastinger.",
    "landing.compress.faq2.q": "Kan jeg komprimere partier av bilder?",
    "landing.compress.faq2.a": "Ja, du kan slippe opptil 10 bilder samtidig. Den lokale motoren vil komprimere alle på én gang og eksportere dem som en enkelt ZIP-fil.",
    "landing.compress.faq3.q": "Vil kvaliteten synlig forringes?",
    "landing.compress.faq3.a": "Algoritmene våre bruker perseptuelt tapsfri komprimering, noe som betyr at filstørrelsen krymper med opptil 90 % mens den visuelle kvaliteten forblir identisk for det blotte øye.",
    "landing.compress.faq4.q": "Er dette trygt for konfidensielle ID-bilder?",
    "landing.compress.faq4.a": "100 % trygt. ID- og passbildene dine forlater aldri enheten din. Komprimeringen skjer utelukkende inne i nettleserens sikre sandkasse."
  },
  he: {
    "landing.global.faq.title": "שאלות נפוצות",
    "landing.global.faq.desc": "כל מה שאתה צריך לדעת על מנוע העיבוד המקומי שלנו.",
    "landing.remove.faq1.q": "האם הסרת הרקע באמת מתבצעת במצב לא מקוון?",
    "landing.remove.faq1.a": "כן. מודל ה-AI שלנו נטען לתוך הזיכרון של הדפדפן שלך, כך שכל זיהוי הרקע קורה על ה-CPU/GPU שלך, מה שמבטיח פרטיות מוחלטת.",
    "landing.remove.faq2.q": "האם רזולוציית התמונה תופחת?",
    "landing.remove.faq2.a": "לא, אנו שומרים על רזולוציית התמונה המקורית שלך. החיתוך נוצר וממוזג עם הפיקסלים המקוריים שלך באיכות גבוהה.",
    "landing.remove.faq3.q": "האם זה עובד היטב עם קצוות שיער מורכבים?",
    "landing.remove.faq3.a": "בהחלט. מודל ה-AI של WebAssembly אומן במיוחד לגזור פרטים עדינים כמו שיער, פרווה וחפצים חצי שקופים.",
    "landing.remove.faq4.q": "האם יש גבול לכמה תמונות אני יכול לעבד?",
    "landing.remove.faq4.a": "מכיוון שהכל פועל על המכשיר שלך, אין לנו עלויות שרת. לכן, אתה יכול לעבד תמונות ללא הגבלה בחינם לחלוטין.",
    "landing.compress.faq1.q": "איך עובדת דחיסה לא מקוונת?",
    "landing.compress.faq1.a": "אנו משתמשים ברינדור Canvas מקומי ובאלגוריתמי דחיסה של WebAssembly כדי לכווץ את גודל הקובץ ישירות בדפדפן שלך ללא כל העלאות רשת.",
    "landing.compress.faq2.q": "האם אוכל לדחוס קבוצות של תמונות?",
    "landing.compress.faq2.a": "כן, אתה יכול לשחרר עד 10 תמונות בו זמנית. המנוע המקומי ידחוס את כולן בבת אחת וייצא אותן כקובץ ZIP אחד.",
    "landing.compress.faq3.q": "האם האיכות תרד באופן גלוי?",
    "landing.compress.faq3.a": "האלגוריתמים שלנו משתמשים בדחיסה נטולת אובדן מבחינה תפיסתית, כלומר גודל הקובץ מתכווץ בעד 90% בעוד שהאיכות החזותית נשארת זהה לעין האנושית.",
    "landing.compress.faq4.q": "האם זה בטוח לתמונות זיהוי חסויות?",
    "landing.compress.faq4.a": "100% בטוח. תמונות תעודת הזהות והדרכון שלך לעולם לא עוזבות את המכשיר שלך. הדחיסה קורית כולה בתוך ארגז החול המאובטח של דפדפן האינטרנט שלך."
  }
};

const scriptDir = __dirname;
const localesDir = path.join(scriptDir, '../public/locales');

for (const [lang, kv] of Object.entries(translations)) {
  const filePath = path.join(localesDir, lang, 'translation.json');
  if (fs.existsSync(filePath)) {
    const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    for (const [key, val] of Object.entries(kv)) {
      data[key] = val;
    }
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
    console.log(`[${lang}] Injected FAQ translations part 2`);
  }
}
