const fs = require('fs');
const path = require('path');

const translations = {
  he: {
    "landing.compress.redesign.heroBadge": "דחיסה חכמה",
    "landing.compress.redesign.heroTitle": "כווץ את גודל קובץ התמונה בעד 90% באופן מיידי",
    "landing.compress.redesign.heroDesc": "הקטן את גודל התמונות שלך מבלי לאבד מהאיכות. מושלם לאתרים ודוא\"ל.",
    "landing.compress.redesign.feat1Badge": "ללא אובדן איכות",
    "landing.compress.redesign.feat1Title": "אופטימיזציה חכמה",
    "landing.compress.redesign.feat1Desc": "מוצא אוטומטית את האיזון המושלם בין גודל קובץ מינימלי לאיכות תמונה מקסימלית.",
    "landing.compress.redesign.feat2Badge": "100% פרטי",
    "landing.compress.redesign.feat2Title": "ללא העלאות",
    "landing.compress.redesign.feat2Desc": "הדחיסה מתבצעת ישירות בדפדפן שלך. שום דבר לא עובר לשרת.",
    "landing.compress.redesign.feat3Badge": "כל פורמט",
    "landing.compress.redesign.feat3Title": "תמיכה רחבה",
    "landing.compress.redesign.feat3Desc": "עובד עם פורמטים סטנדרטיים של JPG ו-PNG, כמו גם פורמטים מודרניים של WEBP.",
    "landing.compress.redesign.whoTag": "למי זה מיועד",
    "landing.compress.redesign.whoTitle": "נבנה עבור רשת ומדיה",
    "landing.compress.redesign.whoDesc": "מושלם למפתחים, מעצבים ומנהלי רשתות חברתיות.",
    "landing.compress.redesign.who1Title": "מפתחי אתרים",
    "landing.compress.redesign.who1Desc": "שפר את ציוני PageSpeed והקטן את זמני הטעינה.",
    "landing.compress.redesign.who1Tags": "אופטימיזציית SEO",
    "landing.compress.redesign.who2Title": "יוצרי תוכן",
    "landing.compress.redesign.who2Desc": "עמוד במגבלות גודל העלאה קפדניות עבור פלטפורמות כמו Discord.",
    "landing.compress.redesign.who2Tags": "רשתות חברתיות",
    "landing.compress.redesign.stepsTag": "איך זה עובד",
    "landing.compress.redesign.stepsTitle": "3 שלבים לאופטימיזציה",
    "landing.compress.redesign.s1Title": "העלאת תמונות",
    "landing.compress.redesign.s1Desc": "גרור ושחרר את התמונות שלך לסביבת העבודה.",
    "landing.compress.redesign.s2Title": "הגדר רמת דחיסה",
    "landing.compress.redesign.s2Desc": "התאם את המחוון כדי למצוא את האיזון הנכון.",
    "landing.compress.redesign.s3Title": "חסוך באחסון",
    "landing.compress.redesign.s3Desc": "הורד את התמונות שעברו אופטימיזציה.",
    "landing.remove.redesign.heroBadge": "חיתוך מבוסס AI",
    "landing.remove.redesign.heroTitle": "הסר רקע בשנייה אחת בדיוק מושלם",
    "landing.remove.redesign.heroDesc": "קבל חיתוך שיער מושלם וקצוות חלקים מבלי להעלות תמונות לשרת.",
    "landing.remove.redesign.feat1Badge": "99.8% דיוק",
    "landing.remove.redesign.feat1Title": "זיהוי שיער וקצוות ללא רבב",
    "landing.remove.redesign.feat1Desc": "הרשת העצבית שלנו מתמודדת בקלות עם פרטים מורכבים.",
    "landing.remove.redesign.feat2Badge": "100% בטוח",
    "landing.remove.redesign.feat2Title": "פרטיות אופליין מלאה",
    "landing.remove.redesign.feat2Desc": "מודל ה-AI נטען ישירות לדפדפן. התמונות שלך לעולם לא עוזבות את המחשב.",
    "landing.remove.redesign.feat3Badge": "מצב אצווה",
    "landing.remove.redesign.feat3Title": "מוכן לעיבוד כמותי",
    "landing.remove.redesign.feat3Desc": "עבד עד 10 תמונות בו זמנית והורד בקובץ ZIP.",
    "landing.remove.redesign.whoTag": "למי זה מיועד",
    "landing.remove.redesign.whoTitle": "מושלם לכל צורך יצירתי",
    "landing.remove.redesign.whoDesc": "בין אם אתה מוכר רכבים, מעצב פוסטרים או יוצר מסמכים.",
    "landing.remove.redesign.who1Title": "מוכרי אי-קומרס",
    "landing.remove.redesign.who1Desc": "צור רקעים לבנים ונקיים לרשימות מוצרים.",
    "landing.remove.redesign.who1Tags": "רשימות מוצרים",
    "landing.remove.redesign.who2Title": "מעצבים גרפיים",
    "landing.remove.redesign.who2Desc": "חלץ לוגואים ונכסים באופן מיידי.",
    "landing.remove.redesign.who2Tags": "נכסי עיצוב",
    "landing.remove.redesign.stepsTag": "איך זה עובד",
    "landing.remove.redesign.stepsTitle": "3 שלבים לרקע שקוף",
    "landing.remove.redesign.s1Title": "העלאת תמונה",
    "landing.remove.redesign.s1Desc": "גרור את התמונה שלך. PNG, JPG או WEBP.",
    "landing.remove.redesign.s2Title": "עיבוד AI",
    "landing.remove.redesign.s2Desc": "ה-AI המקומי מזהה את הנושא בתוך שנייה.",
    "landing.remove.redesign.s3Title": "הורדת HD",
    "landing.remove.redesign.s3Desc": "ייצא את התמונה החתוכה עם רקע שקוף.",
    "home.why.tag": "למה HELPMYIMG",
    "home.why.title": "למה HelpMyIMG היא הבחירה החכמה ביותר",
    "home.why.desc": "תוכנן מאפס לפרטיות מרבית, מהירות שיא ואפס עלות.",
    "home.why.c1.t": "מהירות מקומית מיידית",
    "home.why.c1.d": "התמונות מעובדות ישירות בזיכרון המכשיר ללא השהייה.",
    "home.why.c1.b": "0ms עיכוב שרת",
    "home.why.c2.t": "100% פרטיות מוחלטת",
    "home.why.c2.d": "המסמכים והדיוקנאות שלך מעולם לא עוזבים את המחשב.",
    "home.why.c2.b": "ללא ענן",
    "home.why.c3.t": "חינם וללא הגבלה לתמיד",
    "home.why.c3.d": "ללא מנויים, ללא סימני מים. עריכת תמונות נגישה לכולם.",
    "home.why.c3.b": "$0 / לכל החיים",
    "home.why.c4.t": "עיבוד אצווה עד 10",
    "home.why.c4.d": "גרור עד 10 תמונות וייצא בארכיון ZIP תוך שניות.",
    "home.why.c4.b": "10x מהירות עבודה",
    "home.steps.tag": "איך זה עובד",
    "home.steps.title": "איך HelpMyIMG עובד ב-3 שלבים פשוטים",
    "home.steps.desc": "אין צורך בהתקנת תוכנה. קבל תוצאות מקצועיות מהדפדפן."
  },
  hu: {
    "landing.compress.redesign.heroBadge": "OKOS TÖMÖRÍTÉS",
    "landing.compress.redesign.heroTitle": "Csökkentse a képfájlok méretét akár 90%-kal azonnal",
    "landing.compress.redesign.heroDesc": "Csökkentse a fényképek méretét anélkül, hogy elveszítené a vizuális minőséget. Tökéletes weboldalakhoz és e-mailekhez.",
    "landing.compress.redesign.feat1Badge": "NINCS MINŐSÉGROMLÁS",
    "landing.compress.redesign.feat1Title": "Okos optimalizálás",
    "landing.compress.redesign.feat1Desc": "Automatikusan megtalálja a tökéletes egyensúlyt a minimális fájlméret és a maximális képminőség között.",
    "landing.compress.redesign.feat2Badge": "100% PRIVÁT",
    "landing.compress.redesign.feat2Title": "Nincs feltöltés",
    "landing.compress.redesign.feat2Desc": "A tömörítés közvetlenül a böngészőjében történik. Semmi sem megy a szerverre.",
    "landing.compress.redesign.feat3Badge": "BÁRMILYEN FORMÁTUM",
    "landing.compress.redesign.feat3Title": "Széleskörű támogatás",
    "landing.compress.redesign.feat3Desc": "Működik szabványos JPG és PNG formátumokkal, valamint a modern WEBP formátummal.",
    "landing.compress.redesign.whoTag": "KINEK SZÓL",
    "landing.compress.redesign.whoTitle": "Webre és Média számára épült",
    "landing.compress.redesign.whoDesc": "Tökéletes fejlesztők, tervezők és közösségi média menedzserek számára.",
    "landing.compress.redesign.who1Title": "Webfejlesztők",
    "landing.compress.redesign.who1Desc": "Javítsa a PageSpeed pontszámokat és csökkentse a betöltési időket.",
    "landing.compress.redesign.who1Tags": "SEO OPTIMALIZÁLÁS",
    "landing.compress.redesign.who2Title": "Tartalomkészítők",
    "landing.compress.redesign.who2Desc": "Fejezze meg a szigorú feltöltési méretkorlátokat olyan platformokon, mint a Discord.",
    "landing.compress.redesign.who2Tags": "KÖZÖSSÉGI MÉDIA",
    "landing.compress.redesign.stepsTag": "HOGYAN MŰKÖDIK",
    "landing.compress.redesign.stepsTitle": "3 Lépés az Optimalizáláshoz",
    "landing.compress.redesign.s1Title": "Képek Feltöltése",
    "landing.compress.redesign.s1Desc": "Húzza be a fényképeit a tömörítő munkaterületre.",
    "landing.compress.redesign.s2Title": "Tömörítési Szint Beállítása",
    "landing.compress.redesign.s2Desc": "Állítsa be a minőségcsúszkát az egyensúly megtalálásához.",
    "landing.compress.redesign.s3Title": "Tárhely Megtakarítás",
    "landing.compress.redesign.s3Desc": "Töltse le az optimalizált képeket és élvezze a csökkentett fájlméretet.",
    "landing.remove.redesign.heroBadge": "MI ÁLTAL VEZÉRELT KIVÁGÁS",
    "landing.remove.redesign.heroTitle": "Távolítsa el a hátteret 1 másodperc alatt hibátlan pontossággal",
    "landing.remove.redesign.heroDesc": "Tökéletes haj kivágásokat kaphat anélkül, hogy valaha is feltöltené képeit a szerverre.",
    "landing.remove.redesign.feat1Badge": "99.8% PONTOSSÁG",
    "landing.remove.redesign.feat1Title": "Hibátlan haj és élérzékelés",
    "landing.remove.redesign.feat1Desc": "Neurális hálózatunk könnyedén kezeli a bonyolult részleteket.",
    "landing.remove.redesign.feat2Badge": "100% BIZTONSÁGOS",
    "landing.remove.redesign.feat2Title": "Teljes offline adatvédelem",
    "landing.remove.redesign.feat2Desc": "Az AI modell közvetlenül a böngészőjébe töltődik. A képei soha nem hagyják el a számítógépet.",
    "landing.remove.redesign.feat3Badge": "KÖTEGELT MÓD",
    "landing.remove.redesign.feat3Title": "Készen áll a tömeges feldolgozásra",
    "landing.remove.redesign.feat3Desc": "Húzzon be akár 10 képet egyszerre és töltse le ZIP fájlban.",
    "landing.remove.redesign.whoTag": "KINEK SZÓL",
    "landing.remove.redesign.whoTitle": "Tökéletes minden kreatív igényhez",
    "landing.remove.redesign.whoDesc": "Legyen szó autók eladásáról, plakátok tervezéséről vagy hivatalos dokumentumokról.",
    "landing.remove.redesign.who1Title": "E-kereskedelmi Eladók",
    "landing.remove.redesign.who1Desc": "Hozzon létre tiszta fehér háttereket a terméklistákhoz.",
    "landing.remove.redesign.who1Tags": "TERMÉKLISTÁK",
    "landing.remove.redesign.who2Title": "Grafikus Tervezők",
    "landing.remove.redesign.who2Desc": "Nyerjen ki logókat és eszközöket azonnal.",
    "landing.remove.redesign.who2Tags": "TERVEZÉSI ESZKÖZÖK",
    "landing.remove.redesign.stepsTag": "HOGYAN MŰKÖDIK",
    "landing.remove.redesign.stepsTitle": "3 Lépés az Átlátszó Hátterekhez",
    "landing.remove.redesign.s1Title": "Kép Feltöltése",
    "landing.remove.redesign.s1Desc": "Húzza be a fényképét. PNG, JPG vagy WEBP.",
    "landing.remove.redesign.s2Title": "AI Feldolgozás",
    "landing.remove.redesign.s2Desc": "A helyi AI 1 másodperc alatt felismeri a fő témát.",
    "landing.remove.redesign.s3Title": "HD Letöltése",
    "landing.remove.redesign.s3Desc": "Exportálja a kivágott fényképet átlátszó háttérrel.",
    "home.why.tag": "MIÉRT A HELPMYIMG",
    "home.why.title": "Miért a HelpMyIMG a legokosabb választás",
    "home.why.desc": "A maximális adatvédelem, villámgyors sebesség és nulla költség érdekében tervezték.",
    "home.why.c1.t": "Azonnali Helyi Sebesség",
    "home.why.c1.d": "Képeit közvetlenül az eszköz memóriájában dolgozza fel nulla késleltetéssel.",
    "home.why.c1.b": "0ms Szerver Késleltetés",
    "home.why.c2.t": "100% Abszolút Adatvédelem",
    "home.why.c2.d": "Személyes portréi és bizalmas dokumentumai soha nem hagyják el a számítógépet.",
    "home.why.c2.b": "Nulla Felhőtároló",
    "home.why.c3.t": "Örökre Ingyenes",
    "home.why.c3.d": "Nincs előfizetés, nincs vízjel. HD képszerkesztés mindenki számára elérhető.",
    "home.why.c3.b": "$0 / Élettartam",
    "home.why.c4.t": "Kötegelt Erő",
    "home.why.c4.d": "Húzzon be akár 10 képet, és másodpercek alatt exportálja ZIP-ben.",
    "home.why.c4.b": "10x Munkasebesség",
    "home.steps.tag": "HOGYAN MŰKÖDIK",
    "home.steps.title": "Hogyan működik a HelpMyIMG 3 egyszerű lépésben",
    "home.steps.desc": "Nincs szükség szoftvertelepítésre. Kapjon professzionális eredményeket a böngészőből."
  }
};

const scriptDir = __dirname;
const localesDir = path.join(scriptDir, '../public/locales');

for (const [lang, kv] of Object.entries(translations)) {
  const filePath = path.join(localesDir, lang, 'translation.json');
  if (fs.existsSync(filePath)) {
    const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    for (const [key, val] of Object.entries(kv)) {
      data[key] = val;
    }
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
    console.log(`[${lang}] Injected translations chunk 4`);
  }
}
