const fs = require('fs');
const path = require('path');

const translations = {
  ko: {
    "landing.compress.redesign.heroBadge": "스마트 압축",
    "landing.compress.redesign.heroTitle": "이미지 파일 크기를 즉시 90%까지 줄이세요",
    "landing.compress.redesign.heroDesc": "시각적 품질 저하 없이 사진 크기를 줄이세요. 웹사이트, 이메일 및 엄격한 업로드 제한에 완벽합니다.",
    "landing.compress.redesign.feat1Badge": "품질 손실 없음",
    "landing.compress.redesign.feat1Title": "스마트 최적화",
    "landing.compress.redesign.feat1Desc": "최소 파일 크기와 최대 이미지 품질 사이의 완벽한 균형을 자동으로 찾습니다.",
    "landing.compress.redesign.feat2Badge": "100% 비공개",
    "landing.compress.redesign.feat2Title": "업로드 없음",
    "landing.compress.redesign.feat2Desc": "모든 도구와 마찬가지로 압축은 웹 브라우저에서 바로 수행됩니다. 어떤 서버로도 전송되지 않습니다.",
    "landing.compress.redesign.feat3Badge": "모든 형식",
    "landing.compress.redesign.feat3Title": "광범위한 지원",
    "landing.compress.redesign.feat3Desc": "표준 JPG 및 PNG 형식과 최신 초고효율 WEBP 형식에서 작동합니다.",
    "landing.compress.redesign.whoTag": "대상이 누구인가요",
    "landing.compress.redesign.whoTitle": "웹 및 미디어용으로 제작됨",
    "landing.compress.redesign.whoDesc": "최적화된 이미지가 필요한 개발자, 디자이너 및 소셜 미디어 관리자에게 적합합니다.",
    "landing.compress.redesign.who1Title": "웹 개발자",
    "landing.compress.redesign.who1Desc": "이미지 품질 저하 없이 PageSpeed 점수를 높이고 로드 시간을 단축하세요.",
    "landing.compress.redesign.who1Tags": "SEO 최적화",
    "landing.compress.redesign.who2Title": "콘텐츠 크리에이터",
    "landing.compress.redesign.who2Desc": "Discord, Twitter 또는 이메일 첨부 파일과 같은 플랫폼의 엄격한 업로드 크기 제한을 충족하세요.",
    "landing.compress.redesign.who2Tags": "소셜 미디어",
    "landing.compress.redesign.stepsTag": "사용 방법",
    "landing.compress.redesign.stepsTitle": "최적화를 위한 3단계",
    "landing.compress.redesign.s1Title": "이미지 업로드",
    "landing.compress.redesign.s1Desc": "사진을 압축 작업 공간으로 드래그 앤 드롭하세요.",
    "landing.compress.redesign.s2Title": "압축 수준 설정",
    "landing.compress.redesign.s2Desc": "품질 슬라이더를 조정하여 시각적 품질과 파일 크기 사이의 적절한 균형을 찾으세요.",
    "landing.compress.redesign.s3Title": "저장 공간 절약",
    "landing.compress.redesign.s3Desc": "최적화된 이미지를 다운로드하고 줄어든 파일 크기를 즐기세요.",
    "landing.remove.redesign.heroBadge": "AI 기반 컷아웃",
    "landing.remove.redesign.heroTitle": "완벽한 정밀도로 1초 만에 배경 제거",
    "landing.remove.redesign.heroDesc": "고급 WebAssembly AI를 기반으로, 서버에 사진을 업로드할 필요 없이 완벽한 머리카락 컷아웃과 부드러운 가장자리를 얻으세요.",
    "landing.remove.redesign.feat1Badge": "99.8% 정확도",
    "landing.remove.redesign.feat1Title": "완벽한 머리카락 및 가장자리 감지",
    "landing.remove.redesign.feat1Desc": "저희 신경망은 사람 머리카락, 동물 털 및 반투명 물체와 같은 복잡한 세부 사항을 쉽게 처리합니다.",
    "landing.remove.redesign.feat2Badge": "100% 안전함",
    "landing.remove.redesign.feat2Title": "완벽한 오프라인 개인 정보 보호",
    "landing.remove.redesign.feat2Desc": "AI 모델이 브라우저에 직접 로드됩니다. 귀하의 이미지는 컴퓨터를 떠나지 않습니다.",
    "landing.remove.redesign.feat3Badge": "일괄 모드",
    "landing.remove.redesign.feat3Title": "대량 처리 준비 완료",
    "landing.remove.redesign.feat3Desc": "한 번에 최대 10장의 사진을 드래그 앤 드롭하세요. 동시에 처리하고 깔끔한 ZIP 파일로 다운로드하세요.",
    "landing.remove.redesign.whoTag": "대상이 누구인가요",
    "landing.remove.redesign.whoTitle": "모든 창의적인 요구에 완벽함",
    "landing.remove.redesign.whoDesc": "자동차를 판매하든, 포스터를 디자인하든, 공식 문서를 작성하든 상관없습니다.",
    "landing.remove.redesign.who1Title": "전자 상거래 판매자",
    "landing.remove.redesign.who1Desc": "제품 목록을 위한 깨끗한 흰색 배경을 만드세요.",
    "landing.remove.redesign.who1Tags": "제품 목록",
    "landing.remove.redesign.who2Title": "그래픽 디자이너",
    "landing.remove.redesign.who2Desc": "로고, 서명 및 자산을 즉시 추출하세요.",
    "landing.remove.redesign.who2Tags": "디자인 자산",
    "landing.remove.redesign.stepsTag": "사용 방법",
    "landing.remove.redesign.stepsTitle": "투명 배경을 위한 3단계",
    "landing.remove.redesign.s1Title": "이미지 업로드",
    "landing.remove.redesign.s1Desc": "사진을 드래그 앤 드롭하세요. PNG, JPG 또는 WEBP.",
    "landing.remove.redesign.s2Title": "AI 처리",
    "landing.remove.redesign.s2Desc": "로컬 WASM AI가 1초 만에 주요 주제를 감지합니다.",
    "landing.remove.redesign.s3Title": "HD 다운로드",
    "landing.remove.redesign.s3Desc": "투명한 배경으로 잘린 사진을 내보내세요.",
    "home.why.tag": "왜 HELPMYIMG인가",
    "home.why.title": "HelpMyIMG가 크리에이터와 비즈니스를 위한 가장 현명한 선택인 이유",
    "home.why.desc": "최대한의 개인 정보 보호, 놀라운 속도 및 무료를 위해 처음부터 설계되었습니다.",
    "home.why.c1.t": "즉각적인 로컬 속도",
    "home.why.c1.d": "사진은 지연 없이 장치 메모리에서 직접 처리됩니다.",
    "home.why.c1.b": "0ms 서버 지연",
    "home.why.c2.t": "100% 절대적인 개인 정보 보호",
    "home.why.c2.d": "개인 초상화 및 기밀 문서가 컴퓨터를 떠나지 않습니다.",
    "home.why.c2.b": "클라우드 저장 없음",
    "home.why.c3.t": "영구 무료 및 무제한",
    "home.why.c3.d": "구독이나 워터마크가 없습니다. 모두가 이용할 수 있는 고화질 사진 편집.",
    "home.why.c3.b": "$0 / 평생",
    "home.why.c4.t": "최대 10개 일괄 처리",
    "home.why.c4.d": "최대 10장의 사진을 동시에 드래그 앤 드롭하고 몇 초 만에 ZIP 아카이브로 내보냅니다.",
    "home.why.c4.b": "10x 작업 속도",
    "home.steps.tag": "사용 방법",
    "home.steps.title": "3가지 간단한 단계로 HelpMyIMG가 작동하는 방식",
    "home.steps.desc": "소프트웨어 설치가 필요하지 않습니다. 웹 브라우저에서 직접 전문가 수준의 결과를 얻으세요."
  },
  ms: {
    "landing.compress.redesign.heroBadge": "MAMPATAN PINTAR",
    "landing.compress.redesign.heroTitle": "Kecilkan Saiz Fail Imej hingga 90% Serta-merta",
    "landing.compress.redesign.heroDesc": "Kurangkan saiz foto anda tanpa kehilangan kualiti visual. Sesuai untuk tapak web dan e-mel.",
    "landing.compress.redesign.feat1Badge": "TIADA KEHILANGAN KUALITI",
    "landing.compress.redesign.feat1Title": "Pengoptimuman Pintar",
    "landing.compress.redesign.feat1Desc": "Mencari keseimbangan sempurna antara saiz fail minimum dan kualiti imej maksimum secara automatik.",
    "landing.compress.redesign.feat2Badge": "100% PERIBADI",
    "landing.compress.redesign.feat2Title": "Sifar Muat Naik",
    "landing.compress.redesign.feat2Desc": "Seperti semua alatan kami, pemampatan berlaku terus dalam pelayar web anda. Tiada apa yang dihantar ke pelayan.",
    "landing.compress.redesign.feat3Badge": "SEBARANG FORMAT",
    "landing.compress.redesign.feat3Title": "Sokongan Meluas",
    "landing.compress.redesign.feat3Desc": "Berfungsi dengan format standard JPG dan PNG, serta format WEBP moden.",
    "landing.compress.redesign.whoTag": "UNTUK SIAPA",
    "landing.compress.redesign.whoTitle": "Dicipta untuk Web & Media",
    "landing.compress.redesign.whoDesc": "Sempurna untuk pembangun, pereka, dan pengurus media sosial yang memerlukan imej yang dioptimumkan.",
    "landing.compress.redesign.who1Title": "Pembangun Web",
    "landing.compress.redesign.who1Desc": "Tingkatkan skor PageSpeed dan kurangkan masa muat tanpa mengorbankan kualiti imej.",
    "landing.compress.redesign.who1Tags": "PENGOPTIMUMAN SEO",
    "landing.compress.redesign.who2Title": "Pencipta Kandungan",
    "landing.compress.redesign.who2Desc": "Penuhi had saiz muat naik yang ketat untuk platform seperti Discord atau Twitter.",
    "landing.compress.redesign.who2Tags": "MEDIA SOSIAL",
    "landing.compress.redesign.stepsTag": "BAGAIMANA IA BERFUNGSI",
    "landing.compress.redesign.stepsTitle": "3 Langkah untuk Mengoptimumkan",
    "landing.compress.redesign.s1Title": "Muat Naik Imej",
    "landing.compress.redesign.s1Desc": "Seret dan lepaskan foto anda ke ruang kerja mampatan.",
    "landing.compress.redesign.s2Title": "Tetapkan Tahap Mampatan",
    "landing.compress.redesign.s2Desc": "Laraskan peluncur kualiti untuk mencari keseimbangan yang betul.",
    "landing.compress.redesign.s3Title": "Jimat Storan",
    "landing.compress.redesign.s3Desc": "Muat turun imej yang dioptimumkan dan nikmati saiz fail yang dikurangkan.",
    "landing.remove.redesign.heroBadge": "POTONGAN DIKUASAKAN AI",
    "landing.remove.redesign.heroTitle": "Buang Latar Belakang dalam 1 Saat dengan Ketepatan Sempurna",
    "landing.remove.redesign.heroDesc": "Dikuasakan oleh AI WebAssembly, dapatkan potongan rambut yang sempurna dan tepi yang licin tanpa memuat naik foto anda.",
    "landing.remove.redesign.feat1Badge": "KETEPATAN 99.8%",
    "landing.remove.redesign.feat1Title": "Pengesanan Rambut & Tepi Sempurna",
    "landing.remove.redesign.feat1Desc": "Rangkaian neural kami mengendalikan butiran kompleks seperti rambut manusia, bulu haiwan dengan mudah.",
    "landing.remove.redesign.feat2Badge": "100% SELAMAT",
    "landing.remove.redesign.feat2Title": "Privasi Luar Talian Lengkap",
    "landing.remove.redesign.feat2Desc": "Model AI dimuatkan terus ke dalam pelayar anda. Imej anda tidak pernah meninggalkan komputer anda.",
    "landing.remove.redesign.feat3Badge": "MOD KELOMPOK",
    "landing.remove.redesign.feat3Title": "Sedia untuk Pemprosesan Pukal",
    "landing.remove.redesign.feat3Desc": "Seret dan lepaskan sehingga 10 foto sekaligus. Muat turun semuanya dalam fail ZIP.",
    "landing.remove.redesign.whoTag": "UNTUK SIAPA",
    "landing.remove.redesign.whoTitle": "Sempurna untuk Setiap Keperluan Kreatif",
    "landing.remove.redesign.whoDesc": "Sama ada anda menjual kereta, mereka poster, atau membuat dokumen rasmi.",
    "landing.remove.redesign.who1Title": "Penjual E-Dagang",
    "landing.remove.redesign.who1Desc": "Cipta latar belakang putih bersih untuk senarai produk.",
    "landing.remove.redesign.who1Tags": "SENARAI PRODUK",
    "landing.remove.redesign.who2Title": "Pereka Grafik",
    "landing.remove.redesign.who2Desc": "Ekstrak logo, tandatangan, dan aset serta-merta.",
    "landing.remove.redesign.who2Tags": "ASET REKA BENTUK",
    "landing.remove.redesign.stepsTag": "BAGAIMANA IA BERFUNGSI",
    "landing.remove.redesign.stepsTitle": "3 Langkah ke Latar Belakang Lutsinar",
    "landing.remove.redesign.s1Title": "Muat Naik Imej",
    "landing.remove.redesign.s1Desc": "Seret & lepaskan foto anda. PNG, JPG, atau WEBP.",
    "landing.remove.redesign.s2Title": "Pemprosesan AI",
    "landing.remove.redesign.s2Desc": "AI tempatan mengesan subjek utama dalam 1 saat.",
    "landing.remove.redesign.s3Title": "Muat Turun HD",
    "landing.remove.redesign.s3Desc": "Eksport foto yang dipotong dengan latar belakang lutsinar.",
    "home.why.tag": "MENGAPA HELPMYIMG",
    "home.why.title": "Mengapa HelpMyIMG adalah Pilihan Paling Pintar untuk Pencipta & Perniagaan",
    "home.why.desc": "Direka dari bawah ke atas untuk privasi maksimum, kelajuan kilat, dan sifar kos.",
    "home.why.c1.t": "Kelajuan Tempatan Serta-merta",
    "home.why.c1.d": "Foto anda diproses terus di dalam ingatan peranti anda dengan sifar kependaman.",
    "home.why.c1.b": "Kelewatan Pelayan 0ms",
    "home.why.c2.t": "Privasi Mutlak 100%",
    "home.why.c2.d": "Potret peribadi dan dokumen sulit anda tidak pernah meninggalkan komputer anda.",
    "home.why.c2.b": "Sifar Storan Awan",
    "home.why.c3.t": "Selamanya Percuma & Tanpa Had",
    "home.why.c3.d": "Tiada langganan, tiada tera air. Penyuntingan foto HD yang boleh diakses oleh semua.",
    "home.why.c3.b": "$0 / Seumur Hidup",
    "home.why.c4.t": "Kuasa Kelompok sehingga 10",
    "home.why.c4.d": "Seret dan lepaskan sehingga 10 foto serentak, dan eksport sebagai arkib ZIP dalam beberapa saat.",
    "home.why.c4.b": "10x Kelajuan Aliran Kerja",
    "home.steps.tag": "BAGAIMANA IA BERFUNGSI",
    "home.steps.title": "Bagaimana HelpMyIMG Berfungsi dalam 3 Langkah Mudah",
    "home.steps.desc": "Tiada pemasangan perisian diperlukan. Dapatkan hasil profesional terus dari pelayar web anda."
  },
  nl: {
    "landing.compress.redesign.heroBadge": "SLIMME COMPRESSIE",
    "landing.compress.redesign.heroTitle": "Verklein de grootte van afbeeldingsbestanden onmiddellijk tot wel 90%",
    "landing.compress.redesign.heroDesc": "Verklein de grootte van uw foto's zonder visuele kwaliteit te verliezen. Perfect voor websites en e-mails.",
    "landing.compress.redesign.feat1Badge": "GEEN KWALITEITSVERLIES",
    "landing.compress.redesign.feat1Title": "Slimme optimalisatie",
    "landing.compress.redesign.feat1Desc": "Vindt automatisch de perfecte balans tussen minimale bestandsgrootte en maximale beeldkwaliteit.",
    "landing.compress.redesign.feat2Badge": "100% PRIVÉ",
    "landing.compress.redesign.feat2Title": "Geen uploads",
    "landing.compress.redesign.feat2Desc": "Zoals bij al onze tools gebeurt de compressie direct in uw browser. Er gaat niets naar een server.",
    "landing.compress.redesign.feat3Badge": "ELK FORMAAT",
    "landing.compress.redesign.feat3Title": "Brede ondersteuning",
    "landing.compress.redesign.feat3Desc": "Werkt met standaard JPG- en PNG-formaten, en ook met moderne WEBP-formaten.",
    "landing.compress.redesign.whoTag": "VOOR WIE IS HET",
    "landing.compress.redesign.whoTitle": "Gemaakt voor web en media",
    "landing.compress.redesign.whoDesc": "Perfect voor ontwikkelaars, ontwerpers en social media managers die geoptimaliseerde afbeeldingen nodig hebben.",
    "landing.compress.redesign.who1Title": "Webontwikkelaars",
    "landing.compress.redesign.who1Desc": "Verbeter de PageSpeed-scores en verkort laadtijden zonder dat dit ten koste gaat van de beeldkwaliteit.",
    "landing.compress.redesign.who1Tags": "SEO OPTIMALISATIE",
    "landing.compress.redesign.who2Title": "Contentmakers",
    "landing.compress.redesign.who2Desc": "Voldoe aan strikte uploadlimieten voor platforms zoals Discord of Twitter.",
    "landing.compress.redesign.who2Tags": "SOCIALE MEDIA",
    "landing.compress.redesign.stepsTag": "HOE HET WERKT",
    "landing.compress.redesign.stepsTitle": "3 stappen om te optimaliseren",
    "landing.compress.redesign.s1Title": "Afbeeldingen uploaden",
    "landing.compress.redesign.s1Desc": "Sleep uw foto's naar de compressiewerkruimte.",
    "landing.compress.redesign.s2Title": "Compressieniveau instellen",
    "landing.compress.redesign.s2Desc": "Pas de kwaliteitsschuif aan om de juiste balans te vinden.",
    "landing.compress.redesign.s3Title": "Bespaar opslag",
    "landing.compress.redesign.s3Desc": "Download uw geoptimaliseerde afbeeldingen en geniet van kleinere bestandsgroottes.",
    "landing.remove.redesign.heroBadge": "AI AANGEDREVEN UITSNEDE",
    "landing.remove.redesign.heroTitle": "Verwijder achtergrond in 1 seconde met vlekkeloze precisie",
    "landing.remove.redesign.heroDesc": "Aangedreven door geavanceerde WebAssembly AI, krijg perfecte haaruitsnedes zonder uw foto's naar een server te uploaden.",
    "landing.remove.redesign.feat1Badge": "99.8% NAUWKEURIGHEID",
    "landing.remove.redesign.feat1Title": "Vlekkeloze haar- en randdetectie",
    "landing.remove.redesign.feat1Desc": "Ons neurale netwerk verwerkt eenvoudig complexe details zoals menselijk haar, dierenvacht en halftransparante objecten.",
    "landing.remove.redesign.feat2Badge": "100% VEILIG",
    "landing.remove.redesign.feat2Title": "Volledige offline privacy",
    "landing.remove.redesign.feat2Desc": "Het AI-model wordt direct in uw browser geladen. Uw afbeeldingen verlaten uw computer nooit.",
    "landing.remove.redesign.feat3Badge": "BATCH MODUS",
    "landing.remove.redesign.feat3Title": "Klaar voor bulkverwerking",
    "landing.remove.redesign.feat3Desc": "Sleep maximaal 10 foto's tegelijk en download alles in één ZIP-bestand.",
    "landing.remove.redesign.whoTag": "VOOR WIE IS HET",
    "landing.remove.redesign.whoTitle": "Perfect voor elke creatieve behoefte",
    "landing.remove.redesign.whoDesc": "Of u nu auto's verkoopt, posters ontwerpt of officiële documenten maakt.",
    "landing.remove.redesign.who1Title": "E-commerce verkopers",
    "landing.remove.redesign.who1Desc": "Maak schone witte achtergronden voor productvermeldingen.",
    "landing.remove.redesign.who1Tags": "PRODUCTVERMELDINGEN",
    "landing.remove.redesign.who2Title": "Grafisch ontwerpers",
    "landing.remove.redesign.who2Desc": "Extraheer logo's, handtekeningen en middelen direct.",
    "landing.remove.redesign.who2Tags": "ONTWERPMIDDELEN",
    "landing.remove.redesign.stepsTag": "HOE HET WERKT",
    "landing.remove.redesign.stepsTitle": "3 Stappen naar transparante achtergronden",
    "landing.remove.redesign.s1Title": "Afbeelding uploaden",
    "landing.remove.redesign.s1Desc": "Sleep uw foto. PNG, JPG of WEBP.",
    "landing.remove.redesign.s2Title": "AI verwerking",
    "landing.remove.redesign.s2Desc": "De lokale AI detecteert het hoofdonderwerp in 1 seconde.",
    "landing.remove.redesign.s3Title": "HD downloaden",
    "landing.remove.redesign.s3Desc": "Exporteer uw uitgesneden foto met een transparante achtergrond.",
    "home.why.tag": "WAAROM HELPMYIMG",
    "home.why.title": "Waarom HelpMyIMG de slimste keuze is voor makers en bedrijven",
    "home.why.desc": "Ontworpen vanaf de basis voor maximale privacy, bliksemsnelheid en nul kosten.",
    "home.why.c1.t": "Directe lokale snelheid",
    "home.why.c1.d": "Uw foto's worden direct in het geheugen van uw apparaat verwerkt, zonder vertraging.",
    "home.why.c1.b": "0ms Serververtraging",
    "home.why.c2.t": "100% Absolute privacy",
    "home.why.c2.d": "Uw persoonlijke portretten en vertrouwelijke documenten verlaten uw computer nooit.",
    "home.why.c2.b": "Geen cloudopslag",
    "home.why.c3.t": "Voor altijd gratis en onbeperkt",
    "home.why.c3.d": "Geen abonnementen, geen watermerken. High-definition fotobewerking toegankelijk voor iedereen.",
    "home.why.c3.b": "$0 / Levenslang",
    "home.why.c4.t": "Batchkracht tot 10",
    "home.why.c4.d": "Sleep tot 10 foto's tegelijkertijd en exporteer ze binnen enkele seconden als een ZIP-archief.",
    "home.why.c4.b": "10x Werksnelheid",
    "home.steps.tag": "HOE HET WERKT",
    "home.steps.title": "Hoe HelpMyIMG werkt in 3 eenvoudige stappen",
    "home.steps.desc": "Geen software-installatie nodig. Krijg professionele resultaten rechtstreeks vanuit uw webbrowser."
  },
  no: {
    "landing.compress.redesign.heroBadge": "SMART KOMPRIMERING",
    "landing.compress.redesign.heroTitle": "Krymp bildefilstørrelsen med opptil 90 % umiddelbart",
    "landing.compress.redesign.heroDesc": "Reduser størrelsen på bildene dine uten å miste visuell kvalitet. Perfekt for nettsider og e-post.",
    "landing.compress.redesign.feat1Badge": "INGEN KVALITETSTAP",
    "landing.compress.redesign.feat1Title": "Smart optimalisering",
    "landing.compress.redesign.feat1Desc": "Finner automatisk den perfekte balansen mellom minimal filstørrelse og maksimal bildekvalitet.",
    "landing.compress.redesign.feat2Badge": "100 % PRIVAT",
    "landing.compress.redesign.feat2Title": "Ingen opplastinger",
    "landing.compress.redesign.feat2Desc": "Som med alle verktøyene våre, skjer komprimeringen direkte i nettleseren din. Ingenting går til noen server.",
    "landing.compress.redesign.feat3Badge": "ETHVERT FORMAT",
    "landing.compress.redesign.feat3Title": "Bred støtte",
    "landing.compress.redesign.feat3Desc": "Fungerer med standard JPG og PNG-formater samt moderne WEBP-formater.",
    "landing.compress.redesign.whoTag": "HVEM ER DET FOR",
    "landing.compress.redesign.whoTitle": "Bygget for Web og Media",
    "landing.compress.redesign.whoDesc": "Perfekt for utviklere, designere og ledere for sosiale medier som trenger optimaliserte bilder.",
    "landing.compress.redesign.who1Title": "Nettutviklere",
    "landing.compress.redesign.who1Desc": "Forbedre PageSpeed-score og reduser lastetider uten å ofre bildekvaliteten.",
    "landing.compress.redesign.who1Tags": "SEO OPTIMALISERING",
    "landing.compress.redesign.who2Title": "Innholdsskapere",
    "landing.compress.redesign.who2Desc": "Oppfyll strenge opplastingsgrenser for plattformer som Discord eller Twitter.",
    "landing.compress.redesign.who2Tags": "SOSIALE MEDIER",
    "landing.compress.redesign.stepsTag": "SLIK FUNGERER DET",
    "landing.compress.redesign.stepsTitle": "3 trinn for optimalisering",
    "landing.compress.redesign.s1Title": "Last opp bilder",
    "landing.compress.redesign.s1Desc": "Dra og slipp bildene dine i komprimeringsarbeidsområdet.",
    "landing.compress.redesign.s2Title": "Still inn komprimeringsnivå",
    "landing.compress.redesign.s2Desc": "Juster kvalitetsglideren for å finne den rette balansen.",
    "landing.compress.redesign.s3Title": "Spar lagring",
    "landing.compress.redesign.s3Desc": "Last ned dine optimaliserte bilder og nyt reduserte filstørrelser.",
    "landing.remove.redesign.heroBadge": "AI-DREVET UTSKJÆRING",
    "landing.remove.redesign.heroTitle": "Fjern bakgrunn på 1 sekund med feilfri presisjon",
    "landing.remove.redesign.heroDesc": "Drevet av avansert WebAssembly AI, få perfekte hårbeskjæringer og glatte kanter uten noen gang å laste opp til en server.",
    "landing.remove.redesign.feat1Badge": "99.8 % NØYAKTIGHET",
    "landing.remove.redesign.feat1Title": "Feilfri hår- og kantdeteksjon",
    "landing.remove.redesign.feat1Desc": "Vårt nevrale nettverk håndterer enkelt komplekse detaljer som menneskehår og dyrepels.",
    "landing.remove.redesign.feat2Badge": "100 % SIKKER",
    "landing.remove.redesign.feat2Title": "Komplett offline personvern",
    "landing.remove.redesign.feat2Desc": "AI-modellen lastes direkte inn i nettleseren din. Bildene dine forlater aldri datamaskinen din.",
    "landing.remove.redesign.feat3Badge": "BATCH MODUS",
    "landing.remove.redesign.feat3Title": "Klar for massebehandling",
    "landing.remove.redesign.feat3Desc": "Dra og slipp opptil 10 bilder samtidig og last ned alt i en ZIP-fil.",
    "landing.remove.redesign.whoTag": "HVEM ER DET FOR",
    "landing.remove.redesign.whoTitle": "Perfekt for ethvert kreativt behov",
    "landing.remove.redesign.whoDesc": "Enten du selger biler, designer plakater eller oppretter offisielle dokumenter.",
    "landing.remove.redesign.who1Title": "E-handel Selgere",
    "landing.remove.redesign.who1Desc": "Lag rene hvite bakgrunner for produktoppføringer.",
    "landing.remove.redesign.who1Tags": "PRODUKTOPPFØRINGER",
    "landing.remove.redesign.who2Title": "Grafiske Designere",
    "landing.remove.redesign.who2Desc": "Pakk ut logoer, signaturer og eiendeler umiddelbart.",
    "landing.remove.redesign.who2Tags": "DESIGNEIENDELER",
    "landing.remove.redesign.stepsTag": "SLIK FUNGERER DET",
    "landing.remove.redesign.stepsTitle": "3 trinn til gjennomsiktig bakgrunn",
    "landing.remove.redesign.s1Title": "Last opp bilde",
    "landing.remove.redesign.s1Desc": "Dra og slipp bildet ditt. PNG, JPG eller WEBP.",
    "landing.remove.redesign.s2Title": "AI-behandling",
    "landing.remove.redesign.s2Desc": "Den lokale AI-en oppdager hovedmotivet på 1 sekund.",
    "landing.remove.redesign.s3Title": "Last ned HD",
    "landing.remove.redesign.s3Desc": "Eksporter det utskårne bildet med gjennomsiktig bakgrunn.",
    "home.why.tag": "HVORFOR HELPMYIMG",
    "home.why.title": "Hvorfor HelpMyIMG er det smarteste valget for skapere og bedrifter",
    "home.why.desc": "Designet fra grunnen av for maksimalt personvern, lynrask hastighet og null kostnader.",
    "home.why.c1.t": "Umiddelbar lokal hastighet",
    "home.why.c1.d": "Bildene dine behandles direkte i enhetens minne uten forsinkelse.",
    "home.why.c1.b": "0ms Serverforsinkelse",
    "home.why.c2.t": "100 % Absolutt personvern",
    "home.why.c2.d": "Dine personlige portretter og konfidensielle dokumenter forlater aldri datamaskinen din.",
    "home.why.c2.b": "Null skylagring",
    "home.why.c3.t": "For alltid gratis og ubegrenset",
    "home.why.c3.d": "Ingen abonnementer, ingen vannmerker. Fotoredigering i HD tilgjengelig for alle.",
    "home.why.c3.b": "$0 / Livstid",
    "home.why.c4.t": "Batchkraft opptil 10",
    "home.why.c4.d": "Dra og slipp opptil 10 bilder samtidig, og eksporter som et ZIP-arkiv på sekunder.",
    "home.why.c4.b": "10x Arbeidshastighet",
    "home.steps.tag": "SLIK FUNGERER DET",
    "home.steps.title": "Slik fungerer HelpMyIMG i 3 enkle trinn",
    "home.steps.desc": "Ingen programvareinstallasjon nødvendig. Få profesjonelle resultater direkte fra nettleseren din."
  },
  pl: {
    "landing.compress.redesign.heroBadge": "INTELIGENTNA KOMPRESJA",
    "landing.compress.redesign.heroTitle": "Zmniejsz rozmiar pliku obrazu nawet o 90% natychmiast",
    "landing.compress.redesign.heroDesc": "Zmniejsz rozmiar swoich zdjęć bez utraty jakości wizualnej. Idealne dla stron internetowych i e-maili.",
    "landing.compress.redesign.feat1Badge": "BEZ UTRATY JAKOŚCI",
    "landing.compress.redesign.feat1Title": "Inteligentna optymalizacja",
    "landing.compress.redesign.feat1Desc": "Automatycznie znajduje idealną równowagę między minimalnym rozmiarem pliku a maksymalną jakością obrazu.",
    "landing.compress.redesign.feat2Badge": "100% PRYWATNE",
    "landing.compress.redesign.feat2Title": "Żadnych przesyłania",
    "landing.compress.redesign.feat2Desc": "Podobnie jak w przypadku wszystkich naszych narzędzi, kompresja odbywa się w przeglądarce. Nic nie trafia na serwer.",
    "landing.compress.redesign.feat3Badge": "DOWOLNY FORMAT",
    "landing.compress.redesign.feat3Title": "Szerokie wsparcie",
    "landing.compress.redesign.feat3Desc": "Działa ze standardowymi formatami JPG i PNG, a także nowoczesnymi formatami WEBP.",
    "landing.compress.redesign.whoTag": "DLA KOGO TO JEST",
    "landing.compress.redesign.whoTitle": "Zbudowane dla Sieci i Mediów",
    "landing.compress.redesign.whoDesc": "Idealne dla programistów, projektantów i menedżerów mediów społecznościowych.",
    "landing.compress.redesign.who1Title": "Programiści internetowi",
    "landing.compress.redesign.who1Desc": "Popraw wyniki PageSpeed i zmniejsz czas ładowania bez poświęcania jakości obrazu.",
    "landing.compress.redesign.who1Tags": "OPTYMALIZACJA SEO",
    "landing.compress.redesign.who2Title": "Twórcy treści",
    "landing.compress.redesign.who2Desc": "Spełniaj rygorystyczne limity rozmiaru przesyłania dla platform takich jak Discord lub Twitter.",
    "landing.compress.redesign.who2Tags": "MEDIA SPOŁECZNOŚCIOWE",
    "landing.compress.redesign.stepsTag": "JAK TO DZIAŁA",
    "landing.compress.redesign.stepsTitle": "3 kroki do optymalizacji",
    "landing.compress.redesign.s1Title": "Prześlij obrazy",
    "landing.compress.redesign.s1Desc": "Przeciągnij i upuść swoje zdjęcia do obszaru kompresji.",
    "landing.compress.redesign.s2Title": "Ustaw poziom kompresji",
    "landing.compress.redesign.s2Desc": "Dostosuj suwak jakości, aby znaleźć właściwą równowagę.",
    "landing.compress.redesign.s3Title": "Oszczędzaj miejsce",
    "landing.compress.redesign.s3Desc": "Pobierz zoptymalizowane obrazy i ciesz się mniejszym rozmiarem plików.",
    "landing.remove.redesign.heroBadge": "WYCINANIE AI",
    "landing.remove.redesign.heroTitle": "Usuń tło w 1 sekundę z nieskazitelną precyzją",
    "landing.remove.redesign.heroDesc": "Dzięki zaawansowanej sztucznej inteligencji WebAssembly uzyskasz idealne wycięcia włosów i gładkie krawędzie.",
    "landing.remove.redesign.feat1Badge": "99.8% DOKŁADNOŚĆ",
    "landing.remove.redesign.feat1Title": "Nieskazitelne wykrywanie krawędzi",
    "landing.remove.redesign.feat1Desc": "Nasza sieć neuronowa z łatwością radzi sobie ze skomplikowanymi detalami, takimi jak ludzkie włosy czy sierść zwierząt.",
    "landing.remove.redesign.feat2Badge": "100% BEZPIECZNE",
    "landing.remove.redesign.feat2Title": "Pełna prywatność offline",
    "landing.remove.redesign.feat2Desc": "Model sztucznej inteligencji ładuje się bezpośrednio do przeglądarki. Twoje zdjęcia nigdy nie opuszczają komputera.",
    "landing.remove.redesign.feat3Badge": "TRYB ZBIORCZY",
    "landing.remove.redesign.feat3Title": "Gotowe do masowego przetwarzania",
    "landing.remove.redesign.feat3Desc": "Przeciągnij i upuść do 10 zdjęć naraz. Pobierz wszystko w pliku ZIP.",
    "landing.remove.redesign.whoTag": "DLA KOGO TO JEST",
    "landing.remove.redesign.whoTitle": "Idealne dla każdej kreatywnej potrzeby",
    "landing.remove.redesign.whoDesc": "Niezależnie od tego, czy sprzedajesz samochody, projektujesz plakaty czy tworzysz dokumenty.",
    "landing.remove.redesign.who1Title": "Sprzedawcy E-Commerce",
    "landing.remove.redesign.who1Desc": "Twórz czyste białe tła dla list produktów.",
    "landing.remove.redesign.who1Tags": "LISTY PRODUKTÓW",
    "landing.remove.redesign.who2Title": "Graficy",
    "landing.remove.redesign.who2Desc": "Błyskawicznie wyodrębniaj loga, podpisy i zasoby.",
    "landing.remove.redesign.who2Tags": "ZASOBY PROJEKTOWE",
    "landing.remove.redesign.stepsTag": "JAK TO DZIAŁA",
    "landing.remove.redesign.stepsTitle": "3 kroki do przezroczystego tła",
    "landing.remove.redesign.s1Title": "Prześlij obraz",
    "landing.remove.redesign.s1Desc": "Przeciągnij i upuść zdjęcie. PNG, JPG lub WEBP.",
    "landing.remove.redesign.s2Title": "Przetwarzanie AI",
    "landing.remove.redesign.s2Desc": "Lokalna SI wykrywa główny obiekt w 1 sekundę.",
    "landing.remove.redesign.s3Title": "Pobierz HD",
    "landing.remove.redesign.s3Desc": "Eksportuj wycięte zdjęcie z przezroczystym tłem.",
    "home.why.tag": "DLACZEGO HELPMYIMG",
    "home.why.title": "Dlaczego HelpMyIMG to najmądrzejszy wybór",
    "home.why.desc": "Zaprojektowane od podstaw pod kątem maksymalnej prywatności, błyskawicznej szybkości i zerowych kosztów.",
    "home.why.c1.t": "Natychmiastowa lokalna szybkość",
    "home.why.c1.d": "Twoje zdjęcia są przetwarzane bezpośrednio w pamięci urządzenia z zerowym opóźnieniem.",
    "home.why.c1.b": "0ms Opóźnienie serwera",
    "home.why.c2.t": "100% Absolutna prywatność",
    "home.why.c2.d": "Twoje osobiste portrety i poufne dokumenty nigdy nie opuszczają Twojego komputera.",
    "home.why.c2.b": "Zero chmury",
    "home.why.c3.t": "Zawsze darmowe i nielimitowane",
    "home.why.c3.d": "Żadnych subskrypcji, żadnych znaków wodnych. Edycja zdjęć HD dostępna dla wszystkich.",
    "home.why.c3.b": "$0 / Dożywotnio",
    "home.why.c4.t": "Moc zbiorcza do 10",
    "home.why.c4.d": "Przeciągnij do 10 zdjęć jednocześnie i wyeksportuj jako archiwum ZIP w kilka sekund.",
    "home.why.c4.b": "10x Szybkość pracy",
    "home.steps.tag": "JAK TO DZIAŁA",
    "home.steps.title": "Jak to działa w 3 prostych krokach",
    "home.steps.desc": "Nie wymaga instalacji oprogramowania. Uzyskaj profesjonalne rezultaty w przeglądarce."
  },
  ro: {
    "landing.compress.redesign.heroBadge": "COMPRESIE INTELIGENTĂ",
    "landing.compress.redesign.heroTitle": "Micșorați dimensiunea fișierului imagine cu până la 90% instantaneu",
    "landing.compress.redesign.heroDesc": "Reduceți dimensiunea fotografiilor dvs. fără a pierde calitatea vizuală. Perfect pentru site-uri web și e-mailuri.",
    "landing.compress.redesign.feat1Badge": "FĂRĂ PIERDERE DE CALITATE",
    "landing.compress.redesign.feat1Title": "Optimizare inteligentă",
    "landing.compress.redesign.feat1Desc": "Găsește automat echilibrul perfect între dimensiunea minimă a fișierului și calitatea maximă a imaginii.",
    "landing.compress.redesign.feat2Badge": "100% PRIVAT",
    "landing.compress.redesign.feat2Title": "Zero încărcări",
    "landing.compress.redesign.feat2Desc": "Ca și în cazul tuturor instrumentelor noastre, compresia se întâmplă chiar în browser-ul dvs. Nimic nu merge la niciun server.",
    "landing.compress.redesign.feat3Badge": "ORICE FORMAT",
    "landing.compress.redesign.feat3Title": "Suport larg",
    "landing.compress.redesign.feat3Desc": "Funcționează cu formatele standard JPG și PNG, precum și cu formatele moderne WEBP.",
    "landing.compress.redesign.whoTag": "PENTRU CINE ESTE",
    "landing.compress.redesign.whoTitle": "Construit pentru Web & Media",
    "landing.compress.redesign.whoDesc": "Perfect pentru dezvoltatori, designeri și manageri de social media.",
    "landing.compress.redesign.who1Title": "Dezvoltatori Web",
    "landing.compress.redesign.who1Desc": "Îmbunătățiți scorurile PageSpeed și reduceți timpii de încărcare.",
    "landing.compress.redesign.who1Tags": "OPTIMIZARE SEO",
    "landing.compress.redesign.who2Title": "Creatori de conținut",
    "landing.compress.redesign.who2Desc": "Îndepliniți limitele stricte de dimensiune pentru platforme precum Discord sau Twitter.",
    "landing.compress.redesign.who2Tags": "SOCIAL MEDIA",
    "landing.compress.redesign.stepsTag": "CUM FUNCȚIONEAZĂ",
    "landing.compress.redesign.stepsTitle": "3 Pași pentru Optimizare",
    "landing.compress.redesign.s1Title": "Încărcați Imagini",
    "landing.compress.redesign.s1Desc": "Trageți și plasați fotografiile dvs. în spațiul de compresie.",
    "landing.compress.redesign.s2Title": "Setați Nivelul de Compresie",
    "landing.compress.redesign.s2Desc": "Ajustați cursorul de calitate pentru a găsi echilibrul potrivit.",
    "landing.compress.redesign.s3Title": "Economisiți Stocare",
    "landing.compress.redesign.s3Desc": "Descărcați imaginile optimizate și bucurați-vă de dimensiuni reduse ale fișierelor.",
    "landing.remove.redesign.heroBadge": "DECUPARE BAZATĂ PE AI",
    "landing.remove.redesign.heroTitle": "Eliminați fundalul în 1 secundă cu o precizie impecabilă",
    "landing.remove.redesign.heroDesc": "Datorită AI-ului avansat WebAssembly, obțineți decupări perfecte și margini netede.",
    "landing.remove.redesign.feat1Badge": "PRECISIE DE 99.8%",
    "landing.remove.redesign.feat1Title": "Detectare impecabilă a părului și a marginilor",
    "landing.remove.redesign.feat1Desc": "Rețeaua noastră neuronală gestionează cu ușurință detalii complexe.",
    "landing.remove.redesign.feat2Badge": "100% SIGUR",
    "landing.remove.redesign.feat2Title": "Confidențialitate completă offline",
    "landing.remove.redesign.feat2Desc": "Modelul AI se încarcă direct în browserul dvs. Imaginile nu părăsesc niciodată computerul.",
    "landing.remove.redesign.feat3Badge": "MOD BATCH",
    "landing.remove.redesign.feat3Title": "Pregătit pentru procesare în masă",
    "landing.remove.redesign.feat3Desc": "Procesați până la 10 fotografii simultan și descărcați-le într-un fișier ZIP.",
    "landing.remove.redesign.whoTag": "PENTRU CINE ESTE",
    "landing.remove.redesign.whoTitle": "Perfect pentru orice nevoie creativă",
    "landing.remove.redesign.whoDesc": "Fie că vindeți mașini, proiectați afișe sau creați documente.",
    "landing.remove.redesign.who1Title": "Vânzători E-Commerce",
    "landing.remove.redesign.who1Desc": "Creați fundaluri albe curate pentru listele de produse.",
    "landing.remove.redesign.who1Tags": "LISTĂRI PRODUSE",
    "landing.remove.redesign.who2Title": "Designeri Grafici",
    "landing.remove.redesign.who2Desc": "Extrageți logo-uri și active instantaneu.",
    "landing.remove.redesign.who2Tags": "ACTIVE DE DESIGN",
    "landing.remove.redesign.stepsTag": "CUM FUNCȚIONEAZĂ",
    "landing.remove.redesign.stepsTitle": "3 Pași către Fundaluri Transparente",
    "landing.remove.redesign.s1Title": "Încărcați Imaginea",
    "landing.remove.redesign.s1Desc": "Trageți și plasați fotografia. PNG, JPG sau WEBP.",
    "landing.remove.redesign.s2Title": "Procesare AI",
    "landing.remove.redesign.s2Desc": "AI-ul local detectează subiectul principal în 1 secundă.",
    "landing.remove.redesign.s3Title": "Descărcare HD",
    "landing.remove.redesign.s3Desc": "Exportați fotografia decupată cu fundal transparent.",
    "home.why.tag": "DE CE HELPMYIMG",
    "home.why.title": "De ce HelpMyIMG este cea mai inteligentă alegere",
    "home.why.desc": "Proiectat de la zero pentru intimitate maximă, viteză fulgerătoare și cost zero.",
    "home.why.c1.t": "Viteză Locală Instantanee",
    "home.why.c1.d": "Fotografiile dvs. sunt procesate direct în memoria dispozitivului cu latență zero.",
    "home.why.c1.b": "0ms Întârziere Server",
    "home.why.c2.t": "100% Intimitate Absolută",
    "home.why.c2.d": "Portretele personale și documentele confidențiale nu părăsesc niciodată computerul.",
    "home.why.c2.b": "Zero Stocare Cloud",
    "home.why.c3.t": "Gratuit pentru totdeauna",
    "home.why.c3.d": "Fără abonamente, fără filigrane. Editare foto accesibilă tuturor.",
    "home.why.c3.b": "$0 / Pe Viață",
    "home.why.c4.t": "Procesare în masă",
    "home.why.c4.d": "Trageți până la 10 fotografii simultan și exportați ca arhivă ZIP în câteva secunde.",
    "home.why.c4.b": "10x Viteză de Lucru",
    "home.steps.tag": "CUM FUNCȚIONEAZĂ",
    "home.steps.title": "Cum funcționează HelpMyIMG în 3 pași simpli",
    "home.steps.desc": "Nu necesită instalare software. Obțineți rezultate profesionale direct din browserul web."
  }
};

const scriptDir = __dirname;
const localesDir = path.join(scriptDir, '../public/locales');

for (const [lang, kv] of Object.entries(translations)) {
  const filePath = path.join(localesDir, lang, 'translation.json');
  if (fs.existsSync(filePath)) {
    const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    for (const [key, val] of Object.entries(kv)) {
      data[key] = val;
    }
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
    console.log(`[${lang}] Injected translations chunk 2`);
  }
}
