const fs = require('fs');
const path = require('path');
const localesDir = path.join(__dirname, '../public/locales');

const translations = {
  ms: {
    watermark: { heroBadge: "PERLINDUNGAN JENAMA", heroTitle: "Lindungi Kerja Anda.", heroTitle2: "Bina Identiti Anda.", heroDesc: "Gunakan tera air yang sangat disesuaikan untuk melindungi harta intelek anda. Tambah tindanan teks atau logo dengan kawalan tepat ke atas kelegapan, kedudukan dan mod campuran.", feat1Title: "Pelapisan Tidak Memusnahkan", feat1Desc: "Tambahkan berbilang lapisan tera air tanpa mengubah data imej asal anda. Mudah untuk meletakkan, skala dan putar.", feat2Title: "Kawalan Kelegapan & Campuran", feat2Desc: "Perhalusi ketelusan teks atau logo anda. Pilih mod penggabungan lanjutan untuk menjadikan tera air anda halus namun mustahil untuk dialih keluar.", feat3Title: "Mod Corak Berjubin", feat3Desc: "Ulang tera air anda secara automatik merentas keseluruhan imej dalam corak grid. Perlindungan muktamad terhadap pemangkasan yang tidak dibenarkan.", stepsTag: "ALIRAN KERJA", stepsTitle: "Lindungi dalam 3 Langkah", s1Title: "Muat naik", s1Desc: "Muatkan foto asal anda dengan selamat ke dalam penyemak imbas.", s2Title: "Setem", s2Desc: "Gunakan teks tersuai atau tera air logo anda dengan penggayaan.", s3Title: "Eksport", s3Desc: "Simpan imej yang dilindungi serta-merta ke peranti anda." },
    blurface: { heroBadge: "PRIVASI MUKTAMAD", heroTitle: "Tapis dengan AI.", heroTitle2: "Lindungi Identiti.", heroDesc: "Kesan dan kaburkan muka, plat lesen atau maklumat sensitif secara automatik dalam beberapa saat. 100% peribadi, berjalan sepenuhnya dalam penyemak imbas anda.", feat1Title: "Pengesanan Muka", feat1Desc: "Model AI tempatan kami mencari dan menyerlahkan wajah secara automatik dalam foto anda dengan ketepatan yang luar biasa.", feat2Title: "Kekaburan Pintar", feat2Desc: "Gunakan kekaburan gaussian yang cantik, pikselasi atau blok warna pepejal untuk mengaburkan kawasan sensitif secara kekal.", feat3Title: "Gantian Manual", feat3Desc: "Perlu menyembunyikan plat lesen atau dokumen? Gunakan alat pemilihan manual kami untuk mengaburkan mana-mana kawasan tertentu.", stepsTag: "BAGAIMANA IA BERFUNGSI", stepsTitle: "Tanpa nama dalam 3 Langkah", s1Title: "Muat naik", s1Desc: "Lepaskan foto dengan selamat ke dalam penyemak imbas.", s2Title: "Kesan", s2Desc: "Biarkan AI mencari dan memilih muka secara automatik.", s3Title: "Simpan", s3Desc: "Muat turun foto tanpa nama." },
    convert: { heroBadge: "KESESUAIAN SEJAGAT", heroTitle: "Pengubah Format.", heroTitle2: "Sifar Kehilangan Kualiti.", heroDesc: "Tukar dengan lancar antara WebP, PNG, JPG dan AVIF. Pemprosesan pukal yang sangat pantas berjalan sepenuhnya pada mesin tempatan anda.", feat1Title: "Sepantas Kilat", feat1Desc: "Ubah fail WebP yang besar kepada format Universal dengan serta-merta, menggunakan kuasa pemprosesan penuh peranti anda.", feat2Title: "Pemprosesan Pukal", feat2Desc: "Perlu menukar 500 imej? Hanya seret dan lepaskan keseluruhan folder. Kami mengendalikan penukaran kelompok tanpa had dengan mudah.", feat3Title: "Sokongan Luas", feat3Desc: "Sokongan penuh untuk format gen seterusnya seperti WebP bersama format klasik seperti JPG, PNG dan BMP.", stepsTag: "ALIRAN KERJA", stepsTitle: "Tukar dalam 3 Langkah", s1Title: "Muat naik", s1Desc: "Seret dan lepaskan imej atau folder anda ke ruang kerja.", s2Title: "Format", s2Desc: "Pilih format output yang anda kehendaki daripada menu lungsur turun.", s3Title: "Eksport", s3Desc: "Klik eksport dan dapatkan fail berformat baharu anda serta-merta." }
  },
  id: {
    watermark: { heroBadge: "PERLINDUNGAN MEREK", heroTitle: "Lindungi Karya Anda.", heroTitle2: "Bangun Identitas Anda.", heroDesc: "Terapkan tanda air (watermark) yang dapat disesuaikan untuk melindungi kekayaan intelektual Anda. Tambahkan teks atau logo dengan kontrol penuh atas transparansi, posisi, dan mode blending.", feat1Title: "Lapisan Non-Destruktif", feat1Desc: "Tambahkan banyak lapisan watermark tanpa merusak gambar asli Anda. Mudah diposisikan, diukur, dan diputar.", feat2Title: "Kontrol Opasitas & Blending", feat2Desc: "Atur tingkat transparansi logo atau teks Anda. Pilih mode blending tingkat lanjut agar watermark Anda menyatu namun sulit dihapus.", feat3Title: "Mode Pola Ubin (Tile)", feat3Desc: "Ulangi watermark Anda secara otomatis ke seluruh bagian gambar membentuk pola grid. Perlindungan maksimal dari pemotongan (cropping) ilegal.", stepsTag: "ALUR KERJA", stepsTitle: "Lindungi dalam 3 Langkah", s1Title: "Unggah", s1Desc: "Muat foto asli Anda secara aman ke dalam browser.", s2Title: "Stempel", s2Desc: "Terapkan teks kustom atau watermark logo Anda dengan gaya.", s3Title: "Ekspor", s3Desc: "Simpan gambar yang telah dilindungi secara instan ke perangkat Anda." },
    blurface: { heroBadge: "PRIVASI MAKSIMAL", heroTitle: "Sensor dengan AI.", heroTitle2: "Lindungi Identitas.", heroDesc: "Deteksi dan buramkan wajah, plat nomor kendaraan, atau informasi sensitif secara otomatis dalam hitungan detik. 100% privat, berjalan sepenuhnya di browser Anda.", feat1Title: "Deteksi Wajah", feat1Desc: "Model AI lokal kami secara otomatis menemukan dan menyorot wajah di foto Anda dengan akurasi luar biasa.", feat2Title: "Pemburaman Pintar", feat2Desc: "Terapkan efek gaussian blur, pikselasi, atau blok warna solid untuk menyensor area sensitif secara permanen.", feat3Title: "Kontrol Manual", feat3Desc: "Perlu menyembunyikan dokumen rahasia? Gunakan alat seleksi manual kami untuk memburamkan area spesifik mana pun.", stepsTag: "CARA KERJA", stepsTitle: "Anonimkan dalam 3 Langkah", s1Title: "Unggah", s1Desc: "Tarik dan lepas foto dengan aman ke browser.", s2Title: "Deteksi", s2Desc: "Biarkan AI menemukan dan menyeleksi wajah secara otomatis.", s3Title: "Simpan", s3Desc: "Unduh foto yang telah dianomimkan." },
    convert: { heroBadge: "KOMPATIBILITAS UNIVERSAL", heroTitle: "Transformator Format.", heroTitle2: "Kualitas Tetap Terjaga.", heroDesc: "Konversi mulus antara format WebP, PNG, JPG, dan AVIF. Pemrosesan massal yang sangat cepat yang berjalan sepenuhnya di perangkat lokal Anda.", feat1Title: "Sekilat Cahaya", feat1Desc: "Ubah file WebP berukuran besar menjadi JPG universal secara instan, memanfaatkan seluruh kekuatan pemrosesan perangkat Anda.", feat2Title: "Pemrosesan Massal", feat2Desc: "Perlu mengonversi 500 gambar? Cukup seret dan lepas seluruh folder. Kami menangani konversi batch tanpa batas dengan mudah.", feat3Title: "Dukungan Luas", feat3Desc: "Dukungan penuh untuk format masa depan seperti WebP berdampingan dengan format klasik seperti JPG, PNG, dan BMP.", stepsTag: "ALUR KERJA", stepsTitle: "Konversi dalam 3 Langkah", s1Title: "Unggah", s1Desc: "Seret dan lepas gambar atau folder Anda ke ruang kerja.", s2Title: "Format", s2Desc: "Pilih format output yang Anda inginkan dari menu dropdown.", s3Title: "Ekspor", s3Desc: "Klik ekspor dan dapatkan file dengan format baru Anda secara instan." }
  },
  en: {
    watermark: { heroBadge: "BRAND PROTECTION", heroTitle: "Protect Your Work.", heroTitle2: "Build Your Identity.", heroDesc: "Apply highly customizable watermarks to protect your intellectual property. Add text or logo overlays with precise control over opacity, positioning, and blending modes.", feat1Title: "Non-Destructive Layering", feat1Desc: "Add multiple watermark layers without altering your original image data. Easy to position, scale, and rotate.", feat2Title: "Opacity & Blending Control", feat2Desc: "Fine-tune the transparency of your text or logo. Choose advanced blending modes to make your watermark subtle yet impossible to remove.", feat3Title: "Tiled Pattern Mode", feat3Desc: "Automatically repeat your watermark across the entire image in a grid pattern. Ultimate protection against unauthorized cropping.", stepsTag: "WORKFLOW", stepsTitle: "Protect in 3 Steps", s1Title: "Upload", s1Desc: "Load your original photos securely into the browser.", s2Title: "Stamp", s2Desc: "Apply your custom text or logo watermark with styling.", s3Title: "Export", s3Desc: "Save the protected images instantly to your device." },
    blurface: { heroBadge: "ULTIMATE PRIVACY", heroTitle: "Censor with AI.", heroTitle2: "Protect Identities.", heroDesc: "Automatically detect and blur faces, license plates, or sensitive information in seconds. 100% private, running entirely within your browser.", feat1Title: "Face Detection", feat1Desc: "Our local AI model automatically finds and highlights faces in your photos with incredible accuracy.", feat2Title: "Smart Blurring", feat2Desc: "Apply beautiful gaussian blurs, pixelation, or solid color blocks to obscure sensitive regions permanently.", feat3Title: "Manual Override", feat3Desc: "Need to hide a license plate or a document? Use our manual selection tools to blur any specific area.", stepsTag: "HOW IT WORKS", stepsTitle: "Anonymize in 3 Steps", s1Title: "Upload", s1Desc: "Drop photos safely into the browser.", s2Title: "Detect", s2Desc: "Let AI find and select faces automatically.", s3Title: "Save", s3Desc: "Download the anonymized photos." },
    convert: { heroBadge: "UNIVERSAL COMPATIBILITY", heroTitle: "Format Transformer.", heroTitle2: "Zero Quality Loss.", heroDesc: "Seamlessly convert between WebP, PNG, JPG, and AVIF. Extremely fast bulk processing running entirely on your local machine.", feat1Title: "Lightning Fast", feat1Desc: "Transform huge WebP files into universal JPGs instantly, utilizing the full processing power of your device.", feat2Title: "Bulk Processing", feat2Desc: "Need to convert 500 images? Just drag and drop the entire folder. We handle unlimited batch conversions effortlessly.", feat3Title: "Broad Support", feat3Desc: "Full support for next-gen formats like WebP alongside classic formats like JPG, PNG, and BMP.", stepsTag: "WORKFLOW", stepsTitle: "Convert in 3 Steps", s1Title: "Upload", s1Desc: "Drag and drop your images or folders into the workspace.", s2Title: "Format", s2Desc: "Select your desired output format from the dropdown menu.", s3Title: "Export", s3Desc: "Click export and get your newly formatted files instantly." }
  },
  es: {
    watermark: { heroBadge: "PROTECCIÓN DE MARCA", heroTitle: "Protege Tu Trabajo.", heroTitle2: "Construye Tu Identidad.", heroDesc: "Aplica marcas de agua altamente personalizables para proteger tu propiedad intelectual. Añade texto o logos con control preciso de opacidad y modos de fusión.", feat1Title: "Capas No Destructivas", feat1Desc: "Añade múltiples capas sin alterar los datos originales. Fácil de posicionar y rotar.", feat2Title: "Control de Opacidad", feat2Desc: "Ajusta la transparencia de tu texto o logo con modos de fusión avanzados.", feat3Title: "Modo Patrón de Mosaico", feat3Desc: "Repite automáticamente tu marca de agua en toda la imagen. Protección total contra recortes no autorizados.", stepsTag: "FLUJO DE TRABAJO", stepsTitle: "Protege en 3 Pasos", s1Title: "Subir", s1Desc: "Carga tus fotos de forma segura en el navegador.", s2Title: "Estampar", s2Desc: "Aplica tu marca de agua con estilo.", s3Title: "Exportar", s3Desc: "Guarda las imágenes protegidas al instante." },
    blurface: { heroBadge: "PRIVACIDAD TOTAL", heroTitle: "Censura con IA.", heroTitle2: "Protege Identidades.", heroDesc: "Detecta y desenfoca rostros automáticamente en segundos. 100% privado en tu navegador.", feat1Title: "Detección Facial", feat1Desc: "Nuestro modelo de IA local encuentra rostros con increíble precisión.", feat2Title: "Desenfoque Inteligente", feat2Desc: "Aplica desenfoque gaussiano o pixelado para ocultar regiones sensibles.", feat3Title: "Control Manual", feat3Desc: "¿Necesitas ocultar un documento? Usa las herramientas manuales.", stepsTag: "CÓMO FUNCIONA", stepsTitle: "Anonimiza en 3 Pasos", s1Title: "Subir", s1Desc: "Suelta las fotos de forma segura.", s2Title: "Detectar", s2Desc: "Deja que la IA seleccione los rostros.", s3Title: "Guardar", s3Desc: "Descarga las fotos anonimizadas." },
    convert: { heroBadge: "COMPATIBILIDAD UNIVERSAL", heroTitle: "Transformador de Formato.", heroTitle2: "Sin Pérdida de Calidad.", heroDesc: "Convierte entre WebP, PNG, JPG y AVIF. Procesamiento por lotes ultrarrápido.", feat1Title: "Súper Rápido", feat1Desc: "Transforma archivos enormes al instante usando toda la potencia de tu dispositivo.", feat2Title: "Procesamiento por Lotes", feat2Desc: "¿Convertir 500 imágenes? Arrastra la carpeta completa.", feat3Title: "Amplio Soporte", feat3Desc: "Soporte para formatos de nueva generación como WebP y clásicos como JPG.", stepsTag: "FLUJO DE TRABAJO", stepsTitle: "Convierte en 3 Pasos", s1Title: "Subir", s1Desc: "Arrastra tus imágenes al área de trabajo.", s2Title: "Formatear", s2Desc: "Selecciona el formato de salida deseado.", s3Title: "Exportar", s3Desc: "Haz clic y obtén tus archivos al instante." }
  },
  zh: {
    watermark: { heroBadge: "品牌保护", heroTitle: "保护您的作品。", heroTitle2: "建立您的身份。", heroDesc: "应用高度可定制的水印来保护您的知识产权。添加文本或徽标叠加，并精确控制不透明度和混合模式。", feat1Title: "非破坏性分层", feat1Desc: "添加多个水印层，而不改变原始图像数据。", feat2Title: "不透明度控制", feat2Desc: "微调您的文本或徽标的透明度。", feat3Title: "平铺图案模式", feat3Desc: "自动在整个图像中重复您的水印。防止未经授权的裁剪。", stepsTag: "工作流程", stepsTitle: "3步保护", s1Title: "上传", s1Desc: "将您的原始照片安全地加载到浏览器中。", s2Title: "标记", s2Desc: "应用您的自定义文本或徽标水印。", s3Title: "导出", s3Desc: "立即保存受保护的图像。" },
    blurface: { heroBadge: "终极隐私", heroTitle: "用AI审查。", heroTitle2: "保护身份。", heroDesc: "在几秒钟内自动检测并模糊面部。100%私密，完全在您的浏览器中运行。", feat1Title: "面部检测", feat1Desc: "我们的本地人工智能模型可以极其准确地自动找到照片中的面部。", feat2Title: "智能模糊", feat2Desc: "应用漂亮的高斯模糊或像素化来永久隐藏敏感区域。", feat3Title: "手动覆盖", feat3Desc: "需要隐藏文档吗？使用我们的手动选择工具。", stepsTag: "运作方式", stepsTitle: "3步匿名化", s1Title: "上传", s1Desc: "安全地将照片放入浏览器中。", s2Title: "检测", s2Desc: "让人工智能自动查找并选择面部。", s3Title: "保存", s3Desc: "下载匿名的照片。" },
    convert: { heroBadge: "通用兼容性", heroTitle: "格式转换器。", heroTitle2: "零质量损失。", heroDesc: "在WebP、PNG、JPG和AVIF之间无缝转换。超快的批量处理。", feat1Title: "闪电般快速", feat1Desc: "利用设备的全部处理能力，立即将巨大的文件转换为通用JPG。", feat2Title: "批量处理", feat2Desc: "需要转换500张图片？只需拖放整个文件夹。", feat3Title: "广泛支持", feat3Desc: "全面支持WebP等下一代格式以及JPG等经典格式。", stepsTag: "工作流程", stepsTitle: "3步转换", s1Title: "上传", s1Desc: "将您的图像或文件夹拖放到工作区中。", s2Title: "格式", s2Desc: "从下拉菜单中选择您想要的输出格式。", s3Title: "导出", s3Desc: "单击导出并立即获取新格式的文件。" }
  },
  hi: {
    watermark: { heroBadge: "ब्रांड सुरक्षा", heroTitle: "अपने काम की रक्षा करें।", heroTitle2: "अपनी पहचान बनाएं।", heroDesc: "अपनी बौद्धिक संपदा की रक्षा के लिए अत्यधिक अनुकूलन योग्य वॉटरमार्क लागू करें।", feat1Title: "गैर-विनाशकारी लेयरिंग", feat1Desc: "अपने मूल छवि डेटा को बदले बिना कई वॉटरमार्क परतें जोड़ें।", feat2Title: "अपारदर्शिता नियंत्रण", feat2Desc: "अपने पाठ या लोगो की पारदर्शिता को फाइन-ट्यून करें।", feat3Title: "टाइल पैटर्न मोड", feat3Desc: "ग्रिड पैटर्न में संपूर्ण छवि में अपना वॉटरमार्क स्वचालित रूप से दोहराएं।", stepsTag: "कार्यप्रवाह", stepsTitle: "3 चरणों में रक्षा करें", s1Title: "अपलोड करें", s1Desc: "अपनी मूल तस्वीरें ब्राउज़र में सुरक्षित रूप से लोड करें।", s2Title: "स्टाम्प", s2Desc: "स्टाइलिंग के साथ अपना कस्टम टेक्स्ट या लोगो वॉटरमार्क लागू करें।", s3Title: "निर्यात", s3Desc: "संरक्षित छवियों को तुरंत सहेजें।" },
    blurface: { heroBadge: "अंतिम गोपनीयता", heroTitle: "एआई के साथ सेंसर।", heroTitle2: "पहचान की रक्षा करें।", heroDesc: "सेकंड में स्वचालित रूप से चेहरों का पता लगाएं और धुंधला करें। 100% निजी।", feat1Title: "चेहरा पहचान", feat1Desc: "हमारा एआई मॉडल स्वचालित रूप से आपकी तस्वीरों में चेहरों को ढूंढता है।", feat2Title: "स्मार्ट ब्लरिंग", feat2Desc: "संवेदनशील क्षेत्रों को छिपाने के लिए गॉसियन ब्लर लागू करें।", feat3Title: "मैनुअल ओवरराइड", feat3Desc: "दस्तावेज़ छिपाने की आवश्यकता है? हमारे मैनुअल चयन उपकरण का उपयोग करें।", stepsTag: "यह कैसे काम करता है", stepsTitle: "3 चरणों में अनाम करें", s1Title: "अपलोड करें", s1Desc: "तस्वीरों को सुरक्षित रूप से ब्राउज़र में छोड़ दें।", s2Title: "पता लगाएं", s2Desc: "एआई को स्वचालित रूप से चेहरों का चयन करने दें।", s3Title: "सहेजें", s3Desc: "अनाम तस्वीरें डाउनलोड करें।" },
    convert: { heroBadge: "सार्वभौमिक संगतता", heroTitle: "प्रारूप ट्रांसफार्मर।", heroTitle2: "शून्य गुणवत्ता हानि।", heroDesc: "WebP, PNG, JPG और AVIF के बीच निर्बाध रूप से कनवर्ट करें।", feat1Title: "बिजली की तेजी से", feat1Desc: "अपने डिवाइस की पूरी शक्ति का उपयोग करके फ़ाइलों को तुरंत बदलें।", feat2Title: "थोक प्रसंस्करण", feat2Desc: "500 छवियों को कनवर्ट करने की आवश्यकता है? बस संपूर्ण फ़ोल्डर खींचें।", feat3Title: "व्यापक समर्थन", feat3Desc: "WebP और JPG जैसे क्लासिक प्रारूपों के लिए पूर्ण समर्थन।", stepsTag: "कार्यप्रवाह", stepsTitle: "3 चरणों में कनवर्ट करें", s1Title: "अपलोड करें", s1Desc: "अपनी छवियों को कार्यक्षेत्र में खींचें और छोड़ें।", s2Title: "प्रारूप", s2Desc: "अपने वांछित आउटपुट प्रारूप का चयन करें।", s3Title: "निर्यात", s3Desc: "निर्यात पर क्लिक करें और तुरंत अपनी फाइलें प्राप्त करें।" }
  },
  ja: {
    watermark: { heroBadge: "ブランド保護", heroTitle: "作品を保護する。", heroTitle2: "アイデンティティを構築する。", heroDesc: "高度にカスタマイズ可能な透かしを適用して、知的財産を保護します。", feat1Title: "非破壊レイヤー", feat1Desc: "元の画像データを変更せずに複数の透かしレイヤーを追加します。", feat2Title: "不透明度コントロール", feat2Desc: "テキストまたはロゴの透明度を微調整します。", feat3Title: "タイルパターンモード", feat3Desc: "透かしを画像全体に自動的に繰り返します。", stepsTag: "ワークフロー", stepsTitle: "3ステップで保護", s1Title: "アップロード", s1Desc: "元の写真をブラウザに安全に読み込みます。", s2Title: "スタンプ", s2Desc: "カスタムテキストまたはロゴの透かしを適用します。", s3Title: "エクスポート", s3Desc: "保護された画像をすぐに保存します。" },
    blurface: { heroBadge: "究極のプライバシー", heroTitle: "AIで検閲。", heroTitle2: "IDを保護する。", heroDesc: "数秒で顔を自動的に検出してぼかします。100%プライベート。", feat1Title: "顔検出", feat1Desc: "ローカルAIモデルが顔を自動的に見つけます。", feat2Title: "スマートぼかし", feat2Desc: "ガウスぼかしを適用して機密領域を隠します。", feat3Title: "手動オーバーライド", feat3Desc: "ドキュメントを隠す必要がありますか？手動選択ツールを使用します。", stepsTag: "仕組み", stepsTitle: "3ステップで匿名化", s1Title: "アップロード", s1Desc: "写真をブラウザに安全にドロップします。", s2Title: "検出", s2Desc: "AIに顔を自動的に選択させます。", s3Title: "保存", s3Desc: "匿名化された写真をダウンロードします。" },
    convert: { heroBadge: "ユニバーサルな互換性", heroTitle: "フォーマットトランスフォーマー。", heroTitle2: "品質低下ゼロ。", heroDesc: "WebP、PNG、JPG、AVIF間でシームレスに変換します。", feat1Title: "超高速", feat1Desc: "デバイスの全機能を使用してファイルを即座に変換します。", feat2Title: "バッチ処理", feat2Desc: "500枚の画像を変換する必要がありますか？フォルダ全体をドラッグするだけです。", feat3Title: "幅広いサポート", feat3Desc: "WebPなどの次世代フォーマットとJPGなどのクラシックフォーマットをサポート。", stepsTag: "ワークフロー", stepsTitle: "3ステップで変換", s1Title: "アップロード", s1Desc: "画像をワークスペースにドラッグ＆ドロップします。", s2Title: "フォーマット", s2Desc: "目的の出力フォーマットを選択します。", s3Title: "エクスポート", s3Desc: "エクスポートをクリックして、ファイルをすぐに取得します。" }
  },
  de: {
    watermark: { heroBadge: "MARKENSCHUTZ", heroTitle: "Schützen Sie Ihre Arbeit.", heroTitle2: "Bauen Sie Ihre Identität auf.", heroDesc: "Wenden Sie hochgradig anpassbare Wasserzeichen an, um Ihr geistiges Eigentum zu schützen.", feat1Title: "Zerstörungsfreie Ebenen", feat1Desc: "Fügen Sie mehrere Wasserzeichenebenen hinzu, ohne Ihre Originalbilddaten zu ändern.", feat2Title: "Deckkraftkontrolle", feat2Desc: "Passen Sie die Transparenz Ihres Textes oder Logos an.", feat3Title: "Kachelmuster-Modus", feat3Desc: "Wiederholen Sie Ihr Wasserzeichen automatisch über das gesamte Bild.", stepsTag: "ARBEITSABLAUF", stepsTitle: "In 3 Schritten schützen", s1Title: "Hochladen", s1Desc: "Laden Sie Ihre Originalfotos sicher in den Browser.", s2Title: "Stempeln", s2Desc: "Wenden Sie Ihren benutzerdefinierten Text- oder Logo-Wasserzeichen an.", s3Title: "Exportieren", s3Desc: "Speichern Sie die geschützten Bilder sofort." },
    blurface: { heroBadge: "ULTIMATIVE PRIVATSPHÄRE", heroTitle: "Mit KI zensieren.", heroTitle2: "Identitäten schützen.", heroDesc: "Gesichter in Sekundenschnelle automatisch erkennen und unscharf machen. 100% privat.", feat1Title: "Gesichtserkennung", feat1Desc: "Unser lokales KI-Modell findet Gesichter automatisch.", feat2Title: "Intelligente Unschärfe", feat2Desc: "Wenden Sie Gaußsche Unschärfe an, um sensible Bereiche zu verbergen.", feat3Title: "Manuelle Überschreibung", feat3Desc: "Müssen Sie ein Dokument verbergen? Verwenden Sie das manuelle Auswahlwerkzeug.", stepsTag: "WIE ES FUNKTIONIERT", stepsTitle: "In 3 Schritten anonymisieren", s1Title: "Hochladen", s1Desc: "Legen Sie Fotos sicher im Browser ab.", s2Title: "Erkennen", s2Desc: "Lassen Sie die KI Gesichter automatisch auswählen.", s3Title: "Speichern", s3Desc: "Laden Sie die anonymisierten Fotos herunter." },
    convert: { heroBadge: "UNIVERSELLE KOMPATIBILITÄT", heroTitle: "Format-Transformator.", heroTitle2: "Null Qualitätsverlust.", heroDesc: "Nahtlos zwischen WebP, PNG, JPG und AVIF konvertieren.", feat1Title: "Blitzschnell", feat1Desc: "Konvertieren Sie Dateien sofort mit der vollen Leistung Ihres Geräts.", feat2Title: "Stapelverarbeitung", feat2Desc: "500 Bilder konvertieren? Ziehen Sie einfach den gesamten Ordner.", feat3Title: "Breite Unterstützung", feat3Desc: "Unterstützung für Next-Gen-Formate wie WebP und klassische wie JPG.", stepsTag: "ARBEITSABLAUF", stepsTitle: "In 3 Schritten konvertieren", s1Title: "Hochladen", s1Desc: "Ziehen Sie Ihre Bilder in den Arbeitsbereich.", s2Title: "Format", s2Desc: "Wählen Sie Ihr gewünschtes Ausgabeformat.", s3Title: "Exportieren", s3Desc: "Klicken Sie auf Exportieren und erhalten Sie Ihre Dateien sofort." }
  },
  ru: {
    watermark: { heroBadge: "ЗАЩИТА БРЕНДА", heroTitle: "Защитите свою работу.", heroTitle2: "Создайте свою индивидуальность.", heroDesc: "Применяйте настраиваемые водяные знаки для защиты вашей интеллектуальной собственности.", feat1Title: "Неразрушающие слои", feat1Desc: "Добавляйте слои водяных знаков без изменения исходных данных.", feat2Title: "Управление прозрачностью", feat2Desc: "Точная настройка прозрачности вашего текста или логотипа.", feat3Title: "Режим узора плитки", feat3Desc: "Автоматически повторяйте свой водяной знак по всему изображению.", stepsTag: "РАБОЧИЙ ПРОЦЕСС", stepsTitle: "Защита в 3 шага", s1Title: "Загрузить", s1Desc: "Безопасно загрузите свои оригинальные фотографии в браузер.", s2Title: "Штамп", s2Desc: "Примените водяной знак.", s3Title: "Экспорт", s3Desc: "Мгновенно сохраните защищенные изображения." },
    blurface: { heroBadge: "ПОЛНАЯ КОНФИДЕНЦИАЛЬНОСТЬ", heroTitle: "Цензура с ИИ.", heroTitle2: "Защита личных данных.", heroDesc: "Автоматическое обнаружение и размытие лиц за считанные секунды. 100% конфиденциально.", feat1Title: "Распознавание лиц", feat1Desc: "Наша локальная модель ИИ автоматически находит лица.", feat2Title: "Умное размытие", feat2Desc: "Примените размытие по Гауссу, чтобы скрыть чувствительные области.", feat3Title: "Ручное управление", feat3Desc: "Нужно скрыть документ? Используйте ручной инструмент выделения.", stepsTag: "КАК ЭТО РАБОТАЕТ", stepsTitle: "Анонимизация в 3 шага", s1Title: "Загрузить", s1Desc: "Безопасно перетащите фотографии в браузер.", s2Title: "Обнаружить", s2Desc: "Позвольте ИИ автоматически выбирать лица.", s3Title: "Сохранить", s3Desc: "Скачайте анонимные фотографии." },
    convert: { heroBadge: "УНИВЕРСАЛЬНАЯ СОВМЕСТИМОСТЬ", heroTitle: "Трансформатор форматов.", heroTitle2: "Без потери качества.", heroDesc: "Бесшовное преобразование между WebP, PNG, JPG и AVIF.", feat1Title: "Молниеносно", feat1Desc: "Мгновенно преобразуйте файлы, используя всю мощь вашего устройства.", feat2Title: "Пакетная обработка", feat2Desc: "Нужно преобразовать 500 изображений? Просто перетащите папку.", feat3Title: "Широкая поддержка", feat3Desc: "Поддержка форматов нового поколения, таких как WebP, и классических, таких как JPG.", stepsTag: "РАБОЧИЙ ПРОЦЕСС", stepsTitle: "Преобразование в 3 шага", s1Title: "Загрузить", s1Desc: "Перетащите ваши изображения в рабочую область.", s2Title: "Формат", s2Desc: "Выберите желаемый выходной формат.", s3Title: "Экспорт", s3Desc: "Нажмите «Экспорт» и мгновенно получите свои файлы." }
  },
  ar: {
    watermark: { heroBadge: "حماية العلامة التجارية", heroTitle: "احم عملك.", heroTitle2: "ابن هويتك.", heroDesc: "قم بتطبيق علامات مائية قابلة للتخصيص لحماية ملكيتك الفكرية.", feat1Title: "طبقات غير مدمرة", feat1Desc: "أضف طبقات علامة مائية دون تغيير بيانات الصورة الأصلية.", feat2Title: "التحكم في العتامة", feat2Desc: "قم بضبط شفافية النص أو الشعار الخاص بك.", feat3Title: "وضع النمط المتكرر", feat3Desc: "كرر علامتك المائية تلقائيًا عبر الصورة بأكملها.", stepsTag: "سير العمل", stepsTitle: "حماية في 3 خطوات", s1Title: "رفع", s1Desc: "قم بتحميل صورك الأصلية بأمان إلى المتصفح.", s2Title: "ختم", s2Desc: "قم بتطبيق النص أو الشعار الخاص بك.", s3Title: "تصدير", s3Desc: "احفظ الصور المحمية على الفور." },
    blurface: { heroBadge: "الخصوصية المطلقة", heroTitle: "رقابة باستخدام الذكاء الاصطناعي.", heroTitle2: "حماية الهويات.", heroDesc: "اكتشف وطمس الوجوه تلقائيًا في ثوانٍ. خاص بنسبة 100٪.", feat1Title: "اكتشاف الوجوه", feat1Desc: "نموذج الذكاء الاصطناعي المحلي لدينا يجد الوجوه تلقائيًا.", feat2Title: "تمويه ذكي", feat2Desc: "قم بتطبيق تمويه غاوسي لإخفاء المناطق الحساسة.", feat3Title: "تجاوز يدوي", feat3Desc: "هل تحتاج إلى إخفاء مستند؟ استخدم أداة التحديد اليدوي.", stepsTag: "كيف يعمل", stepsTitle: "إخفاء الهوية في 3 خطوات", s1Title: "رفع", s1Desc: "أسقط الصور بأمان في المتصفح.", s2Title: "اكتشاف", s2Desc: "دع الذكاء الاصطناعي يختار الوجوه تلقائيًا.", s3Title: "حفظ", s3Desc: "قم بتنزيل الصور المجهولة." },
    convert: { heroBadge: "التوافق العالمي", heroTitle: "محول التنسيقات.", heroTitle2: "صفر فقدان للجودة.", heroDesc: "قم بالتحويل بسلاسة بين WebP و PNG و JPG و AVIF.", feat1Title: "سريع جدا", feat1Desc: "قم بتحويل الملفات على الفور باستخدام القوة الكاملة لجهازك.", feat2Title: "معالجة الدفعات", feat2Desc: "هل تحتاج إلى تحويل 500 صورة؟ ما عليك سوى سحب المجلد بأكمله.", feat3Title: "دعم واسع", feat3Desc: "دعم تنسيقات الجيل التالي مثل WebP والكلاسيكية مثل JPG.", stepsTag: "سير العمل", stepsTitle: "التحويل في 3 خطوات", s1Title: "رفع", s1Desc: "قم بسحب وإسقاط صورك في مساحة العمل.", s2Title: "التنسيق", s2Desc: "حدد تنسيق الإخراج المطلوب.", s3Title: "تصدير", s3Desc: "انقر فوق تصدير واحصل على ملفاتك على الفور." }
  },
  pt: {
    watermark: { heroBadge: "PROTEÇÃO DE MARCA", heroTitle: "Proteja Seu Trabalho.", heroTitle2: "Construa Sua Identidade.", heroDesc: "Aplique marcas d'água altamente personalizáveis para proteger sua propriedade intelectual.", feat1Title: "Camadas Não Destrutivas", feat1Desc: "Adicione várias camadas de marca d'água sem alterar os dados originais.", feat2Title: "Controle de Opacidade", feat2Desc: "Ajuste a transparência do seu texto ou logotipo.", feat3Title: "Modo de Padrão em Ladrilho", feat3Desc: "Repita automaticamente sua marca d'água em toda a imagem.", stepsTag: "FLUXO DE TRABALHO", stepsTitle: "Proteja em 3 Passos", s1Title: "Enviar", s1Desc: "Carregue suas fotos originais com segurança no navegador.", s2Title: "Carimbar", s2Desc: "Aplique sua marca d'água personalizada.", s3Title: "Exportar", s3Desc: "Salve as imagens protegidas instantaneamente." },
    blurface: { heroBadge: "PRIVACIDADE TOTAL", heroTitle: "Censure com IA.", heroTitle2: "Proteja Identidades.", heroDesc: "Detecte e desfoque rostos automaticamente em segundos. 100% privado.", feat1Title: "Detecção Facial", feat1Desc: "Nosso modelo de IA local encontra rostos automaticamente.", feat2Title: "Desfoque Inteligente", feat2Desc: "Aplique desfoque gaussiano para ocultar regiões sensíveis.", feat3Title: "Controle Manual", feat3Desc: "Precisa esconder um documento? Use a ferramenta de seleção manual.", stepsTag: "COMO FUNCIONA", stepsTitle: "Anonimize em 3 Passos", s1Title: "Enviar", s1Desc: "Solte as fotos com segurança no navegador.", s2Title: "Detectar", s2Desc: "Deixe a IA selecionar os rostos automaticamente.", s3Title: "Salvar", s3Desc: "Baixe as fotos anonimizadas." },
    convert: { heroBadge: "COMPATIBILIDADE UNIVERSAL", heroTitle: "Transformador de Formato.", heroTitle2: "Zero Perda de Qualidade.", heroDesc: "Converta perfeitamente entre WebP, PNG, JPG e AVIF.", feat1Title: "Extremamente Rápido", feat1Desc: "Converta arquivos instantaneamente usando toda a potência do seu dispositivo.", feat2Title: "Processamento em Lote", feat2Desc: "Precisa converter 500 imagens? Basta arrastar a pasta inteira.", feat3Title: "Amplo Suporte", feat3Desc: "Suporte para formatos de última geração como WebP e clássicos como JPG.", stepsTag: "FLUXO DE TRABALHO", stepsTitle: "Converta em 3 Passos", s1Title: "Enviar", s1Desc: "Arraste e solte suas imagens na área de trabalho.", s2Title: "Formato", s2Desc: "Selecione o formato de saída desejado.", s3Title: "Exportar", s3Desc: "Clique em exportar e obtenha seus arquivos instantaneamente." }
  },
  ko: {
    watermark: { heroBadge: "브랜드 보호", heroTitle: "작업물을 보호하세요.", heroTitle2: "정체성을 구축하세요.", heroDesc: "매우 맞춤화 가능한 워터마크를 적용하여 지적 재산권을 보호합니다.", feat1Title: "비파괴 레이어", feat1Desc: "원본 이미지 데이터를 변경하지 않고 여러 워터마크 레이어를 추가합니다.", feat2Title: "불투명도 제어", feat2Desc: "텍스트 또는 로고의 투명도를 미세 조정합니다.", feat3Title: "타일 패턴 모드", feat3Desc: "이미지 전체에 워터마크를 자동으로 반복합니다.", stepsTag: "워크플로우", stepsTitle: "3단계로 보호", s1Title: "업로드", s1Desc: "원본 사진을 브라우저에 안전하게 로드합니다.", s2Title: "스탬프", s2Desc: "사용자 정의 텍스트 또는 로고 워터마크를 적용합니다.", s3Title: "내보내기", s3Desc: "보호된 이미지를 즉시 저장합니다." },
    blurface: { heroBadge: "궁극의 프라이버시", heroTitle: "AI로 모자이크.", heroTitle2: "신원을 보호하세요.", heroDesc: "몇 초 만에 얼굴을 자동으로 감지하고 흐리게 처리합니다. 100% 비공개.", feat1Title: "얼굴 감지", feat1Desc: "로컬 AI 모델이 사진에서 얼굴을 자동으로 찾습니다.", feat2Title: "스마트 블러링", feat2Desc: "가우시안 블러를 적용하여 민감한 영역을 숨깁니다.", feat3Title: "수동 재정의", feat3Desc: "문서를 숨겨야 합니까? 수동 선택 도구를 사용하십시오.", stepsTag: "작동 방식", stepsTitle: "3단계로 익명화", s1Title: "업로드", s1Desc: "사진을 브라우저에 안전하게 놓습니다.", s2Title: "감지", s2Desc: "AI가 자동으로 얼굴을 선택하도록 합니다.", s3Title: "저장", s3Desc: "익명화된 사진을 다운로드합니다." },
    convert: { heroBadge: "보편적 호환성", heroTitle: "포맷 변환기.", heroTitle2: "품질 손실 제로.", heroDesc: "WebP, PNG, JPG 및 AVIF 간에 원활하게 변환합니다.", feat1Title: "번개처럼 빠른", feat1Desc: "장치의 전체 처리 능력을 사용하여 파일을 즉시 변환합니다.", feat2Title: "일괄 처리", feat2Desc: "500장의 이미지를 변환해야 합니까? 전체 폴더를 드래그하기만 하면 됩니다.", feat3Title: "폭넓은 지원", feat3Desc: "WebP와 같은 차세대 포맷 및 JPG와 같은 클래식 포맷 지원.", stepsTag: "워크플로우", stepsTitle: "3단계로 변환", s1Title: "업로드", s1Desc: "이미지를 작업 영역으로 끌어다 놓습니다.", s2Title: "포맷", s2Desc: "원하는 출력 형식을 선택합니다.", s3Title: "내보내기", s3Desc: "내보내기를 클릭하고 즉시 파일을 가져옵니다." }
  },
  // English Fallback strategy for the remaining languages to ensure script runs and completes the injection
  th: {}, vi: {}, tr: {}, fa: {}, ur: {}, 
  nl: {}, it: {}, pl: {}, uk: {}, ro: {}, 
  hu: {}, cs: {}, el: {}, sv: {}, bg: {}, 
  da: {}, fi: {}, sk: {}
};

// Copy EN to missing translations for the remaining languages
const enT = translations.en;
const supportedLocales = fs.readdirSync(localesDir).filter(f => fs.statSync(path.join(localesDir, f)).isDirectory());

supportedLocales.forEach(locale => {
  // Deep merge or fallback to EN if the locale doesn't have the new keys
  const t = translations[locale] && translations[locale].watermark ? translations[locale] : enT;
  
  const translationFilePath = path.join(localesDir, locale, 'translation.json');
  if (fs.existsSync(translationFilePath)) {
    try {
      const content = fs.readFileSync(translationFilePath, 'utf8');
      const json = JSON.parse(content);
      
      // We will inject FLAT KEYS directly into the root level object
      
      // 1. Watermark
      json['landing.watermark.redesign.heroBadge'] = t.watermark.heroBadge;
      json['landing.watermark.redesign.heroTitle'] = t.watermark.heroTitle;
      json['landing.watermark.redesign.heroTitle2'] = t.watermark.heroTitle2;
      json['landing.watermark.redesign.heroDesc'] = t.watermark.heroDesc;
      json['landing.watermark.redesign.feat1Title'] = t.watermark.feat1Title;
      json['landing.watermark.redesign.feat1Desc'] = t.watermark.feat1Desc;
      json['landing.watermark.redesign.feat2Title'] = t.watermark.feat2Title;
      json['landing.watermark.redesign.feat2Desc'] = t.watermark.feat2Desc;
      json['landing.watermark.redesign.feat3Title'] = t.watermark.feat3Title;
      json['landing.watermark.redesign.feat3Desc'] = t.watermark.feat3Desc;
      json['landing.watermark.redesign.stepsTag'] = t.watermark.stepsTag;
      json['landing.watermark.redesign.stepsTitle'] = t.watermark.stepsTitle;
      json['landing.watermark.redesign.s1Title'] = t.watermark.s1Title;
      json['landing.watermark.redesign.s1Desc'] = t.watermark.s1Desc;
      json['landing.watermark.redesign.s2Title'] = t.watermark.s2Title;
      json['landing.watermark.redesign.s2Desc'] = t.watermark.s2Desc;
      json['landing.watermark.redesign.s3Title'] = t.watermark.s3Title;
      json['landing.watermark.redesign.s3Desc'] = t.watermark.s3Desc;
      
      // 2. BlurFace
      json['landing.blurface.redesign.heroBadge'] = t.blurface.heroBadge;
      json['landing.blurface.redesign.heroTitle'] = t.blurface.heroTitle;
      json['landing.blurface.redesign.heroTitle2'] = t.blurface.heroTitle2;
      json['landing.blurface.redesign.heroDesc'] = t.blurface.heroDesc;
      json['landing.blurface.redesign.feat1Title'] = t.blurface.feat1Title;
      json['landing.blurface.redesign.feat1Desc'] = t.blurface.feat1Desc;
      json['landing.blurface.redesign.feat2Title'] = t.blurface.feat2Title;
      json['landing.blurface.redesign.feat2Desc'] = t.blurface.feat2Desc;
      json['landing.blurface.redesign.feat3Title'] = t.blurface.feat3Title;
      json['landing.blurface.redesign.feat3Desc'] = t.blurface.feat3Desc;
      json['landing.blurface.redesign.stepsTag'] = t.blurface.stepsTag;
      json['landing.blurface.redesign.stepsTitle'] = t.blurface.stepsTitle;
      json['landing.blurface.redesign.s1Title'] = t.blurface.s1Title;
      json['landing.blurface.redesign.s1Desc'] = t.blurface.s1Desc;
      json['landing.blurface.redesign.s2Title'] = t.blurface.s2Title;
      json['landing.blurface.redesign.s2Desc'] = t.blurface.s2Desc;
      json['landing.blurface.redesign.s3Title'] = t.blurface.s3Title;
      json['landing.blurface.redesign.s3Desc'] = t.blurface.s3Desc;
      
      // 3. Convert
      json['landing.convert.redesign.heroBadge'] = t.convert.heroBadge;
      json['landing.convert.redesign.heroTitle'] = t.convert.heroTitle;
      json['landing.convert.redesign.heroTitle2'] = t.convert.heroTitle2;
      json['landing.convert.redesign.heroDesc'] = t.convert.heroDesc;
      json['landing.convert.redesign.feat1Title'] = t.convert.feat1Title;
      json['landing.convert.redesign.feat1Desc'] = t.convert.feat1Desc;
      json['landing.convert.redesign.feat2Title'] = t.convert.feat2Title;
      json['landing.convert.redesign.feat2Desc'] = t.convert.feat2Desc;
      json['landing.convert.redesign.feat3Title'] = t.convert.feat3Title;
      json['landing.convert.redesign.feat3Desc'] = t.convert.feat3Desc;
      json['landing.convert.redesign.stepsTag'] = t.convert.stepsTag;
      json['landing.convert.redesign.stepsTitle'] = t.convert.stepsTitle;
      json['landing.convert.redesign.s1Title'] = t.convert.s1Title;
      json['landing.convert.redesign.s1Desc'] = t.convert.s1Desc;
      json['landing.convert.redesign.s2Title'] = t.convert.s2Title;
      json['landing.convert.redesign.s2Desc'] = t.convert.s2Desc;
      json['landing.convert.redesign.s3Title'] = t.convert.s3Title;
      json['landing.convert.redesign.s3Desc'] = t.convert.s3Desc;

      fs.writeFileSync(translationFilePath, JSON.stringify(json, null, 2));
      console.log(`Updated translations for ${locale}`);
    } catch (err) {
      console.error(`Error processing ${locale}:`, err);
    }
  }
});
console.log('All Watermark, BlurFace, and Convert translations injected successfully!');
