const fs = require('fs');
const path = require('path');

const translations = {
  cs: {
    "landing.compress.redesign.heroBadge": "CHYTRÁ KOMPRESE",
    "landing.compress.redesign.heroTitle": "Okamžitě zmenšete velikost obrázku až o 90%",
    "landing.compress.redesign.heroDesc": "Snižte velikost svých fotek bez ztráty vizuální kvality. Ideální pro weby, e-maily a přísné limity nahrávání.",
    "landing.compress.redesign.feat1Badge": "BEZ ZTRÁTY KVALITY",
    "landing.compress.redesign.feat1Title": "Chytrá optimalizace",
    "landing.compress.redesign.feat1Desc": "Automaticky najde perfektní rovnováhu mezi minimální velikostí souboru a maximální kvalitou obrázku.",
    "landing.compress.redesign.feat2Badge": "100% SOUKROMÉ",
    "landing.compress.redesign.feat2Title": "Žádné nahrávání na server",
    "landing.compress.redesign.feat2Desc": "Stejně jako u všech našich nástrojů, komprese probíhá přímo ve vašem prohlížeči. Nic se neodesílá na server.",
    "landing.compress.redesign.feat3Badge": "JAKÝKOLIV FORMÁT",
    "landing.compress.redesign.feat3Title": "Široká podpora",
    "landing.compress.redesign.feat3Desc": "Funguje se standardními formáty JPG a PNG i s moderními ultra efektivními formáty WEBP.",
    "landing.compress.redesign.whoTag": "PRO KOHO TO JE",
    "landing.compress.redesign.whoTitle": "Vyrobeno pro Web & Média",
    "landing.compress.redesign.whoDesc": "Ideální pro vývojáře, designéry a správce sociálních sítí, kteří potřebují vysoce optimalizované obrázky.",
    "landing.compress.redesign.who1Title": "Weboví vývojáři",
    "landing.compress.redesign.who1Desc": "Zlepšete skóre PageSpeed a snižte dobu načítání bez obětování kvality obrázku.",
    "landing.compress.redesign.who1Tags": "SEO OPTIMALIZACE",
    "landing.compress.redesign.who2Title": "Tvůrci obsahu",
    "landing.compress.redesign.who2Desc": "Splňte přísné limity velikosti nahrávání pro platformy jako Discord, Twitter nebo přílohy e-mailů.",
    "landing.compress.redesign.who2Tags": "SOCIÁLNÍ SÍTĚ",
    "landing.compress.redesign.stepsTag": "JAK TO FUNGUJE",
    "landing.compress.redesign.stepsTitle": "3 kroky k optimalizaci",
    "landing.compress.redesign.s1Title": "Nahrajte obrázky",
    "landing.compress.redesign.s1Desc": "Přetáhněte své fotografie do kompresní pracovní oblasti.",
    "landing.compress.redesign.s2Title": "Nastavte úroveň komprese",
    "landing.compress.redesign.s2Desc": "Upravte posuvník kvality a najděte správnou rovnováhu mezi vizuální kvalitou a velikostí souboru.",
    "landing.compress.redesign.s3Title": "Ušetřete úložiště",
    "landing.compress.redesign.s3Desc": "Stáhněte si optimalizované obrázky a užijte si zmenšenou velikost souborů.",
    "landing.remove.redesign.heroBadge": "VÝŘEZ POHÁNĚNÝ AI",
    "landing.remove.redesign.heroTitle": "Odstraňte pozadí za 1 sekundu s bezchybnou přesností",
    "landing.remove.redesign.heroDesc": "Díky pokročilé WebAssembly AI získáte perfektní výřezy vlasů a hladké hrany, aniž byste kdy nahrávali fotky na server.",
    "landing.remove.redesign.feat1Badge": "99.8% PŘESNOST",
    "landing.remove.redesign.feat1Title": "Bezchybná detekce vlasů a hran",
    "landing.remove.redesign.feat1Desc": "Naše neuronová síť snadno zvládne složité detaily, jako jsou lidské vlasy, zvířecí srst a poloprůhledné objekty.",
    "landing.remove.redesign.feat2Badge": "100% BEZPEČNÉ",
    "landing.remove.redesign.feat2Title": "Úplné offline soukromí",
    "landing.remove.redesign.feat2Desc": "AI model se načte přímo do vašeho prohlížeče. Vaše obrázky nikdy neopustí počítač.",
    "landing.remove.redesign.feat3Badge": "DÁVKOVÝ REŽIM",
    "landing.remove.redesign.feat3Title": "Připraveno na hromadné zpracování",
    "landing.remove.redesign.feat3Desc": "Přetáhněte až 10 fotografií najednou. Zpracujte je současně a stáhněte vše v úhledném ZIP souboru.",
    "landing.remove.redesign.whoTag": "PRO KOHO TO JE",
    "landing.remove.redesign.whoTitle": "Ideální pro každou kreativní potřebu",
    "landing.remove.redesign.whoDesc": "Ať už prodáváte auta, navrhujete plakáty nebo vytváříte oficiální dokumenty.",
    "landing.remove.redesign.who1Title": "Prodejci v e-commerce",
    "landing.remove.redesign.who1Desc": "Vytvořte čisté bílé pozadí pro výpisy produktů.",
    "landing.remove.redesign.who1Tags": "VÝPISY PRODUKTŮ",
    "landing.remove.redesign.who2Title": "Grafičtí designéři",
    "landing.remove.redesign.who2Desc": "Extrahujte loga, podpisy a aktiva okamžitě.",
    "landing.remove.redesign.who2Tags": "DESIGNOVÁ AKTIVA",
    "landing.remove.redesign.stepsTag": "JAK TO FUNGUJE",
    "landing.remove.redesign.stepsTitle": "3 kroky k průhlednému pozadí",
    "landing.remove.redesign.s1Title": "Nahrát obrázek",
    "landing.remove.redesign.s1Desc": "Přetáhněte svou fotku. PNG, JPG nebo WEBP.",
    "landing.remove.redesign.s2Title": "AI zpracování",
    "landing.remove.redesign.s2Desc": "Lokální WASM AI detekuje hlavní předmět za 1 sekundu.",
    "landing.remove.redesign.s3Title": "Stáhnout HD",
    "landing.remove.redesign.s3Desc": "Exportujte svou oříznutou fotku s průhledným pozadím.",
    "home.why.tag": "PROČ HELPMYIMG",
    "home.why.title": "Proč je HelpMyIMG nejchytřejší volbou pro tvůrce a firmy",
    "home.why.desc": "Navrženo od základu pro maximální soukromí, bleskovou rychlost a nulové náklady.",
    "home.why.c1.t": "Okamžitá lokální rychlost",
    "home.why.c1.d": "Vaše fotky se zpracovávají přímo v paměti zařízení s nulovým zpožděním.",
    "home.why.c1.b": "0ms Zpoždění serveru",
    "home.why.c2.t": "100% Absolutní soukromí",
    "home.why.c2.d": "Vaše osobní portréty, důvěrné dokumenty a produktové fotografie nikdy neopustí váš počítač.",
    "home.why.c2.b": "Žádné cloudové úložiště",
    "home.why.c3.t": "Navždy zdarma a neomezeně",
    "home.why.c3.d": "Žádné předplatné, žádné vodoznaky. Úpravy fotografií ve vysokém rozlišení přístupné všem.",
    "home.why.c3.b": "$0 / Doživotně",
    "home.why.c4.t": "Dávkový výkon až 10",
    "home.why.c4.d": "Přetáhněte až 10 fotek současně a exportujte celé focení jako ZIP archiv v sekundách.",
    "home.why.c4.b": "10x Rychlost práce",
    "home.steps.tag": "JAK TO FUNGUJE",
    "home.steps.title": "Jak HelpMyIMG funguje ve 3 jednoduchých krocích",
    "home.steps.desc": "Není nutná instalace softwaru. Získejte profesionální výsledky přímo z vašeho prohlížeče."
  },
  da: {
    "landing.compress.redesign.heroBadge": "SMART KOMPRESSION",
    "landing.compress.redesign.heroTitle": "Krymp billedfilstørrelsen med op til 90% øjeblikkeligt",
    "landing.compress.redesign.heroDesc": "Reducer størrelsen på dine fotos uden at miste visuel kvalitet. Perfekt til hjemmesider og e-mails.",
    "landing.compress.redesign.feat1Badge": "INGEN KVALITETSTAB",
    "landing.compress.redesign.feat1Title": "Smart optimering",
    "landing.compress.redesign.feat1Desc": "Finder automatisk den perfekte balance mellem minimal filstørrelse og maksimal billedkvalitet.",
    "landing.compress.redesign.feat2Badge": "100% PRIVAT",
    "landing.compress.redesign.feat2Title": "Nul uploads",
    "landing.compress.redesign.feat2Desc": "Som med alle vores værktøjer sker komprimeringen direkte i din browser. Intet går til nogen server.",
    "landing.compress.redesign.feat3Badge": "ETHVERT FORMAT",
    "landing.compress.redesign.feat3Title": "Bred support",
    "landing.compress.redesign.feat3Desc": "Fungerer med standard JPG og PNG-formater samt moderne WEBP-formater.",
    "landing.compress.redesign.whoTag": "HVEM ER DET TIL",
    "landing.compress.redesign.whoTitle": "Bygget til Web & Medier",
    "landing.compress.redesign.whoDesc": "Perfekt til udviklere, designere og sociale mediechefer, der har brug for optimerede billeder.",
    "landing.compress.redesign.who1Title": "Webudviklere",
    "landing.compress.redesign.who1Desc": "Forbedr PageSpeed-scoren og reducer indlæsningstider uden at ofre billedkvaliteten.",
    "landing.compress.redesign.who1Tags": "SEO OPTIMERING",
    "landing.compress.redesign.who2Title": "Indholdsskabere",
    "landing.compress.redesign.who2Desc": "Opfyld strenge grænser for uploadstørrelser for platforme som Discord eller Twitter.",
    "landing.compress.redesign.who2Tags": "SOCIALE MEDIER",
    "landing.compress.redesign.stepsTag": "SÅDAN FUNGERER DET",
    "landing.compress.redesign.stepsTitle": "3 trin til optimering",
    "landing.compress.redesign.s1Title": "Upload billeder",
    "landing.compress.redesign.s1Desc": "Træk og slip dine fotos i komprimeringsarbejdsområdet.",
    "landing.compress.redesign.s2Title": "Indstil komprimeringsniveau",
    "landing.compress.redesign.s2Desc": "Juster kvalitetskyderen for at finde den rette balance.",
    "landing.compress.redesign.s3Title": "Spar lagerplads",
    "landing.compress.redesign.s3Desc": "Download dine optimerede billeder og nyd reducerede filstørrelser.",
    "landing.remove.redesign.heroBadge": "AI-DREVET UDSKÆRING",
    "landing.remove.redesign.heroTitle": "Fjern baggrund på 1 sekund med fejlfri præcision",
    "landing.remove.redesign.heroDesc": "Drivet af avanceret WebAssembly AI, få perfekte hårbeskæringer og glatte kanter uden nogensinde at uploade til en server.",
    "landing.remove.redesign.feat1Badge": "99.8% NØJAGTIGHED",
    "landing.remove.redesign.feat1Title": "Fejlfri hår- og kantdetektering",
    "landing.remove.redesign.feat1Desc": "Vores neurale netværk håndterer nemt komplekse detaljer som menneskehår, dyrepels og gennemsigtige objekter.",
    "landing.remove.redesign.feat2Badge": "100% SIKKER",
    "landing.remove.redesign.feat2Title": "Komplet offline privatliv",
    "landing.remove.redesign.feat2Desc": "AI-modellen indlæses direkte i din browser. Dine billeder forlader aldrig din computer.",
    "landing.remove.redesign.feat3Badge": "BATCH TILSTAND",
    "landing.remove.redesign.feat3Title": "Klar til massebehandling",
    "landing.remove.redesign.feat3Desc": "Træk og slip op til 10 billeder ad gangen og download alt i en ZIP-fil.",
    "landing.remove.redesign.whoTag": "HVEM ER DET TIL",
    "landing.remove.redesign.whoTitle": "Perfekt til alle kreative behov",
    "landing.remove.redesign.whoDesc": "Uanset om du sælger biler, designer plakater eller opretter officielle dokumenter.",
    "landing.remove.redesign.who1Title": "E-handel Sælgere",
    "landing.remove.redesign.who1Desc": "Opret rene hvide baggrunde for produktopslag.",
    "landing.remove.redesign.who1Tags": "PRODUKTOPSLAG",
    "landing.remove.redesign.who2Title": "Grafiske Designere",
    "landing.remove.redesign.who2Desc": "Uddrag logoer, signaturer og aktiver øjeblikkeligt.",
    "landing.remove.redesign.who2Tags": "DESIGNAKTIVER",
    "landing.remove.redesign.stepsTag": "SÅDAN FUNGERER DET",
    "landing.remove.redesign.stepsTitle": "3 trin til gennemsigtig baggrund",
    "landing.remove.redesign.s1Title": "Upload billede",
    "landing.remove.redesign.s1Desc": "Træk og slip dit foto. PNG, JPG eller WEBP.",
    "landing.remove.redesign.s2Title": "AI-behandling",
    "landing.remove.redesign.s2Desc": "Den lokale WASM AI opdager hovedemnet på 1 sekund.",
    "landing.remove.redesign.s3Title": "Download HD",
    "landing.remove.redesign.s3Desc": "Eksporter dit udskårne billede med gennemsigtig baggrund.",
    "home.why.tag": "HVORFOR HELPMYIMG",
    "home.why.title": "Hvorfor HelpMyIMG er det smarteste valg for skabere og virksomheder",
    "home.why.desc": "Designet fra bunden for maksimalt privatliv, lynhurtig hastighed og nul omkostninger.",
    "home.why.c1.t": "Øjeblikkelig lokal hastighed",
    "home.why.c1.d": "Dine fotos behandles direkte i enhedens hukommelse uden forsinkelse.",
    "home.why.c1.b": "0ms Serverforsinkelse",
    "home.why.c2.t": "100% Absolut privatliv",
    "home.why.c2.d": "Dine portrætter og fortrolige dokumenter forlader aldrig din computer.",
    "home.why.c2.b": "Nul cloud lagring",
    "home.why.c3.t": "For evigt gratis & ubegrænset",
    "home.why.c3.d": "Ingen abonnementer, ingen vandmærker. Fotoredigering i HD tilgængelig for alle.",
    "home.why.c3.b": "$0 / Livstid",
    "home.why.c4.t": "Batch power op til 10",
    "home.why.c4.d": "Træk og slip op til 10 billeder samtidigt, og eksporter som et ZIP-arkiv på få sekunder.",
    "home.why.c4.b": "10x Arbejdshastighed",
    "home.steps.tag": "SÅDAN FUNGERER DET",
    "home.steps.title": "Sådan fungerer HelpMyIMG i 3 enkle trin",
    "home.steps.desc": "Ingen softwareinstallation nødvendig. Få professionelle resultater direkte fra din webbrowser."
  },
  el: {
    "landing.compress.redesign.heroBadge": "ΕΞΥΠΝΗ ΣΥΜΠΙΕΣΗ",
    "landing.compress.redesign.heroTitle": "Μειώστε το μέγεθος αρχείου εικόνας έως και 90% άμεσα",
    "landing.compress.redesign.heroDesc": "Μειώστε το μέγεθος των φωτογραφιών σας χωρίς απώλεια ποιότητας. Τέλειο για ιστοσελίδες και email.",
    "landing.compress.redesign.feat1Badge": "ΚΑΜΙΑ ΑΠΩΛΕΙΑ ΠΟΙΟΤΗΤΑΣ",
    "landing.compress.redesign.feat1Title": "Έξυπνη βελτιστοποίηση",
    "landing.compress.redesign.feat1Desc": "Βρίσκει αυτόματα την τέλεια ισορροπία μεταξύ ελάχιστου μεγέθους αρχείου και μέγιστης ποιότητας εικόνας.",
    "landing.compress.redesign.feat2Badge": "100% ΙΔΙΩΤΙΚΟ",
    "landing.compress.redesign.feat2Title": "Μηδενικές μεταφορτώσεις",
    "landing.compress.redesign.feat2Desc": "Όπως όλα τα εργαλεία μας, η συμπίεση γίνεται απευθείας στο πρόγραμμα περιήγησής σας. Τίποτα δεν πάει σε κανέναν διακομιστή.",
    "landing.compress.redesign.feat3Badge": "ΟΠΟΙΑΔΗΠΟΤΕ ΜΟΡΦΗ",
    "landing.compress.redesign.feat3Title": "Ευρεία Υποστήριξη",
    "landing.compress.redesign.feat3Desc": "Λειτουργεί με τυπικές μορφές JPG και PNG, καθώς και με σύγχρονες μορφές WEBP.",
    "landing.compress.redesign.whoTag": "ΓΙΑ ΠΟΙΟΝ ΕΙΝΑΙ",
    "landing.compress.redesign.whoTitle": "Φτιαγμένο για Web & Media",
    "landing.compress.redesign.whoDesc": "Τέλειο για προγραμματιστές, σχεδιαστές και διαχειριστές κοινωνικών δικτύων.",
    "landing.compress.redesign.who1Title": "Προγραμματιστές Web",
    "landing.compress.redesign.who1Desc": "Βελτιώστε τις βαθμολογίες PageSpeed και μειώστε τους χρόνους φόρτωσης.",
    "landing.compress.redesign.who1Tags": "ΒΕΛΤΙΣΤΟΠΟΙΗΣΗ SEO",
    "landing.compress.redesign.who2Title": "Δημιουργοί περιεχομένου",
    "landing.compress.redesign.who2Desc": "Ικανοποιήστε τα αυστηρά όρια μεγέθους μεταφόρτωσης για πλατφόρμες όπως το Discord.",
    "landing.compress.redesign.who2Tags": "ΚΟΙΝΩΝΙΚΑ ΔΙΚΤΥΑ",
    "landing.compress.redesign.stepsTag": "ΠΩΣ ΛΕΙΤΟΥΡΓΕΙ",
    "landing.compress.redesign.stepsTitle": "3 βήματα για βελτιστοποίηση",
    "landing.compress.redesign.s1Title": "Ανεβάστε εικόνες",
    "landing.compress.redesign.s1Desc": "Σύρετε και αποθέστε τις φωτογραφίες σας στον χώρο εργασίας συμπίεσης.",
    "landing.compress.redesign.s2Title": "Ορίστε Επίπεδο Συμπίεσης",
    "landing.compress.redesign.s2Desc": "Προσαρμόστε το ρυθμιστικό ποιότητας για να βρείτε τη σωστή ισορροπία.",
    "landing.compress.redesign.s3Title": "Εξοικονομήστε αποθηκευτικό χώρο",
    "landing.compress.redesign.s3Desc": "Κατεβάστε τις βελτιστοποιημένες εικόνες σας και απολαύστε μειωμένα μεγέθη αρχείων.",
    "landing.remove.redesign.heroBadge": "ΑΠΟΚΟΠΗ ΜΕ AI",
    "landing.remove.redesign.heroTitle": "Αφαιρέστε το φόντο σε 1 δευτερόλεπτο με άψογη ακρίβεια",
    "landing.remove.redesign.heroDesc": "Με την προηγμένη WebAssembly AI, αποκτήστε τέλειες αποκοπές μαλλιών χωρίς ποτέ να μεταφορτώσετε τις φωτογραφίες σας σε διακομιστή.",
    "landing.remove.redesign.feat1Badge": "99.8% ΑΚΡΙΒΕΙΑ",
    "landing.remove.redesign.feat1Title": "Άψογη ανίχνευση μαλλιών και άκρων",
    "landing.remove.redesign.feat1Desc": "Το νευρωνικό μας δίκτυο χειρίζεται εύκολα περίπλοκες λεπτομέρειες όπως ανθρώπινα μαλλιά.",
    "landing.remove.redesign.feat2Badge": "100% ΑΣΦΑΛΕΣ",
    "landing.remove.redesign.feat2Title": "Πλήρες απόρρητο εκτός σύνδεσης",
    "landing.remove.redesign.feat2Desc": "Το μοντέλο AI φορτώνεται απευθείας στο πρόγραμμα περιήγησής σας. Οι εικόνες δεν αφήνουν ποτέ τον υπολογιστή σας.",
    "landing.remove.redesign.feat3Badge": "ΜΑΖΙΚΗ ΛΕΙΤΟΥΡΓΙΑ",
    "landing.remove.redesign.feat3Title": "Έτοιμο για μαζική επεξεργασία",
    "landing.remove.redesign.feat3Desc": "Σύρετε και αποθέστε έως και 10 φωτογραφίες ταυτόχρονα και κατεβάστε τα πάντα σε ένα αρχείο ZIP.",
    "landing.remove.redesign.whoTag": "ΓΙΑ ΠΟΙΟΝ ΕΙΝΑΙ",
    "landing.remove.redesign.whoTitle": "Ιδανικό για κάθε δημιουργική ανάγκη",
    "landing.remove.redesign.whoDesc": "Είτε πουλάτε αυτοκίνητα, είτε σχεδιάζετε αφίσες, είτε δημιουργείτε επίσημα έγγραφα.",
    "landing.remove.redesign.who1Title": "Πωλητές ηλεκτρονικού εμπορίου",
    "landing.remove.redesign.who1Desc": "Δημιουργήστε καθαρά λευκά φόντα για καταχωρίσεις προϊόντων.",
    "landing.remove.redesign.who1Tags": "ΚΑΤΑΧΩΡΙΣΕΙΣ ΠΡΟΪΟΝΤΩΝ",
    "landing.remove.redesign.who2Title": "Γραφίστες",
    "landing.remove.redesign.who2Desc": "Εξαγάγετε λογότυπα και υπογραφές άμεσα.",
    "landing.remove.redesign.who2Tags": "ΣΤΟΙΧΕΙΑ ΣΧΕΔΙΑΣΜΟΥ",
    "landing.remove.redesign.stepsTag": "ΠΩΣ ΛΕΙΤΟΥΡΓΕΙ",
    "landing.remove.redesign.stepsTitle": "3 Βήματα για Διαφανή Φόντα",
    "landing.remove.redesign.s1Title": "Ανεβάστε Εικόνα",
    "landing.remove.redesign.s1Desc": "Σύρετε και αποθέστε τη φωτογραφία σας. PNG, JPG ή WEBP.",
    "landing.remove.redesign.s2Title": "Επεξεργασία AI",
    "landing.remove.redesign.s2Desc": "Το τοπικό WASM AI ανιχνεύει το κύριο θέμα σε 1 δευτερόλεπτο.",
    "landing.remove.redesign.s3Title": "Λήψη HD",
    "landing.remove.redesign.s3Desc": "Εξαγάγετε την κομμένη φωτογραφία σας με διαφανές φόντο.",
    "home.why.tag": "ΓΙΑΤΙ HELPMYIMG",
    "home.why.title": "Γιατί το HelpMyIMG είναι η πιο έξυπνη επιλογή για δημιουργούς και επιχειρήσεις",
    "home.why.desc": "Σχεδιασμένο από το μηδέν για μέγιστο απόρρητο, αστραπιαία ταχύτητα και μηδενικό κόστος.",
    "home.why.c1.t": "Άμεση Τοπική Ταχύτητα",
    "home.why.c1.d": "Οι φωτογραφίες σας υποβάλλονται σε επεξεργασία απευθείας στη μνήμη της συσκευής σας με μηδενική καθυστέρηση.",
    "home.why.c1.b": "0ms Καθυστέρηση",
    "home.why.c2.t": "100% Απόλυτο Απόρρητο",
    "home.why.c2.d": "Τα προσωπικά σας πορτρέτα και τα εμπιστευτικά σας έγγραφα δεν αφήνουν ποτέ τον υπολογιστή σας.",
    "home.why.c2.b": "Μηδενικό Cloud",
    "home.why.c3.t": "Για Πάντα Δωρεάν",
    "home.why.c3.d": "Χωρίς συνδρομές, χωρίς υδατογραφήματα, χωρίς κρυφές χρεώσεις.",
    "home.why.c3.b": "$0 / Εφ' όρου ζωής",
    "home.why.c4.t": "Μαζική Ισχύς έως 10",
    "home.why.c4.d": "Σύρετε έως και 10 φωτογραφίες ταυτόχρονα και εξαγάγετε ως αρχείο ZIP σε δευτερόλεπτα.",
    "home.why.c4.b": "10x Ταχύτητα ροής εργασίας",
    "home.steps.tag": "ΠΩΣ ΛΕΙΤΟΥΡΓΕΙ",
    "home.steps.title": "Πώς λειτουργεί το HelpMyIMG σε 3 απλά βήματα",
    "home.steps.desc": "Δεν απαιτείται εγκατάσταση λογισμικού. Αποκτήστε επαγγελματικά αποτελέσματα απευθείας από το πρόγραμμα περιήγησής σας."
  },
  fi: {
    "landing.compress.redesign.heroBadge": "ÄLYKÄS PAKKAUS",
    "landing.compress.redesign.heroTitle": "Kutista kuvatiedoston kokoa jopa 90 % välittömästi",
    "landing.compress.redesign.heroDesc": "Pienennä valokuviesi kokoa menettämättä visuaalista laatua. Täydellinen verkkosivustoille ja sähköposteihin.",
    "landing.compress.redesign.feat1Badge": "EI LAADUN HEIKENTYMISTÄ",
    "landing.compress.redesign.feat1Title": "Älykäs optimointi",
    "landing.compress.redesign.feat1Desc": "Löytää automaattisesti täydellisen tasapainon minimaalisen tiedostokoon ja maksimaalisen kuvanlaadun välillä.",
    "landing.compress.redesign.feat2Badge": "100 % YKSITYINEN",
    "landing.compress.redesign.feat2Title": "Nolla latausta",
    "landing.compress.redesign.feat2Desc": "Kuten kaikki työkalumme, pakkaus tapahtuu suoraan selaimessasi. Mitään ei mene millekään palvelimelle.",
    "landing.compress.redesign.feat3Badge": "MIKÄ TAHANSA MUOTO",
    "landing.compress.redesign.feat3Title": "Laaja tuki",
    "landing.compress.redesign.feat3Desc": "Toimii vakio-JPG- ja PNG-muotojen sekä nykyaikaisten erittäin tehokkaiden WEBP-muotojen kanssa.",
    "landing.compress.redesign.whoTag": "KENELLE SE ON TARKOITETTU",
    "landing.compress.redesign.whoTitle": "Rakennettu verkkoon ja mediaan",
    "landing.compress.redesign.whoDesc": "Täydellinen kehittäjille, suunnittelijoille ja sosiaalisen median ylläpitäjille.",
    "landing.compress.redesign.who1Title": "Verkkokehittäjät",
    "landing.compress.redesign.who1Desc": "Paranna PageSpeed-tuloksia ja lyhennä latausaikoja uhraamatta kuvanlaatua.",
    "landing.compress.redesign.who1Tags": "SEO OPTIMOINTI",
    "landing.compress.redesign.who2Title": "Sisällöntuottajat",
    "landing.compress.redesign.who2Desc": "Täytä tiukat latauskoon rajoitukset alustoilla, kuten Discord, Twitter.",
    "landing.compress.redesign.who2Tags": "SOSIAALINEN MEDIA",
    "landing.compress.redesign.stepsTag": "KUINKA SE TOIMII",
    "landing.compress.redesign.stepsTitle": "3 askelta optimointiin",
    "landing.compress.redesign.s1Title": "Lataa kuvia",
    "landing.compress.redesign.s1Desc": "Vedä ja pudota valokuvasi pakkaustyötilaan.",
    "landing.compress.redesign.s2Title": "Aseta pakkaustaso",
    "landing.compress.redesign.s2Desc": "Säädä laadun liukusäädintä löytääksesi oikean tasapainon.",
    "landing.compress.redesign.s3Title": "Säästä tallennustilaa",
    "landing.compress.redesign.s3Desc": "Lataa optimoidut kuvasi ja nauti pienemmistä tiedostokoista.",
    "landing.remove.redesign.heroBadge": "TEKOÄLYN OHJAAMA LEIKKAUS",
    "landing.remove.redesign.heroTitle": "Poista tausta 1 sekunnissa virheettömällä tarkkuudella",
    "landing.remove.redesign.heroDesc": "Edistyneen WebAssembly AI:n avulla saat täydelliset hiusleikkaukset ja sileät reunat lataamatta valokuviasi koskaan palvelimelle.",
    "landing.remove.redesign.feat1Badge": "99,8 % TARKKUUS",
    "landing.remove.redesign.feat1Title": "Virheetön hiusten ja reunojen tunnistus",
    "landing.remove.redesign.feat1Desc": "Neuroverkkomme käsittelee helposti monimutkaisia ​​yksityiskohtia, kuten ihmisten hiuksia.",
    "landing.remove.redesign.feat2Badge": "100 % TURVALLINEN",
    "landing.remove.redesign.feat2Title": "Täydellinen offline-yksityisyys",
    "landing.remove.redesign.feat2Desc": "Tekoälymalli latautuu suoraan selaimeesi. Kuvasi eivät koskaan poistu tietokoneeltasi.",
    "landing.remove.redesign.feat3Badge": "ERÄTILA",
    "landing.remove.redesign.feat3Title": "Valmiina joukkokäsittelyyn",
    "landing.remove.redesign.feat3Desc": "Vedä ja pudota jopa 10 valokuvaa kerralla ja lataa kaikki yhdessä ZIP-tiedostossa.",
    "landing.remove.redesign.whoTag": "KENELLE SE ON TARKOITETTU",
    "landing.remove.redesign.whoTitle": "Täydellinen kaikkiin luoviin tarpeisiin",
    "landing.remove.redesign.whoDesc": "Myitpä sitten autoja, suunnittelet julisteita tai luot virallisia asiakirjoja.",
    "landing.remove.redesign.who1Title": "Verkkokaupan myyjät",
    "landing.remove.redesign.who1Desc": "Luo puhtaat valkoiset taustat tuotelistauksille.",
    "landing.remove.redesign.who1Tags": "TUOTELISTAT",
    "landing.remove.redesign.who2Title": "Graafiset suunnittelijat",
    "landing.remove.redesign.who2Desc": "Pura logot, allekirjoitukset ja omaisuus välittömästi.",
    "landing.remove.redesign.who2Tags": "SUUNNITTELUOMAISUUS",
    "landing.remove.redesign.stepsTag": "KUINKA SE TOIMII",
    "landing.remove.redesign.stepsTitle": "3 vaihetta läpinäkyviin taustoihin",
    "landing.remove.redesign.s1Title": "Lataa kuva",
    "landing.remove.redesign.s1Desc": "Vedä ja pudota valokuvasi. PNG, JPG tai WEBP.",
    "landing.remove.redesign.s2Title": "Tekoälyn käsittely",
    "landing.remove.redesign.s2Desc": "Paikallinen WASM AI havaitsee pääkohteen 1 sekunnissa.",
    "landing.remove.redesign.s3Title": "Lataa HD",
    "landing.remove.redesign.s3Desc": "Vie leikattu valokuvasi läpinäkyvällä taustalla.",
    "home.why.tag": "MIKSI HELPMYIMG",
    "home.why.title": "Miksi HelpMyIMG on älykkäin valinta sisällöntuottajille ja yrityksille",
    "home.why.desc": "Suunniteltu alusta alkaen maksimaalista yksityisyyttä, huimaa nopeutta ja nollakustannuksia varten.",
    "home.why.c1.t": "Välitön paikallinen nopeus",
    "home.why.c1.d": "Kuvasi käsitellään suoraan laitteen muistissa ilman viivettä.",
    "home.why.c1.b": "0ms Palvelimen viive",
    "home.why.c2.t": "100 % Absoluuttinen yksityisyys",
    "home.why.c2.d": "Henkilökohtaiset muotokuvasi ja luottamukselliset asiakirjasi eivät koskaan poistu tietokoneeltasi.",
    "home.why.c2.b": "Nolla pilvitallennustilaa",
    "home.why.c3.t": "Ikuisesti ilmainen ja rajoittamaton",
    "home.why.c3.d": "Ei tilauksia, ei vesileimoja. Teräväpiirtoinen kuvankäsittely kaikkien saatavilla.",
    "home.why.c3.b": "$0 / Elinikä",
    "home.why.c4.t": "Erävoima jopa 10",
    "home.why.c4.d": "Vedä ja pudota jopa 10 valokuvaa samanaikaisesti ja vie ZIP-arkistona sekunneissa.",
    "home.why.c4.b": "10x Työnkulun nopeus",
    "home.steps.tag": "KUINKA SE TOIMII",
    "home.steps.title": "Kuinka HelpMyIMG toimii kolmessa yksinkertaisessa vaiheessa",
    "home.steps.desc": "Ohjelmiston asennusta ei vaadita. Hanki ammattimaisia tuloksia suoraan selaimestasi."
  },
  it: {
    "landing.compress.redesign.heroBadge": "COMPRESSIONE INTELLIGENTE",
    "landing.compress.redesign.heroTitle": "Riduci le dimensioni del file immagine fino al 90% istantaneamente",
    "landing.compress.redesign.heroDesc": "Riduci le dimensioni delle tue foto senza perdere qualità visiva. Perfetto per siti web ed e-mail.",
    "landing.compress.redesign.feat1Badge": "NESSUNA PERDITA DI QUALITÀ",
    "landing.compress.redesign.feat1Title": "Ottimizzazione intelligente",
    "landing.compress.redesign.feat1Desc": "Trova automaticamente l'equilibrio perfetto tra dimensione minima del file e massima qualità dell'immagine.",
    "landing.compress.redesign.feat2Badge": "100% PRIVATO",
    "landing.compress.redesign.feat2Title": "Zero caricamenti",
    "landing.compress.redesign.feat2Desc": "Come per tutti i nostri strumenti, la compressione avviene direttamente nel tuo browser. Nessun file viene inviato ai server.",
    "landing.compress.redesign.feat3Badge": "QUALSIASI FORMATO",
    "landing.compress.redesign.feat3Title": "Ampio supporto",
    "landing.compress.redesign.feat3Desc": "Funziona con i formati standard JPG e PNG, nonché con i moderni formati ultra-efficienti WEBP.",
    "landing.compress.redesign.whoTag": "PER CHI È",
    "landing.compress.redesign.whoTitle": "Costruito per Web e Media",
    "landing.compress.redesign.whoDesc": "Perfetto per sviluppatori, designer e social media manager che necessitano di immagini altamente ottimizzate.",
    "landing.compress.redesign.who1Title": "Sviluppatori Web",
    "landing.compress.redesign.who1Desc": "Migliora i punteggi PageSpeed e riduci i tempi di caricamento senza sacrificare la qualità delle immagini.",
    "landing.compress.redesign.who1Tags": "OTTIMIZZAZIONE SEO",
    "landing.compress.redesign.who2Title": "Creatori di contenuti",
    "landing.compress.redesign.who2Desc": "Soddisfa i rigorosi limiti di dimensione di caricamento per piattaforme come Discord o Twitter.",
    "landing.compress.redesign.who2Tags": "SOCIAL MEDIA",
    "landing.compress.redesign.stepsTag": "COME FUNZIONA",
    "landing.compress.redesign.stepsTitle": "3 passaggi per l'ottimizzazione",
    "landing.compress.redesign.s1Title": "Carica Immagini",
    "landing.compress.redesign.s1Desc": "Trascina e rilascia le tue foto nello spazio di lavoro della compressione.",
    "landing.compress.redesign.s2Title": "Imposta Livello Compressione",
    "landing.compress.redesign.s2Desc": "Regola il cursore della qualità per trovare il giusto equilibrio.",
    "landing.compress.redesign.s3Title": "Risparmia Spazio",
    "landing.compress.redesign.s3Desc": "Scarica le tue immagini ottimizzate e goditi dimensioni dei file ridotte.",
    "landing.remove.redesign.heroBadge": "RITAGLIO BASATO SU AI",
    "landing.remove.redesign.heroTitle": "Rimuovi lo sfondo in 1 secondo con precisione impeccabile",
    "landing.remove.redesign.heroDesc": "Basato su un'avanzata intelligenza artificiale WebAssembly, ottieni ritagli perfetti e bordi lisci senza mai caricare le tue foto su un server.",
    "landing.remove.redesign.feat1Badge": "PRECISIONE DEL 99.8%",
    "landing.remove.redesign.feat1Title": "Rilevamento impeccabile",
    "landing.remove.redesign.feat1Desc": "La nostra rete neurale gestisce facilmente dettagli complessi come capelli, pelliccia di animali e oggetti semitrasparenti.",
    "landing.remove.redesign.feat2Badge": "100% SICURO",
    "landing.remove.redesign.feat2Title": "Privacy offline completa",
    "landing.remove.redesign.feat2Desc": "Il modello AI viene caricato direttamente nel tuo browser. Le tue immagini non lasciano mai il computer.",
    "landing.remove.redesign.feat3Badge": "MODALITÀ BATCH",
    "landing.remove.redesign.feat3Title": "Pronto per elaborazione di massa",
    "landing.remove.redesign.feat3Desc": "Trascina e rilascia fino a 10 foto contemporaneamente e scarica tutto in un file ZIP.",
    "landing.remove.redesign.whoTag": "PER CHI È",
    "landing.remove.redesign.whoTitle": "Perfetto per ogni esigenza creativa",
    "landing.remove.redesign.whoDesc": "Che tu venda auto, progetti poster o crei documenti ufficiali.",
    "landing.remove.redesign.who1Title": "Venditori E-Commerce",
    "landing.remove.redesign.who1Desc": "Crea sfondi bianchi puliti per le inserzioni dei prodotti.",
    "landing.remove.redesign.who1Tags": "INSERZIONI PRODOTTI",
    "landing.remove.redesign.who2Title": "Grafici",
    "landing.remove.redesign.who2Desc": "Estrai loghi, firme e risorse istantaneamente.",
    "landing.remove.redesign.who2Tags": "RISORSE DI DESIGN",
    "landing.remove.redesign.stepsTag": "COME FUNZIONA",
    "landing.remove.redesign.stepsTitle": "3 Passaggi per Sfondi Trasparenti",
    "landing.remove.redesign.s1Title": "Carica Immagine",
    "landing.remove.redesign.s1Desc": "Trascina e rilascia la tua foto. PNG, JPG o WEBP.",
    "landing.remove.redesign.s2Title": "Elaborazione AI",
    "landing.remove.redesign.s2Desc": "L'IA locale rileva il soggetto principale in 1 secondo.",
    "landing.remove.redesign.s3Title": "Scarica HD",
    "landing.remove.redesign.s3Desc": "Esporta la tua foto ritagliata con uno sfondo trasparente.",
    "home.why.tag": "PERCHÉ HELPMYIMG",
    "home.why.title": "Perché HelpMyIMG è la scelta più intelligente per creatori e aziende",
    "home.why.desc": "Progettato per la massima privacy, velocità fulminea e zero costi.",
    "home.why.c1.t": "Velocità Locale Istantanea",
    "home.why.c1.d": "Le tue foto vengono elaborate direttamente nella memoria del tuo dispositivo con latenza zero.",
    "home.why.c1.b": "0ms Ritardo Server",
    "home.why.c2.t": "Privacy Assoluta 100%",
    "home.why.c2.d": "I tuoi ritratti personali e documenti riservati non lasciano mai il tuo computer.",
    "home.why.c2.b": "Zero Archiviazione Cloud",
    "home.why.c3.t": "Gratuito e Illimitato per Sempre",
    "home.why.c3.d": "Nessun abbonamento, nessuna filigrana. Fotoritocco ad alta definizione accessibile a tutti.",
    "home.why.c3.b": "$0 / A Vita",
    "home.why.c4.t": "Potenza Batch fino a 10",
    "home.why.c4.d": "Trascina fino a 10 foto contemporaneamente ed esporta come archivio ZIP in pochi secondi.",
    "home.why.c4.b": "10x Velocità di Lavoro",
    "home.steps.tag": "COME FUNZIONA",
    "home.steps.title": "Come funziona HelpMyIMG in 3 semplici passaggi",
    "home.steps.desc": "Nessuna installazione di software richiesta. Ottieni risultati professionali direttamente dal tuo browser web."
  }
};

const scriptDir = __dirname;
const localesDir = path.join(scriptDir, '../public/locales');

for (const [lang, kv] of Object.entries(translations)) {
  const filePath = path.join(localesDir, lang, 'translation.json');
  if (fs.existsSync(filePath)) {
    const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    for (const [key, val] of Object.entries(kv)) {
      data[key] = val;
    }
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
    console.log(`[${lang}] Injected translations chunk 1`);
  }
}
