const fs = require('fs');
const path = require('path');
const localesDir = path.join(__dirname, '../public/locales');

const translations = {
  ar: {
    design: {
      heroBadge: "جناح الإبداع",
      heroTitle: "صمم بصريات جميلة.",
      heroTitle2: "مباشرة في متصفحك.",
      heroDesc: "محرر صور كامل الميزات مع فلاتر احترافية، أدوات نصوص، أشكال، وقدرات رسم. لا يتطلب تثبيت أي برامج.",
      feat1Title: "طباعة غنية",
      feat1Desc: "أضف طبقات نصوص مخصصة واختر من مئات الخطوط وأضف الظلال والتدرجات.",
      feat2Title: "فلاتر احترافية",
      feat2Desc: "قم بتطبيق تعديلات الألوان السينمائية والاحترافية محلياً.",
      feat3Title: "أشكال متجهية",
      feat3Desc: "ارسم الأشكال الهندسية والأسهم والحدود بدقة.",
      feat4Title: "إدارة الطبقات",
      feat4Desc: "نظم تصميماتك بسهولة. قم بتجميع الطبقات وإخفائها وقفلها لإنشاء تركيبات معقدة.",
      stepsTag: "سير العمل",
      stepsTitle: "أنشئ في 3 خطوات",
      s1Title: "ابدأ القماش",
      s1Desc: "افتح لوحة قماشية فارغة أو استورد صورة.",
      s2Title: "صمم",
      s2Desc: "أضف النصوص والرسومات والفلاتر.",
      s3Title: "تصدير",
      s3Desc: "قم بتنزيل تحفتك النهائية."
    },
    rotate: {
      heroBadge: "التحكم المكاني",
      heroTitle: "تدوير وقلب.",
      heroTitle2: "اتجاه مثالي.",
      heroDesc: "قم بتصحيح الصور الجانبية، وإنشاء تأثيرات المرآة، وضبط دوران الصورة بدرجات دقيقة. سريع ومجاني.",
      feat1Title: "دوران 90 درجة سريع",
      feat1Desc: "أصلح الصور ذات الاتجاه الخاطئ على الفور. قم بالتدوير يساراً أو يميناً بزيادات 90 درجة.",
      feat2Title: "تأثيرات المرآة",
      feat2Desc: "اقلب الصور أفقياً لإصلاح صور السيلفي، أو عمودياً للتأثيرات الإبداعية.",
      feat3Title: "ضبط الأفق",
      feat3Desc: "هل لديك صورة أفقية مائلة؟ استخدم شريط التدوير الدقيق لتسوية الأفق.",
      stepsTag: "سير العمل",
      stepsTitle: "إعادة التوجيه في 3 خطوات",
      s1Title: "رفع",
      s1Desc: "أضف الصور التي تريد إصلاحها.",
      s2Title: "تعديل",
      s2Desc: "استخدم أزرار التدوير والقلب.",
      s3Title: "حفظ",
      s3Desc: "قم بتنزيل الصور المصححة."
    },
    picker: {
      heroBadge: "دقة البكسل",
      heroTitle: "استخراج ألوان مثالية.",
      heroTitle2: "أنشئ لوحات مذهلة.",
      heroDesc: "ارفع صورة واستخرج رموز HEX و RGB و HSL لأي بكسل. قم بإنشاء لوحات ألوان متناغمة على الفور.",
      feat1Title: "تفاصيل مجهرية",
      feat1Desc: "تسمح لك العدسة المكبرة المدمجة بالتكبير إلى وحدات البكسل الفردية.",
      feat2Title: "صيغ متعددة",
      feat2Desc: "احصل على ألوانك محولة فوراً إلى صيغ HEX و RGB و HSL. انقر للنسخ.",
      feat3Title: "إنشاء لوحات تلقائي",
      feat3Desc: "يقوم خوارزمية الذكاء الاصطناعي بتحليل صورتك وإنشاء لوحة ألوان متناغمة من 5 ألوان تلقائياً.",
      stepsTag: "سير العمل",
      stepsTitle: "استخراج في 3 خطوات",
      s1Title: "رفع",
      s1Desc: "قم بتحميل صورتك المرجعية.",
      s2Title: "التقاط",
      s2Desc: "مرر فوق أي بكسل وانقر لالتقاطه.",
      s3Title: "نسخ",
      s3Desc: "انسخ قيم HEX/RGB على الفور."
    }
  },
  cs: {
    design: {
      heroBadge: "KREATIVNÍ SADA",
      heroTitle: "Navrhujte krásné vizuály.",
      heroTitle2: "Přímo ve vašem prohlížeči.",
      heroDesc: "Plně vybavený editor obrázků s profesionálními filtry, texty, tvary a kreslením. Bez instalace softwaru.",
      feat1Title: "Bohatá typografie",
      feat1Desc: "Přidejte vlastní textové vrstvy, vyberte si ze stovek písem a přidejte stíny a přechody.",
      feat2Title: "Pro Filtry",
      feat2Desc: "Aplikujte filmové třídění barev a profesionální úpravy nativně.",
      feat3Title: "Vektorové tvary",
      feat3Desc: "Kreslete geometrické tvary, šipky a okraje s přesností.",
      feat4Title: "Správa vrstev",
      feat4Desc: "Uspořádejte své návrhy. Skládejte, seskupujte, skrývejte a zamykejte více vrstev.",
      stepsTag: "PRACOVNÍ POSTUP",
      stepsTitle: "Vytvořte ve 3 krocích",
      s1Title: "Začít",
      s1Desc: "Otevřete prázdné plátno nebo importujte fotku.",
      s2Title: "Navrhnout",
      s2Desc: "Přidejte text, grafiku a aplikujte filtry.",
      s3Title: "Exportovat",
      s3Desc: "Stáhněte si finální mistrovské dílo."
    },
    rotate: {
      heroBadge: "PROSTOROVÁ KONTROLA",
      heroTitle: "Otočte a překlopte.",
      heroTitle2: "Dokonalá orientace.",
      heroDesc: "Opravte fotografie, vytvořte zrcadlové efekty a dolaďte otáčení. Rychle, zdarma a ve vašem prohlížeči.",
      feat1Title: "Rychlé otočení o 90°",
      feat1Desc: "Opravte fotografie s nesprávnou orientací. Otočte doleva nebo doprava o 90 stupňů.",
      feat2Title: "Zrcadlové efekty",
      feat2Desc: "Překlopte obrázky vodorovně pro opravu selfie, nebo svisle pro kreativní odrazy.",
      feat3Title: "Doladění horizontu",
      feat3Desc: "Máte křivou fotku krajiny? Použijte přesný posuvník pro vyrovnání horizontu.",
      stepsTag: "PRACOVNÍ POSTUP",
      stepsTitle: "Přeorientujte ve 3 krocích",
      s1Title: "Nahrát",
      s1Desc: "Přidejte obrázky, které chcete opravit.",
      s2Title: "Upravit",
      s2Desc: "Použijte tlačítka pro otočení a překlopení.",
      s3Title: "Uložit",
      s3Desc: "Stáhněte si opravené obrázky."
    },
    picker: {
      heroBadge: "PIXELOVÁ PŘESNOST",
      heroTitle: "Extrahujte dokonalé barvy.",
      heroTitle2: "Sestavte úžasné palety.",
      heroDesc: "Nahrajte obrázek a najeďte myší pro získání kódů HEX, RGB a HSL jakéhokoli pixelu. Okamžitě vygenerujte palety.",
      feat1Title: "Mikroskopický detail",
      feat1Desc: "Zabudovaná lupa vám umožní přiblížit se k jednotlivým pixelům.",
      feat2Title: "Více formátů",
      feat2Desc: "Získejte své barvy převedené do formátů HEX, RGB a HSL. Kliknutím zkopírujte.",
      feat3Title: "Automatické palety",
      feat3Desc: "Náš algoritmus umělé inteligence analyzuje váš obrázek a automaticky vygeneruje paletu 5 barev.",
      stepsTag: "PRACOVNÍ POSTUP",
      stepsTitle: "Extrahujte ve 3 krocích",
      s1Title: "Nahrát",
      s1Desc: "Načtěte svůj referenční obrázek.",
      s2Title: "Vybrat",
      s2Desc: "Najeďte na libovolný pixel a klikněte.",
      s3Title: "Kopírovat",
      s3Desc: "Okamžitě zkopírujte hodnoty HEX/RGB."
    }
  },
  da: {
    design: {
      heroBadge: "KREATIV SUITE",
      heroTitle: "Design smukke visuelle elementer.",
      heroTitle2: "Direkte i din browser.",
      heroDesc: "En fuldt udstyret billedredigerer pakket med professionelle filtre, tekstværktøjer, former og tegnemuligheder. Ingen softwareinstallation kræves.",
      feat1Title: "Rig typografi",
      feat1Desc: "Tilføj brugerdefinerede tekstlag, vælg mellem hundredvis af skrifttyper, og style dem med skygger og gradienter.",
      feat2Title: "Pro-filtre",
      feat2Desc: "Anvend filmisk farvekorrigering og professionelle justeringer.",
      feat3Title: "Vektorformer",
      feat3Desc: "Tegn geometriske former, pile og kanter med præcision.",
      feat4Title: "Lagstyring",
      feat4Desc: "Organiser komplekse designs let. Stabl, gruppér, skjul og lås flere lag.",
      stepsTag: "ARBEJDSGANG",
      stepsTitle: "Opret i 3 trin",
      s1Title: "Start lærred",
      s1Desc: "Åbn et tomt lærred, eller importer et foto.",
      s2Title: "Design",
      s2Desc: "Tilføj tekst, grafik, og anvend filtre.",
      s3Title: "Eksporter",
      s3Desc: "Download dit endelige mesterværk."
    },
    rotate: {
      heroBadge: "RUMLIG KONTROL",
      heroTitle: "Roter og vend.",
      heroTitle2: "Perfekt orientering.",
      heroDesc: "Ret sidelæns billeder, opret spejleffekter, og finjuster billedrotation. Hurtigt, gratis og i din browser.",
      feat1Title: "Hurtige 90° sving",
      feat1Desc: "Ret fotos taget i den forkerte orientering med det samme. Roter i trin af 90 grader.",
      feat2Title: "Spejleffekter",
      feat2Desc: "Vend billeder vandret for at rette selfies, eller lodret for kreative refleksioner.",
      feat3Title: "Finjuster horisonten",
      feat3Desc: "Har du et skævt landskabsbillede? Brug skyderen til at udjævne horisonten.",
      stepsTag: "ARBEJDSGANG",
      stepsTitle: "Omorienter i 3 trin",
      s1Title: "Upload",
      s1Desc: "Tilføj de billeder, du vil rette.",
      s2Title: "Juster",
      s2Desc: "Brug rotations- og flip-knapperne.",
      s3Title: "Gem",
      s3Desc: "Download de korrigerede billeder."
    },
    picker: {
      heroBadge: "PIXEL-PRÆCISION",
      heroTitle: "Udtræk perfekte farver.",
      heroTitle2: "Byg fantastiske paletter.",
      heroDesc: "Upload et billede og hold musen over for at finde HEX, RGB og HSL koder. Generer farvepaletter øjeblikkeligt.",
      feat1Title: "Mikroskopiske detaljer",
      feat1Desc: "Den indbyggede lup lader dig zoome ned til individuelle pixels.",
      feat2Title: "Flere formater",
      feat2Desc: "Få dine farver konverteret til HEX, RGB og HSL formater. Klik for at kopiere.",
      feat3Title: "Generer paletter automatisk",
      feat3Desc: "Vores AI-algoritme analyserer dit billede og genererer automatisk en palet med 5 farver.",
      stepsTag: "ARBEJDSGANG",
      stepsTitle: "Udtræk i 3 trin",
      s1Title: "Upload",
      s1Desc: "Indlæs dit referencebillede.",
      s2Title: "Vælg",
      s2Desc: "Hold over enhver pixel og klik for at fange den.",
      s3Title: "Kopier",
      s3Desc: "Kopier HEX/RGB-værdierne øjeblikkeligt."
    }
  },
  de: {
    design: {
      heroBadge: "KREATIV-SUITE",
      heroTitle: "Entwerfe wunderschöne Visuals.",
      heroTitle2: "Direkt in deinem Browser.",
      heroDesc: "Ein voll ausgestatteter Bildeditor mit professionellen Filtern, Textwerkzeugen, Formen und Zeichenfunktionen. Keine Softwareinstallation erforderlich.",
      feat1Title: "Reiche Typografie",
      feat1Desc: "Füge benutzerdefinierte Textebenen hinzu, wähle aus Hunderten von Schriftarten und style sie mit Schatten und Verläufen.",
      feat2Title: "Profi-Filter",
      feat2Desc: "Wende kinoreife Farbkorrekturen und professionelle Anpassungen an.",
      feat3Title: "Vektorformen",
      feat3Desc: "Zeichne geometrische Formen, Pfeile und Ränder mit Präzision.",
      feat4Title: "Ebenenverwaltung",
      feat4Desc: "Organisiere komplexe Designs mühelos. Stapele, gruppiere, verstecke und sperre mehrere Ebenen.",
      stepsTag: "ARBEITSABLAUF",
      stepsTitle: "Erstellen in 3 Schritten",
      s1Title: "Leinwand starten",
      s1Desc: "Öffne eine leere Leinwand oder importiere ein Foto.",
      s2Title: "Designen",
      s2Desc: "Füge Text, Grafiken hinzu und wende Filter an.",
      s3Title: "Exportieren",
      s3Desc: "Lade dein fertiges Meisterwerk herunter."
    },
    rotate: {
      heroBadge: "RÄUMLICHE KONTROLLE",
      heroTitle: "Drehen und spiegeln.",
      heroTitle2: "Perfekte Ausrichtung.",
      heroDesc: "Korrigiere seitliche Fotos, erstelle Spiegeleffekte und feinjustiere die Bilddrehung um exakte Grade. Schnell und kostenlos.",
      feat1Title: "Schnelle 90°-Drehungen",
      feat1Desc: "Korrigiere sofort falsch ausgerichtete Fotos. Drehe sie in präzisen 90-Grad-Schritten.",
      feat2Title: "Spiegeleffekte",
      feat2Desc: "Spiegele Bilder horizontal für Selfies oder vertikal für kreative Reflexionseffekte.",
      feat3Title: "Horizont feinjustieren",
      feat3Desc: "Hast du ein schiefes Landschaftsfoto? Nutze den Schieberegler, um den Horizont auszugleichen.",
      stepsTag: "ARBEITSABLAUF",
      stepsTitle: "Neu ausrichten in 3 Schritten",
      s1Title: "Hochladen",
      s1Desc: "Füge die Bilder hinzu, die du reparieren möchtest.",
      s2Title: "Anpassen",
      s2Desc: "Nutze die Schaltflächen zum Drehen und Spiegeln.",
      s3Title: "Speichern",
      s3Desc: "Lade die korrigierten Bilder herunter."
    },
    picker: {
      heroBadge: "PIXELPRÄZISION",
      heroTitle: "Perfekte Farben extrahieren.",
      heroTitle2: "Baue atemberaubende Paletten.",
      heroDesc: "Lade ein Bild hoch und fahre mit der Maus darüber, um HEX, RGB und HSL-Codes zu ermitteln. Generiere sofort Farbpaletten.",
      feat1Title: "Mikroskopisches Detail",
      feat1Desc: "Mit der integrierten Lupe kannst du auf einzelne Pixel hineinzoomen.",
      feat2Title: "Mehrere Formate",
      feat2Desc: "Erhalte deine Farben sofort in HEX, RGB und HSL konvertiert. Klicke zum Kopieren.",
      feat3Title: "Paletten automatisch generieren",
      feat3Desc: "Unser KI-Algorithmus analysiert dein Bild und generiert automatisch eine 5-Farben-Palette.",
      stepsTag: "ARBEITSABLAUF",
      stepsTitle: "Extrahieren in 3 Schritten",
      s1Title: "Hochladen",
      s1Desc: "Lade dein Referenzbild hoch.",
      s2Title: "Auswählen",
      s2Desc: "Fahre über ein Pixel und klicke, um es zu erfassen.",
      s3Title: "Kopieren",
      s3Desc: "Kopiere die HEX/RGB-Werte sofort."
    }
  },
  el: {
    design: {
      heroBadge: "ΔΗΜΙΟΥΡΓΙΚΗ ΣΟΥΙΤΑ",
      heroTitle: "Σχεδιάστε όμορφα οπτικά.",
      heroTitle2: "Απευθείας στον browser σας.",
      heroDesc: "Ένας πλήρης επεξεργαστής εικόνας με επαγγελματικά φίλτρα, εργαλεία κειμένου, σχήματα και δυνατότητες σχεδίασης.",
      feat1Title: "Πλούσια Τυπογραφία",
      feat1Desc: "Προσθέστε προσαρμοσμένα στρώματα κειμένου, επιλέξτε από εκατοντάδες γραμματοσειρές.",
      feat2Title: "Επαγγελματικά Φίλτρα",
      feat2Desc: "Εφαρμόστε κινηματογραφικές διορθώσεις χρωμάτων.",
      feat3Title: "Διανυσματικά Σχήματα",
      feat3Desc: "Σχεδιάστε γεωμετρικά σχήματα, βέλη και περιγράμματα με ακρίβεια.",
      feat4Title: "Διαχείριση Στρωμάτων",
      feat4Desc: "Οργανώστε πολύπλοκα σχέδια χωρίς κόπο. Στοίβαξη, ομαδοποίηση, απόκρυψη και κλείδωμα.",
      stepsTag: "ΡΟΗ ΕΡΓΑΣΙΑΣ",
      stepsTitle: "Δημιουργήστε σε 3 Βήματα",
      s1Title: "Έναρξη",
      s1Desc: "Ανοίξτε έναν κενό καμβά ή εισαγάγετε μια φωτογραφία.",
      s2Title: "Σχεδίαση",
      s2Desc: "Προσθέστε κείμενο, γραφικά και φίλτρα.",
      s3Title: "Εξαγωγή",
      s3Desc: "Κατεβάστε το τελικό σας αριστούργημα."
    },
    rotate: {
      heroBadge: "ΧΩΡΙΚΟΣ ΕΛΕΓΧΟΣ",
      heroTitle: "Περιστροφή και Αναστροφή.",
      heroTitle2: "Τέλεια προσανατολισμός.",
      heroDesc: "Διορθώστε φωτογραφίες, δημιουργήστε εφέ καθρέφτη και ρυθμίστε την περιστροφή με ακρίβεια.",
      feat1Title: "Γρήγορες Περιστροφές 90°",
      feat1Desc: "Διορθώστε αμέσως τις φωτογραφίες με λάθος προσανατολισμό. Περιστρέψτε αριστερά ή δεξιά.",
      feat2Title: "Εφέ Καθρέφτη",
      feat2Desc: "Αναστρέψτε τις εικόνες οριζόντια για selfies, ή κάθετα για αντανακλάσεις.",
      feat3Title: "Ρύθμιση Ορίζοντα",
      feat3Desc: "Έχετε μια στραβή φωτογραφία τοπίου; Χρησιμοποιήστε το ρυθμιστικό για να ισιώσετε τον ορίζοντα.",
      stepsTag: "ΡΟΗ ΕΡΓΑΣΙΑΣ",
      stepsTitle: "Αναπροσανατολισμός σε 3 Βήματα",
      s1Title: "Ανέβασμα",
      s1Desc: "Προσθέστε τις εικόνες που θέλετε να φτιάξετε.",
      s2Title: "Ρύθμιση",
      s2Desc: "Χρησιμοποιήστε τα κουμπιά περιστροφής.",
      s3Title: "Αποθήκευση",
      s3Desc: "Κατεβάστε τις διορθωμένες εικόνες."
    },
    picker: {
      heroBadge: "ΑΚΡΙΒΕΙΑ PIXEL",
      heroTitle: "Εξάγετε τέλεια χρώματα.",
      heroTitle2: "Φτιάξτε εκπληκτικές παλέτες.",
      heroDesc: "Ανεβάστε μια εικόνα και βρείτε τους κωδικούς HEX, RGB και HSL οποιουδήποτε pixel.",
      feat1Title: "Μικροσκοπική Λεπτομέρεια",
      feat1Desc: "Ο μεγεθυντικός φακός σας επιτρέπει να ζουμάρετε σε μεμονωμένα pixels.",
      feat2Title: "Πολλαπλές Μορφές",
      feat2Desc: "Λάβετε τα χρώματά σας σε HEX, RGB και HSL. Κάντε κλικ για αντιγραφή.",
      feat3Title: "Αυτόματη Δημιουργία Παλετών",
      feat3Desc: "Ο αλγόριθμος AI αναλύει την εικόνα και δημιουργεί μια παλέτα 5 χρωμάτων.",
      stepsTag: "ΡΟΗ ΕΡΓΑΣΙΑΣ",
      stepsTitle: "Εξαγωγή σε 3 Βήματα",
      s1Title: "Ανέβασμα",
      s1Desc: "Φορτώστε την εικόνα αναφοράς.",
      s2Title: "Επιλογή",
      s2Desc: "Κάντε κλικ σε ένα pixel για να το πιάσετε.",
      s3Title: "Αντιγραφή",
      s3Desc: "Αντιγράψτε αμέσως τις τιμές HEX/RGB."
    }
  },
  en: {
    design: {
      heroBadge: "CREATIVE SUITE",
      heroTitle: "Design Beautiful Visuals.",
      heroTitle2: "Right in Your Browser.",
      heroDesc: "A full-featured image editor packed with professional filters, text tools, shapes, and drawing capabilities. No software installation required.",
      feat1Title: "Rich Typography",
      feat1Desc: "Add custom text layers, choose from hundreds of web fonts, and style them with strokes, shadows, and gradients for maximum impact.",
      feat2Title: "Pro Filters",
      feat2Desc: "Apply cinematic color grading and professional adjustments natively.",
      feat3Title: "Vector Shapes",
      feat3Desc: "Draw geometric shapes, arrows, and borders with precision.",
      feat4Title: "Layer Management",
      feat4Desc: "Organize complex designs effortlessly. Stack, group, hide, and lock multiple layers to create intricate compositions without losing control.",
      stepsTag: "WORKFLOW",
      stepsTitle: "Create in 3 Steps",
      s1Title: "Start Canvas",
      s1Desc: "Open a blank canvas or import a photo.",
      s2Title: "Design",
      s2Desc: "Add text, graphics, and apply filters.",
      s3Title: "Export",
      s3Desc: "Download the final masterpiece."
    },
    rotate: {
      heroBadge: "SPATIAL CONTROL",
      heroTitle: "Rotate and Flip.",
      heroTitle2: "Perfect Orientation.",
      heroDesc: "Correct sideways photos, create mirror effects, and fine-tune image rotation by exact degrees. Fast, free, and done entirely in your browser.",
      feat1Title: "Quick 90° Turns",
      feat1Desc: "Fix photos taken in the wrong orientation instantly. Rotate left or right in precise 90-degree increments to snap images upright.",
      feat2Title: "Mirror Effects",
      feat2Desc: "Flip images horizontally to fix mirrored selfies, or vertically for creative reflection effects. The transformation is applied instantly without reloading.",
      feat3Title: "Fine-Tune Horizon",
      feat3Desc: "Got a crooked landscape photo? Use the precise rotation slider to level the horizon by exact degrees. Auto-crops boundaries seamlessly.",
      stepsTag: "WORKFLOW",
      stepsTitle: "Reorient in 3 Steps",
      s1Title: "Upload",
      s1Desc: "Add the images you want to fix.",
      s2Title: "Adjust",
      s2Desc: "Use the rotate and flip buttons.",
      s3Title: "Save",
      s3Desc: "Download the corrected images."
    },
    picker: {
      heroBadge: "PIXEL PRECISION",
      heroTitle: "Extract Perfect Colors.",
      heroTitle2: "Build Stunning Palettes.",
      heroDesc: "Upload an image and hover to pinpoint the exact HEX, RGB, and HSL codes of any pixel. Instantly generate harmonious color palettes for your next design project.",
      feat1Title: "Microscopic Detail",
      feat1Desc: "The built-in magnifying loupe lets you zoom down to individual pixels. No more guessing which shade of blue you are clicking on.",
      feat2Title: "Multiple Formats",
      feat2Desc: "Get your colors instantly converted into HEX, RGB, and HSL formats. Click once to copy to your clipboard and paste directly into your CSS.",
      feat3Title: "Auto-Generate Palettes",
      feat3Desc: "Don't just pick one color. Our AI algorithm analyzes your uploaded image and automatically generates a harmonious 5-color palette based on the most dominant and striking colors present.",
      stepsTag: "WORKFLOW",
      stepsTitle: "Extract in 3 Steps",
      s1Title: "Upload",
      s1Desc: "Load your reference image.",
      s2Title: "Pick",
      s2Desc: "Hover over any pixel and click to capture.",
      s3Title: "Copy",
      s3Desc: "Copy the HEX/RGB values instantly."
    }
  },
  es: {
    design: {
      heroBadge: "SUITE CREATIVA",
      heroTitle: "Diseña visuales hermosos.",
      heroTitle2: "Directo en tu navegador.",
      heroDesc: "Un editor de imágenes completo repleto de filtros profesionales, herramientas de texto, formas y dibujo. Sin instalación de software.",
      feat1Title: "Tipografía Rica",
      feat1Desc: "Añade capas de texto personalizadas, elige entre cientos de fuentes web y dales estilo con sombras y degradados.",
      feat2Title: "Filtros Pro",
      feat2Desc: "Aplica corrección de color cinematográfica y ajustes profesionales.",
      feat3Title: "Formas Vectoriales",
      feat3Desc: "Dibuja formas geométricas, flechas y bordes con precisión.",
      feat4Title: "Gestión de Capas",
      feat4Desc: "Organiza diseños complejos sin esfuerzo. Apila, agrupa, oculta y bloquea múltiples capas.",
      stepsTag: "FLUJO DE TRABAJO",
      stepsTitle: "Crea en 3 Pasos",
      s1Title: "Iniciar Lienzo",
      s1Desc: "Abre un lienzo en blanco o importa una foto.",
      s2Title: "Diseñar",
      s2Desc: "Añade texto, gráficos y aplica filtros.",
      s3Title: "Exportar",
      s3Desc: "Descarga tu obra maestra final."
    },
    rotate: {
      heroBadge: "CONTROL ESPACIAL",
      heroTitle: "Rota y Voltea.",
      heroTitle2: "Orientación Perfecta.",
      heroDesc: "Corrige fotos de lado, crea efectos de espejo y ajusta la rotación en grados exactos. Rápido, gratis y en tu navegador.",
      feat1Title: "Giros Rápidos de 90°",
      feat1Desc: "Arregla fotos con orientación incorrecta al instante. Rota a la izquierda o derecha en incrementos de 90 grados.",
      feat2Title: "Efectos de Espejo",
      feat2Desc: "Voltea imágenes horizontalmente para arreglar selfies, o verticalmente para efectos creativos.",
      feat3Title: "Ajustar el Horizonte",
      feat3Desc: "¿Tienes una foto de paisaje torcida? Usa el control deslizante para nivelar el horizonte.",
      stepsTag: "FLUJO DE TRABAJO",
      stepsTitle: "Reorienta en 3 Pasos",
      s1Title: "Subir",
      s1Desc: "Añade las imágenes que quieres arreglar.",
      s2Title: "Ajustar",
      s2Desc: "Usa los botones de rotar y voltear.",
      s3Title: "Guardar",
      s3Desc: "Descarga las imágenes corregidas."
    },
    picker: {
      heroBadge: "PRECISIÓN DE PÍXELES",
      heroTitle: "Extrae Colores Perfectos.",
      heroTitle2: "Crea Paletas Increíbles.",
      heroDesc: "Sube una imagen y pasa el ratón para obtener los códigos HEX, RGB y HSL de cualquier píxel. Genera paletas de colores al instante.",
      feat1Title: "Detalle Microscópico",
      feat1Desc: "La lupa integrada te permite hacer zoom en píxeles individuales.",
      feat2Title: "Múltiples Formatos",
      feat2Desc: "Obtén tus colores convertidos al instante en formatos HEX, RGB y HSL. Haz clic para copiar.",
      feat3Title: "Generar Paletas Automáticamente",
      feat3Desc: "Nuestro algoritmo de IA analiza tu imagen y genera automáticamente una paleta de 5 colores armoniosa.",
      stepsTag: "FLUJO DE TRABAJO",
      stepsTitle: "Extrae en 3 Pasos",
      s1Title: "Subir",
      s1Desc: "Carga tu imagen de referencia.",
      s2Title: "Elegir",
      s2Desc: "Pasa el ratón sobre cualquier píxel y haz clic.",
      s3Title: "Copiar",
      s3Desc: "Copia los valores HEX/RGB al instante."
    }
  },
  fi: {
    design: {
      heroBadge: "LUOVA PAKETTI",
      heroTitle: "Suunnittele kauniita visuaaleja.",
      heroTitle2: "Suoraan selaimessasi.",
      heroDesc: "Täysin varusteltu kuvankäsittelyohjelma, jossa on ammattimaiset suodattimet, tekstityökalut, muodot ja piirustusominaisuudet. Ohjelmistoa ei tarvitse asentaa.",
      feat1Title: "Rikas Typografia",
      feat1Desc: "Lisää mukautettuja tekstikerroksia, valitse sadoista kirjasimista ja tyylittele niitä varjoilla ja liukuväreillä.",
      feat2Title: "Pro-suodattimet",
      feat2Desc: "Käytä elokuvamaisia värimäärittelyjä ja ammattimaisia säätöjä.",
      feat3Title: "Vektorimuodot",
      feat3Desc: "Piirrä geometrisia muotoja, nuolia ja reunoja tarkasti.",
      feat4Title: "Kerrosten hallinta",
      feat4Desc: "Järjestä monimutkaiset mallit vaivattomasti. Pinoa, ryhmittele, piilota ja lukitse useita kerroksia.",
      stepsTag: "TYÖNKULKU",
      stepsTitle: "Luo 3 vaiheessa",
      s1Title: "Aloita kankaalta",
      s1Desc: "Avaa tyhjä kangas tai tuo kuva.",
      s2Title: "Suunnittele",
      s2Desc: "Lisää tekstiä, grafiikkaa ja suodattimia.",
      s3Title: "Vie",
      s3Desc: "Lataa lopullinen mestariteoksesi."
    },
    rotate: {
      heroBadge: "TILAN HALLINTA",
      heroTitle: "Kierrä ja käännä.",
      heroTitle2: "Täydellinen suunta.",
      heroDesc: "Korjaa sivuttain olevat valokuvat, luo peilitehosteita ja hienosäädä kuvan kiertoa tarkoilla asteilla. Nopea, ilmainen ja selaimessasi.",
      feat1Title: "Nopeat 90° käännökset",
      feat1Desc: "Korjaa väärin suunnatut valokuvat heti. Kierrä vasemmalle tai oikealle 90 asteen välein.",
      feat2Title: "Peilitehosteet",
      feat2Desc: "Käännä kuvat vaakasuunnassa korjataksesi selfiet, tai pystysuunnassa luovia heijastuksia varten.",
      feat3Title: "Hienosäädä horisonttia",
      feat3Desc: "Onko sinulla vino maisemakuva? Käytä liukusäädintä tasoittaaksesi horisontin.",
      stepsTag: "TYÖNKULKU",
      stepsTitle: "Suuntaa uudelleen 3 vaiheessa",
      s1Title: "Lataa",
      s1Desc: "Lisää korjattavat kuvat.",
      s2Title: "Säädä",
      s2Desc: "Käytä kierto- ja kääntöpainikkeita.",
      s3Title: "Tallenna",
      s3Desc: "Lataa korjatut kuvat."
    },
    picker: {
      heroBadge: "PIKSELITARKKA",
      heroTitle: "Poimi täydelliset värit.",
      heroTitle2: "Rakenna upeita paletteja.",
      heroDesc: "Lataa kuva ja osoita saadaksesi minkä tahansa pikselin HEX-, RGB- ja HSL-koodit. Luo väripaletteja hetkessä.",
      feat1Title: "Mikroskooppinen yksityiskohta",
      feat1Desc: "Sisäänrakennetun suurennuslasin avulla voit zoomata yksittäisiin pikseleihin.",
      feat2Title: "Useita formaatteja",
      feat2Desc: "Saat värisi muunnettuna heti HEX-, RGB- ja HSL-muotoihin. Kopioi napsauttamalla.",
      feat3Title: "Automaattiset paletit",
      feat3Desc: "Tekoälyalgoritmimme analysoi kuvasi ja luo automaattisesti 5 värin paletin.",
      stepsTag: "TYÖNKULKU",
      stepsTitle: "Poimi 3 vaiheessa",
      s1Title: "Lataa",
      s1Desc: "Lataa viitekuva.",
      s2Title: "Valitse",
      s2Desc: "Osoita pikseliä ja napsauta kaapataksesi.",
      s3Title: "Kopioi",
      s3Desc: "Kopioi HEX/RGB-arvot heti."
    }
  },
  fr: {
    design: {
      heroBadge: "SUITE CRÉATIVE",
      heroTitle: "Concevez de beaux visuels.",
      heroTitle2: "Directement dans votre navigateur.",
      heroDesc: "Un éditeur d'images complet avec des filtres professionnels, des outils de texte, des formes et des capacités de dessin. Aucune installation requise.",
      feat1Title: "Typographie riche",
      feat1Desc: "Ajoutez des calques de texte personnalisés, choisissez parmi des centaines de polices et stylisez-les avec des ombres et des dégradés.",
      feat2Title: "Filtres Pro",
      feat2Desc: "Appliquez une correction des couleurs cinématographique et des ajustements professionnels.",
      feat3Title: "Formes Vectorielles",
      feat3Desc: "Dessinez des formes géométriques, des flèches et des bordures avec précision.",
      feat4Title: "Gestion des Calques",
      feat4Desc: "Organisez des conceptions complexes sans effort. Empilez, regroupez, masquez et verrouillez plusieurs calques.",
      stepsTag: "FLUX DE TRAVAIL",
      stepsTitle: "Créez en 3 étapes",
      s1Title: "Démarrer",
      s1Desc: "Ouvrez une toile vierge ou importez une photo.",
      s2Title: "Concevoir",
      s2Desc: "Ajoutez du texte, des graphiques et des filtres.",
      s3Title: "Exporter",
      s3Desc: "Téléchargez votre chef-d'œuvre."
    },
    rotate: {
      heroBadge: "CONTRÔLE SPATIAL",
      heroTitle: "Faites pivoter et Retournez.",
      heroTitle2: "Orientation parfaite.",
      heroDesc: "Corrigez les photos de travers, créez des effets de miroir et ajustez la rotation avec des degrés exacts. Rapide, gratuit et dans votre navigateur.",
      feat1Title: "Rotations rapides à 90°",
      feat1Desc: "Corrigez instantanément les photos mal orientées. Faites pivoter à gauche ou à droite par incréments de 90 degrés.",
      feat2Title: "Effets de Miroir",
      feat2Desc: "Retournez les images horizontalement pour corriger les selfies, ou verticalement pour des reflets créatifs.",
      feat3Title: "Ajuster l'Horizon",
      feat3Desc: "Vous avez une photo de paysage de travers ? Utilisez le curseur pour niveler l'horizon.",
      stepsTag: "FLUX DE TRAVAIL",
      stepsTitle: "Réorientez en 3 étapes",
      s1Title: "Téléverser",
      s1Desc: "Ajoutez les images que vous souhaitez corriger.",
      s2Title: "Ajuster",
      s2Desc: "Utilisez les boutons de rotation et de retournement.",
      s3Title: "Enregistrer",
      s3Desc: "Téléchargez les images corrigées."
    },
    picker: {
      heroBadge: "PRÉCISION DES PIXELS",
      heroTitle: "Extrayez des couleurs parfaites.",
      heroTitle2: "Créez des palettes superbes.",
      heroDesc: "Téléversez une image et survolez pour obtenir les codes HEX, RGB et HSL de n'importe quel pixel. Générez des palettes de couleurs instantanément.",
      feat1Title: "Détail Microscopique",
      feat1Desc: "La loupe intégrée vous permet de zoomer sur des pixels individuels.",
      feat2Title: "Formats Multiples",
      feat2Desc: "Obtenez vos couleurs converties instantanément aux formats HEX, RGB et HSL. Cliquez pour copier.",
      feat3Title: "Générer des Palettes Automatiquement",
      feat3Desc: "Notre algorithme d'IA analyse votre image et génère automatiquement une palette harmonieuse de 5 couleurs.",
      stepsTag: "FLUX DE TRAVAIL",
      stepsTitle: "Extrayez en 3 étapes",
      s1Title: "Téléverser",
      s1Desc: "Chargez votre image de référence.",
      s2Title: "Choisir",
      s2Desc: "Survolez n'importe quel pixel et cliquez.",
      s3Title: "Copier",
      s3Desc: "Copiez les valeurs HEX/RGB instantanément."
    }
  },
  he: {
    design: {
      heroBadge: "חבילת עיצוב",
      heroTitle: "עצב תמונות יפהפיות.",
      heroTitle2: "ישירות בדפדפן שלך.",
      heroDesc: "עורך תמונות מלא עם פילטרים מקצועיים, כלי טקסט, צורות ויכולות ציור. ללא צורך בהתקנת תוכנה.",
      feat1Title: "טיפוגרפיה עשירה",
      feat1Desc: "הוסף שכבות טקסט מותאמות אישית, בחר מתוך מאות גופנים ועצב עם הצללות ומעברי צבע.",
      feat2Title: "פילטרים מקצועיים",
      feat2Desc: "החל תיקוני צבע קולנועיים והתאמות מקצועיות.",
      feat3Title: "צורות וקטוריות",
      feat3Desc: "צייר צורות גיאומטריות, חצים וגבולות בדיוק.",
      feat4Title: "ניהול שכבות",
      feat4Desc: "ארגן עיצובים מורכבים בקלות. קבץ, הסתר ונעל שכבות מרובות.",
      stepsTag: "תהליך עבודה",
      stepsTitle: "צור ב-3 שלבים",
      s1Title: "התחל",
      s1Desc: "פתח קנבס ריק או יבא תמונה.",
      s2Title: "עצב",
      s2Desc: "הוסף טקסט, גרפיקה ופילטרים.",
      s3Title: "ייצא",
      s3Desc: "הורד את יצירת המופת שלך."
    },
    rotate: {
      heroBadge: "שליטה במרחב",
      heroTitle: "סובב והפוך.",
      heroTitle2: "כיוון מושלם.",
      heroDesc: "תקן תמונות הפוכות, צור אפקטי מראה, וכוונן את סיבוב התמונה במעלות מדויקות. מהיר, חינמי.",
      feat1Title: "סיבובי 90° מהירים",
      feat1Desc: "תקן תמונות שצולמו בכיוון לא נכון באופן מיידי. סובב שמאלה או ימינה ב-90 מעלות.",
      feat2Title: "אפקטי מראה",
      feat2Desc: "הפוך תמונות אופקית לתיקון סלפי, או אנכית להשתקפויות יצירתיות.",
      feat3Title: "כוונון אופק",
      feat3Desc: "יש לך תמונת נוף עקומה? השתמש במחוון כדי ליישר את האופק.",
      stepsTag: "תהליך עבודה",
      stepsTitle: "כוון מחדש ב-3 שלבים",
      s1Title: "העלה",
      s1Desc: "הוסף את התמונות שברצונך לתקן.",
      s2Title: "התאם",
      s2Desc: "השתמש בכפתורי הסיבוב וההיפוך.",
      s3Title: "שמור",
      s3Desc: "הורד את התמונות המתוקנות."
    },
    picker: {
      heroBadge: "דיוק פיקסלים",
      heroTitle: "חלץ צבעים מושלמים.",
      heroTitle2: "בנה פלטות מדהימות.",
      heroDesc: "העלה תמונה ורחף מעל כדי למצוא קודי HEX, RGB ו-HSL. צור פלטות צבעים באופן מיידי.",
      feat1Title: "פרט מיקרוסקופי",
      feat1Desc: "זכוכית המגדלת המובנית מאפשרת לך להתמקד בפיקסלים בודדים.",
      feat2Title: "פורמטים מרובים",
      feat2Desc: "קבל את הצבעים שלך בפורמטים HEX, RGB ו-HSL. לחץ כדי להעתיק.",
      feat3Title: "יצירת פלטות אוטומטית",
      feat3Desc: "אלגוריתם ה-AI שלנו מנתח את התמונה שלך ויוצר אוטומטית פלטת 5 צבעים.",
      stepsTag: "תהליך עבודה",
      stepsTitle: "חלץ ב-3 שלבים",
      s1Title: "העלה",
      s1Desc: "טען את תמונת הייחוס שלך.",
      s2Title: "בחר",
      s2Desc: "רחף מעל כל פיקסל ולחץ כדי ללכוד.",
      s3Title: "העתק",
      s3Desc: "העתק את ערכי HEX/RGB באופן מיידי."
    }
  },
  hi: {
    design: {
      heroBadge: "क्रिएटिव सूट",
      heroTitle: "सुंदर विज़ुअल डिज़ाइन करें।",
      heroTitle2: "सीधे अपने ब्राउज़र में।",
      heroDesc: "पेशेवर फिल्टर, टेक्स्ट टूल्स, आकार और ड्राइंग क्षमताओं के साथ पैक किया गया एक पूर्ण-विशेषताओं वाला चित्र संपादक। कोई सॉफ़्टवेयर स्थापना आवश्यक नहीं है।",
      feat1Title: "रिच टाइपोग्राफी",
      feat1Desc: "कस्टम टेक्स्ट लेयर जोड़ें, सैकड़ों फ़ॉन्ट चुनें और उन्हें शैडो के साथ स्टाइल करें।",
      feat2Title: "प्रो फिल्टर",
      feat2Desc: "सिनेमैटिक कलर ग्रेडिंग और पेशेवर समायोजन लागू करें।",
      feat3Title: "वेक्टर आकृतियाँ",
      feat3Desc: "सटीकता के साथ ज्यामितीय आकार, तीर और सीमाएं खींचें।",
      feat4Title: "लेयर प्रबंधन",
      feat4Desc: "जटिल डिज़ाइनों को आसानी से व्यवस्थित करें। कई परतों को स्टैक, ग्रुप, छिपाएं और लॉक करें।",
      stepsTag: "कार्यप्रवाह",
      stepsTitle: "3 चरणों में बनाएं",
      s1Title: "कैनवास प्रारंभ करें",
      s1Desc: "एक खाली कैनवास खोलें या एक फोटो आयात करें।",
      s2Title: "डिज़ाइन",
      s2Desc: "टेक्स्ट, ग्राफिक्स जोड़ें और फ़िल्टर लागू करें।",
      s3Title: "निर्यात",
      s3Desc: "अपनी उत्कृष्ट कृति डाउनलोड करें।"
    },
    rotate: {
      heroBadge: "स्थानिक नियंत्रण",
      heroTitle: "घुमाएँ और पलटें।",
      heroTitle2: "बिल्कुल सही अभिविन्यास।",
      heroDesc: "तिरछी तस्वीरों को ठीक करें, दर्पण प्रभाव बनाएं, और चित्र रोटेशन को सटीक डिग्री तक फाइन-ट्यून करें।",
      feat1Title: "त्वरित 90° घुमाव",
      feat1Desc: "गलत ओरिएंटेशन वाली तस्वीरों को तुरंत ठीक करें। 90 डिग्री के अंतराल में बाएँ या दाएँ घुमाएँ।",
      feat2Title: "दर्पण प्रभाव",
      feat2Desc: "सेल्फी को ठीक करने के लिए क्षैतिज रूप से पलटें, या रचनात्मक प्रतिबिंब के लिए लंबवत रूप से पलटें।",
      feat3Title: "क्षितिज को फाइन-ट्यून करें",
      feat3Desc: "क्या कोई टेढ़ी लैंडस्केप तस्वीर है? क्षितिज को समतल करने के लिए स्लाइडर का उपयोग करें।",
      stepsTag: "कार्यप्रवाह",
      stepsTitle: "3 चरणों में सुधारें",
      s1Title: "अपलोड",
      s1Desc: "वे चित्र जोड़ें जिन्हें आप ठीक करना चाहते हैं।",
      s2Title: "समायोजित करें",
      s2Desc: "घुमाने और पलटने वाले बटनों का उपयोग करें।",
      s3Title: "सहेजें",
      s3Desc: "सही की गई छवियां डाउनलोड करें।"
    },
    picker: {
      heroBadge: "पिक्सेल परिशुद्धता",
      heroTitle: "सही रंग निकालें।",
      heroTitle2: "आश्चर्यजनक पट्टियाँ बनाएँ।",
      heroDesc: "एक छवि अपलोड करें और किसी भी पिक्सेल के सटीक HEX, RGB और HSL कोड पिनपॉइंट करने के लिए होवर करें।",
      feat1Title: "सूक्ष्म विवरण",
      feat1Desc: "अंतर्निहित आवर्धक चश्मा आपको व्यक्तिगत पिक्सेल पर ज़ूम इन करने देता है।",
      feat2Title: "एकाधिक प्रारूप",
      feat2Desc: "अपने रंगों को तुरंत HEX, RGB और HSL प्रारूपों में परिवर्तित करें। कॉपी करने के लिए क्लिक करें।",
      feat3Title: "स्वतः पट्टियाँ बनाएँ",
      feat3Desc: "हमारा AI एल्गोरिदम आपकी छवि का विश्लेषण करता है और स्वचालित रूप से 5-रंगों का पैलेट बनाता है।",
      stepsTag: "कार्यप्रवाह",
      stepsTitle: "3 चरणों में निकालें",
      s1Title: "अपलोड",
      s1Desc: "अपनी संदर्भ छवि लोड करें।",
      s2Title: "चुनें",
      s2Desc: "किसी भी पिक्सेल पर होवर करें और कैप्चर करने के लिए क्लिक करें।",
      s3Title: "कॉपी करें",
      s3Desc: "HEX/RGB मानों को तुरंत कॉपी करें।"
    }
  },
  hu: {
    design: {
      heroBadge: "KREATÍV CSOMAG",
      heroTitle: "Tervezz gyönyörű vizuális tartalmakat.",
      heroTitle2: "Közvetlenül a böngésződben.",
      heroDesc: "Egy teljes körű képszerkesztő professzionális szűrőkkel, szöveges eszközökkel, alakzatokkal. Nincs szükség telepítésre.",
      feat1Title: "Gazdag tipográfia",
      feat1Desc: "Adj hozzá egyéni szövegrétegeket, válassz több száz betűtípus közül.",
      feat2Title: "Pro Szűrők",
      feat2Desc: "Alkalmazz mozis színkorrekciót és professzionális beállításokat.",
      feat3Title: "Vektoros alakzatok",
      feat3Desc: "Rajzolj geometriai alakzatokat, nyilakat és szegélyeket pontosan.",
      feat4Title: "Rétegkezelés",
      feat4Desc: "Rendezd az összetett terveket. Több réteg csoportosítása, elrejtése és zárolása.",
      stepsTag: "MUNKAfolyamat",
      stepsTitle: "Készíts 3 lépésben",
      s1Title: "Vászon indítása",
      s1Desc: "Nyiss egy üres vásznat vagy importálj egy fotót.",
      s2Title: "Tervezés",
      s2Desc: "Adj hozzá szöveget, grafikát és szűrőket.",
      s3Title: "Exportálás",
      s3Desc: "Töltsd le a végső mesterművet."
    },
    rotate: {
      heroBadge: "TÉRBELI KONTROLL",
      heroTitle: "Forgatás és tükrözés.",
      heroTitle2: "Tökéletes tájolás.",
      heroDesc: "Javítsd ki a ferde fotókat, hozz létre tükröződéseket. Gyors, ingyenes és a böngésződben működik.",
      feat1Title: "Gyors 90°-os forgatás",
      feat1Desc: "Azonnal javítsd a rossz tájolású fotókat. Forgass balra vagy jobbra.",
      feat2Title: "Tükör effektek",
      feat2Desc: "Tükrözd a képeket vízszintesen a szelfik javításához, vagy függőlegesen.",
      feat3Title: "Horizont finomhangolása",
      feat3Desc: "Ferde a tájkép? Használd a csúszkát a horizont kiegyenlítéséhez.",
      stepsTag: "MUNKAfolyamat",
      stepsTitle: "Újratájolás 3 lépésben",
      s1Title: "Feltöltés",
      s1Desc: "Add hozzá a javítandó képeket.",
      s2Title: "Beállítás",
      s2Desc: "Használd a forgatás és tükrözés gombokat.",
      s3Title: "Mentés",
      s3Desc: "Töltsd le a javított képeket."
    },
    picker: {
      heroBadge: "PIXEL PONTOSSÁG",
      heroTitle: "Tökéletes színek kinyerése.",
      heroTitle2: "Építs lenyűgöző palettákat.",
      heroDesc: "Tölts fel egy képet, és vidd fölé az egeret bármely pixel HEX, RGB és HSL kódjának megállapításához.",
      feat1Title: "Mikroszkopikus részlet",
      feat1Desc: "A beépített nagyító lehetővé teszi az egyes pixelek nagyítását.",
      feat2Title: "Több formátum",
      feat2Desc: "Kapd meg a színeket HEX, RGB és HSL formátumban. Kattints a másoláshoz.",
      feat3Title: "Paletták automatikus generálása",
      feat3Desc: "AI algoritmusunk elemzi a képet és automatikusan generál egy 5 színű palettát.",
      stepsTag: "MUNKAfolyamat",
      stepsTitle: "Kinyerés 3 lépésben",
      s1Title: "Feltöltés",
      s1Desc: "Töltsd be a referenciaképet.",
      s2Title: "Kiválasztás",
      s2Desc: "Vidd az egeret egy pixel fölé, és kattints a rögzítéshez.",
      s3Title: "Másolás",
      s3Desc: "Másold a HEX/RGB értékeket azonnal."
    }
  },
  id: {
    design: {
      heroBadge: "CREATIVE SUITE",
      heroTitle: "Desain Visual Memukau.",
      heroTitle2: "Langsung di Browser Anda.",
      heroDesc: "Editor gambar berfitur lengkap dengan filter profesional, alat teks, bentuk, dan kemampuan menggambar. Tanpa instalasi software.",
      feat1Title: "Tipografi Kaya",
      feat1Desc: "Tambahkan lapisan teks kustom, pilih dari ratusan font web, dan beri gaya dengan bayangan serta gradien.",
      feat2Title: "Filter Pro",
      feat2Desc: "Terapkan gradasi warna sinematik dan penyesuaian profesional secara native.",
      feat3Title: "Bentuk Vektor",
      feat3Desc: "Gambar bentuk geometris, panah, dan batas dengan presisi tinggi.",
      feat4Title: "Manajemen Layer",
      feat4Desc: "Atur desain kompleks dengan mudah. Susun, kelompokkan, sembunyikan, dan kunci berbagai layer.",
      stepsTag: "CARA KERJA",
      stepsTitle: "Buat dalam 3 Langkah",
      s1Title: "Mulai Kanvas",
      s1Desc: "Buka kanvas kosong atau impor foto.",
      s2Title: "Desain",
      s2Desc: "Tambahkan teks, grafis, dan terapkan filter.",
      s3Title: "Ekspor",
      s3Desc: "Unduh hasil karya akhir Anda."
    },
    rotate: {
      heroBadge: "KONTROL SPASIAL",
      heroTitle: "Putar dan Balik.",
      heroTitle2: "Orientasi Sempurna.",
      heroDesc: "Perbaiki foto miring, buat efek cermin, dan atur rotasi gambar dengan derajat yang pasti. Cepat, gratis, dan langsung di browser.",
      feat1Title: "Putaran 90° Cepat",
      feat1Desc: "Perbaiki foto dengan orientasi salah secara instan. Putar ke kiri atau kanan dalam kelipatan 90 derajat.",
      feat2Title: "Efek Cermin",
      feat2Desc: "Balik gambar secara horizontal untuk memperbaiki selfie, atau vertikal untuk efek pantulan.",
      feat3Title: "Perbaiki Horizon",
      feat3Desc: "Punya foto pemandangan miring? Gunakan slider presisi untuk meratakan horizon.",
      stepsTag: "CARA KERJA",
      stepsTitle: "Atur Arah dalam 3 Langkah",
      s1Title: "Unggah",
      s1Desc: "Tambahkan gambar yang ingin diperbaiki.",
      s2Title: "Sesuaikan",
      s2Desc: "Gunakan tombol putar dan balik.",
      s3Title: "Simpan",
      s3Desc: "Unduh gambar yang sudah diperbaiki."
    },
    picker: {
      heroBadge: "PRESISI PIKSEL",
      heroTitle: "Ekstrak Warna Sempurna.",
      heroTitle2: "Buat Palet Mengagumkan.",
      heroDesc: "Unggah gambar dan arahkan kursor untuk mengetahui kode HEX, RGB, dan HSL dari piksel mana pun. Hasilkan palet warna harmonis secara instan.",
      feat1Title: "Detail Mikroskopis",
      feat1Desc: "Kaca pembesar bawaan memungkinkan Anda memperbesar hingga piksel individual.",
      feat2Title: "Berbagai Format",
      feat2Desc: "Dapatkan warna yang dikonversi instan ke HEX, RGB, dan HSL. Klik untuk menyalin.",
      feat3Title: "Buat Palet Otomatis",
      feat3Desc: "Algoritma AI kami menganalisis gambar Anda dan secara otomatis menghasilkan 5 palet warna yang harmonis.",
      stepsTag: "CARA KERJA",
      stepsTitle: "Ekstrak dalam 3 Langkah",
      s1Title: "Unggah",
      s1Desc: "Muat gambar referensi Anda.",
      s2Title: "Pilih",
      s2Desc: "Arahkan ke piksel mana pun dan klik untuk mengambil.",
      s3Title: "Salin",
      s3Desc: "Salin nilai HEX/RGB secara instan."
    }
  },
  it: {
    design: {
      heroBadge: "SUITE CREATIVA",
      heroTitle: "Progetta immagini bellissime.",
      heroTitle2: "Direttamente nel tuo browser.",
      heroDesc: "Un editor di immagini completo con filtri professionali, strumenti di testo, forme e disegno. Nessuna installazione richiesta.",
      feat1Title: "Tipografia Ricca",
      feat1Desc: "Aggiungi livelli di testo personalizzati, scegli tra centinaia di font web.",
      feat2Title: "Filtri Pro",
      feat2Desc: "Applica correzioni colore cinematografiche e regolazioni professionali.",
      feat3Title: "Forme Vettoriali",
      feat3Desc: "Disegna forme geometriche, frecce e bordi con precisione.",
      feat4Title: "Gestione Livelli",
      feat4Desc: "Organizza design complessi senza sforzo. Raggruppa e blocca più livelli.",
      stepsTag: "FLUSSO DI LAVORO",
      stepsTitle: "Crea in 3 Passaggi",
      s1Title: "Inizia Tela",
      s1Desc: "Apri una tela vuota o importa una foto.",
      s2Title: "Progetta",
      s2Desc: "Aggiungi testo, grafica e filtri.",
      s3Title: "Esporta",
      s3Desc: "Scarica il tuo capolavoro finale."
    },
    rotate: {
      heroBadge: "CONTROLLO SPAZIALE",
      heroTitle: "Ruota e Capovolgi.",
      heroTitle2: "Orientamento Perfetto.",
      heroDesc: "Correggi le foto storte, crea effetti specchio e regola la rotazione. Veloce, gratuito e nel tuo browser.",
      feat1Title: "Giri Rapidi di 90°",
      feat1Desc: "Correggi istantaneamente le foto con orientamento errato. Ruota a sinistra o a destra.",
      feat2Title: "Effetti Specchio",
      feat2Desc: "Capovolgi le immagini orizzontalmente per i selfie o verticalmente.",
      feat3Title: "Regola l'Orizzonte",
      feat3Desc: "Hai una foto di paesaggio storta? Usa il cursore per livellare l'orizzonte.",
      stepsTag: "FLUSSO DI LAVORO",
      stepsTitle: "Riorienta in 3 Passaggi",
      s1Title: "Carica",
      s1Desc: "Aggiungi le immagini da correggere.",
      s2Title: "Regola",
      s2Desc: "Usa i pulsanti di rotazione e capovolgimento.",
      s3Title: "Salva",
      s3Desc: "Scarica le immagini corrette."
    },
    picker: {
      heroBadge: "PRECISIONE DEI PIXEL",
      heroTitle: "Estrai colori perfetti.",
      heroTitle2: "Crea tavolozze straordinarie.",
      heroDesc: "Carica un'immagine e passa il mouse per ottenere i codici HEX, RGB e HSL di qualsiasi pixel.",
      feat1Title: "Dettaglio Microscopico",
      feat1Desc: "La lente d'ingrandimento integrata ti consente di ingrandire i singoli pixel.",
      feat2Title: "Formati Multipli",
      feat2Desc: "Ottieni i tuoi colori convertiti in formati HEX, RGB e HSL. Clicca per copiare.",
      feat3Title: "Genera Tavolozze Automaticamente",
      feat3Desc: "Il nostro algoritmo IA analizza la tua immagine e genera automaticamente una tavolozza di 5 colori.",
      stepsTag: "FLUSSO DI LAVORO",
      stepsTitle: "Estrai in 3 Passaggi",
      s1Title: "Carica",
      s1Desc: "Carica la tua immagine di riferimento.",
      s2Title: "Scegli",
      s2Desc: "Passa il mouse su qualsiasi pixel e clicca.",
      s3Title: "Copia",
      s3Desc: "Copia istantaneamente i valori HEX/RGB."
    }
  },
  ja: {
    design: {
      heroBadge: "クリエイティブスイート",
      heroTitle: "美しいビジュアルをデザインする。",
      heroTitle2: "ブラウザで直接。",
      heroDesc: "プロフェッショナルなフィルター、テキストツール、図形、描画機能を備えたフル機能の画像エディター。ソフトウェアのインストールは不要です。",
      feat1Title: "リッチなタイポグラフィ",
      feat1Desc: "カスタムテキストレイヤーを追加し、何百ものWebフォントから選択してスタイルを設定します。",
      feat2Title: "プロフィルター",
      feat2Desc: "シネマティックなカラーグレーディングとプロの調整を適用します。",
      feat3Title: "ベクター図形",
      feat3Desc: "幾何学的な図形、矢印、境界線を正確に描きます。",
      feat4Title: "レイヤー管理",
      feat4Desc: "複雑なデザインを簡単に整理。複数のレイヤーをグループ化、非表示、ロックします。",
      stepsTag: "ワークフロー",
      stepsTitle: "3ステップで作成",
      s1Title: "キャンバスを開始",
      s1Desc: "空白のキャンバスを開くか、写真をインポートします。",
      s2Title: "デザイン",
      s2Desc: "テキストやグラフィックを追加し、フィルターを適用します。",
      s3Title: "エクスポート",
      s3Desc: "最終的な傑作をダウンロードします。"
    },
    rotate: {
      heroBadge: "空間制御",
      heroTitle: "回転と反転。",
      heroTitle2: "完璧な向き。",
      heroDesc: "横向きの写真を修正し、ミラー効果を作成し、画像の回転を正確な角度で微調整します。",
      feat1Title: "クイック90°回転",
      feat1Desc: "向きが間違っている写真を即座に修正。90度単位で左右に回転します。",
      feat2Title: "ミラー効果",
      feat2Desc: "自撮り写真を水平方向に反転したり、垂直方向に反転してクリエイティブな反射を作成します。",
      feat3Title: "地平線の微調整",
      feat3Desc: "風景写真が傾いていますか？スライダーを使用して地平線を水平にします。",
      stepsTag: "ワークフロー",
      stepsTitle: "3ステップで向きを調整",
      s1Title: "アップロード",
      s1Desc: "修正したい画像を追加します。",
      s2Title: "調整",
      s2Desc: "回転と反転ボタンを使用します。",
      s3Title: "保存",
      s3Desc: "修正した画像をダウンロードします。"
    },
    picker: {
      heroBadge: "ピクセル精度",
      heroTitle: "完璧な色を抽出。",
      heroTitle2: "見事なパレットを作成。",
      heroDesc: "画像をアップロードし、ホバーして任意のピクセルのHEX、RGB、HSLコードを特定します。",
      feat1Title: "顕微鏡レベルの詳細",
      feat1Desc: "組み込みの拡大鏡を使用して、個々のピクセルにズームインできます。",
      feat2Title: "複数のフォーマット",
      feat2Desc: "色をHEX、RGB、HSLフォーマットに即座に変換します。クリックしてコピー。",
      feat3Title: "パレットの自動生成",
      feat3Desc: "AIアルゴリズムが画像を分析し、5色の調和のとれたパレットを自動生成します。",
      stepsTag: "ワークフロー",
      stepsTitle: "3ステップで抽出",
      s1Title: "アップロード",
      s1Desc: "参照画像を読み込みます。",
      s2Title: "選択",
      s2Desc: "任意のピクセルにホバーしてクリックしてキャプチャします。",
      s3Title: "コピー",
      s3Desc: "HEX/RGB値を即座にコピーします。"
    }
  },
  ko: {
    design: {
      heroBadge: "크리에이티브 스위트",
      heroTitle: "아름다운 시각 효과 디자인.",
      heroTitle2: "브라우저에서 바로.",
      heroDesc: "전문적인 필터, 텍스트 도구, 도형 및 그리기 기능을 갖춘 모든 기능을 갖춘 이미지 편집기입니다. 소프트웨어 설치가 필요 없습니다.",
      feat1Title: "풍부한 타이포그래피",
      feat1Desc: "사용자 정의 텍스트 레이어를 추가하고 수백 개의 웹 글꼴 중에서 선택하십시오.",
      feat2Title: "프로 필터",
      feat2Desc: "영화 같은 색상 보정 및 전문적인 조정을 적용합니다.",
      feat3Title: "벡터 도형",
      feat3Desc: "기하학적 도형, 화살표 및 테두리를 정밀하게 그립니다.",
      feat4Title: "레이어 관리",
      feat4Desc: "복잡한 디자인을 쉽게 정리하십시오. 여러 레이어를 스택, 그룹화, 숨기기 및 잠급니다.",
      stepsTag: "워크플로우",
      stepsTitle: "3단계로 생성",
      s1Title: "캔버스 시작",
      s1Desc: "빈 캔버스를 열거나 사진을 가져옵니다.",
      s2Title: "디자인",
      s2Desc: "텍스트, 그래픽을 추가하고 필터를 적용합니다.",
      s3Title: "내보내기",
      s3Desc: "최종 걸작을 다운로드합니다."
    },
    rotate: {
      heroBadge: "공간 제어",
      heroTitle: "회전 및 뒤집기.",
      heroTitle2: "완벽한 방향.",
      heroDesc: "옆으로 누운 사진을 수정하고 미러 효과를 만들고 정확한 각도로 이미지 회전을 미세 조정합니다.",
      feat1Title: "빠른 90° 회전",
      feat1Desc: "잘못된 방향으로 찍힌 사진을 즉시 수정합니다. 90도 단위로 좌우로 회전합니다.",
      feat2Title: "미러 효과",
      feat2Desc: "셀카를 수정하기 위해 가로로 뒤집거나 창의적인 반사 효과를 위해 세로로 뒤집습니다.",
      feat3Title: "수평선 미세 조정",
      feat3Desc: "풍경 사진이 삐뚤어졌습니까? 슬라이더를 사용하여 수평을 맞춥니다.",
      stepsTag: "워크플로우",
      stepsTitle: "3단계로 방향 재설정",
      s1Title: "업로드",
      s1Desc: "수정할 이미지를 추가합니다.",
      s2Title: "조정",
      s2Desc: "회전 및 뒤집기 버튼을 사용합니다.",
      s3Title: "저장",
      s3Desc: "수정된 이미지를 다운로드합니다."
    },
    picker: {
      heroBadge: "픽셀 정밀도",
      heroTitle: "완벽한 색상 추출.",
      heroTitle2: "멋진 팔레트 구축.",
      heroDesc: "이미지를 업로드하고 마우스를 올려 모든 픽셀의 HEX, RGB 및 HSL 코드를 정확히 찾아냅니다.",
      feat1Title: "미세한 세부 사항",
      feat1Desc: "내장 돋보기를 사용하면 개별 픽셀을 확대할 수 있습니다.",
      feat2Title: "다중 형식",
      feat2Desc: "색상을 HEX, RGB 및 HSL 형식으로 즉시 변환하십시오. 클릭하여 복사.",
      feat3Title: "자동 팔레트 생성",
      feat3Desc: "AI 알고리즘이 이미지를 분석하고 5가지 색상 팔레트를 자동으로 생성합니다.",
      stepsTag: "워크플로우",
      stepsTitle: "3단계로 추출",
      s1Title: "업로드",
      s1Desc: "참조 이미지를 불러옵니다.",
      s2Title: "선택",
      s2Desc: "아무 픽셀에나 마우스를 올리고 클릭하여 캡처합니다.",
      s3Title: "복사",
      s3Desc: "HEX/RGB 값을 즉시 복사합니다."
    }
  }
};

const keys = ['ar','cs','da','de','el','es','fi','fr','he','hi','hu','id','it','ja','ko'];

keys.forEach(lang => {
  const filePath = path.join(localesDir, lang, 'translation.json');
  if (fs.existsSync(filePath)) {
    const content = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    
    if (!content.landing) content.landing = {};
    
    // Inject design
    if (!content.landing.design) content.landing.design = {};
    content.landing.design.redesign = translations[lang].design;

    // Inject rotate
    if (!content.landing.rotate) content.landing.rotate = {};
    content.landing.rotate.redesign = translations[lang].rotate;

    // Inject picker
    if (!content.landing.picker) content.landing.picker = {};
    content.landing.picker.redesign = translations[lang].picker;

    fs.writeFileSync(filePath, JSON.stringify(content, null, 2));
    console.log(`[${lang}] Successfully injected DRP part 1`);
  }
});
