const fs = require('fs');
const path = require('path');

const translations = {
  de: {
    "landing.compress.redesign.heroBadge": "INTELLIGENTE KOMPRIMIERUNG",
    "landing.compress.redesign.heroTitle": "Reduzieren Sie die Bilddateigröße sofort um bis zu 90 %",
    "landing.compress.redesign.heroDesc": "Verkleinern Sie Ihre Fotos ohne Verlust der visuellen Qualität. Perfekt für Websites und E-Mails.",
    "landing.compress.redesign.feat1Badge": "KEIN QUALITÄTSVERLUST",
    "landing.compress.redesign.feat1Title": "Intelligente Optimierung",
    "landing.compress.redesign.feat1Desc": "Findet automatisch die perfekte Balance zwischen minimaler Dateigröße und maximaler Bildqualität.",
    "landing.compress.redesign.feat2Badge": "100% PRIVAT",
    "landing.compress.redesign.feat2Title": "Null Uploads",
    "landing.compress.redesign.feat2Desc": "Die Komprimierung erfolgt direkt in Ihrem Webbrowser. Es wird nichts an Server gesendet.",
    "landing.compress.redesign.feat3Badge": "JEDES FORMAT",
    "landing.compress.redesign.feat3Title": "Breite Unterstützung",
    "landing.compress.redesign.feat3Desc": "Funktioniert mit den Standardformaten JPG und PNG sowie modernen WEBP-Formaten.",
    "landing.compress.redesign.whoTag": "FÜR WEN ES IST",
    "landing.compress.redesign.whoTitle": "Gebaut für Web & Medien",
    "landing.compress.redesign.whoDesc": "Perfekt für Entwickler, Designer und Social-Media-Manager, die optimierte Bilder benötigen.",
    "landing.compress.redesign.who1Title": "Webentwickler",
    "landing.compress.redesign.who1Desc": "Verbessern Sie die PageSpeed-Werte und reduzieren Sie die Ladezeiten, ohne die Bildqualität zu beeinträchtigen.",
    "landing.compress.redesign.who1Tags": "SEO OPTIMIERUNG",
    "landing.compress.redesign.who2Title": "Content-Ersteller",
    "landing.compress.redesign.who2Desc": "Erfüllen Sie strenge Upload-Größenbeschränkungen für Plattformen wie Discord oder Twitter.",
    "landing.compress.redesign.who2Tags": "SOZIALE MEDIEN",
    "landing.compress.redesign.stepsTag": "WIE ES FUNKTIONIERT",
    "landing.compress.redesign.stepsTitle": "3 Schritte zur Optimierung",
    "landing.compress.redesign.s1Title": "Bilder hochladen",
    "landing.compress.redesign.s1Desc": "Ziehen Sie Ihre Fotos per Drag-and-Drop in den Komprimierungsarbeitsbereich.",
    "landing.compress.redesign.s2Title": "Komprimierungsstufe einstellen",
    "landing.compress.redesign.s2Desc": "Passen Sie den Qualitätsregler an, um die richtige Balance zu finden.",
    "landing.compress.redesign.s3Title": "Speicherplatz sparen",
    "landing.compress.redesign.s3Desc": "Laden Sie Ihre optimierten Bilder herunter und genießen Sie kleinere Dateigrößen.",
    "landing.remove.redesign.heroBadge": "KI-GESTÜTZTES AUSSCHNEIDEN",
    "landing.remove.redesign.heroTitle": "Hintergrund in 1 Sekunde mit makelloser Präzision entfernen",
    "landing.remove.redesign.heroDesc": "Angetrieben von fortschrittlicher WebAssembly-KI erhalten Sie perfekte Haarausschnitte und glatte Kanten, ohne Ihre Fotos jemals auf einen Server hochzuladen.",
    "landing.remove.redesign.feat1Badge": "99,8% GENAUIGKEIT",
    "landing.remove.redesign.feat1Title": "Makellose Haar- und Kantenerkennung",
    "landing.remove.redesign.feat1Desc": "Unser neuronales Netzwerk verarbeitet mühelos komplexe Details wie menschliches Haar, Tierfell und halbtransparente Objekte.",
    "landing.remove.redesign.feat2Badge": "100% SICHER",
    "landing.remove.redesign.feat2Title": "Vollständige Offline-Privatsphäre",
    "landing.remove.redesign.feat2Desc": "Das KI-Modell wird direkt in Ihren Browser geladen. Ihre Bilder verlassen niemals Ihren Computer.",
    "landing.remove.redesign.feat3Badge": "STAPELMODUS",
    "landing.remove.redesign.feat3Title": "Bereit für Massenverarbeitung",
    "landing.remove.redesign.feat3Desc": "Ziehen Sie bis zu 10 Fotos gleichzeitig per Drag-and-Drop. Laden Sie alles in einer einzigen ZIP-Datei herunter.",
    "landing.remove.redesign.whoTag": "FÜR WEN ES IST",
    "landing.remove.redesign.whoTitle": "Perfekt für jeden kreativen Bedarf",
    "landing.remove.redesign.whoDesc": "Egal, ob Sie Autos verkaufen, Poster entwerfen oder offizielle Dokumente erstellen.",
    "landing.remove.redesign.who1Title": "E-Commerce-Verkäufer",
    "landing.remove.redesign.who1Desc": "Erstellen Sie saubere weiße Hintergründe für Produktangebote, die sich von selbst verkaufen.",
    "landing.remove.redesign.who1Tags": "PRODUKTANGEBOTE",
    "landing.remove.redesign.who2Title": "Grafikdesigner",
    "landing.remove.redesign.who2Desc": "Extrahieren Sie Logos, Signaturen und Assets sofort für Ihre Composite-Designs.",
    "landing.remove.redesign.who2Tags": "DESIGN-ASSETS",
    "landing.remove.redesign.stepsTag": "WIE ES FUNKTIONIERT",
    "landing.remove.redesign.stepsTitle": "3 Schritte zu transparenten Hintergründen",
    "landing.remove.redesign.s1Title": "Bild hochladen",
    "landing.remove.redesign.s1Desc": "Ziehen Sie Ihr Foto per Drag-and-Drop. PNG, JPG oder WEBP werden unterstützt.",
    "landing.remove.redesign.s2Title": "KI-Verarbeitung",
    "landing.remove.redesign.s2Desc": "Die lokale KI erkennt das Hauptmotiv in 1 Sekunde.",
    "landing.remove.redesign.s3Title": "HD-Download",
    "landing.remove.redesign.s3Desc": "Exportieren Sie Ihr ausgeschnittenes Foto mit einem transparenten Hintergrund.",
    "home.why.tag": "WARUM HELPMYIMG",
    "home.why.title": "Warum HelpMyIMG die intelligenteste Wahl ist",
    "home.why.desc": "Von Grund auf für maximale Privatsphäre, blitzschnelle Geschwindigkeit und null Kosten konzipiert.",
    "home.why.c1.t": "Sofortige lokale Geschwindigkeit",
    "home.why.c1.d": "Ihre Fotos werden direkt im Speicher Ihres Geräts mit null Latenz verarbeitet.",
    "home.why.c1.b": "0ms Serververzögerung",
    "home.why.c2.t": "100% Absolute Privatsphäre",
    "home.why.c2.d": "Ihre persönlichen Porträts und vertraulichen Dokumente verlassen niemals Ihren Computer.",
    "home.why.c2.b": "Null Cloud-Speicher",
    "home.why.c3.t": "Immer kostenlos und unbegrenzt",
    "home.why.c3.d": "Keine Abonnements, keine Wasserzeichen. Hochauflösende Fotobearbeitung für alle zugänglich.",
    "home.why.c3.b": "0 $ / Lebenslang",
    "home.why.c4.t": "Stapelverarbeitung bis 10",
    "home.why.c4.d": "Ziehen Sie bis zu 10 Fotos gleichzeitig und exportieren Sie sie in Sekunden als ZIP-Archiv.",
    "home.why.c4.b": "10x Arbeitsgeschwindigkeit",
    "home.steps.tag": "WIE ES FUNKTIONIERT",
    "home.steps.title": "Wie HelpMyIMG in 3 einfachen Schritten funktioniert",
    "home.steps.desc": "Keine Softwareinstallation erforderlich. Erhalten Sie professionelle Ergebnisse direkt aus Ihrem Webbrowser."
  },
  en: {
    "landing.compress.redesign.heroBadge": "SMART COMPRESSION",
    "landing.compress.redesign.heroTitle": "Reduce Image File Size by up to 90% Instantly",
    "landing.compress.redesign.heroDesc": "Shrink the size of your photos without losing visual quality. Perfect for websites and emails.",
    "landing.compress.redesign.feat1Badge": "NO QUALITY LOSS",
    "landing.compress.redesign.feat1Title": "Smart Optimization",
    "landing.compress.redesign.feat1Desc": "Automatically finds the perfect balance between minimal file size and maximum image quality.",
    "landing.compress.redesign.feat2Badge": "100% PRIVATE",
    "landing.compress.redesign.feat2Title": "Zero Uploads",
    "landing.compress.redesign.feat2Desc": "Compression happens directly in your web browser. Nothing is sent to servers.",
    "landing.compress.redesign.feat3Badge": "ANY FORMAT",
    "landing.compress.redesign.feat3Title": "Broad Support",
    "landing.compress.redesign.feat3Desc": "Works with standard JPG and PNG formats as well as modern WEBP formats.",
    "landing.compress.redesign.whoTag": "WHO IT'S FOR",
    "landing.compress.redesign.whoTitle": "Built for Web & Media",
    "landing.compress.redesign.whoDesc": "Perfect for developers, designers, and social media managers who need optimized images.",
    "landing.compress.redesign.who1Title": "Web Developers",
    "landing.compress.redesign.who1Desc": "Improve PageSpeed scores and reduce load times without sacrificing image quality.",
    "landing.compress.redesign.who1Tags": "SEO OPTIMIZATION",
    "landing.compress.redesign.who2Title": "Content Creators",
    "landing.compress.redesign.who2Desc": "Meet strict upload size limits for platforms like Discord or Twitter.",
    "landing.compress.redesign.who2Tags": "SOCIAL MEDIA",
    "landing.compress.redesign.stepsTag": "HOW IT WORKS",
    "landing.compress.redesign.stepsTitle": "3 Steps to Optimization",
    "landing.compress.redesign.s1Title": "Upload Images",
    "landing.compress.redesign.s1Desc": "Drag and drop your photos into the compression workspace.",
    "landing.compress.redesign.s2Title": "Set Compression Level",
    "landing.compress.redesign.s2Desc": "Adjust the quality slider to find the right balance.",
    "landing.compress.redesign.s3Title": "Save Storage",
    "landing.compress.redesign.s3Desc": "Download your optimized images and enjoy reduced file sizes.",
    "landing.remove.redesign.heroBadge": "AI POWERED CUTOUT",
    "landing.remove.redesign.heroTitle": "Remove Background in 1 Second with Flawless Precision",
    "landing.remove.redesign.heroDesc": "Powered by advanced WebAssembly AI, get perfect hair cutouts and smooth edges without ever uploading your photos to a server.",
    "landing.remove.redesign.feat1Badge": "99.8% ACCURACY",
    "landing.remove.redesign.feat1Title": "Flawless Hair & Edge Detection",
    "landing.remove.redesign.feat1Desc": "Our neural network easily handles complex details like human hair, animal fur, and semi-transparent objects.",
    "landing.remove.redesign.feat2Badge": "100% SECURE",
    "landing.remove.redesign.feat2Title": "Complete Offline Privacy",
    "landing.remove.redesign.feat2Desc": "The AI model loads directly into your browser. Your images never leave your computer.",
    "landing.remove.redesign.feat3Badge": "BATCH MODE",
    "landing.remove.redesign.feat3Title": "Ready for Mass Processing",
    "landing.remove.redesign.feat3Desc": "Drag and drop up to 10 photos at once. Download everything in a single ZIP file.",
    "landing.remove.redesign.whoTag": "WHO IT'S FOR",
    "landing.remove.redesign.whoTitle": "Perfect for Every Creative Need",
    "landing.remove.redesign.whoDesc": "Whether you are selling cars, designing posters, or creating official documents.",
    "landing.remove.redesign.who1Title": "E-Commerce Sellers",
    "landing.remove.redesign.who1Desc": "Create clean white backgrounds for product listings that sell themselves.",
    "landing.remove.redesign.who1Tags": "PRODUCT LISTINGS",
    "landing.remove.redesign.who2Title": "Graphic Designers",
    "landing.remove.redesign.who2Desc": "Extract logos, signatures, and assets instantly for your composite designs.",
    "landing.remove.redesign.who2Tags": "DESIGN ASSETS",
    "landing.remove.redesign.stepsTag": "HOW IT WORKS",
    "landing.remove.redesign.stepsTitle": "3 Steps to Transparent Backgrounds",
    "landing.remove.redesign.s1Title": "Upload Image",
    "landing.remove.redesign.s1Desc": "Drag and drop your photo. PNG, JPG or WEBP are supported.",
    "landing.remove.redesign.s2Title": "AI Processing",
    "landing.remove.redesign.s2Desc": "Local AI detects the main subject in 1 second.",
    "landing.remove.redesign.s3Title": "HD Download",
    "landing.remove.redesign.s3Desc": "Export your cutout photo with a transparent background.",
    "home.why.tag": "WHY HELPMYIMG",
    "home.why.title": "Why HelpMyIMG is the Smartest Choice",
    "home.why.desc": "Designed from the ground up for maximum privacy, lightning speed, and zero cost.",
    "home.why.c1.t": "Instant Local Speed",
    "home.why.c1.d": "Your photos are processed directly inside your device memory with zero latency.",
    "home.why.c1.b": "0ms Server Delay",
    "home.why.c2.t": "100% Absolute Privacy",
    "home.why.c2.d": "Your personal portraits and confidential documents never leave your computer.",
    "home.why.c2.b": "Zero Cloud Storage",
    "home.why.c3.t": "Always Free & Unlimited",
    "home.why.c3.d": "No subscriptions, no watermarks. High-definition photo editing accessible to everyone.",
    "home.why.c3.b": "$0 / Lifetime",
    "home.why.c4.t": "Batch Power up to 10",
    "home.why.c4.d": "Drag up to 10 photos simultaneously and export as a ZIP archive in seconds.",
    "home.why.c4.b": "10x Work Speed",
    "home.steps.tag": "HOW IT WORKS",
    "home.steps.title": "How HelpMyIMG Works in 3 Simple Steps",
    "home.steps.desc": "No software installation required. Get professional results straight from your web browser."
  }
};

const scriptDir = __dirname;
const localesDir = path.join(scriptDir, '../public/locales');

for (const [lang, kv] of Object.entries(translations)) {
  const filePath = path.join(localesDir, lang, 'translation.json');
  if (fs.existsSync(filePath)) {
    const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    for (const [key, val] of Object.entries(kv)) {
      data[key] = val;
    }
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
    console.log(`[${lang}] Injected translations chunk 7`);
  }
}
